### PR TITLE
fix: handle Shift+Space in Kitty keyboard protocol terminals

### LINKED ISSUE #15703: Shift+space does not insert space character
### What happened?

I have pressed `Shift+Space`. The `<Space>` was not inserted.

### What did you expect to happen?

`<Space>` inserted as in any other CLI or GUI application.

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
CLI Version  0.22.4              
Git Commit   e00aaa123           
Model        auto-gemini-3       
Sandbox      no sandbox          
OS           linux               
Auth Method  OAuth               
User Email   foobar@gmail.com
```

</details>

### Login information

Google Account

### Anything else we need to know?

Debian 13.2, `foot` terminal v1.21.0

### PR DESCRIPTION
**Pull request by tt-a1i**
## Summary

- Fixed Shift+Space not inserting a space character in terminals using Kitty keyboard protocol (e.g., foot, kitty)
- Kitty terminals can send Shift+Space as CSI-u (e.g. `\x1b[32;2u`); we now recognize the normalized key code and treat it as an insertable space

## Root Cause

In Kitty protocol terminals, space with modifiers is often sent as a CSI-u sequence. The key parser normalizes CSI-u keys into a modifier-free code (e.g. `[32u`) and derives modifiers from the numeric parameter. Since `[32u` wasn't mapped, we fell through to `name='undefined'` and the raw escape sequence was never normalized into an insertable `' '`.

## Changes

- Added `[32u` to `KEY_INFO_MAP` as the `space` key
- When the resolved key is `space` without `ctrl/meta`, normalize the raw CSI-u sequence to `' '` and mark it `insertable` so downstream text insertion uses the correct input
- Added test cases for Shift+Space and Ctrl+Space in Kitty protocol

## Test Plan

- [x] `npx vitest run src/ui/contexts/KeypressContext.test.tsx`
- [x] Manual testing in foot terminal (requires user verification)

Fixes #15703

## AI Assistance Disclosure

I used Codex to review the changes, sanity-check the implementation against existing patterns, and help spot potential edge cases.

### CODE REVIEW

File: packages/cli/src/ui/contexts/KeypressContext.tsx [hunk 1]
```diff
@@ -438,14 +438,21 @@ function* emitKeys(
...
             codeNumber >= 'a'.charCodeAt(0) &&
             codeNumber <= 'z'.charCodeAt(0)
           ) {
             name = String.fromCharCode(codeNumber);
+          } else if (codeNumber === ' '.charCodeAt(0)) {
+            // Handle space key (ASCII 32) - e.g., Shift+Space in Kitty protocol
+            name = 'space';
+            insertable = true;
           }
         }
```
[the remark this answers is not in the document]
Comment (tt-a1i) [reply packages/cli/src/ui/contexts/KeypressContext.tsx]: Keeping this PR scoped to the reported regression in foot/kitty: Shift+Space shows up as CSI-u (\x1b[32;2u) and we weren’t turning that into an actual space.

We currently enable kitty progressive enhancement (\x1b[>1u), so plain Space is still expected to come through the normal single-char path (ch === " ") — I didn’t try to add full support for unmodified CSI-u like \x1b[32u here.

When we treat CSI-u Space as insertable, we normalize sequence to a literal space so the text buffer doesn’t insert the raw escape sequence; Ctrl/Meta+Space stays non-insertable on purpose (but still bindable via name=space + ctrl=true).

If we ever switch to full CSI-u reporting, happy to follow up with a broader refactor + tests for unmodified \x1b[32u.

**Comment by scidomino** [comment]
Taking a look now. This is a delicate area of the code so it might take a while.

File: packages/cli/src/ui/contexts/KeypressContext.tsx [hunk 2]
```diff
@@ -438,14 +438,26 @@ function* emitKeys(
...
           const codeNumber = parseInt(code.slice(1, -1), 10);
           if (
             codeNumber >= 'a'.charCodeAt(0) &&
             codeNumber <= 'z'.charCodeAt(0)
           ) {
             name = String.fromCharCode(codeNumber);
+          } else if (codeNumber === ' '.charCodeAt(0)) {
+            // Handle space key (ASCII 32) - e.g., Shift+Space in Kitty protocol
+            name = 'space';
+            if (!ctrl && !meta) {
```
Comment (scidomino) [inline packages/cli/src/ui/contexts/KeypressContext.tsx]: Is this if necessary? Wouldn't it be ok to always set

    sequence = ' ';
    insertable = true;

?

File: packages/cli/src/ui/contexts/KeypressContext.tsx [hunk 3]
```diff
@@ -438,14 +438,26 @@ function* emitKeys(
         }
       } else {
         name = 'undefined';
-        if ((ctrl || meta) && (code.endsWith('u') || code.endsWith('~'))) {
+        if (
```
Comment (scidomino) [inline packages/cli/src/ui/contexts/KeypressContext.tsx]: The reason we weren't looking for shift is that shift + letter is never sent (they just send 'F' instead of 'shift+f').

I think the right way to do this is to revert all this and add this to the KEY_INFO_MAP:

  '[32u': { name: 'space' },

Does that make sense?

There's no need to update `sequence` since it will always be ' ' in this case.

**Comment by tt-a1i** [comment]
@scidomino yep, makes sense — the CSI-u parser already normalizes the key code (e.g. '[32u') and extracts modifiers separately, so mapping '[32u' in KEY_INFO_MAP is cleaner than expanding the CSI-u fallback.\n\none nuance: the emitted 'sequence' is still the raw CSI-u string, and text insertion uses insertable + sequence, so for non-ctrl/meta space I normalize sequence to ' ' and mark it insertable.\n\njust pushed an update + tests.

**Review by scidomino — APPROVED** [review]
