### PR TITLE
fix(cli): clear stale retry/loading state after cancellation (#21096)

### LINKED ISSUE #21096: Request gets stuck with “This is taking a bit longer, we're still on it” after canceling request
Environment
App/Tool: Termux
Model: gemini-3.1-pro-preview
Sandbox: no sandbox
CLI Version: v0.32.1 Stable
OS: Android 15
Auth Method:- Logged in with Google.
Plan type:- Gemini Code Assist in Google One AI Pro.
Description
After canceling a request, the interface still displays the message:
“This is taking a bit longer, we're still on it. (esc to cancel…)”
The request appears stuck model doesnot respond and does not properly reset the UI state.
Steps to Reproduce
Open the chat interface.
Send a prompt to the model.
Wait until the request runs for some time.
Cancel the request using ESC.
Try running another command (e.g., > Continue).
Expected Behavior
After canceling, the request should terminate completely.
The UI should reset and allow new prompts without showing the previous loading message.
Actual Behavior
The UI still shows:
“This is taking a bit longer, we're still on it.”
Request state appears stuck even after cancellation.
Screenshot

Frequency
Occurs: Always
Possible Impact
Blocks further interaction with the model
Requires restarting the interface/session
Additional Notes
Model usage indicator shows 99%.
Happens when using gemini-3.1-pro-preview.

### PR DESCRIPTION
**Pull request by Aaxhirrr**
## Summary

Fixes the stuck loading-state bug after cancel (`Esc`) for issue #21096.

The root cause was a race: canceling a request could still allow a late retry event to update UI state, so the app kept showing `"This is taking a bit longer, we're still on it."` even when the turn was already canceled/idle.

- Ensures canceled turns fully reset loading state so users can immediately continue with a new prompt.

## Details

- **Core retry safety**
  - Added an abort guard before every `onRetry(...)` callback in `retryWithBackoff`.
  - If the request is already canceled, retry events are not emitted and an `AbortError` is thrown immediately.
- **UI state hardening**
  - In `useGeminiStream`, `RetryAttempt` events are ignored when the turn is canceled or not actively responding.
  - `retryStatus` is cleared immediately during `cancelOngoingRequest` (instead of only waiting for `isResponding` effects).
- **Loading indicator correctness**
  - Retry phrase now renders only in `StreamingState.Responding`.
  - `(esc to cancel, ...)` timer/help text now renders only in `StreamingState.Responding`.

This keeps cancellation behavior clean and prevents stale retry/loading text from leaking into the next turn.

**Regression coverage**
  - Added tests for:
    - abort-before-retry-callback behavior,
    - late retry events after cancel,
    - no retry phrase in Idle,
    - no cancel/timer hint in Idle.

## Related Issues

- Fixes #21096

## How to Validate

1. Repro manually:
1. Start a prompt on a model likely to retry/back off.
2. Wait until loading/retry text appears.
3. Press `Esc` to cancel.
4. Send another prompt.
5. Confirm old retry/loading text is gone and UI is reset.

2. Run tests:
- `npm run test --workspace @google/gemini-cli-core -- src/utils/retry.test.ts`
- `npm run test --workspace @google/gemini-cli -- src/ui/hooks/useGeminiStream.test.tsx -t "Retry Handling"`
- `npm run test --workspace @google/gemini-cli -- src/ui/hooks/useLoadingIndicator.test.tsx src/ui/components/LoadingIndicator.test.tsx`

## Specific validation update (macOS smoke test, March 10, 2026):

- Node.js: v22.14.0
- Gemini CLI: 0.34.0-nightly.20260304.28af4e127
- Branch: fix/21096-cancel-retry-loading-main
- Auth: Login with Google (OAuth)
- Model: gemini-3.1-pro-preview

Ran 5 iterations of the repro flow:
1) send long prompt
2) wait for retry/loading message
3) cancel with Esc
4) immediately send follow-up prompt

Result: PASS (5/5). No stuck `"This is taking a bit longer..."` line after cancel; follow-up prompts executed normally without restart.

## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [x] Added/updated tests (if needed)
- [x] Noted breaking changes (if any): none
- [x] Validated on required platforms/methods:
  - [x] MacOS
    - [x] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [x] Windows
    - [x] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

**Comment by Aaxhirrr** [comment]
> Thank you for fixing this UI loading-state race condition! The fix successfully clears stale retry statuses during cancellations and accurately guards the `retryPhrase` based on `StreamingState.Responding`. The React tests use `act` and `waitFor` exactly as required by the development rules.

> Great work on this fix!

@devr0306  Thanks again for the review. 
I’ve now addressed both of the requested cleanup items in this PR:

- switched `isResponding` over to `useStateAndRef`
- centralized the abort checks in `retry.ts` and updated the related regression coverage accordingly

I also reran the targeted tests for the retry/cancel/loading paths after making those changes.

One scope question before I do anything further: the issue thread for #21096 has grown pretty broad, and a number of comments now seem to mix the original cancel-related stale UI bug with longer-running backend/capacity/429-related "This is taking a bit longer..." cases.

Given the current scope of this PR, would you prefer that I keep it focused on the UI loading-state race condition during cancellation, or should I expand/update this PR to try to cover the broader "taking a bit longer" reports from the issue thread as well?

If the latter would be better handled as a separate follow-up issue/PR, I’m happy to keep this one narrowly scoped and work with you to get this merged first, and then I can immediately move on to investigating any broader follow-up issues in a separate PR if needed.

Waiting for your call, and thanks for your appreciation, always happy to contribute.

File: packages/cli/src/ui/hooks/useGeminiStream.ts [hunk 1]
```diff
@@ -274,13 +267,16 @@ export const useGeminiStream = (
...
+        return;
+      }
       setRetryStatus(payload);
     };
     coreEvents.on(CoreEvent.RetryAttempt, handleRetryAttempt);
     return () => {
       coreEvents.off(CoreEvent.RetryAttempt, handleRetryAttempt);
     };
-  }, []);
+  }, [isRespondingRef]);
```
Comment (devr0306) [inline packages/cli/src/ui/hooks/useGeminiStream.ts:285]: shouldn't this also depend on turnCancelledRef

File: packages/cli/src/ui/hooks/useGeminiStream.ts [hunk 2]
```diff
@@ -1645,7 +1642,6 @@ export const useGeminiStream = (
       setThought,
       maybeAddSuppressedToolErrorNote,
       maybeAddLowVerbosityFailureNote,
-      settings.merged.billing?.overageStrategy,
```
Comment (devr0306) [inline packages/cli/src/ui/hooks/useGeminiStream.ts:1768]: is there a reason why this was removed?

Comment (Aaxhirrr) [reply packages/cli/src/ui/hooks/useGeminiStream.ts:1768]: > is there a reason why this was removed?

@devr0306 There isn’t a good reason for that removal.

That line was dropped during the March 27 rebase / cleanup pass, but `handleSubmitQuery` still calls:

`config.resetBillingTurnState(settings.merged.billing?.overageStrategy)`

so the dependency should still be there unless that logic is refactored out of the callback. In other words, this was accidental on my side rather than an intentional behavior change.

I strongly apologize, thank you for pointing it out. I should've reviewed after resolving that conflict.

I’m going to restore that dependency right now.

File: packages/cli/src/ui/hooks/useGeminiStream.ts (hunk 1 above)
Comment (Aaxhirrr) [reply packages/cli/src/ui/hooks/useGeminiStream.ts:285]: > shouldn't this also depend on turnCancelledRef

I don’t think it needs to depend on `turnCancelledRef`.

Both `turnCancelledRef` and `isRespondingRef` are refs, and the handler reads `.current` at event time, so adding them to the dependency array would not track value changes the way state/props deps do. In that sense, `turnCancelledRef` does not need to be added here.

More broadly, I think `[]` would actually be the clearest dependency list for this effect, since the ref identities are stable and the logic relies on their current values at callback time, not on re-subscribing when they change.

I can clean that up in the next update as well.

**Review by devr0306 — APPROVED** [review]
LGTM

**Comment by Aaxhirrr** [comment]
> LGTM

Thank you for the approval.

I see that the Lint is failing, so I'm currently working on committing one final change to address the failing lint check, and once that is pushed this should turn green.

EDIT:
Pushed a small follow-up to address the hook-deps lint failures; lint should pass now; waiting for CI rerun, and will iterate accordingly
