### PR TITLE
fix(ui): prevent content leak in `MaxSizedBox` bottom overflow

### LINKED ISSUE #17990: Fix content leak in `MaxSizedBox` with bottom overflow
When using overflowDirection="bottom", content bleeds after the hidden indicator:

`... last 18 lines hidden ...rtant`

The inner overflow Box lacks a height constraint, so `overflow="hidden"` doesn't clip properly.

### PR DESCRIPTION
**Pull request by jerop**
When using `overflowDirection="bottom"`, content was bleeding through after the `"... last N lines hidden ..."` indicator:

```
... last 18 lines hidden ...rtant
```

This was caused by the inner overflow Box not having a constrained height. This change adds `maxHeight` constraint to inner overflow Box when overflowing.

Fixes https://github.com/google-gemini/gemini-cli/issues/17990

### CODE REVIEW

File: packages/cli/src/ui/components/shared/MaxSizedBox.tsx [hunk 1]
```diff
@@ -120,7 +120,12 @@ export const MaxSizedBox: React.FC<MaxSizedBoxProps> = ({
           hidden ...
         </Text>
       )}
-      <Box flexDirection="column" overflow="hidden" flexGrow={1}>
+      <Box
+        flexDirection="column"
+        overflow="hidden"
+        flexGrow={1}
```
Comment (jacob314) [inline packages/cli/src/ui/components/shared/MaxSizedBox.tsx]: actually I think the real bug is the inner child shouldn't be flexGrow. 
If you set flexGrow={0} 
then would expect the height constraint from the parent to properly propogate. if that doesn't work we can do this but it would be nice if we didn't have to duplicate this constraint.

Comment (jerop) [reply packages/cli/src/ui/components/shared/MaxSizedBox.tsx]: Tried removing the `maxHeight` and just setting `flexGrow={0}`, but the tests failed with content leaks in bottom overflow mode. It seems Ink needs the explicit `maxHeight` on this inner Box to correctly clip the content when we are shifting the margin for top-overflow or constraining it for bottom-overflow.

Updated the implementation to use `flexGrow={0}` while retaining the `maxHeight` constraint to satisfy both the flex preference and the clipping requirements.

https://github.com/google-gemini/gemini-cli/pull/17991/changes/fd9a7adcb38f06fb8fedd3683b40f513771d595d

**Review by jacob314 — APPROVED** [review]
Ok I think I understand why this is need now. Approved. We should try to clean this up a little at some point but this is fine for now.
