### PR TITLE
fix(cli): use newline in shell command wrapping to avoid breaking heredocs

### LINKED ISSUE #25536: Fix shell command wrapping breaking heredocs
Summary:
run_shell_command wraps the user's command in a bash group command { <command>; }; __code=0; ... (in useExecutionLifecycle.ts). This breaks all heredoc-terminated commands because the ; is appended directly to the heredoc delimiter, making bash unable to recognize it.

Steps to Reproduce:
Run a shell command ending in a heredoc:
cat << 'EOF' > output.txt
hello world
EOF

The CLI transforms this into:
{ cat << 'EOF' > output.txt
hello world
EOF; }; __code=0; pwd > "/tmp/xxx"; exit ;

Proposed Fix:
In packages/cli/src/ui/hooks/useExecutionLifecycle.ts, replace the semicolon with a newline before closing the brace:
commandToExecute = `{ ${command}\n}; __code=$?; pwd > "${pwdFilePath}"; exit $__code`;

Impact:
Heredocs fail if the delimiter is on the final line, causing model retries and token waste.

I have verified the fix with reproduction scripts and added unit tests in packages/cli and packages/core.

### PR DESCRIPTION
**Pull request by cocosheng-g**
## Summary
This pull request enhances the security, reliability, and cross-platform robustness of shell command execution.

## Key Changes
*   **Secure Temporary Directories**: Replaced predictable temporary filenames with unique directories created via `fs.mkdtempSync()`. This mitigates symlink attacks, resource leaks, and prevents race conditions.
*   **Command Injection Prevention**: Introduced `escapeShellArg` to safely escape file paths before interpolating them into shell wrappers.
*   **Robust Command Wrapping**: Commands are now wrapped using literal newlines (e.g., `{\n${command}\n}`) instead of trailing semicolons. This properly supports heredocs, trailing comments, and commands ending with a backslash.
*   **Cross-Platform Fixes**: Ensured POSIX utility outputs (like `pgrep`) are parsed robustly by explicitly splitting on `\n` and trimming each line to handle potential `\r` (CRLF) carriage returns.
*   **Test Suite Resiliency**: Completely overhauled the shell tests by removing brittle global `node:fs` mocks that previously broke WASM parsing and sandbox heuristic checks on CI. Tests now dynamically capture and assert against the true generated temporary paths using resilient string matching.

fix https://github.com/google-gemini/gemini-cli/issues/25536

### CODE REVIEW

**Review by jacob314 — APPROVED** [review]
### Code Review Summary
This PR provides excellent robustness and security improvements to the shell execution logic. Moving to `mkdtempSync` prevents potential race conditions and symlink attacks when creating temporary status files. Shifting from trailing-semicolon command wrapping to newline wrapping correctly handles previously breaking edge cases involving heredocs and inline comments. The changes are thoroughly tested and handle cleanups safely.

### Findings

**Improvements & Nitpicks:**
* **Redundant Cleanup Logic:** In both `packages/cli/src/ui/hooks/useExecutionLifecycle.ts` and `packages/core/src/tools/shell.ts`, the cleanup logic explicitly unlinks the temporary file before recursively removing the temporary directory. Since `fsPromises.rm(..., { recursive: true })` (and the synchronous equivalent `fs.rmSync`) will naturally delete all contents within the directory, you can safely drop the explicit file unlink logic to simplify these cleanup blocks.
* **Hardcoded Shell Variant for Escaping:** Using `escapeShellArg(pwdFilePath, 'bash')` is hardcoded to `'bash'`. While the user's default shell might be `zsh` or `sh`, the POSIX escaping strategy applied by `'bash'` (wrapping in single quotes and safely escaping internals) is universally compatible across POSIX-compliant shells. This is safe, but worth noting.

Great work on this!

File: packages/core/src/tools/shell.ts [hunk 1]
```diff
@@ -450,10 +451,8 @@ export class ShellToolInvocation extends BaseToolInvocation<
     }
 
     const isWindows = os.platform() === 'win32';
-    const tempFileName = `shell_pgrep_${crypto
-      .randomBytes(6)
-      .toString('hex')}.tmp`;
-    const tempFilePath = path.join(os.tmpdir(), tempFileName);
+    let tempFilePath = '';
+    let tempDir = '';
```
Comment (jacob314) [inline packages/core/src/tools/shell.ts:455]: can you provide a temp dir on windows?

**Review by SandyTao520 — APPROVED** [review]

**Review by jacob314 — APPROVED** [review]
lgtm

File: packages/core/src/tools/shell.ts (hunk 1 above)
Comment (cocosheng-g) [reply packages/core/src/tools/shell.ts:455]: moved out of the windows condition.
