### PR TITLE
fix: Prevent garbled input during "Login With Google" OAuth prompt on…

### LINKED ISSUE #10632: Seeing junk chacters "1;2c" on the input area where authentication key is expected (Login via Google approach)
### What happened?

When the user selected "Login with Google", a link is provided to sign in and then copy the authorization code. This input area appends junk characters "1;2c".
Due to these junk characters, when the authorization code is pasted, it fails saying incorrect code. 

The user has to remove these junk characters and then paste the code. 

Image

### What did you expect to happen?

The junk characters must not be appended.

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console

About Gemini CLI                                             
│                                                               
│ CLI Version          0.7.0                                    
│ Git Commit           f28ffaa3                                 
│ Model                gemini-2.5-pro                           
│ Sandbox              no sandbox                               
│ OS                   linux                                    
│ Auth Method          gemini-api-key                           
│ IDE Client           VS Code 
```

</details>

### Login information

Login with Google

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by MJjainam**
… Linux

## TLDR
Wait for kitty terminal protocol detection to complete before moving to asking for Authz code.

## Linked issues / bugs
- Fixes #10632

### CODE REVIEW

File: packages/cli/src/gemini.tsx [hunk 1]
```diff
@@ -399,7 +399,9 @@ export async function main() {
     }
 
     setMaxSizedBoxDebugging(isDebugMode);
-
+    // Ensure terminal protocol detection completes before showing OAuth prompt
+    // to prevent escape sequence responses from appearing in readline input
+    await kittyProtocolDetectionComplete;
```
Comment (jacob314) [inline packages/cli/src/gemini.tsx]: please simplify further. If this is needed then line 398 can be just replaced to 
await detectAndEnableKittyProtocol();
and kittyProtocolDetectionComplete can be removed.

**Review by jacob314 — COMMENTED** [review]
Approved once the small comment is addressed.

File: packages/cli/src/gemini.tsx (hunk 1 above)
Comment (MJjainam) [reply packages/cli/src/gemini.tsx]: That should also work.

I was wondering - if tomorrow some time-taking lines need to be added in between line 398 and 404, we can do that.  _the await can wait_ in that scenario.

This split covers both scenarios.

Wdyt?

[the remark this answers is not in the document]
Comment (MJjainam) [reply packages/cli/src/gemini.tsx]: Resolved.

**Review by jacob314 — APPROVED** [review]
lgtm
