### PR TITLE
fix(cli): fix issue updating a component while rendering a different component

### LINKED ISSUE #12149: Cannot update a component (`InputPrompt`) while rendering a different component (`AppContainer`)
### What happened?

I'm occasionally seeing the following issue when running debug builds of Gemini CLI.
We should root cause this issue and fix it.
 ✖  Cannot update a component (`InputPrompt`) while rendering a different component (`AppContainer`). To locate the bad setState() call inside      │
│    `AppContainer`, follow the stack trace as described in https://react.dev/link/setstate-in-render

### What did you expect to happen?

Expect to not see any errors about updates to a component while rendering a different component.

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
# paste output here
```

</details>

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by jacob314**
## Summary

Its unsafe to trigger operations that may modify react state within a setState callback. Fixed core issue with popAllMessages causing this. I'm unfortunately not able to reliably reproduce so I'm not 100% confident this fixes the issue.

## Details

Also tossed in a couple reasonable safe fixes suggested by Gemini CLI as part of  auditing the code to fix the issue.
Gemini CLI caught some dead code that might have triggering looping behavior and made a tweak to reduce the number of setState calls/

## Related Issues

Fixes: #12149

### CODE REVIEW

File: packages/cli/src/ui/hooks/useMessageQueue.ts [hunk 1]
```diff
@@ -53,21 +53,14 @@ export function useMessageQueue({
...
-        }
-        // Join all messages with double newlines, same as when they're sent
-        const allMessages = prev.join('\n\n');
-        onPop(allMessages);
-        return []; // Clear the entire queue
-      });
-    },
-    [],
-  );
+  const popAllMessages = useCallback(() => {
```
Comment (jacob314) [inline packages/cli/src/ui/hooks/useMessageQueue.ts:56]: the core code causing this issue was having calling setMessageQueue trigger side effects by calling onPop directly.
Unless we are immediately adding a message and then calling popAllMessages within the same React loop the new behavior is equivalent.
The only difference in behavior is if you queued a message so quickly it didn't even show up in the UI and then cancelled. Alternate fixes would be more complex and more involved to implement so aren't worth it. Seems perfectly reasonable to only return back the messages that were actually visually displayed as queued up.

File: packages/cli/src/ui/AppContainer.tsx [hunk 2]
```diff
@@ -832,11 +830,14 @@ Logging in with Google... Restarting Gemini CLI to continue.
   useLayoutEffect(() => {
     if (mainControlsRef.current) {
       const fullFooterMeasurement = measureElement(mainControlsRef.current);
-      if (fullFooterMeasurement.height > 0) {
+      if (
```
Comment (jacob314) [inline packages/cli/src/ui/AppContainer.tsx:835]: this change is a little silly but doesn't hurt.

File: packages/cli/src/ui/components/InputPrompt.tsx [hunk 3]
```diff
@@ -143,15 +140,6 @@ export const InputPrompt: React.FC<InputPromptProps> = ({
   const pasteTimeoutRef = useRef<NodeJS.Timeout | null>(null);
```
Comment (jacob314) [inline packages/cli/src/ui/components/InputPrompt.tsx:143]: this code wasn't actually needed as useCommandCompletion wasn't actually using dirs.

**Review by scidomino — APPROVED** [review]

**Review by abhipatel12 — APPROVED** [review]
LGTM!

**Review by LIHUA919 — APPROVED** [review]
