### PR TITLE
fix(infra) - Add pr number to the release branch name for final step of release

### LINKED ISSUE #10344: Bug: Patch Broken by Single threading
This card https://github.com/google-gemini/gemini-cli/issues/9205

Changed the way branches for hotfixes are named. However we can see from this faling release that that update has not been plumbed through to the rest of the patch process. https://github.com/google-gemini/gemini-cli/actions/runs/18166325058/job/51709450193

Lets finish this out. @shishu314 had worked on this previously, might be good to get context from there if he isn't the one that picks it up.

### PR DESCRIPTION
**Pull request by shishu314**
## TLDR

Add pr number to the release branch

## Dive Deeper

This fixes the branch fetching as well as adds the pr number to the release branch when looking up release branch

## Reviewer Test Plan

`gh workflow run release-patch-2-trigger.yml --ref ss/patchPlumb -f ref=hotfix/v0.7.0-preview.1/preview/cherry-pick-4c5ab80 -f workflow_ref=ss/patchPlumb -f dry_run=true`

[Dry Run] (https://github.com/google-gemini/gemini-cli/actions/runs/18174208838/job/51736104306)

> Running command: gh workflow run release-patch-3-release.yml --ref main --field type=preview --field dry_run=true --field force_skip_tests=false --field release_ref=release/v0.7.0-preview.1-pr-10283 --field original_pr=10283

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | ❓  | ❓  | ❓  |
| npx      | ❓  | ❓  | ❓  |
| Docker   | ❓  | ❓  | ❓  |
| Podman   | ❓  | -   | -   |
| Seatbelt | ❓  | -   | -   |

## Linked issues / bugs

Fixes #10344

### CODE REVIEW

**Review by richieforeman — APPROVED** [review]
LG

File: scripts/releasing/patch-trigger.js [hunk 1]
```diff
@@ -101,45 +101,32 @@ async function main() {
...
-
   // Try to find the original PR that requested this patch
   let originalPr = null;
   if (!testMode) {
     try {
       console.log('Looking for original PR using search...');
       const { execFileSync } = await import('node:child_process');
 
+      // Split search string into searchArgs to prevent triple escaping on the quoted filters
+      const searchArgs =
```
Comment (mattKorwel) [inline scripts/releasing/patch-trigger.js:112]: I've lost the thread on this but can't we just parse this info from the branch names? That might be more deterministic than seraching?

**Review by mattKorwel — APPROVED** [review]
I see the testing for step 2 and 3 🙇 thanks for making sure to put that in. I don't love the searching, per the comment but if its working for now i don't think its a blocker.

File: scripts/releasing/patch-trigger.js (hunk 1 above)
Comment (shishu314) [reply scripts/releasing/patch-trigger.js:112]: So we've included the original PR number on the **release** branches, but not the **hotfix** branch, which is the input passed in here.
Release branch ex - release/v0.7.0-preview.1-pr-1234
Hotfix branch ex- hotfix/v0.7.0-preview.1/preview/cherry-pick-4c5ab80

Hotfix branch does not have the original pr info. Unless we modify our workflow to pass that along as well. Open to doing that if you think it's a better idea.

Comment (mattKorwel) [reply scripts/releasing/patch-trigger.js:112]: Given we have a lot in flight, lets keep it as is. If we see failures because of searching, the error message "couldn't find the original pr" we'll come back and switch it up. LGTM lets merge it.
