### PR TITLE
fix(hooks): propagate stopHookActive in AfterAgent retry path (#20426)

### LINKED ISSUE #20426: AfterAgent hooks endless loop in version 0.30.0？
I use 'stop_hook_active' to stop afteragent hook retry, but it did not work.I outout stop_hook_active to log file, and it always false.

stop_hook_active remains permanently false due to missing state propagation

Analysis:

Incomplete Function Call: In client.ts:205, the call to fireAfterAgentEvent fails to pass the third argument, stopHookActive.

Default Value Overwrites: Because the argument is missing, it defaults to false in both hookSystem.ts:251 and hookEventHandler.ts:159.

Retry Logic Gap: Within the retry logic in client.ts:897-905, the recursive call to sendMessageStream lacks a mechanism to flag the request as a "retry" attempt, preventing the state from being correctly updated.

Is this the intended behavior, or am I misusing?

Below is my .sh file:

input=$(cat)
prompt_response=$(echo "$input" | jq -r '.prompt_response // ""')
is_active=$(echo "$input" | jq -r '.stop_hook_active // false')

{
  echo "--- Hook Execution @ $(date) ---"
  echo "Stop Hook Active: $is_active"
  echo "Prompt Response (Truncated): ${prompt_response:0:100}..." 
  echo ""
  echo "=== Full STDIN Input ==="
  echo "$input"
  echo "=== End STDIN ==="
  echo "--------------------------------"
} >> /tmp/test_hook.log

if [ "$is_active" != "true" ]; then
  cat <<EOF
{
  "decision": "deny",
  "reason": "test retry."
}
EOF
  exit 0
fi

echo '{}'
exit 0

### PR DESCRIPTION
**Pull request by Aarchi-07**
## Summary

The AfterAgent hook's stop_hook_active field was never set to true on retries, causing hooks that rely on it to create infinite deny loops.

Root cause: fireAfterAgentHookSafe called fireAfterAgentEvent without passing stopHookActive, and the activeCalls guard prevented the hook from firing on recursive retry calls.

Fix:
- Add stopHookActive parameter to fireAfterAgentHookSafe and sendMessageStream
- On retry, stopHookActive bypasses the activeCalls guard so the AfterAgent hook fires on nested calls
- Pass stopHookActive=true on the retry path so hooks receive stop_hook_active: true and can break the loop

## Test Fixes
Two pre-existing issues in the `clearContext` AfterAgent E2E test were uncovered by this fix:
- [hooks-agent-flow.test.ts](https://github.com/google-gemini/gemini-cli/blob/main/integration-tests/hooks-agent-flow.test.ts#L201-L202): Corrected placement of `enabled: true` from inside `hooks` to inside `hooksConfig` (schema validation error on startup).
- [hooks-system.after-agent.responses](https://github.com/google-gemini/gemini-cli/blob/main/integration-tests/hooks-system.after-agent.responses): Added a 3rd fake response, which correctly makes the AfterAgent hook fire on the retry turn and consumes an additional LLM call that the test file previously lacked a response for.

## Related Issues

Fixes #20426

## Pre-Merge Checklist

- [x] Updated relevant documentation and README (if needed)
- [x] Added/updated tests (if needed)
- [x] Noted breaking changes (if any): none
- [x] Validated on required platforms/methods:
  - [x] Windows
    - [x] npm run
    - [x] npx
    - [x] Docker

### CODE REVIEW

**Comment by Aarchi-07** [comment]
@scidomino Done. Please review again.

File: packages/core/src/core/client.ts [hunk 1]
```diff
@@ -183,10 +183,11 @@ export class GeminiClient {
     currentRequest: PartListUnion,
     prompt_id: string,
     turn?: Turn,
+    stopHookActive: boolean = false,
   ): Promise<DefaultHookOutput | undefined> {
     const hookState = this.hookStateMap.get(prompt_id);
-    // Only fire on the outermost call (when activeCalls is 1)
-    if (!hookState || hookState.activeCalls !== 1) {
+    // Fire on the outermost call (when activeCalls is 1) OR if it's a retry (stopHookActive)
```
Comment (scidomino) [inline packages/core/src/core/client.ts]: The second half of the comment is useless as it just restates the code.

**Review by scidomino — COMMENTED** [review]
Please update the description to accurately reflect the new implemention and make the other change and I will approve.

**Comment by Aarchi-07** [comment]
Updated the description and inline comment, please take a look again @scidomino

**Review by scidomino — APPROVED** [review]

**Comment by Aarchi-07** [comment]
Thank you! I'll get that updated right away.

**Comment by Aarchi-07** [comment]
@scidomino Could you please approve the workflows so I can test the implementation? Thanks.

**Review by scidomino — APPROVED** [review]
