### PR TITLE
Fix shell tool description to be os-specific

### LINKED ISSUE #4616: failed to delete a directory with rd command
### What happened?

gemini created a diractory and some files inside, then I ve asked to undo changes and I ve had error with the remove directory command, so impossible de remove the directory

### What did you expect to happen?

remove the directory created few minutes ago

### Client information

* **CLI Version:** 0.1.13
* **Git Commit:** 412b78c5 (local modifications)
* **Operating System:** win32 v22.17.1
* **Sandbox Environment:** no sandbox
* **Model Version:** gemini-2.5-pro
* **Memory Usage:** 173.3 MB

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by scidomino**
## TLDR

Fixes the shell tool description to not always be linux-specific.

## Reviewer Test Plan

Ask GCLI to delete a file in windows and verify it uses "del" instead of "rm".

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | ❓  | x  | ❓  |
| npx      | ❓  | ❓  | ❓  |
| Docker   | ❓  | ❓  | ❓  |
| Podman   | ❓  | -   | -   |
| Seatbelt | ❓  | -   | -   |

## Linked issues / bugs

Fixes https://github.com/google-gemini/gemini-cli/issues/4616

### CODE REVIEW

File: packages/core/src/tools/shell.ts [hunk 1]
```diff
@@ -311,14 +301,42 @@ export class ShellTool extends BaseDeclarativeTool<
       Exit Code: Exit code or \`(none)\` if terminated by signal.
       Signal: Signal number or \`(none)\` if no signal was received.
       Background PIDs: List of background processes started or \`(none)\`.
-      Process Group PGID: Process group started or \`(none)\``,
+      Process Group PGID: Process group started or \`(none)\\`;
```
Comment (jacob314) [inline packages/core/src/tools/shell.ts]: can we add a golden tests for windows and non windows  it is easier to visually make sure the output looks like we would want on both platforms?
I would nudge gemini cli to align this to the golden tests already available for the system prompt.

**Review by jacob314 — APPROVED** [review]
Can you follow up using the snapshot files like in the system prompt test? That will make it easier for people to update the goldens.

**Comment by scidomino** [comment]
> Can you follow up using the snapshot files like in the system prompt test? That will make it easier for people to update the goldens.

Oh! My bad. I didn't understand what you meant. Will do!
