### PR TITLE
fix(core): ensure silent local subagent delegation while allowing remote confirmation

### LINKED ISSUE #16077: Support execution confirmation for remote agents
### What would you like to be added?

Tool Calls to remote agents should require confirmation

### Why is this needed?

While local subagents are read only for the moment, remote agents require explicit approval before executing as they may have mutating effects server-side.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by adamfweidman**
## Summary

Updated agent delegation behavior to default to `ask_user` in the policy engine while ensuring local agent delegation remains silent and non-interactive.

## Details

This change adjusts the default policy for the `delegate_to_agent` tool from `allow` to `ask_user`. To maintain the established user experience for local agents (where sub-agent actions are already checked individually by the policy engine), the `DelegateInvocation` has been updated to explicitly bypass confirmation for local agents. This ensures that:
   1. **Local Agents:** Continue to execute silently as their internal tool calls provide the necessary security boundaries.
   2. **Remote Agents:** Can now properly participate in the confirmation flow, allowing them to prompt the user when a delegation occurs if required by their remote configuration.

## Related Issues

(re)-fixes: https://github.com/google-gemini/gemini-cli/issues/16077

## How to Validate

Follow instructions for starting https://github.com/adamfweidman/deep-research-adk/ locally

Ensure calls to the deep research agent begin by prompting the user for confirmation

## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [ ] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [ ] Validated on required platforms/methods:
  - [ ] MacOS
    - [x] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

File: packages/core/src/agents/delegate-to-agent-tool.ts [hunk 1]
```diff
@@ -172,7 +172,8 @@ class DelegateInvocation extends BaseToolInvocation<
   ): Promise<ToolCallConfirmationDetails | false> {
     const definition = this.registry.getDefinition(this.params.agent_name);
     if (!definition || definition.kind !== 'remote') {
-      return super.shouldConfirmExecute(abortSignal);
+      // Local agents should execute silently
```
Comment (NTaylorMullen) [inline packages/core/src/agents/delegate-to-agent-tool.ts]:
```suggestion
      // Local agents should execute without confirmation. Inner tool calls will bubble up their own confirmations to the user.
```

File: packages/core/src/policy/policies/agent.toml [hunk 2]
```diff
@@ -27,5 +27,5 @@
 
 [[rule]]
 toolName = "delegate_to_agent"
-decision = "allow"
+decision = "ask_user"
```
Comment (NTaylorMullen) [inline packages/core/src/policy/policies/agent.toml:30]: Just for my own education, ask_user in this case == call `shouldConfirmExecute`?

**Review by NTaylorMullen — APPROVED** [review]

File: packages/core/src/policy/policies/agent.toml (hunk 2 above)
Comment (adamfweidman) [reply packages/core/src/policy/policies/agent.toml:30]: yes!
