### PR TITLE
Fix Arrow Keys and make Kitty Protocol more robust

### LINKED ISSUE #6227: In Ghostty, arrow keys not working since 0.1.21 update
### What happened?

The previous version used to work without any issues. This morning, I updated gemini to `0.1.21` and it started misbehaving.

I cannot use the arrow keys as before to go back in history or use it to select options for commands.

See the screen shot below.

Image

### What did you expect to happen?

I expect the arrow keys to work as normal.

### Client information

<details>

```console
$ gemini /about

╭───────────────────────────────────────────────────────────╮
│                                                           │
│ About Gemini CLI                                          │
│                                                           │
│ CLI Version         0.1.21                                │
│ Git Commit          055fe46d                              │
│ Model               gemini-2.5-flash                      │
│ Sandbox             no sandbox                            │
│ OS                  linux                                 │
│ Auth Method         OAuth                                 │
│                                                           │
╰───────────────────────────────────────────────────────────╯

```

</details>

### Login information

_No response_

### Anything else we need to know?

I switched to Konsole and arrow keys do work there.

### PR DESCRIPTION
**Pull request by deepankarsharma**
## TLDR

Fix for Arrow Keys and make Kitty Protocol detection more robust

## Dive Deeper

- Add prefix “peel-and-continue” parser to consume one complete sequence at a time, preventing buffer overflow and stray fragments
- Support parameterized functional keys ESC[1;NmX]:
  - Arrows A/B/C/D → up/down/right/left
  - Home/End H/F → home/end
  - F1–F4 P/Q/R/S → f1/f2/f3/f4
- Handle reverse Tab as Shift+Tab:
  - Legacy ESC[Z
  - Parameterized ESC[1;2Z
- Accept legacy arrows ESC[A/B/C/D] when Kitty is enabled (no modifiers).
- Map tilde-coded CSI sequences (ESC[<number>~):
  - 1 → home, 2 → insert, 3 → delete, 4 → end, 5 → pageup, 6 → pagedown
  - Fixes spillage like “9~” on Delete by consuming the full sequence.
- Raise MAX_KITTY_SEQUENCE_LENGTH from 12 → 32.
- Normalize modifiers when “event types” bit is set (>=128) and introduce named bit constants:
  - MODIFIER_SHIFT_BIT, MODIFIER_ALT_BIT, MODIFIER_CTRL_BIT
- Improve readability: symbol→name lookup table and inline regex comments.

Tests
- Parameterized functional keys (Home/End/F1–F4)
- Reverse Tab forms (ESC[Z, ESC[1;2Z])
- Legacy arrows under Kitty
- Tilde-coded function keys (Delete/Home/End/PageUp/PageDown/Insert)
- Double-tap Delete emits two delete events
- Concatenated sequences in one chunk
- Incomplete + complete sequence handling

## Reviewer Test Plan

1. Run test suite
2. Recreate using user setups from #6227

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | ❓  | ❓  | Y  |
| npx      | ❓  | ❓  | ❓  |
| Docker   | ❓  | ❓  | ❓  |
| Podman   | ❓  | -   | -   |
| Seatbelt | ❓  | -   | -   |

## Linked issues / bugs

- Resolves #6227

### CODE REVIEW

File: packages/cli/src/ui/contexts/KeypressContext.tsx [hunk 1]
```diff
@@ -114,79 +120,282 @@ export function KeypressProvider({
...
+            ctrl: false,
+            meta: false,
+            shift: false,
+            paste: false,
+            sequence: buffer.slice(0, m[0].length),
+            kittyProtocol: true,
+          },
+          length: m[0].length,
         };
       }
```
[the remark this answers is not in the document]
Comment (jacob314) [reply packages/cli/src/ui/contexts/KeypressContext.tsx]: this seems worth addressing

[the remark this answers is not in the document]
Comment (deepankarsharma) [reply packages/cli/src/ui/contexts/KeypressContext.tsx]: Done!

File: packages/cli/src/ui/contexts/KeypressContext.tsx [hunk 2]
```diff
@@ -116,48 +121,283 @@ export function KeypressProvider({
...
-      const keyNameMap: Record<number, string> = {
-        [CHAR_CODE_ESC]: 'escape',
-        [KITTY_KEYCODE_TAB]: 'tab',
-        [KITTY_KEYCODE_BACKSPACE]: 'backspace',
-        [KITTY_KEYCODE_ENTER]: 'return',
-        [KITTY_KEYCODE_NUMPAD_ENTER]: 'return',
-      };
-
-      if (keyCode in keyNameMap) {
+    // New: Parse a single complete kitty sequence from the start (prefix) of the
```
Comment (jacob314) [inline packages/cli/src/ui/contexts/KeypressContext.tsx]: Remove the words `New: `

File: packages/cli/src/ui/contexts/KeypressContext.tsx [hunk 3]
```diff
@@ -116,48 +121,283 @@ export function KeypressProvider({
...
+    // This lets us "peel off" one complete event when multiple sequences arrive
+    // in a single chunk, preventing buffer overflow and fragmentation.
+    // Parse a single complete kitty/parameterized/legacy sequence from the start
+    // of the buffer and return both the parsed Key and the number of characters
+    // consumed. This enables peel-and-continue parsing for batched input.
+    const parseKittyPrefix = (
+      buffer: string,
+    ): { key: Key; length: number } | null => {
+      // 0) Reverse Tab (legacy): ESC [ Z
+      //    Treat as Shift+Tab for UI purposes.
```
Comment (jacob314) [inline packages/cli/src/ui/contexts/KeypressContext.tsx:139]: can you add a comment clarifying why is this treated like shift-tab instead of just tab?

File: packages/cli/src/ui/contexts/KeypressContext.tsx [hunk 4]
```diff
@@ -116,48 +121,283 @@ export function KeypressProvider({
...
+                sequence: buffer.slice(0, m[0].length),
+                kittyProtocol: true,
+              },
+              length: m[0].length,
+            };
+          }
+        }
+
+        // Escape
+        if (keyCode === CHAR_CODE_ESC) {
```
Comment (jacob314) [inline packages/cli/src/ui/contexts/KeypressContext.tsx]: can you merge the following cases into a single case using a Map from keycode to name?

File: packages/cli/src/ui/contexts/KeypressContext.tsx [hunk 5]
```diff
@@ -285,18 +525,40 @@ export function KeypressProvider({
...
+                kittySequenceBuffer = kittySequenceBuffer.slice(nextStart);
+                continue;
+              }
+              break;
+            }
             if (debugKeystrokeLogging) {
               console.log(
-                '[DEBUG] Kitty sequence parsed successfully:',
-                kittySequenceBuffer,
+                '[DEBUG] Kitty sequence parsed successfully (prefix):',
```
Comment (jacob314) [inline packages/cli/src/ui/contexts/KeypressContext.tsx]: can you only add prefix if it happens that there are additional chars to parse that we haven't parsed yet?

File: packages/cli/src/ui/contexts/KeypressContext.test.tsx [hunk 6]
```diff
@@ -584,4 +587,257 @@ describe('KeypressContext - Kitty Protocol', () => {
...
+      expect(keyHandler).toHaveBeenCalledWith(
+        expect.objectContaining({ name: 'home' }),
+      );
+    });
+
+    it('should recognize End via CSI[4~', async () => {
+      const keyHandler = vi.fn();
+      const { result } = renderHook(() => useKeypressContext(), { wrapper });
+      act(() => result.current.subscribe(keyHandler));
+      act(() => stdin.sendKittySequence(`\x1b[4~`));
```
Comment (jacob314) [inline packages/cli/src/ui/contexts/KeypressContext.test.tsx]: ask Gemini CLI to parameterize these tests. That will reduce the boilerplate. 
Parameters for the test should be the kittySquence and the name of the key expected.

File: packages/cli/src/ui/contexts/KeypressContext.test.tsx [hunk 7]
```diff
@@ -584,4 +587,257 @@ describe('KeypressContext - Kitty Protocol', () => {
...
+          name: 'left',
+          ctrl: false,
+          meta: false,
+          shift: false,
+        }),
+      );
+    });
+  });
+
+  describe('Legacy Home/End while Kitty enabled', () => {
```
Comment (jacob314) [inline packages/cli/src/ui/contexts/KeypressContext.test.tsx]: nit: is there are reason these aren't just in the parameterized block above with one keystroke per case?

**Comment by jacob314** [comment]
This is a fantastic improvement to the keyboard input handling. Great work!

A few highlights:
*   The move to a "peel-and-continue" parser (`parseKittyPrefix`) is a very robust way to handle batched or fragmented input streams. This should make the CLI much more reliable across different terminal emulators and conditions.
*   The expanded support for a wide range of sequences (parameterized keys, tilde-coded keys, legacy arrows) is comprehensive and will resolve a lot of user friction.
*   The new tests are excellent and cover the new functionality thoroughly, which gives a lot of confidence in these changes.

The code is well-structured and the changes are easy to follow. I don"t have any suggestions for changes. This looks ready to merge once the checks pass.

File: packages/cli/src/ui/contexts/KeypressContext.test.tsx [hunk 8]
```diff
@@ -584,4 +587,257 @@ describe('KeypressContext - Kitty Protocol', () => {
...
+      act(() => result.current.subscribe(keyHandler));
+
+      act(() => stdin.sendKittySequence(`\x1b[1;2Z`));
+      expect(keyHandler).toHaveBeenCalledWith(
+        expect.objectContaining({ name: 'tab', shift: true }),
+      );
+    });
+  });
+
+  describe('Legacy arrows while Kitty enabled', () => {
```
Comment (jacob314) [inline packages/cli/src/ui/contexts/KeypressContext.test.tsx]: is there a reason this isn't in the parameterized block above with one keystroke per case?

**Review by jacob314 — COMMENTED** [review]
Looks good! Approved after these minor comments are addressed.
Thank you for continuing to dive into making this code more robust!

File: packages/cli/src/ui/contexts/KeypressContext.test.tsx (hunk 8 above)
Comment (deepankarsharma) [reply packages/cli/src/ui/contexts/KeypressContext.test.tsx]: Moved

File: packages/cli/src/ui/contexts/KeypressContext.test.tsx (hunk 6 above)
Comment (deepankarsharma) [reply packages/cli/src/ui/contexts/KeypressContext.test.tsx]: Done.

File: packages/cli/src/ui/contexts/KeypressContext.tsx (hunk 5 above)
Comment (deepankarsharma) [reply packages/cli/src/ui/contexts/KeypressContext.tsx]: Done

File: packages/cli/src/ui/contexts/KeypressContext.tsx (hunk 4 above)
Comment (deepankarsharma) [reply packages/cli/src/ui/contexts/KeypressContext.tsx]: Done.

File: packages/cli/src/ui/contexts/KeypressContext.tsx (hunk 3 above)
Comment (deepankarsharma) [reply packages/cli/src/ui/contexts/KeypressContext.tsx:139]: Done

File: packages/cli/src/ui/contexts/KeypressContext.tsx (hunk 2 above)
Comment (deepankarsharma) [reply packages/cli/src/ui/contexts/KeypressContext.tsx]: Done.

**Comment by hassankhan2608** [comment]
when this will be merged ??

**Review by jacob314 — APPROVED** [review]
lgtm

**Comment by deepankarsharma** [comment]
@hassankhan2608 - thanks to @jacob314 this is headed to be merged today :)

**Review by jacob314 — APPROVED** [review]
lgtm
