### PR TITLE
fix(core): properly support allowRedirect in policy engine

### LINKED ISSUE #16450: Permanent Tool Call Permissions Not Working
### What happened?

i allowed permanent tool allowances in settings. i tell gemini cli to allow tools for all future requests, but that doesn't work, I still have to approve them.

### What did you expect to happen?

i expected to not have to approve anymore

### Client information

* **CLI Version:** 0.23.0
* **Git Commit:** 3ff055840
* **Session ID:** 1e4d8e0f-9d6e-4849-910d-1c80600a6a47
* **Operating System:** darwin v22.20.0
* **Sandbox Environment:** no sandbox
* **Model Version:** auto-gemini-3
* **Memory Usage:** 292.8 MB
* **Terminal Name:** Unknown
* **Terminal Background:** #282c33
* **Kitty Keyboard Protocol:** Unsupported

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by scidomino**
## Summary

Fixed a bug where shell commands with redirection (e.g. `echo > file`) would ask for approval on every call even after being permanently allowed by the user.

## Details

- Updated `splitCommands` in `shell-utils.ts` to filter out redirection tokens (`>`, `<`, `<<`, `<<<`) from recursive checks. The `PolicyEngine` was treating them as standalone commands and failing the authorization check. The top-level command still handles the actual redirection security check correctly.
- Enabled `camelCase` support for `allowRedirection` and `denyMessage` in TOML parsing (`toml-loader.ts`), preserving `snake_case` for backwards compatibility. This makes those two flags consistent with the rest of the camel cased fields in the policy engine.
- Plumbed the `allowRedirection` flag from the UI prompt down to policy persistence.
- Added regression tests for redirection parsing and TOML persistence.
- Documented the `allowRedirection` field in `docs/reference/policy-engine.md`.

## Related Issues

Fixes #16450

## How to Validate

1. Run a shell command with redirection (e.g., `echo "test" > redirection_test.txt`).
2. When prompted, select "Allow this command for future sessions".
3. Run the exact same command again. It should now execute automatically without re-prompting.
4. Review the `~/.gemini/policies/auto-saved.toml` file to verify the `allowRedirection = true` flag was saved.

## Pre-Merge Checklist

- [x] Updated relevant documentation and README (if needed)
- [x] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [ ] Validated on required platforms/methods:
  - [x] MacOS
    - [x] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

File: packages/core/src/policy/toml-loader.ts [hunk 1]
```diff
@@ -478,9 +480,10 @@ export async function loadPoliciesFromToml(
                   modes: rule.modes,
                   interactive: rule.interactive,
                   toolAnnotations: rule.toolAnnotations,
-                  allowRedirection: rule.allow_redirection,
+                  allowRedirection:
+                    rule.allowRedirection ?? rule.allow_redirection,
                   source: `${tierName.charAt(0).toUpperCase() + tierName.slice(1)}: ${file}`,
-                  denyMessage: rule.deny_message,
+                  denyMessage: rule.denyMessage ?? rule.deny_message,
```
Comment (NTaylorMullen) [inline packages/core/src/policy/toml-loader.ts:486]:
```suggestion
                  denyMessage: rule.denyMessage ?? rule.denyMessage,
```

File: packages/core/src/tools/shell.ts [hunk 2]
```diff
@@ -100,10 +100,12 @@ export class ShellToolInvocation extends BaseToolInvocation<
     ) {
       const command = stripShellWrapper(this.params.command);
       const rootCommands = [...new Set(getCommandRoots(command))];
+      const allowRedirection = hasRedirection(command) ? true : undefined;
```
Comment (NTaylorMullen) [inline packages/core/src/tools/shell.ts:103]: So if a command has redirection we auto-allow it? That's how this reads anyways. Feels odd to have here vs. in the consumer who looks up the policyupdateoptions

File: packages/core/src/utils/shell-utils.ts [hunk 3]
```diff
@@ -663,7 +663,16 @@ export function splitCommands(command: string): string[] {
     return [];
   }
 
-  return parsed.details.map((detail) => detail.text).filter(Boolean);
+  return parsed.details
+    .filter(
+      (detail) =>
+        // Redirection tokens are filtered as they are validated at the top level by PolicyEngine
+        !detail.name.startsWith('redirection') &&
```
Comment (NTaylorMullen) [inline packages/core/src/utils/shell-utils.ts]: Doing string look ups via name comes across as brittle, is there a better way?

**Review by gundermanc — APPROVED** [review]

File: packages/core/src/policy/toml-loader.ts (hunk 1 above)
Comment (scidomino) [reply packages/core/src/policy/toml-loader.ts:486]: No. We wouldn't want to make that change since we purposefully want to support the old snake_case style as a fallback.

File: packages/core/src/utils/shell-utils.ts (hunk 3 above)
Comment (scidomino) [reply packages/core/src/utils/shell-utils.ts]: There isn't. But your comment helped me realize that we already filter for these elsewhere and can reuse the array of known redirects.

File: packages/core/src/tools/shell.ts (hunk 2 above)
Comment (scidomino) [reply packages/core/src/tools/shell.ts:103]: No. This is the code that runs when the user has picks "Always allow". This is basically just constructing a policy that would have auto-approved the command (whatever it is).

Comment (NTaylorMullen) [reply packages/core/src/tools/shell.ts:103]: Ah why not always pass `true` then? If there's no redirection then it doesn't do anything anyways 😄

Comment (scidomino) [reply packages/core/src/tools/shell.ts:103]: That would work, but would make the policy more lenient than strictly necessary. So I think it's best to keep it as is.

File: packages/core/src/utils/shell-utils.test.ts [hunk 4]
```diff
@@ -304,6 +305,40 @@ describeWindowsOnly('PowerShell integration', () => {
   });
 });
 
+describe('splitCommands', () => {
```
Comment (kschaab) [inline packages/core/src/utils/shell-utils.test.ts:308]: Missing test for escaped redirection token `\>`

**Review by kschaab — APPROVED** [review]
