### PR TITLE
fix(mcp): Display OAuth authentication messages in CLI UI instead of debug console

### LINKED ISSUE #6808: bug(cli): /mcp auth hangs and does not show subsequent messages in normal mode
### What happened?

When running the `/mcp auth <Server Name>` command, the CLI displays the initial message "Starting OAuth authentication for MCP server" but then hangs. No subsequent messages, such as the authentication URL or confirmation codes, are displayed. This prevents the user from completing the OAuth flow.

A workaround is to run the CLI in debug mode (`gemini -d`). In debug mode, the authentication messages are displayed correctly, and the flow can be completed.

### What did you expect to happen?

After running the `/mcp auth <Server Name>` command, the CLI should display all necessary information for the user to proceed with the authentication, including the URL to open in a browser.

### Client information

<details>

```console
CLI Version 0.1.22
Git Commit 5fe4e023
Model gemini-2.5-pro
Sandbox no sandbox
OS linux
Auth Method OAuth
GCP Project hardy-position-464100-s4
```

</details>

### Login information

This issue occurs when attempting to log in to an MCP server using the OAuth flow.

### Anything else we need to know?

This issue occurs when attempting to log in to an MCP server using the OAuth flow.

### PR DESCRIPTION
**Pull request by Louis454545**
## Summary

- Fixed OAuth authentication messages not being visible in normal CLI mode
- Implemented callback-based architecture to display messages in main UI
- Maintains backward compatibility with existing OAuth implementations

## Details

This PR resolves issue #6808 where critical OAuth authentication messages (including authentication URLs) were only visible in debug mode.

### Root Cause
The CLI uses ConsolePatcher to intercept console.log calls and treats them as debug messages, hidden by default. The OAuth provider in the core package was using console.log for user-facing messages, creating an architectural mismatch.

### Solution
Implemented the callback-based solution suggested in the issue:

1. **Added `MCPOAuthMessageHandler` interface** - Provides a clean contract for message display
2. **Modified `MCPOAuthProvider.authenticate()`** - Accepts optional message handler parameter  
3. **Updated CLI `/mcp auth` command** - Provides proper UI message handler
4. **Maintained backward compatibility** - Falls back to console.log when no handler provided

### Changes Made
- `packages/core/src/mcp/oauth-provider.ts`: Added message handler interface and updated authenticate method
- `packages/cli/src/ui/commands/mcpCommand.ts`: Implemented message handler for UI display
- `packages/core/src/index.ts`: Exported new interface

### Test Plan
- [x] Build and type checking pass
- [x] Linting passes  
- [x] OAuth provider tests pass
- [x] Maintains API compatibility

Fixes google-gemini/gemini-cli#6808

### CODE REVIEW

**Comment by yoichiro** [comment]
@Louis454545 Thanks a lot for this pull request — really appreciate you jumping on this so quickly!

I tested it with `gemini mcp auth uuid` (screenshot attached). The flow works, but the user-facing output is hard to read:

* Every line shows a log level/marker (e.g., `i` / `[info]`) even for instructions.
* There’s a blank line after each message, which makes the output long and pushes the important URL off screen.
* Progress logs and user instructions are mixed together.

**Suggestion:** default to a compact, human-readable "user mode," and reserve noisy details for `--verbose` / `--debug`. Also group the instructions into a single block.

**Proposed default output**

```
Starting OAuth for MCP server "uuid"…

✓ No authorization URL; using OAuth discovery
✓ Dynamic client registration successful
→ Opening your browser for OAuth sign-in...

If the browser does not open, copy and paste this URL into your browser:
http://localhost:8080/auth?client_id=...&response_type=code&redirect_uri=...

Tip: Triple-click the line above to select the entire URL.
```

**Logging policy (rough outline)**

* **Default:** human-readable messages without `[INFO]` prefixes and without extra blank lines.
* **--verbose / --debug:** include log levels and low-level details (discovery endpoints, code challenge, etc.).
* **Errors:** show a clear, single-line summary and next steps; include full details only with `--verbose`.

Happy to test another revision or send a follow-up PR that applies this formatting.

スクリーンショット 2025-08-24 204936

**Comment by Louis454545** [comment]
> @Louis454545 Thanks a lot for this pull request — really appreciate you jumping on this so quickly!
> 
> I tested it with `gemini mcp auth uuid` (screenshot attached). The flow works, but the user-facing output is hard to read:
> 
> * Every line shows a log level/marker (e.g., `i` / `[info]`) even for instructions.
> * There’s a blank line after each message, which makes the output long and pushes the important URL off screen.
> * Progress logs and user instructions are mixed together.
> 
> **Suggestion:** default to a compact, human-readable "user mode," and reserve noisy details for `--verbose` / `--debug`. Also group the instructions into a single block.
> 
> **Proposed default output**
> 
> ```
> Starting OAuth for MCP server "uuid"…
> 
> ✓ No authorization URL; using OAuth discovery
> ✓ Dynamic client registration successful
> → Opening your browser for OAuth sign-in...
> 
> If the browser does not open, copy and paste this URL into your browser:
> http://localhost:8080/auth?client_id=...&response_type=code&redirect_uri=...
> 
> Tip: Triple-click the line above to select the entire URL.
> ```
> 
> **Logging policy (rough outline)**
> 
> * **Default:** human-readable messages without `[INFO]` prefixes and without extra blank lines.
> * **--verbose / --debug:** include log levels and low-level details (discovery endpoints, code challenge, etc.).
> * **Errors:** show a clear, single-line summary and next steps; include full details only with `--verbose`.
> 
> Happy to test another revision or send a follow-up PR that applies this formatting.
> 
> スクリーンショット 2025-08-24 204936
> 

Yeah, thanks for the recommendation I think your implementation is much better. I will fix that ! 😀

**Comment by Louis454545** [comment]
@yoichiro here it is !

**Comment by cornmander** [comment]
Thanks for the change! I'll look at this today.

File: packages/cli/src/ui/commands/mcpCommand.ts [hunk 1]
```diff
@@ -383,12 +384,24 @@ const authCommand: SlashCommand = {
         oauthConfig = { enabled: false };
       }
 
-      // Pass the MCP server URL for OAuth discovery
```
Comment (cornmander) [inline packages/cli/src/ui/commands/mcpCommand.ts:388]: please restore this deleted comment

File: packages/core/src/mcp/oauth-provider.ts [hunk 2]
```diff
@@ -576,18 +583,27 @@ export class MCPOAuthProvider {
...
+      } else {
+        console.log(message);
+      }
+    };
+
     if (!config.authorizationUrl && mcpServerUrl) {
-      console.log(
-        'No authorization URL provided, attempting OAuth discovery...',
-      );
+      displayMessage(`Starting OAuth for MCP server "${serverName}"…\n`);
```
Comment (cornmander) [inline packages/core/src/mcp/oauth-provider.ts]: you should consolidate this into a single call to displayMessage()

File: packages/core/src/mcp/oauth-provider.ts [hunk 3]
```diff
@@ -720,30 +734,12 @@ export class MCPOAuthProvider {
...
-    console.log(separator);
-    console.log('');
-    console.log(
-      '💡 TIP: Triple-click to select the entire URL, then copy and paste it into your browser.',
-    );
-    console.log(
-      '⚠️  Make sure to copy the COMPLETE URL - it may wrap across multiple lines.',
-    );
-    console.log('');
+    displayMessage('If the browser does not open, copy and paste this URL into your browser:');
```
Comment (cornmander) [inline packages/core/src/mcp/oauth-provider.ts]: same as above -- you should pass in a single string into displayMessage(). You should preserve the warning text and emojis to copy the entire URL.

File: packages/cli/src/ui/commands/mcpCommand.ts [hunk 4]
```diff
@@ -383,12 +384,24 @@ const authCommand: SlashCommand = {
...
+      const messageHandler: MCPOAuthMessageHandler = {
+        onDisplayMessage: (message: string) => {
+          context.ui.addItem(
```
Comment (cornmander) [inline packages/cli/src/ui/commands/mcpCommand.ts]: Adding @jacob314 to review about whether this is the right way to surface this message in the UI.

**Review by cornmander — COMMENTED** [review]
Overall looks good, please address comments. I've also added @jacob314 to add comments on the UI code.

**Comment by yoichiro** [comment]
@Louis454545 Thanks for the quick follow-ups on this! I pulled the latest and tested with `mcp auth uuid`. The UI is much clearer now—log-level prefixes are gone for user messages, spacing is tighter, and the instructions are grouped into a focused block. The URL + triple-click tip is especially helpful.

This is a big improvement over the initial version. 🙌
Screenshot attached for reference. Happy to help test further tweaks if needed.

> whether this is the right way to surface this message in the UI.

@cornmander @jacob314 I’m also not fully confident that this approach is the right one. That said, personally I think it’s a fairly common abstraction for separating the UI from the logic.

スクリーンショット 2025-08-25 064800

**Comment by yoichiro** [comment]
@Louis454545 @cornmander If possible, I think it would be even better to assign a separate log level to each output message. Users don’t need every message. For example, for the messages touched by this pull request, we could assign levels like this: at the Info level, only “Starting authentication,” “Fallback URL,” and “Authentication complete” need to be shown; the rest can be considered for debugging.

| Message | Level |
|---------|-------|
| Starting OAuth for MCP server "${serverName}"… | Debug |
| ✓ No authorization URL; using OAuth discovery | Debug |
| → Attempting dynamic client registration... | Debug |
| ✓ Dynamic client registration successful | Debug |
| → Opening your browser for OAuth sign-in... <br> If the browser does not open, copy and paste this URL into your browser: <br> ${authUrl} <br> TIP: Triple-click to select the entire URL, then copy and paste it into your browser.<br> ⚠️  Make sure to copy the COMPLETE URL - it may wrap across multiple lines. | Info |
| \n✓ Authorization code received, exchanging for tokens... | Debug |
| ✓ Authentication successful! Token saved. | Debug |
| ✓ Token verification successful: ${tokenPreview} | Debug |

By allowing the displayMessage function to take a level as an argument, we could achieve the above. If you think this proposal makes sense, I’d really appreciate it if you could implement it.

**Comment by cornmander** [comment]
Let's leave that to a follow up, with input from @jacob314 . I do think we need a comprehensive solution for log levels and filtering logs which merits its own issue. Feel free to write a proposal!

**Comment by yoichiro** [comment]
@cornmander OK, I agree your comment.
@jacob314 Could you review this pull request including the architecture and the structure about displaying messages from logics in the `core` pacakge?

File: packages/core/src/mcp/oauth-provider.ts [hunk 5]
```diff
@@ -576,18 +583,27 @@ export class MCPOAuthProvider {
...
    */
   static async authenticate(
     serverName: string,
     config: MCPOAuthConfig,
     mcpServerUrl?: string,
+    messageHandler?: MCPOAuthMessageHandler,
   ): Promise<MCPOAuthToken> {
-    // If no authorization URL is provided, try to discover OAuth configuration
+    // Helper function to display messages through handler or fallback to console.log
+    const displayMessage = (message: string) => {
```
Comment (jacob314) [inline packages/core/src/mcp/oauth-provider.ts:591]: The more idiomatic way to do this is using events using `node:events`.
That will play nicely dispatching from the core package that doesn't use React and listening in the cli package that does.

The best example of the right pattern for this is to use `node:events` EventEmitter

This is used in one place today in the cli package and we should use it more for events we want to listen to in the cli package from core.

Breadcrumbs:
https://github.com/google-gemini/gemini-cli/blob/366483853ef96d081f14338a154c83d5cc0e7520/packages/cli/src/utils/events.ts#L7

appEvents.emit(AppEvent.LogError, errorMessage);

(https://github.com/google-gemini/gemini-cli/blob/366483853ef96d081f14338a154c83d5cc0e7520/packages/cli/src/gemini.tsx#L124)

**Comment by yoichiro** [comment]
@jacob314 Thank you for your comments and the architecture proposal. Indeed, `node:events` is a good solution. I also think it’s better than defining our own callback function types.

@Louis454545 Could you update the differences in this Pull Request to use the `node:events` approach? If it takes too much time, I can handle it as well. However, since I don’t think I can commit directly to this Pull Request, I would probably need to submit a separate one. I believe this issue could be a major barrier, especially for users working with WSL2. Please let me know your thoughts.

**Comment by yoichiro** [comment]
@Louis454545, I have submitted a pull request to the [Louis454545/gemini-cli](https://github.com/Louis454545/gemini-cli) repository regarding the refactoring to use EventEmitter. I would be grateful if you could perform a code review.

https://github.com/Louis454545/gemini-cli/pull/1

**Comment by yoichiro** [comment]
Hi @Louis454545, this branch has conflicts with the main branch. Could you please merge the main branch into this branch or rebase it to resolve the conflicts?

**Comment by yoichiro** [comment]
Hi @jacob314,
I've refactored the code to use EventEmitter for event dispatching instead of the previous custom callback implementation. Could you please take a look and review the changes when you have a moment? Thanks!

File: packages/core/src/mcp/oauth-provider.ts [hunk 6]
```diff
@@ -576,18 +579,27 @@ export class MCPOAuthProvider {
...
    * @param config OAuth configuration
    * @param mcpServerUrl Optional MCP server URL for OAuth discovery
+   * @param messageHandler Optional handler for displaying user-facing messages
    * @returns The obtained OAuth token
    */
   static async authenticate(
     serverName: string,
     config: MCPOAuthConfig,
     mcpServerUrl?: string,
+    events?: EventEmitter,
```
Comment (jacob314) [inline packages/core/src/mcp/oauth-provider.ts:588]: nit: I would suggest making this a required parameter so that we don't accidentally omit passing the event emitter and regress the way this data is logged.

File: packages/core/src/mcp/oauth-provider.ts [hunk 7]
```diff
@@ -7,11 +7,14 @@
 import * as http from 'node:http';
 import * as crypto from 'node:crypto';
 import { URL } from 'node:url';
+import { EventEmitter } from 'node:events';
 import { openBrowserSecurely } from '../utils/secure-browser-launcher.js';
 import { MCPOAuthToken, MCPOAuthTokenStorage } from './oauth-token-storage.js';
 import { getErrorMessage } from '../utils/errors.js';
 import { OAuthUtils } from './oauth-utils.js';
 
+export const OAUTH_DISPLAY_MESSAGE_EVENT = 'oauth-display-message' as const;
```
Comment (jacob314) [inline packages/core/src/mcp/oauth-provider.ts:17]: nit: remove the `as const`

**Review by jacob314 — APPROVED** [review]
lgtm

**Comment by jacob314** [comment]
Thank you again for your contribution. Please resolve the conflicts and then I will ensure it gets merged.

**Comment by yoichiro** [comment]
@jacob314 Thank you for the reviewing!

@Louis454545 I created a pull request to solve the conflicts. Could you review and merge it? Thank you in advance!  https://github.com/Louis454545/gemini-cli/pull/2

**Comment by Louis454545** [comment]
> @jacob314 Thank you for the reviewing!
> 
> @Louis454545 I created a pull request to solve the conflicts. Could you review and merge it? Thank you in advance! [Louis454545#2](https://github.com/Louis454545/gemini-cli/pull/2)

Thanks a lot for the PR! I didn’t have much time to resolve the conflicts myself, really appreciate your help 🙏
@yoichiro

**Review by jacob314 — APPROVED** [review]
lgtm

**Comment by yoichiro** [comment]
@Louis454545 @jacob314 Thanks!
