### PR TITLE
[ide-mode] Send ping every 30 seconds to prevent client from closing connection

### LINKED ISSUE #4333: Fix │ ✖  MCP ERROR (_ide_server): Error: SSE stream disconnected: TypeError: terminated
The SSE stream disconnects after exactly 5 minutes of inactivity due to a bug in the SDK (https://github.com/modelcontextprotocol/typescript-sdk/issues/270). We should send a periodic keep-alive notification to all clients to prevent termination

### PR DESCRIPTION
**Pull request by chrstnb**
## TLDR

Currently, if you leave the cli running without interacting with the MCP server, the client stream will disconnect. This prevents that by sending a heartbeat every 30 seconds.

https://github.com/upstash/context7/issues/341 <- related?

## Reviewer Test Plan

Leave gemini CLI running <5 minutes and confirm the IDE mcp server doesn't time out

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | ❓  | ❓  | ❓  |
| npx      | ❓  | ❓  | ❓  |
| Docker   | ❓  | ❓  | ❓  |
| Podman   | ❓  | -   | -   |
| Seatbelt | ❓  | -   | -   |

## Linked issues / bugs

Fixes #4333

### CODE REVIEW

File: packages/vscode-ide-companion/src/ide-server.ts [hunk 1]
```diff
@@ -57,7 +57,12 @@ export async function startIDEServer(context: vscode.ExtensionContext) {
         },
       });
 
+      const keepAlive = setInterval(() => {
+        transport.send({ jsonrpc: '2.0', method: 'ping' });
+      }, 30000); // Send ping every 30 seconds
```
[the remark this answers is not in the document]
Comment (bdmorgan) [reply packages/vscode-ide-companion/src/ide-server.ts]: @chrstnb can you add this try/catch?

Comment (skeshive) [inline packages/vscode-ide-companion/src/ide-server.ts]: wondering if we can up this to every few minutes instead since the timeout happens after 5? also were you able to confirm this fix keeps the SSE connection alive for longer than 5 min?

File: packages/vscode-ide-companion/src/ide-server.ts [hunk 2]
```diff
@@ -57,7 +57,22 @@ export async function startIDEServer(context: vscode.ExtensionContext) {
         },
       });
 
+      const keepAlive = setInterval(() => {
+        try {
+          transport.send({ jsonrpc: '2.0', method: 'ping' });
+        } catch (e) {
+          // If sending a ping fails, the connection is likely broken.
+          // Log the error and clear the interval to prevent further attempts.
+          console.error(
```
Comment (skeshive) [inline packages/vscode-ide-companion/src/ide-server.ts]: lets use the logger here

**Review by skeshive — DISMISSED** [review]

File: packages/vscode-ide-companion/src/ide-server.ts (hunk 1 above)
Comment (chrstnb) [reply packages/vscode-ide-companion/src/ide-server.ts]: updated to 1 minute! and yes it did keep it alive :)

**Review by NTaylorMullen — APPROVED** [review]
