### PR TITLE
fix(cli): prevent subcommand shadowing and skip auth for commands

### LINKED ISSUE #23173: Fix Yargs Command Shadowing and API Key Requirement for Subcommands
### What happened?
The Gemini CLI uses `yargs` for argument parsing. A greedy default command (`$0 [query..]`) was registered at the top of the command chain, causing it to shadow explicit subcommands like `mcp`, `extensions`, `skills`, and `hooks`. 

When a user runs a subcommand (e.g., `gemini extensions install ...`), `yargs` incorrectly matches it against the default command, treating the subcommand and its arguments as a conversational query. This triggers the main application logic in `gemini.tsx`, which attempts to initialize the Gemini API client. This initialization requires a `GEMINI_API_KEY`, which is not needed for administrative subcommands, leading to a fatal error if the key is missing.

### What did you expect to happen?
- Subcommands should be matched first and executed without requiring a Gemini API key (unless the subcommand itself requires it).
- The default conversational query should only be matched if no explicit subcommand is provided.
- The application should not attempt to initialize the LLM client or enter interactive mode when a management subcommand is being executed.

#### Implementation Plan
1. **Reorder Command Registration in `packages/cli/src/config/config.ts`**
   - Register all explicit subcommands (`mcp`, `extensions`, `skills`, `hooks`) **before** the default `$0` command.
   - Ensure `mcpCommand` is actually registered using `yargsInstance.command(mcpCommand)`.

2. **Add High-Priority Middleware to Set `isCommand`**
   - Add a yargs middleware at the top level of `parseArguments` to explicitly flag when a subcommand is matched.
   ```typescript
   yargsInstance.middleware((argv) => {
     const subcommands = ['mcp', 'extensions', 'extension', 'skills', 'skill', 'hooks', 'hook'];
     if (subcommands.includes(argv._[0] as string)) {
       argv.isCommand = true;
     }
   }, true);
   ```

3. **Update `gemini.tsx` to Respect `isCommand`**
   - Skip authentication (`partialConfig.refreshAuth` and `validateNonInteractiveAuth`) if `argv.isCommand` is true.
   - Skip sandbox/child process relaunching logic if `argv.isCommand` is true.

#### Verification & Testing
- **Manual Verification**: Run `gemini extensions install ...` without a `GEMINI_API_KEY` set and verify it proceeds to installation.
- **Unit Tests**: Ensure that `argv.isCommand` is correctly set in `parseArguments` for various subcommands.

### PR DESCRIPTION
**Pull request by mattKorwel**
## Summary

This PR fixes an issue where the Gemini CLI's greedy default command (`$0 [query..]`) shadowed administrative subcommands like `mcp`, `extensions`, `skills`, and `hooks`. This caused subcommands to be incorrectly treated as conversational queries, triggering unnecessary authentication checks and sandbox relaunches that would fail if a `GEMINI_API_KEY` was missing.

## Details

- **Reordered Command Registration**: In `packages/cli/src/config/config.ts`, explicit subcommands are now registered **before** the default query command to ensure priority matching.
- **Added `isCommand` Middleware**: Implemented a yargs middleware to explicitly flag when a management subcommand is matched via `argv['isCommand'] = true`.
- **Bypassed Auth & Sandbox for Commands**: Updated `packages/cli/src/gemini.tsx` to skip `refreshAuth` and sandbox relaunching when `argv.isCommand` is true. This enables administrative tasks to run without an API key.
- **Restored Lost Logic**: Re-implemented the `.check()`, `.fail()`, and global `debug` option that were inadvertently removed during recent refactoring, ensuring robust flag validation (e.g., preventing conflicting prompt flags).
- **Unconditional Registration**: Subcommands are now registered unconditionally, allowing `yargs` to handle help and validation correctly even if the underlying feature is disabled in settings.

## Related Issues

Fixes #23173

## How to Validate

1. **Manual Verification**: Run `gemini extensions list` or `gemini mcp list` without a `GEMINI_API_KEY` environment variable. The command should execute successfully (showing an empty list or help) instead of failing with an authentication error.
2. **Automated Tests**: Run the configuration unit tests:
   ```bash
   npm test -w @google/gemini-cli -- src/config/config.test.ts
   ```
   Verify that the new `isCommand middleware` test suite passes and that existing validation tests (like conflicting flags) are restored and passing.

## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [x] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [x] Validated on required platforms/methods:
  - [x] MacOS
    - [x] npm run

### CODE REVIEW

File: packages/cli/src/config/config.ts [hunk 1]
```diff
@@ -153,7 +153,7 @@ export function getRequestedWorktreeName(
 }
 
 export async function parseArguments(
-  settings: MergedSettings,
+  _settings: MergedSettings,
```
Comment (scidomino) [inline packages/cli/src/config/config.ts]: Why we this renamed? I associate a leading underscore with an arg not being used, but this is used.

File: packages/cli/src/config/config.ts [hunk 2]
```diff
@@ -163,12 +163,76 @@ export async function parseArguments(
...
+      if (argv['prompt'] && argv['promptInteractive']) {
+        return 'Cannot use both --prompt (-p) and --prompt-interactive (-i) together';
+      }
+      if (argv['yolo'] && argv['approvalMode']) {
+        return 'Cannot use both --yolo (-y) and --approval-mode together. Use --approval-mode=yolo instead.';
+      }
+      if (
+        argv['outputFormat'] &&
+        !['text', 'json', 'stream-json'].includes(
+          // eslint-disable-next-line @typescript-eslint/no-unsafe-type-assertion
```
Comment (scidomino) [inline packages/cli/src/config/config.ts]: instead of disabling the lint, do a typeof assertion.

File: packages/cli/src/config/config.ts [hunk 3]
```diff
@@ -163,12 +163,76 @@ export async function parseArguments(
...
+    // Ensure validation flows through .fail() for clean UX
+    .fail((msg, err) => {
+      if (err) throw err;
+      throw new Error(msg);
+    })
+    .check((argv) => {
+      // The 'query' positional can be a string (for one arg) or string[] (for multiple).
+      // This guard safely checks if any positional argument was provided.
+      // eslint-disable-next-line @typescript-eslint/no-unsafe-type-assertion
+      const query = argv['query'] as string | string[] | undefined;
```
Comment (scidomino) [inline packages/cli/src/config/config.ts]: instead of disabling the lint do separate typeof assertions.

File: plans/implemented/fix-typeerror-config.md [hunk 4]
```diff
@@ -0,0 +1,46 @@
+# Plan - Fix Subcommand Shadowing and TypeError in Config
```
Comment (scidomino) [inline plans/implemented/fix-typeerror-config.md]: remove

File: plans/implemented/fix-yargs-shadowing.md [hunk 5]
```diff
@@ -0,0 +1,84 @@
+# Plan: Fix Yargs Command Shadowing and API Key Requirement for Subcommands
```
Comment (scidomino) [inline plans/implemented/fix-yargs-shadowing.md]: remove

**Review by scidomino — APPROVED** [review]
