### PR TITLE
fix(core): truncate large telemetry log entries

### LINKED ISSUE #11845: Logs that are too large are dropped
### What happened?

When logs are too big to be consumed by the logging endpoint (GCP in my case), an error occurs and they are dropped. For example:

```
│ ✖ {"stack":"Error: 3 INVALID_ARGUMENT: Log entry with size 438.0K exceeds maximum size of 256.0K\n    at           │
│   callErrorFromStatus (file:///home/user/gemini-cli/bundle/gemini.js:96853:21)\n    at Object.onReceiveStatus       │
│   (file:///home/user/gemini-cli/bundle/gemini.js:97533:70)\n    at Object.onReceiveStatus                           │
│   (file:///home/user/gemini-cli/bundle/gemini.js:97336:140)\n    at Object.onReceiveStatus                          │
│   (file:///home/user/gemini-cli/bundle/gemini.js:97302:178)\n    at                                                 │
│   file:///home/user/gemini-cli/bundle/gemini.js:110487:77\n    at process.processTicksAndRejections                 │
│   (node:internal/process/task_queues:77:11)\nfor call at\n    at ServiceClientImpl.makeUnaryRequest                 │
│   (file:///home/user/gemini-cli/bundle/gemini.js:97503:32)\n    at ServiceClientImpl.<anonymous>                    │
│   (file:///home/user/gemini-cli/bundle/gemini.js:97811:19)\n    at                                                  │
│   file:///home/user/gemini-cli/bundle/gemini.js:185003:25\n    at                                                   │
│   file:///home/user/gemini-cli/bundle/gemini.js:174149:16\n    at repeat                                            │
│   (file:///home/user/gemini-cli/bundle/gemini.js:174198:23)\n    at Task._apiCall                                   │
│   (file:///home/user/gemini-cli/bundle/gemini.js:174234:11)\n    at Task.run                                        │
│   (file:///home/user/gemini-cli/bundle/gemini.js:172548:35)\n    at BundleExecutor._runNow                          │
│   (file:///home/user/gemini-cli/bundle/gemini.js:172788:14)\n    at Timeout._onTimeout                              │
│   (file:///home/user/gemini-cli/bundle/gemini.js:172734:18)\n    at listOnTimeout                                   │
│   (node:internal/timers:581:17)","message":"3 INVALID_ARGUMENT: Log entry with size 438.0K exceeds maximum size of  │
│   256.0K","code":"3","details":"Log entry with size 438.0K exceeds maximum size of 256.0K","metadata":"[object      │
│   Object]","note":"Exception occurred in retry method that was not classified as transient","name":"Error"}         │
```

### What did you expect to happen?

Probably the log should be truncated in this case. Dropping it would at least be less messy but I believe we still want the log emitted. I'm not quite sure HOW we want to truncate this, (would be great if https://github.com/open-telemetry/semantic-conventions/blob/main/docs/gen-ai/gen-ai-events.md provided some guidance), especially since we're talking about json objects that we can't just cut off without breaking.

### Client information

n/a

### Login information

n/a

### Anything else we need to know?

When telemetry is turned on, the user's prompt is logged by default, and with the changes I've been making in #9215, the entire request Parts, response Parts and system instructions are also logged, so it's very easy to get into a state where these are larger than the [256k limit](https://cloud.google.com/logging/quotas).

### PR DESCRIPTION
**Pull request by sehoon38**
## Summary

Truncate large telemetry log entries to prevent rejection by the logging endpoint (GCP) when they exceed the 256KB limit.

## Details

Introduced a `GLOBAL_TEXT_LIMIT` of 160KB for the aggregate size of all string content within a single log entry. A new `limitTotalLength` function dynamically calculates the total size and distributes the budget among "large" parts, ensuring that the total log entry size (including JSON overhead) remains safely under 256KB. This prevents data loss for large contexts while preserving as much information as possible.

## Related Issues

Fixes #11845

## How to Validate

Run the new truncation tests:
`npx vitest run packages/core/src/telemetry/semantic.truncation.test.ts`

## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [x] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [ ] Validated on required platforms/methods:
  - [ ] MacOS
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

File: packages/core/src/telemetry/semantic.ts [hunk 1]
```diff
@@ -19,12 +19,111 @@ import type {
...
+    Math.floor(remainingBudget / largeRefs.length),
+  );
+
+  for (const ref of largeRefs) {
+    const original = ref.get();
+    if (original) {
+      ref.set(truncateString(original, budgetPerLargePart));
+    }
+  }
+}
```
[the remark this answers is not in the document]
Comment (sehoon38) [reply packages/core/src/telemetry/semantic.ts:118]: the suffix length is pretty trivial considering the total buffer is almost 100kb

File: packages/core/src/telemetry/semantic.ts [hunk 2]
```diff
@@ -19,12 +19,111 @@ import type {
...
+// The total log entry size limit is 256KB. We leave ~96KB (approx 37%) for JSON overhead (escaping, structure) and other fields.
+const GLOBAL_TEXT_LIMIT = 160 * 1024;
+
+interface StringReference {
+  get: () => string | undefined;
+  set: (val: string) => void;
+  len: () => number;
+}
+
+function getStringReferences(parts: AnyPart[]): StringReference[] {
```
Comment (NTaylorMullen) [inline packages/core/src/telemetry/semantic.ts:34]: Double check there isn't already a helper for this. It seems like there would be in the genai SDK.

**Review by NTaylorMullen — APPROVED** [review]
Approving to unblock but is there a world where we partition our events into multiple events in the case that one lien goes too long? I guess we can always wait to see how much of an issue this ends up being.

File: packages/core/src/telemetry/semantic.ts (hunk 2 above)
Comment (sehoon38) [reply packages/core/src/telemetry/semantic.ts:34]: yeah the structure is defined locally here for Otel usage, think there might be a way to do this first before mapping out our structure, but we can go with this for now.

**Review by iqbalbhatti49 — APPROVED** [review]
