### PR TITLE
fix: resolve infinite loop when using 'Modify with external editor'

### LINKED ISSUE #7669: Modify with external editor not working
### What happened?

1. I was given a code change tool request
2. I selected "Modify with external editor"
3. It asks which editor, I selected "Vim" or "Neovim" (I tried both independently)
4. it asks me again if I'll apply the change
5. I select "Modify with external editor" again
6. infinite loop, it still asks me for my editor

```
 │ Apply this change?                                                                                                                                                                                                                                         │
 │                                                                                                                                                                                                                                                            │
 │   1. Yes, allow once                                                                                                                                                                                                                                       │
 │   2. Yes, allow always                                                                                                                                                                                                                                     │
 │ ● 3. Modify with external editor                                                                                                                                                                                                                           │
 │   4. No, suggest changes (esc)                                                                                                                                                                                                                             │
 │                                                                                                                                                                                                                                                            │
 ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Press ctrl-s to show more lines
╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                                                                                                                                            │
│ > Select Editor                                                                                                   Editor Preference                                                                                                                        │
│ ● 1. None                                                                                                                                                                                                                                                  │
│   2. Cursor (Not installed)                                                                                       These editors are currently supported. Please note that some editors cannot be used in sandbox mode.                                     │
│   3. Emacs (Not installed)                                                                                                                                                                                                                                 │
│   4. Neovim                                                                                                       Your preferred editor is: None.                                                                                                          │
│   5. Vim                                                                                                                                                                                                                                                   │
│   6. VS Code (Not installed)                                                                                                                                                                                                                               │
│   7. VSCodium (Not installed)                                                                                                                                                                                                                              │
│   8. Windsurf (Not installed)                                                                                                                                                                                                                              │
│   9. Zed (Not installed)                                                                                                                                                                                                                                   │
│                                                                                                                                                                                                                                                            │
│   Apply To                                                                                                                                                                                                                                                 │
│ ● 1. User Settings                                                                                                                                                                                                                                         │
│   2. Workspace Settings                                                                                                                                                                                                                                    │
│                                                                                                                                                                                                                                                            │
│ (Use Enter to select, Tab to change focus)                                                                                                                                                                                                                 │
│                                                                                                                                                                                                                                                            │
```

### What did you expect to happen?

at least the second time it should just go into the selected editor somehow and let me edit the change diff. Or warn me of any issue.

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
│ CLI Version                          0.2.2-git.4d07cb7d                                                   │
│ Git Commit                           4d07cb7d                                                             │
│ Model                                gemini-2.5-pro                                                       │
│ Sandbox                              no sandbox                                                           │
│ OS                                   linux                                                                │
│ Auth Method                          gemini-api-key      
```

</details>

### Login information

api key...

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by ppgranger**
## Summary

Fix infinite loop when selecting "Modify with external editor" without a configured or available editor. Also improve the user experience by prompting the user to select an editor interactively.

## Details

**Root cause:** In both `confirmation.ts` and `coreToolScheduler.ts`, when `getPreferredEditor()` returned `undefined`, the code silently returned without changing the loop outcome variable, causing the confirmation loop to repeat indefinitely.

**Solution:**
- Added `resolveEditorAsync()` - validates availability of preferred editor and prompts the user to select an editor
- Updated `confirmation.ts` to check editor resolution result and return to previous screen when unavailable
 
## Related Issues

Fixes #7669

## How to Validate

1. Run `npm run start` in a workspace where `preferredEditor` is NOT set in `settings.json`.
2. Ask Gemini to make a code change (e.g., "add a comment to README.md").
3. When prompted to confirm, select `Modify with Editor`.
4. Observe that the "choose an editor" dialog appeared.
5. Hit `Esc` or choose "none" in the editor dialog.
6. Observe that you are returned to the `accept once` / `accept always` prompt with an error message, instead of the turn being cancelled.
7. Try again, but this time select an editor (e.g., `vim`).
8. Observe that `vim` opens with the diff.

## Pre-Merge Checklist

- [x] Updated relevant documentation and README (if needed)
- [x] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any) - Not Applicable
- [x] Validated on required platforms/methods:
  - [x] MacOS
    - [x] npm run
    - [x] npx
    - [x] Docker
    - [x] Podman
    - [x] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [x] Linux
    - [x] npm run
    - [x] npx
    - [x] Docker

### CODE REVIEW

File: packages/core/src/utils/editor.ts [hunk 1]
```diff
@@ -142,6 +142,79 @@ export function isEditorAvailable(editor: string | undefined): boolean {
...
+    if (isEditorAvailable(editor)) {
+      return editor;
+    }
+  }
+  // Fall back to GUI editors (won't work in sandbox mode but checked above)
+  for (const editor of GUI_EDITORS) {
+    if (isEditorAvailable(editor)) {
+      return editor;
+    }
+  }
```
[the remark this answers is not in the document]
Comment (ppgranger) [reply packages/core/src/utils/editor.ts]: 1. Added commandExistsAsync - Uses promisify(exec) instead of execSync to check if a command exists without blocking.
  2. Added async versions of all affected functions:                                                                   
    - checkHasEditorTypeAsync                                                                                          
    - isEditorAvailableAsync                                                                                           
    - detectFirstAvailableEditorAsync                                                                                  
    - resolveEditorAsync                                                                                               
  3. Updated callers to use async versions:                                                                            
    - confirmation.ts:handleExternalModification() now uses await resolveEditorAsync()                                 
    - coreToolScheduler.ts:handleConfirmationResponse() now uses await resolveEditorAsync()                            
  4. Kept synchronous versions for UI components (used in useEditorSettings.ts, editorSettingsManager.ts), require synchronous execution in React hooks&constructors. Marked resolveEditor as @deprecated to encourage use of the async version.                                                                                                             
  5. Added comprehensive tests for all new async functions.                                                            
                                                                                                                       
  Why this approach:                                                                                                   
  - Both callers (confirmation.ts and coreToolScheduler.ts) are already in async contexts, so switching to async was   
  straightforward                                                                                                      
  - The async functions follow the same logic as their sync counterparts for consistency                               
  - Keeping sync versions avoids breaking changes for UI components that can not be made async easily

File: packages/core/src/scheduler/confirmation.ts [hunk 2]
```diff
@@ -182,8 +198,19 @@ async function notifyHooks(
   }
 }
 
+/**
+ * Result of attempting external modification.
+ */
+interface ExternalModificationResult {
+  /** Whether the modification was successful (editor was opened) */
```
Comment (scidomino) [inline packages/core/src/scheduler/confirmation.ts]: Is it the case that `success` is true if and only if `error` is undefined? If so, remove it and just check for the presence of `error` to find out if the call was successful.

File: packages/core/src/utils/editor.ts [hunk 3]
```diff
@@ -108,17 +127,30 @@ const editorCommands: Record<
...
   const commandConfig = editorCommands[editor];
-  const commands =
-    process.platform === 'win32' ? commandConfig.win32 : commandConfig.default;
-  return commands.some((cmd) => commandExists(cmd));
+  return process.platform === 'win32'
+    ? commandConfig.win32
+    : commandConfig.default;
+}
+
+export function checkHasEditorType(editor: EditorType): boolean {
```
Comment (scidomino) [inline packages/core/src/utils/editor.ts]: Not your fault but this is a badly named function. Can we rename it to "hasValidCommand" or something?

Rename the corresponding functions appropriately.

File: packages/core/src/utils/editor.ts [hunk 4]
```diff
@@ -108,17 +127,30 @@ const editorCommands: Record<
...
+  return getEditorCommands(editor).some((cmd) => commandExists(cmd));
+}
+
+export async function checkHasEditorTypeAsync(
+  editor: EditorType,
+): Promise<boolean> {
+  for (const cmd of getEditorCommands(editor)) {
```
Comment (scidomino) [inline packages/core/src/utils/editor.ts]: Run these in parallel instead of serially.

File: packages/core/src/utils/editor.ts [hunk 5]
```diff
@@ -134,15 +166,53 @@ export function allowEditorTypeInSandbox(editor: EditorType): boolean {
...
+  return (
+    !!editor && isValidEditorType(editor) && allowEditorTypeInSandbox(editor)
+  );
+}
+
 /**
  * Check if the editor is valid and can be used.
  * Returns false if preferred editor is not set / invalid / not available / not allowed in sandbox.
  */
 export function isEditorAvailable(editor: string | undefined): boolean {
```
Comment (scidomino) [inline packages/core/src/utils/editor.ts:180]: Is it important to keep these synchronous versions of the methods? Please verify that we can't just change all the other references to use the async version.

File: packages/core/src/utils/editor.ts [hunk 6]
```diff
@@ -134,15 +166,53 @@ export function allowEditorTypeInSandbox(editor: EditorType): boolean {
...
-  if (editor && isValidEditorType(editor)) {
-    return checkHasEditorType(editor) && allowEditorTypeInSandbox(editor);
+  return isEditorTypeAvailable(editor) && checkHasEditorType(editor);
+}
+
+/**
```
Comment (scidomino) [inline packages/core/src/utils/editor.ts:184]: This comment is repetitive. I wouldn't even mention that it's the async version of anything or that it does this without blocking the event loop.

File: packages/core/src/scheduler/confirmation.ts (hunk 2 above)
Comment (ppgranger) [reply packages/core/src/scheduler/confirmation.ts]: You're right, success is redundant here. I'll simplify the interface to just  
  use error?: string and check for its presence.

File: packages/core/src/utils/editor.ts (hunk 3 above)
Comment (ppgranger) [reply packages/core/src/utils/editor.ts]: You right.

File: packages/core/src/utils/editor.ts (hunk 4 above)
Comment (ppgranger) [reply packages/core/src/utils/editor.ts]: Done

File: packages/core/src/utils/editor.ts (hunk 5 above)
Comment (ppgranger) [reply packages/core/src/utils/editor.ts:180]: EditorSettingsDialog.tsx: in React component render logic
editorSettingsManager.ts :i n class constructor
useEditorSettings.ts : Used in a React callback for immediate validation

The constructor case (editorSettingsManager.ts) is the main blockern need to refactor it to use a factory pattern or lazy initialization to make it async. The React component usages would also require adding loading states. 
Given the scope of changes required, I think keeping the sync versions is reasonable for now. Let me know if you'd prefer I refactor these to async.

File: packages/core/src/utils/editor.ts (hunk 6 above)
Comment (ppgranger) [reply packages/core/src/utils/editor.ts:184]: simplified the comment to match the sync version

**Review by scidomino — APPROVED** [review]
