### PR TITLE
Make merged settings non-nullable and fix all lints related to that.

### LINKED ISSUE #15284: Make defaults apply to settings
### What happened?

Right now the defaults only impact the settings dialog and not when users read the value via settings.merged.someSetting. 

### What did you expect to happen?

We want the defaults to apply to settings

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
# paste output here
```

</details>

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by jacob314**
## Summary
@devr0306 made some great changes to include default values in the settings but they still show as 
nullable to the type system even though the merged settings are now non-nullablle.

This results in a bunch of spurious null aware checks in the code base and a lot of spurious duplicate default value logic that was hard to catch without removing.
This PR mucks with the type system to make the merged versions of the settings non-nullable and then fixes all the cascading type lints that surfaces.

## Details
* **Type Safety Enhancement**: The `MergedSettings` type has been introduced and applied across the codebase, ensuring that properties within the merged settings object are consistently non-nullable. This significantly reduces the need for optional chaining and nullish coalescing.
* **Simplified Settings Access**: Optional chaining (`?.`) and nullish coalescing (`??`) operators have been removed from numerous locations where `settings.merged` properties are accessed, leading to cleaner and more readable code.
* **Refactored Default Settings Handling**: The `getDefaultsFromSchema` function and `mergeSettings` logic have been updated to consistently produce a fully populated `MergedSettings` object, guaranteeing the presence of all expected properties and simplifying their initialization.
* **Improved Test Utilities**: New helper functions like `createTestSettings` have been added to streamline the creation of mock `MergedSettings` objects in tests, ensuring they conform to the new non-nullable structure and improving test reliability.
* **Streamlined Hooks Logic**: The logic for enabling/disabling hooks, previously encapsulated in `getEnableHooks` and `getEnableHooksUI` functions, has been integrated directly into the relevant code paths, removing redundant abstractions and making the logic more explicit.

## Related Issues

Fixes #15284

## How to Validate

Make sure nothing is broken and that there are not any spurious ?. in the codebase.

### CODE REVIEW

File: packages/cli/src/config/settings.ts [hunk 1]
```diff
@@ -24,12 +24,24 @@ import { DefaultDark } from '../ui/themes/default.js';
...
   type Settings,
+  type MergedSettings,
   type MemoryImportFormat,
   type MergeStrategy,
   type SettingsSchema,
   type SettingDefinition,
   getSettingsSchema,
 } from './settingsSchema.js';
+
+export {
```
Comment (devr0306) [inline packages/cli/src/config/settings.ts:35]: I'm curious on why we import the types from `./settingsSchema.js` and export them as is? Is `settings.ts` a central file for exporting values to other packages or can other files import the types straight from `./settingsSchema.js`?

**Review by scidomino — APPROVED** [review]

File: packages/cli/src/gemini.tsx [hunk 2]
```diff
@@ -263,8 +263,7 @@ export async function startInteractiveUI(
       patchConsole: false,
       alternateBuffer: useAlternateBuffer,
       incrementalRendering:
-        settings.merged.ui?.incrementalRendering !== false &&
-        useAlternateBuffer,
+        settings.merged.ui.incrementalRendering !== false && useAlternateBuffer,
```
Comment (devr0306) [inline packages/cli/src/gemini.tsx:266]: should this just be changed to `!settings.merged.ui.incrementalRendering && useAlternateBuffer`

File: packages/core/src/telemetry/sdk.test.ts [hunk 3]
```diff
@@ -312,7 +312,8 @@ describe('Telemetry SDK', () => {
     expect(GcpTraceExporter).not.toHaveBeenCalled();
 
     // 2. Set project ID and emit post_auth event
-    process.env['GOOGLE_CLOUD_PROJECT'] = 'test-project';
+    vi.stubEnv('GOOGLE_CLOUD_PROJECT', 'test-project');
+    vi.stubEnv('OTLP_GOOGLE_CLOUD_PROJECT', 'test-project');
```
Comment (devr0306) [inline packages/core/src/telemetry/sdk.test.ts:316]: just wanted to double check if these changes are related to the merged settings because it looks different than the rest of the changes.

**Review by devr0306 — COMMENTED** [review]
LGTM. Just had questions about some very minor things but everything works as expected.

File: packages/cli/src/config/settings.ts (hunk 1 above)
Comment (jacob314) [reply packages/cli/src/config/settings.ts:35]: yep. settings.ts is the core file people should import. settingSchema is the implementation detail.

File: packages/core/src/telemetry/sdk.test.ts (hunk 3 above)
Comment (jacob314) [reply packages/core/src/telemetry/sdk.test.ts:316]: this is unrelated but something gemini kept wanting to make on my local env as otherwise this test failed. I should have put it on a separate pr but forgot.
