### PR TITLE
fix(core): add retry logic for transient SSL/TLS errors (#17318)

### LINKED ISSUE #17318: [Bug]: Unhandled ERR_SSL_SSLV3_ALERT_BAD_RECORD_MAC causes crash during long sessions
### What happened?

I was using the Gemini CLI to inspect my project (`nanobanana-cli`) during a long session. It was working perfectly for a while until it hit a transient SSL error and completely stopped execution, breaking my workflow.

I had to manually restart the task, which worked immediately. I am including the full terminal and F12 debug output below for context on where the crash occurred.

**Error Log:**

✕ [API Error: request to
  https://cloudcode-pa.googleapis.com/v1internal:streamGenerateContent?alt=sse failed, reason:
  402CE20302000000:error:0A0003FC:SSL routines:ssl3_read_bytes:sslv3 alert bad record
  mac:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1605:SSL alert number 20
  ]

 6 GEMINI.md files | 7 MCP servers

╭─────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Debug Console (F12 to close)                                                                    │
│                                                                                                 │
│    fetch/lib/index.js:1501:11)                                                                  │
│          at ClientRequest.emit (node:events:518:28)                                             │
│          at emitErrorEvent (node:_http_client:104:11)                                           │
│          at TLSSocket.socketErrorListener (node:_http_client:518:5)                             │
│          at TLSSocket.emit (node:events:518:28)                                                 │
│          at TLSSocket._emitTLSError (node:_tls_wrap:1034:10)                                    │
│          at TLSWrap.onerror (node:_tls_wrap:475:11)                                             │
│          at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17) {                     │
│        type: 'system',                                                                          │
│        errno: 'ERR_SSL_SSLV3_ALERT_BAD_RECORD_MAC',                                             │
│        code: 'ERR_SSL_SSLV3_ALERT_BAD_RECORD_MAC'                                               │
│      },                                                                                         │
│      code: 'ERR_SSL_SSLV3_ALERT_BAD_RECORD_MAC',                                                │
│      [Symbol(gaxios-gaxios-error)]: '6.7.1'                                                    █│
│    }                                                                                           █│
╰─────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────╮
│ >    Type your message or @path/to/file                                                         │
╰─────────────────────────────────────────────────────────────────────────────────────────────────╯
 ~/.../nanobanana-cli                    no sandbox                    gemini-3-pro-preview /model

### What did you expect to happen?

I expect the Gemini CLI to be resilient to transient network or SSL glitches. It clearly could have given I just said "try again" and it worked without restarting Gemini CLI.

This error (`ERR_SSL_SSLV3_ALERT_BAD_RECORD_MAC`) was temporary—simply retrying the request worked immediately. The CLI should have detected this as a recoverable network error and attempted an auto-retry internally, rather than crashing the process and forcing me to restart my session manually. It should not break the user's flow for a one-off socket error.

### Client information

│ About Gemini CLI                                                                                │
│                                                                                                 │
│ CLI Version                      0.27.0-nightly.20260121.97aac696f                              │
│ Git Commit                       20e54964                                                       │
│ Model                            gemini-3-pro-preview                                           │
│ Sandbox                          no sandbox                                                     │
│ OS                               darwin                                                         │
│ Auth Method                      OAuth

### Login information

OAuth, AI Ultra subscription

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by ppgranger**
## Summary
                                                                                                                                                                   
  Add automatic retry for transient SSL errors like `ERR_SSL_SSLV3_ALERT_BAD_RECORD_MAC` that can occur during long sessions, preventing unnecessary crashes.

  Previously, a transient SSL error would crash the entire CLI, forcing users to manually restart their session even though a simple retry would succeed
  immediately.

  ## Details

  ### Changes

  - **Add SSL error codes to `RETRYABLE_NETWORK_CODES`** (`retry.ts`):
    - `ERR_SSL_SSLV3_ALERT_BAD_RECORD_MAC`
    - `ERR_SSL_WRONG_VERSION_NUMBER`
    - `ERR_SSL_DECRYPTION_FAILED_OR_BAD_RECORD_MAC`
    - `ERR_SSL_BAD_RECORD_MAC`
    - `EPROTO` (generic protocol error)

  - **Improve error code extraction** (`retry.ts`):
    - Traverse nested `cause` chains up to 5 levels deep
    - SSL errors from OpenSSL are often wrapped in multiple error layers

  - **Allow retry during connection phase** (`geminiChat.ts`):
    - Previously, connection phase errors were always thrown immediately
    - Now, retryable errors trigger the retry logic with exponential backoff

  ### Test Coverage

  Added 9 new tests covering:
  - SSL error codes recognition
  - Deeply nested SSL errors in cause chains
  - Connection phase SSL errors
  - Mid-stream SSL errors (exact scenario from the issue)
  - Gaxios-style error structure

  ## Related Issues

  Fixes #17318

  ## How to Validate

  1. Run the new tests:
     ```bash
     npm test -w @google/gemini-cli-core -- --testNamePattern="SSL|GeminiChat Network Retries"

  2. Verify all tests pass (17 tests in the network retry suite)
  3. Build and lint:
  npm run build && npm run lint
  4. (Optional) To manually test, you could simulate an SSL error during a long session and verify the CLI retries automatically instead of crashing.


  Pre-Merge Checklist
- [ ] Updated relevant documentation and README (if needed)
- [x] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [x] Validated on required platforms/methods:
  - [x] MacOS
    - [x] npm run
    - [x] npx
    - [x] Docker
    - [x] Podman
    - [x] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [x] Linux
    - [x] npm run
    - [x] npx
    - [x] Docker

### CODE REVIEW

File: packages/core/src/core/geminiChat.ts [hunk 1]
```diff
@@ -394,8 +394,17 @@ export class GeminiChat {
               return; // Stop the generator
             }
 
+            // For connection phase errors, check if they are retryable
+            // (e.g., transient SSL errors like ERR_SSL_SSLV3_ALERT_BAD_RECORD_MAC)
             if (isConnectionPhase) {
-              throw error;
+              const isRetryable = isRetryableError(
```
Comment (sehoon38) [inline packages/core/src/core/geminiChat.ts]: nit: can pull this call out above if (isConnectionPhase) as it's immediately used below

**Review by sehoon38 — APPROVED** [review]
just a minor nit, lgtm overall. thanks for the contribution!

File: packages/core/src/core/geminiChat.ts (hunk 1 above)
Comment (ppgranger) [reply packages/core/src/core/geminiChat.ts]: Done :). Thx for this!

**Comment by ppgranger** [comment]
@sehoon38 Ready to merge :).
