### PR TITLE
fix(cli): resolve double rendering in shpool and address vscode lint warnings

### LINKED ISSUE #18703: UI rendering artifacts (double rendering) in Gemini CLI when used within shpool sessions
### What happened?

* Issue: When running the Gemini CLI interactive UI inside a multiplexed terminal session using shpool, UI elements like the footer and settings dialogs often render twice or exhibit flickering artifacts.

* Root Cause: The application was manually entering the alternate screen buffer while simultaneously instructing the ink library to do the same, leading to redundant and conflicting terminal control sequences. Additionally, shpool requires a small stabilization window during TUI startup and can exhibit frame-replay artifacts with incremental rendering enabled.

### What did you expect to happen?

rendering should look correct

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
│ About Gemini CLI                                                                                                       │
│                                                                                                                        │
│ CLI Version                              0.28.0-preview.6                                                              │
│ Git Commit                               44c67daa0                                                                     │
│ Model                                    auto-gemini-3                                                                 │
│ Sandbox                                  no sandbox                                                                    │
│ OS                                       linux                                                                         │
│ Auth Method                              Logged in with Google (REDACTED)                                    │
│ GCP Project                              shared-g3-gemini-quota   
```

</details>

### Login information

Google account

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by braddux**
This commit fixes rendering artifacts (specifically double rendering of the footer
and settings menu) when running Gemini CLI within an shpool session.

Key changes for shpool:
- Detected shpool sessions via the SHPOOL_SESSION_NAME environment variable.
- Added a 100ms delay before initial TUI rendering in shpool to allow terminal
  state and size to stabilize.
- Disabled incrementalRendering for shpool sessions, which prevents frame
  replay artifacts common in multiplexed environments.
- Removed redundant manual enterAlternateScreen() and disableLineWrapping()
  calls in the boot sequence, delegating alternate buffer management entirely
  to the ink library.
- Ensured line wrapping is disabled after alternate buffer entry and properly
  restored on exit via registered cleanup functions.

VS Code Companion refactorings:
- Addressed unsafe type assertions in diff-manager.ts and ide-server.ts by
  using proper type guards (instanceof vscode.TabInputTextDiff) and safer
  header extraction logic. This removes the need for eslint-disable directives
  and ensures compliance with root linting rules.

Test updates:
- Updated unit tests to account for additional cleanup registrations and
  ensured consistent environment variable handling.

Fixes #18703

### CODE REVIEW

File: packages/vscode-ide-companion/src/diff-manager.ts [hunk 1]
```diff
@@ -243,14 +243,11 @@ export class DiffManager {
...
       for (const tab of tabGroup.tabs) {
-        // eslint-disable-next-line @typescript-eslint/no-unsafe-type-assertion
-        const input = tab.input as {
-          modified?: vscode.Uri;
-          original?: vscode.Uri;
-        };
-        if (input && input.modified?.toString() === rightDocUri.toString()) {
-          await vscode.window.tabGroups.close(tab);
-          return;
+        if (tab.input instanceof vscode.TabInputTextDiff) {
```
Comment (jacob314) [inline packages/vscode-ide-companion/src/diff-manager.ts]: please revert this change. it is not related to your pr.

File: packages/vscode-ide-companion/src/ide-server.ts [hunk 2]
```diff
@@ -206,10 +206,10 @@ export class IDEServer {
       context.subscriptions.push(onDidChangeDiffSubscription);
 
       app.post('/mcp', async (req: Request, res: Response) => {
```
Comment (jacob314) [inline packages/vscode-ide-companion/src/ide-server.ts:208]: please revert this change. also unrelated to your pr

File: packages/vscode-ide-companion/src/diff-manager.ts (hunk 1 above)
Comment (braddux) [reply packages/vscode-ide-companion/src/diff-manager.ts]: Sorry, I had resolved the lint error.

**Review by jacob314 — APPROVED** [review]
lgtm
