### PR TITLE
fix(cli): skip workspace policy loading when in home directory

### LINKED ISSUE #20034: Need to ensure we don't accidentally treat user level policies as workspace level policies
Repro:
Running from my home directory I get the following prompt because the model is confused that the .gemini directory under my home directory is the directory for my workspace. We need to check that the directory is the home directory and not add workspace level tools for that case.

Image

### PR DESCRIPTION
**Pull request by Abhijit-2592**
## Summary

This PR fixes an issue where the Gemini CLI incorrectly identified the user's home directory as a workspace directory. This led to redundant policy loading and unnecessary "New Workspace Policies" prompts when running the CLI from `~`.

## Details

The fix involves checking if the resolved `.gemini` directory for the current workspace (via `storage.getGeminiDir()`) is the same as the global Gemini directory (via `Storage.getGlobalGeminiDir()`). If they match, `resolveWorkspacePolicyState` now returns early, effectively skipping workspace-level policy discovery for the home directory.

## Related Issues

Fixes #20034

## How to Validate

1. **Unit Test**: Run `npm test -w @google/gemini-cli -- src/config/policy.test.ts`. A new test case `should not return workspace policies if cwd is the home directory` verifies the fix.
2. **Manual Verification**:
   - Navigate to your home directory: `cd ~`.
   - Run the local build of the CLI: `node path/to/gemini-cli/scripts/start.js`.
   - Verify that you are **not** prompted to "Accept new workspace policies" and no warnings about automatic acceptance are printed in non-interactive mode.

## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [x] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [x] Validated on required platforms/methods:
  - [x] MacOS
    - [x] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

File: packages/cli/src/config/policy.ts [hunk 1]
```diff
@@ -67,9 +69,19 @@ export async function resolveWorkspacePolicyState(options: {
     | undefined;
 
   if (trustedFolder) {
-    const potentialWorkspacePoliciesDir = new Storage(
-      cwd,
-    ).getWorkspacePoliciesDir();
+    const storage = new Storage(cwd);
+
+    // If we are in the home directory (or rather, our target Gemini dir is the global one),
```
Comment (jacob314) [inline packages/cli/src/config/policy.ts:72]: can you check how this is being done or not done for settings.json? This code should be aligned rather than defining a separate helper for the same task.

Comment (Abhijit-2592) [reply packages/cli/src/config/policy.ts:72]: Unified the logic inside `Storage.isWorkspaceSameAsGlobalStorage`

File: packages/core/src/config/storage.ts [hunk 2]
```diff
@@ -142,6 +143,17 @@ export class Storage {
     return path.join(this.targetDir, GEMINI_DIR);
   }
 
+  /**
+   * Checks if the current workspace storage location is the same as the global/user storage location.
+   * This handles symlinks and platform-specific path normalization.
+   */
+  isWorkspaceSameAsGlobalStorage(): boolean {
```
Comment (jacob314) [inline packages/core/src/config/storage.ts]: nit: would isWorkspaceHomeDir() be clearer?

**Review by jacob314 — APPROVED** [review]
lgtm

File: packages/core/src/config/storage.ts (hunk 2 above)
Comment (Abhijit-2592) [reply packages/core/src/config/storage.ts]: Done. Changed the name to `isWorkspaceHomeDir()`
