### PR TITLE
fix(ui): persist expansion in AskUser dialog when navigating options

### LINKED ISSUE #18909: Persist expansion in `AskUser` dialog when navigating options
After expanding ask user tool page there if you move between different answer options it re-truncates

### PR DESCRIPTION
**Pull request by jerop**
- Lowered handleGlobalKeypress priority to Low in AppContainer. This ensures that focused interactive components (like AskUserDialog, BaseSelectionList, or text inputs) consume their keypresses first, preventing the global fallback logic from collapsing the expanded view during user interaction.
- Added "Expansion Persistence" test suite to AppContainer.test.tsx to verify that the expanded view persists when keys are handled elsewhere and correctly toggles via Ctrl+O.

Fixes #18909

### CODE REVIEW

File: packages/cli/src/ui/AppContainer.tsx [hunk 1]
```diff
@@ -1834,11 +1810,10 @@ Logging in with Google... Restarting Gemini CLI to continue.
         }
         return true;
       }
+
       return false;
     },
     [
```
Comment (Adib234) [inline packages/cli/src/ui/AppContainer.tsx:1838]: Can this warning be addressed?

**Review by Adib234 — APPROVED** [review]
