### PR TITLE
fix(cli): resolve home/end keybinding conflict

### LINKED ISSUE #16517: Overloaded HOME END key in navigation
### What happened?

With "Use Alternate Screen Buffer" set to "true", and focused on the prompt input box, when the HOME or END key is pressed the cursor jumps to head or tail as expected, but the screen buffer also jumps. 

### What did you expect to happen?

Screen buffer should be allocated separate shortcuts instead of colliding with the existing cursor commands. 

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
# paste output here
```

</details>

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by scidomino**
## Summary

This PR resolves a keybinding conflict where the HOME and END keys were triggering both cursor movement and buffer scrolling. This change ensures that  and  are used for scrolling, while the un-modified  and  keys are used for cursor movement.

## Details

The  were updated to assign  to  and , and  to  and  to differentiate the actions.

## Related Issues

Fixes #16517

## How to Validate

1. Run the CLI in alternate buffer mode.
2. Press  and  to verify the cursor moves to the start and end of the line.
3. Press  and  to verify the buffer scrolls to the top and bottom.

## Pre-Merge Checklist

- [x] Updated relevant documentation and README (if needed)
- [x] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [x] Validated on required platforms/methods:
  - [x] MacOS
    - [x] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

File: packages/cli/src/config/keyBindings.ts [hunk 1]
```diff
@@ -117,8 +117,14 @@ export const defaultKeyBindings: KeyBindingConfig = {
...
   // Cursor Movement
-  [Command.HOME]: [{ key: 'a', ctrl: true }, { key: 'home' }],
-  [Command.END]: [{ key: 'e', ctrl: true }, { key: 'end' }],
+  [Command.HOME]: [
+    { key: 'a', ctrl: true },
+    { key: 'home', ctrl: false },
+  ],
+  [Command.END]: [
+    { key: 'e', ctrl: true },
+    { key: 'end', ctrl: false },
```
Comment (jacob314) [inline packages/cli/src/config/keyBindings.ts]: nit: need shift:false as well

File: packages/cli/src/config/keyBindings.ts [hunk 2]
```diff
@@ -117,8 +117,14 @@ export const defaultKeyBindings: KeyBindingConfig = {
   [Command.EXIT]: [{ key: 'd', ctrl: true }],
 
   // Cursor Movement
-  [Command.HOME]: [{ key: 'a', ctrl: true }, { key: 'home' }],
-  [Command.END]: [{ key: 'e', ctrl: true }, { key: 'end' }],
+  [Command.HOME]: [
+    { key: 'a', ctrl: true },
+    { key: 'home', ctrl: false },
```
Comment (jacob314) [inline packages/cli/src/config/keyBindings.ts]: need shift:false as well

File: packages/cli/src/config/keyBindings.ts [hunk 3]
```diff
@@ -431,5 +443,6 @@ export const commandDescriptions: Readonly<Record<Command, string>> = {
   [Command.FOCUS_SHELL_INPUT]: 'Focus the shell input from the gemini input.',
   [Command.UNFOCUS_SHELL_INPUT]: 'Focus the Gemini input from the shell input.',
   [Command.CLEAR_SCREEN]: 'Clear the terminal screen and redraw the UI.',
-  [Command.RESTART_APP]: 'Restart the application.',
+  [Command.RESTART_APP]:
+    'Restart the application when admin settings have been changed.',
```
Comment (jacob314) [inline packages/cli/src/config/keyBindings.ts]: seems unrelated. revert.

**Review by jacob314 — APPROVED** [review]
lgtm
