### PR TITLE
Fix multiple bugs with auth flow including using the implemented but unused restart support.

### LINKED ISSUE #12893: Authentication URL is cut off in iTerm2
### What happened?

The OAuth URL does not word wrap in iTerm2 when running Gemini CLI inside a container.

### What did you expect to happen?

The URL should wrap and I should be able to click on it to login.

### Client information

I can't provide this since I can't even type `/about`.

Operating system: macOS 26.0.1
iTerm2: 3.6.5
Gemini CLI version: 0.13.0
Node version: 24.11.0

### Login information

This was tested with the "Login with Google" option.

### Anything else we need to know?

1. Run `docker run -it --rm node:24 /bin/sh` to start a Node.js Docker container.
2. Install Gemini CLI inside the container with `npm i -g @google/gemini-cli`.
3. Run `gemini`.
4. Select the first "Login with Google" option.
5. Gemini CLI will exit.
6. Restart with `gemini`.
7. Observe that the URL is cut off.

These other issues may be related:
- #11824
- #11945

https://github.com/user-attachments/assets/cd088687-4fa7-4f13-bff8-d0e8affea621

### PR DESCRIPTION
**Pull request by jacob314**
## Summary

The auth flow was hard to read with important information sent to the debug console rather than displayed on the screen so users would have little indication of what was going on.

We were also neglecting to use the functionality @shrutip90 added to support restarting the IDE and so we were forcing users to restart manually in multiple places. Audited all places we were exiting adding the proper cleanup logic and calling the appropriate command to restart for cases where it was intended the user would restart.

## Details

* **Centralized Terminal Control**: Terminal interaction functions (mouse events, Kitty protocol, alternate screen, line wrapping) have been moved from `packages/cli` to a new shared `packages/core/src/utils/terminal.ts` module for improved reusability and consistency across the application.
* **Improved Authentication Flow**: The user code authentication process (when `NO_BROWSER=true`) has been enhanced by utilizing the alternate screen buffer for a cleaner user experience and providing clearer feedback messages directly to the terminal.
* **Structured CLI Restart Mechanism**: Direct `process.exit(0)` calls for scenarios requiring a CLI restart (e.g., after Google login when browser launch is suppressed) have been replaced with a specific `RELAUNCH_EXIT_CODE` and `runExitCleanup()`, enabling better external process management and a more graceful restart.
* **Enhanced Error Handling & User Feedback**: Core error handling now consistently uses `writeToStderr` for critical errors, and informational/error messages during authentication are communicated via `CoreEvent.UserFeedback`, improving user communication.

## Related Issues
Fixes: #12893

## How to Validate

Demo of auth flow with browser:
https://screencast.googleplex.com/cast/NjQyNzU5Mjg4MTA3ODI3Mnw3NzQ1OGIxZC05Nw 

Demo of auth flow with browser disabled:
https://screencast.googleplex.com/cast/NjIxNzg5Nzg2NDA2OTEyMHxkNWFiMGQxZC1mOA

Disable authentication with the browser via config and verify you can still authenticate seeing the whole auth string with correct line wrap in the console.

Validate cancelling the auth flow.

Validate that editing.a setting requiring restart now restarts automatically when you press r rather than making you do it.

The one known issue I wasn't able to fix is that ctrl-C does not work to exit with the readline based security code entry logic in core.

### CODE REVIEW

File: packages/core/src/code_assist/oauth2.ts [hunk 1]
```diff
@@ -266,55 +310,77 @@ export async function getOauthClient(
...
-  try {
-    const { tokens } = await client.getToken({
-      code,
-      codeVerifier: codeVerifier.codeVerifier,
-      redirect_uri: redirectUri,
+      rl.question('Enter the authorization code: ', (code) => {
+        rl.close();
+        resolve(code.trim());
+      });
     });
```
[the remark this answers is not in the document]
Comment (jacob314) [reply packages/core/src/code_assist/oauth2.ts:345]: I tried this but it doesn't resolve the issue.

File: packages/core/src/code_assist/oauth2.ts [hunk 2]
```diff
@@ -185,28 +202,45 @@ async function initOauthClient(
...
     let success = false;
     const maxRetries = 2;
-    for (let i = 0; !success && i < maxRetries; i++) {
-      success = await authWithUserCode(client);
-      if (!success) {
-        debugLogger.error(
-          '\nFailed to authenticate with user code.',
-          i === maxRetries - 1 ? '' : 'Retrying...\n',
-        );
+    // Enter alternate buffer
```
Comment (jacob314) [inline packages/core/src/code_assist/oauth2.ts:205]: Rendering this in the alternate buffer is perhaps overkill but depending on if Gemini CLI was already rendering it is better if we ensure this is rendered in the alternate buffer than clear the main buffer as would be needed to ensure this UI doesn't conflict with Gemini CLI

File: packages/core/src/code_assist/oauth2.ts [hunk 3]
```diff
@@ -185,28 +202,45 @@ async function initOauthClient(
...
+    enterAlternateScreen();
+    // Clear screen and move cursor to top-left.
+    writeToStdout('\u001B[2J\u001B[H');
+    disableMouseEvents();
+    disableKittyKeyboardProtocol();
+    enableLineWrapping();
```
Comment (jacob314) [inline packages/core/src/code_assist/oauth2.ts:211]: enabling line wrapping is key so the URL is copyable/clickable

File: packages/core/src/code_assist/oauth2.ts [hunk 4]
```diff
@@ -266,55 +310,77 @@ export async function getOauthClient(
...
-    access_type: 'offline',
-    scope: OAUTH_SCOPE,
-    code_challenge_method: CodeChallengeMethod.S256,
-    code_challenge: codeVerifier.codeChallenge,
-    state,
-  });
-  debugLogger.log(
-    'Please visit the following URL to authorize the application:',
-  );
-  debugLogger.log('');
```
Comment (jacob314) [inline packages/core/src/code_assist/oauth2.ts:283]: the fact that these were debugLogger was very strange this was always UI written to stdout.

File: packages/core/src/utils/terminal.ts [hunk 5]
```diff
@@ -0,0 +1,50 @@
...
+  // Disable mouse tracking with SGR format
+  writeToStdout('\u001b[?1006l\u001b[?1002l');
+}
+
+export function enableKittyKeyboardProtocol() {
+  writeToStdout('\x1b[>1u');
+}
+
+export function disableKittyKeyboardProtocol() {
+  writeToStdout('\x1b[<u');
```
Comment (jacob314) [inline packages/core/src/utils/terminal.ts:26]: I've switched these back to the standard writeToStdout method as the sync version wasn't fixing issues anyway.

**Review by scidomino — APPROVED** [review]
