### PR TITLE
fix(cli): stabilize copy mode to prevent flickering and cursor resets

### LINKED ISSUE #13033: Native Selection in Alternate Buffer Mode
### What would you like to be added?

Text selection of arbitrary text from the Gemini CLI while in "Alternate Buffer Mode" without requiring users to press ctrl-S.

We should natively detect what range of text has been selected and trigger the appropriate copy event when they press ctrl-C or CMD-C for terminals that allow it.

This will provide a superior text copy and paste experience to the current UI as we will be able to retain the line wrapping the of the raw input  and we will not have to require a special shortcut to enter text selection mode.

### Why is this needed?

Users are confused about how to select text with the new UI and the current experience is cumbersome with a ctrl-S shortcut just to enter selection mode.
For example: https://github.com/google-gemini/gemini-cli/issues/13031

### Additional context

To support scroll wheel based scrolling well in alternate buffer mode we have to listen for mouse events which unfortunately means we cannot allow users to copy and paste normally due to terminal restrictions.

### LINKED ISSUE #18701: Alternate buffer copy mode should hide frames
### What would you like to be added?

Would like to remove the frames around tool uses etc in alternate buffer copy mode to make it easier to copy stuff out.

### Why is this needed?

Otherwise if you copy stuff it gets weird spacing and pipes.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mattKorwel**
## Problem
On macOS and Windows, users in **Alternate Buffer Mode** (fullscreen) experienced significant flickering and cursor resets when attempting to highlight text for copying. This was primarily caused by:
1. **Periodic UI Updates:** The `MemoryUsageDisplay` updated every 2 seconds, and the `InputPrompt` maintained an active cursor. In many terminals, any screen update or cursor movement during a selection forces the terminal to reset the selection or scroll back to the bottom.
2. **Layout Shifts:** Entering 'Copy Mode' (`Ctrl+S`) triggered a sequence of component unmounts (Footer, InputPrompt) and visibility changes (CopyModeWarning). These changes caused the history area (`MainContent`) to resize and the terminal to jump, breaking the user's focus and selection.

## Fix
This PR implements a "Freeze Frame" approach to Copy Mode:
- **Locked Layout Height:** Introduced `stableControlsHeight` in `AppContainer`. When Copy Mode is active, the height of the bottom controls area is locked to its last known size, preventing the chat history from resizing or jumping.
- **Height-Stable Warnings:** Updated `CopyModeWarning` to always occupy a 1-line box, even when hidden, to eliminate the 1-line layout shift when entering/exiting.
- **Total Silence:** 
    - Paused the memory update interval when copy mode is active.
    - Unmounted the `InputPrompt` to prevent cursor interference.
    - Hidden the `Footer` to eliminate re-renders from status items.
- **Padding Stability:** Maintained a consistent `paddingBottom` in the root layout to avoid shifts in Alternate Buffer mode.

These changes ensure that once a user enters Copy Mode, the screen is perfectly static, allowing the terminal's native selection logic to function without interference.

## Verification
- Verified manually on macOS (iTerm2 and Terminal.app).
- All relevant UI tests passed.

### Related Issues:
- Fixes #13033 (Native Selection in Alternate Buffer Mode)
- Fixes #18701 (Alternate buffer copy mode should hide frames)
- Related to #10673 (Flicker free robust terminal rendering)
- Related to #18250 (Flicker-Free User Experience)
- Related to #18896 (Screen Glitching and Flickering on Windows)
- Related to #22028 (Scroll reset on click)
- Related to #17302 (Constant scroll reset in VS Code)

---
**Note to reviewer:** I will attach a screen recording demonstrating the fix in the comments below.

### CODE REVIEW

**Review by mattKorwel — COMMENTED** [review]
### 🤖 Automated Review Assessment (via Gemini CLI)

Functional verification and behavioral analysis for this PR have identified a transient CI issue but verified the core stabilization logic.

#### ✅ Key Improvements
*   **Copy Mode Stabilization:** The fixes for flickering and cursor resets were verified in a TTY environment. The PTY management framework correctly handles the stabilization.
*   **Build & Review:** The core build and automated review passed successfully.

#### ⚠️ Observation: CI Status
*   **CI Status Failed:** GitHub Actions failed during the run. However, **Local Diagnostics (lint/typecheck) passed**. This indicates the CI failure is likely a transient environment issue (e.g., resource timeout) and not a regression in the code.

**Recommendation:** Approve once CI is re-run and passing.

**Review by jacob314 — CHANGES_REQUESTED** [review]
Here is a review from `/review-frontend` regarding the `mk-copy-mode` changes:

### Summary
The core approach to resolving the flickering and cursor resets is solid. By tracking and freezing the `stableControlsHeight` in `AppContainer.tsx` when entering Copy Mode, you successfully prevent the terminal height from fluctuating, which is what typically triggers the scroll resets in the `BaseSelectionList`. 

However, there are a couple of unintended UI regressions and dead code paths that were introduced to the presentation components as part of this fix. These should be cleaned up.

### Feedback

**1. `CopyModeWarning.tsx` introduces a permanent empty line**
The component was changed to always render a `<Box height={1}>` even when `copyModeEnabled` is false, whereas it previously returned `null`. 
This creates a permanent blank line directly above the `Composer` when the user is *not* in copy mode (which is the default state). 

Because the `<Footer />` (which is 1 line tall) is explicitly unmounted during copy mode, and the `CopyModeWarning` (which is also 1 line tall) appears in its place, the total lines rendered naturally remain the same. The `stableControlsHeight` in `AppContainer.tsx` also enforces the container boundaries. Therefore, padding the UI with an empty Box is unnecessary and degrades the standard visual layout. 
**Action:** Revert `CopyModeWarning.tsx` back to returning `null` when `copyModeEnabled` is false. You will also need to update the snapshot tests in `App.test.tsx.snap` to reflect the removal of the empty line.

**2. Dead code in `MemoryUsageDisplay.tsx` and `Footer.tsx`**
You added an `isActive` prop to `MemoryUsageDisplay` to clear the `setInterval` when in copy mode, passing it down from `Footer` as `isActive={!uiState.copyModeEnabled}`.
However, if you look at `Composer.tsx`, the entire `<Footer />` component is conditionally unmounted:
```tsx
{!uiState.copyModeEnabled && <Footer />}
```
Because the `Footer` is completely removed from the React tree during copy mode, `MemoryUsageDisplay` is also unmounted. When a component unmounts, its `useEffect` cleanup automatically runs (clearing the interval). Therefore, `isActive` will *always* be `true` whenever `MemoryUsageDisplay` is mounted, rendering the prop completely useless.
**Action:** Remove the `isActive` prop from `MemoryUsageDisplay` and `Footer`.

**3. `DefaultAppLayout.tsx` and `AppContainer.tsx`**
The logic to maintain a consistent `paddingBottom={1}` during alternate buffer mode and the core `stableControlsHeight` math in `AppContainer.tsx` are excellent and should remain as implemented.

File: packages/cli/src/ui/components/MemoryUsageDisplay.tsx [hunk 1]
```diff
@@ -22,9 +22,10 @@ export const MemoryUsageDisplay: React.FC<{ color?: string }> = ({
       const usage = process.memoryUsage().rss;
       setMemoryUsage(formatBytes(usage));
       setMemoryUsageColor(
-        usage >= 2 * 1024 * 1024 * 1024 ? theme.status.error : color,
+        usage > 1024 * 1024 * 512 ? theme.status.error : color,
```
Comment (jacob314) [inline packages/cli/src/ui/components/MemoryUsageDisplay.tsx]: seems like an accidental change. you are now making it look like an error any time memory is over 512 mb.

**Review by jacob314 — APPROVED** [review]
Please revert the accidental change to MemoryUsageDisplay before committing.
