### PR TITLE
fix(ui): add accelerated scrolling on alternate buffer mode

### LINKED ISSUE #14413: Speed up scroll wheel speed
Terminals other than Ghostty report too few scrolling events on moving the scroll wheel resulting in the perception that scrolling is slower than it should be when manually performing scrolling with the alternate buffer.
We should address this by increasing the maximum scroll speed when the user scrolls with momentum by around 5X on non-ghostty terminals.
The right algorithm likely involves some amount of simulation of momentum and delayed trigger of the acceleration so small scrolls still feel precise while large scrolls are fast.

### PR DESCRIPTION
**Pull request by devr0306**
## Summary

Added accelerated scrolling for alternate buffer mode.

## Details

* **Accelerated Scrolling**: Implemented accelerated scrolling for non-Ghostty terminals to improve navigation speed in the alternate buffer mode.
* **Terminal Check**: Added a check to see if a terminal is Ghostty or not.

## Related Issues

Closes #14413

## How to Validate

1. Run the CLI locally on alternate buffer mode(preferably with a long chat session). 
2. Try scrolling slow and fast. 
3. Both should behave differently.

Example screencast(added comparison to before behavior at the end):

https://github.com/user-attachments/assets/d1293a57-89e0-41f5-9f5b-5f69144a5768

## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [x] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [x] Validated on required platforms/methods:
  - [x] MacOS
    - [x] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

File: packages/cli/src/ui/contexts/ScrollProvider.tsx [hunk 1]
```diff
@@ -125,8 +126,34 @@ export const ScrollProvider: React.FC<{ children: React.ReactNode }> = ({
...
+    const now = Date.now();
+
+    if (!terminalCapabilityManager.isGhosttyTerminal()) {
+      const timeSinceLastScroll = now - scrollMomentumRef.current.lastTime;
+      // 50ms threshold to consider scrolls consecutive
+      if (timeSinceLastScroll < 50) {
+        scrollMomentumRef.current.count += 1;
+        if (scrollMomentumRef.current.count > 50) {
+          // Accelerate up to 5x
+          multiplier = Math.min(
```
Comment (jacob314) [inline packages/cli/src/ui/contexts/ScrollProvider.tsx]: simplify this formula and lets limit the multiplier to 2 or 3X at first to derisk. from the forumula it should be clear the maximum is 5x multiplier not the minimum is a 5x multiplier.

File: packages/cli/src/ui/contexts/ScrollProvider.tsx [hunk 2]
```diff
@@ -125,8 +126,34 @@ export const ScrollProvider: React.FC<{ children: React.ReactNode }> = ({
...
+            1 + (scrollMomentumRef.current.count - 50) * 0.5,
+          );
+        }
+      } else {
+        scrollMomentumRef.current.count = 0;
+      }
+    }
+    scrollMomentumRef.current.lastTime = now;
+
+    const delta = (direction === 'up' ? -1 : 1) * Math.floor(multiplier);
```
Comment (jacob314) [inline packages/cli/src/ui/contexts/ScrollProvider.tsx]: i think this is more blocky than it needs to be. we are getting a ton of scroll deltas of one. if you do this more effectively you could apply a delta of 1.1 or similar. You will just need to keep track of a floating point intermediate value and round.

**Review by jacob314 — APPROVED** [review]
lgtm
