### PR TITLE
fix: prevent orphaned processes from consuming 100% CPU when terminal closes

### LINKED ISSUE #15873: [BUG] Orphaned gemini-cli process consumes 100% CPU after terminal closure (47+ days)
# [BUG] Orphaned gemini-cli process consumes 100% CPU after terminal closure (47+ days)

## Summary

A `gemini-cli` process becomes orphaned when the parent terminal is closed, enters a CPU spin loop, and runs indefinitely consuming 100% CPU. The observed instance has been running for **47+ days** accumulating **232+ hours of CPU time** (9.7 days of continuous CPU usage).

## Environment

| Component | Value |
|-----------|-------|
| **OS** | macOS Sequoia (Darwin 24.x, arm64) |
| **Hardware** | Apple Mac M4 |
| **Node.js** | v20.x / v22.x (LTS) |
| **gemini-cli version** | v0.15.4 (affected) |
| **Current version** | v0.22.3 |
| **Shell** | zsh / Terminal.app / iTerm2 |

## Steps to Reproduce

1. Open a terminal window
2. Start a gemini-cli session:
   ```bash
   gemini "Analyze this codebase for performance issues"
   ```
3. While the session is active (before it completes), **close the terminal window** using:
   - `Cmd+W` (close window)
   - `Cmd+Q` (quit Terminal.app)
   - Or clicking the window's close button
4. The `gemini` process becomes orphaned and continues running indefinitely

### Minimal Reproduction

```bash
# Terminal 1: Start gemini in background-ish context
cd /path/to/large/project
gemini "Analyze all files in this directory"

# Terminal 2: Simulate terminal closure
kill -HUP $(pgrep -f "gemini")
# Process should terminate gracefully but does NOT
```

## Expected Behavior

When the parent terminal is closed (sending `SIGHUP`), the `gemini-cli` process should:

1. Detect the hangup signal
2. Gracefully terminate any active API connections
3. Clean up resources (file handles, network sockets)
4. Exit with appropriate status code

## Actual Behavior

The process:

1. **Ignores `SIGHUP`** - No signal handler registered
2. **Becomes orphaned** - Reparented to `launchd` (PPID=1)
3. **Loses all file descriptors** - stdin/stdout/stderr become "(revoked)"
4. **Enters infinite spin loop** - Likely polling revoked FDs or awaiting input that never comes
5. **Consumes 100% CPU indefinitely** - Until manually killed

### Process State (47 days after terminal closure)

```
$ ps aux | grep 66164
USER    PID   %CPU %MEM   VSZ    RSS   TT  STAT STARTED      TIME COMMAND
aadel  66164 100.0  0.1 437092864 118896  ??  Rs   18Nov25 232:47.82 node /opt/homebrew/lib/node_modules/@anthropic-ai/claude-code/node_modules/.pnpm/@anthropic-ai+claude-cli@0.15.4/node_modules/@google/gemini-cli/dist/cli.js
```

**Key observations:**
- `%CPU: 100.0` - Full core saturation
- `STAT: Rs` - Running, session leader (orphaned)
- `TT: ??` - No controlling terminal
- `STARTED: 18Nov25` - Running since November 18, 2025
- `TIME: 232:47.82` - 232+ hours of CPU time consumed

### File Descriptor State

```
$ lsof -p 66164
COMMAND   PID  USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
node    66164 aadel  cwd    DIR    1,9     1632  ... /Users/aadel/22_MyAgent
node    66164 aadel  txt    REG    1,9 114955600 ... /opt/homebrew/Cellar/node/22.9.0/bin/node
node    66164 aadel    0u   CHR    2,0      0t0  ... /dev/null (revoked)
node    66164 aadel    1u   CHR    2,0      0t0  ... /dev/null (revoked)
node    66164 aadel    2u   CHR    2,0      0t0  ... /dev/null (revoked)
node    66164 aadel    3u  IPv4 0x...        0t0  ... TCP *:* (CLOSED)
node    66164 aadel    4u  unix 0x...        0t0  ... (revoked)
node    66164 aadel    5u  KQUEUE            ...     count=0, state=0
```

**Critical finding:** All standard file descriptors (0, 1, 2) show `(revoked)` status, indicating the terminal device was deallocated but the process continues attempting I/O operations.

### Parent Process

```
$ ps -o ppid= -p 66164
    1
```

PPID=1 confirms the process was orphaned and reparented to `launchd`.

### 1. Missing Signal Handlers

The CLI does not register handlers for terminal-related signals:

```javascript
// MISSING in cli.js:
process.on('SIGHUP', () => {
  cleanup();
  process.exit(0);
});

process.on('SIGTERM', () => {
  cleanup();
  process.exit(0);
});
```

### 2. Unchecked I/O Operations

The event loop likely contains code that:
- Polls `stdin` for user input without checking if the stream is valid
- Attempts to write to `stdout` without error handling for closed streams
- Uses blocking or busy-wait patterns when streams become unavailable

### 3. No TTY Detection

The process doesn't detect when it loses its controlling terminal:

```javascript
// MISSING check:
if (!process.stdin.isTTY) {
  // Handle non-interactive mode or exit
}
```

## Resource Impact

| Metric | Value | Impact |
|--------|-------|--------|
| CPU Time | 232+ hours | 9.7 days of single-core usage |
| Wall Time | 47+ days | Process lifetime |
| Memory | ~119 MB RSS | Persistent allocation |
| Power | Significant | Continuous M4 efficiency core usage |
| Thermal | Elevated | Sustained CPU load |

### Estimated Energy Cost

At ~5W for M4 efficiency core under load:
- 232 hours x 5W = 1,160 Wh = **1.16 kWh wasted**

### 1. Add Signal Handlers (Critical)

```javascript
// In cli.js or main entry point

const cleanup = () => {
  // Close API connections
  if (activeSession) {
    activeSession.abort();
  }
  // Close file handles
  // Clear timeouts/intervals
};

const gracefulShutdown = (signal) => {
  console.error(`\nReceived ${signal}, shutting down gracefully...`);
  cleanup();
  process.exit(0);
};

process.on('SIGHUP', () => gracefulShutdown('SIGHUP'));
process.on('SIGTERM', () => gracefulShutdown('SIGTERM'));
process.on('SIGINT', () => gracefulShutdown('SIGINT'));

// Handle uncaught exceptions that might cause spin loops
process.on('uncaughtException', (err) => {
  console.error('Uncaught exception:', err);
  cleanup();
  process.exit(1);
});
```

### 2. Add TTY Monitoring

```javascript
// Detect terminal disconnection
process.stdin.on('end', () => {
  console.error('stdin closed, exiting');
  cleanup();
  process.exit(0);
});

process.stdout.on('error', (err) => {
  if (err.code === 'EPIPE' || err.code === 'EIO') {
    cleanup();
    process.exit(0);
  }
});

// Periodic TTY check for long-running sessions
setInterval(() => {
  if (!process.stdin.isTTY && !process.env.GEMINI_NON_INTERACTIVE) {
    console.error('Lost controlling terminal, exiting');
    cleanup();
    process.exit(0);
  }
}, 5000);
```

### 3. Add Watchdog Timer (Defense in Depth)

```javascript
// If no activity for extended period with no TTY, exit
let lastActivity = Date.now();

const watchdog = setInterval(() => {
  const idleMinutes = (Date.now() - lastActivity) / 60000;
  if (idleMinutes > 30 && !process.stdin.isTTY) {
    console.error('Watchdog: No activity with detached terminal, exiting');
    cleanup();
    process.exit(0);
  }
}, 60000);

watchdog.unref(); // Don't block process exit
```

## Workaround (For Affected Users)

Until fixed, users can:

```bash
# Find and kill orphaned gemini processes
pkill -f "gemini-cli"

# Or more specifically
ps aux | grep gemini | grep -v grep | awk '{print $2}' | xargs kill -9

# Add to ~/.zshrc or ~/.bashrc for periodic cleanup
alias gemini-cleanup='pkill -9 -f "gemini-cli.*node"'
```

## Related Issues

- #5942 - Process hangs after API timeout (potentially related event loop issue)
- #5950 - High CPU usage during idle sessions
- Node.js issue: https://github.com/nodejs/node/issues/... (stdin handling after terminal close)

## Version Information

```bash
$ gemini --version
@google/gemini-cli v0.15.4 (affected version)

$ node --version
v22.9.0

$ sw_vers
ProductName:    macOS
ProductVersion: 15.x
BuildVersion:   24xxxxx
```

## Checklist for Fix Verification

- [ ] `SIGHUP` properly terminates the process
- [ ] `SIGTERM` properly terminates the process
- [ ] Closing terminal window terminates child gemini process
- [ ] No orphaned processes after 1 hour of terminal closures
- [ ] CPU usage drops to 0% within 5 seconds of terminal closure
- [ ] Graceful cleanup of API connections on signal
- [ ] Test on macOS (arm64 and x86_64) and Linux

## Additional Context

This bug has significant implications for:

1. **Developer machines** - Accumulated orphan processes over time
2. **CI/CD environments** - Processes may persist after job completion
3. **Server deployments** - Resource exhaustion over time
4. **Battery-powered devices** - Significant power drain

The 47-day runtime demonstrates that this is not a transient issue but a fundamental architectural problem with signal handling in the CLI.

---

**Labels:** `bug`, `high-priority`, `signal-handling`, `resource-leak`, `macos`

**Assignees:** @gemini-cli-team

---

Ahmed Adel Bakr Alderai

### LINKED ISSUE #15874: [BUG] Orphaned gemini-cli process consumes 100% CPU after terminal closure (47+ days)
# [BUG] Orphaned gemini-cli process consumes 100% CPU after terminal closure (47+ days)

## Summary

A `gemini-cli` process becomes orphaned when the parent terminal is closed, enters a CPU spin loop, and runs indefinitely consuming 100% CPU. The observed instance has been running for **47+ days** accumulating **232+ hours of CPU time** (9.7 days of continuous CPU usage).

## Environment

| Component | Value |
|-----------|-------|
| **OS** | macOS Sequoia (Darwin 24.x, arm64) |
| **Hardware** | Apple Mac M4 |
| **Node.js** | v20.x / v22.x (LTS) |
| **gemini-cli version** | v0.15.4 (affected) |
| **Current version** | v0.22.3 |
| **Shell** | zsh / Terminal.app / iTerm2 |

## Steps to Reproduce

1. Open a terminal window
2. Start a gemini-cli session:
   ```bash
   gemini "Analyze this codebase for performance issues"
   ```
3. While the session is active (before it completes), **close the terminal window** using:
   - `Cmd+W` (close window)
   - `Cmd+Q` (quit Terminal.app)
   - Or clicking the window's close button
4. The `gemini` process becomes orphaned and continues running indefinitely

### Minimal Reproduction

```bash
# Terminal 1: Start gemini in background-ish context
cd /path/to/large/project
gemini "Analyze all files in this directory"

# Terminal 2: Simulate terminal closure
kill -HUP $(pgrep -f "gemini")
# Process should terminate gracefully but does NOT
```

## Expected Behavior

When the parent terminal is closed (sending `SIGHUP`), the `gemini-cli` process should:

1. Detect the hangup signal
2. Gracefully terminate any active API connections
3. Clean up resources (file handles, network sockets)
4. Exit with appropriate status code

## Actual Behavior

The process:

1. **Ignores `SIGHUP`** - No signal handler registered
2. **Becomes orphaned** - Reparented to `launchd` (PPID=1)
3. **Loses all file descriptors** - stdin/stdout/stderr become "(revoked)"
4. **Enters infinite spin loop** - Likely polling revoked FDs or awaiting input that never comes
5. **Consumes 100% CPU indefinitely** - Until manually killed

### Process State (47 days after terminal closure)

```
$ ps aux | grep 66164
USER    PID   %CPU %MEM   VSZ    RSS   TT  STAT STARTED      TIME COMMAND
aadel  66164 100.0  0.1 437092864 118896  ??  Rs   18Nov25 232:47.82 node /opt/homebrew/lib/node_modules/@anthropic-ai/claude-code/node_modules/.pnpm/@anthropic-ai+claude-cli@0.15.4/node_modules/@google/gemini-cli/dist/cli.js
```

**Key observations:**
- `%CPU: 100.0` - Full core saturation
- `STAT: Rs` - Running, session leader (orphaned)
- `TT: ??` - No controlling terminal
- `STARTED: 18Nov25` - Running since November 18, 2025
- `TIME: 232:47.82` - 232+ hours of CPU time consumed

### File Descriptor State

```
$ lsof -p 66164
COMMAND   PID  USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
node    66164 aadel  cwd    DIR    1,9     1632  ... /Users/aadel/22_MyAgent
node    66164 aadel  txt    REG    1,9 114955600 ... /opt/homebrew/Cellar/node/22.9.0/bin/node
node    66164 aadel    0u   CHR    2,0      0t0  ... /dev/null (revoked)
node    66164 aadel    1u   CHR    2,0      0t0  ... /dev/null (revoked)
node    66164 aadel    2u   CHR    2,0      0t0  ... /dev/null (revoked)
node    66164 aadel    3u  IPv4 0x...        0t0  ... TCP *:* (CLOSED)
node    66164 aadel    4u  unix 0x...        0t0  ... (revoked)
node    66164 aadel    5u  KQUEUE            ...     count=0, state=0
```

**Critical finding:** All standard file descriptors (0, 1, 2) show `(revoked)` status, indicating the terminal device was deallocated but the process continues attempting I/O operations.

### Parent Process

```
$ ps -o ppid= -p 66164
    1
```

PPID=1 confirms the process was orphaned and reparented to `launchd`.

### 1. Missing Signal Handlers

The CLI does not register handlers for terminal-related signals:

```javascript
// MISSING in cli.js:
process.on('SIGHUP', () => {
  cleanup();
  process.exit(0);
});

process.on('SIGTERM', () => {
  cleanup();
  process.exit(0);
});
```

### 2. Unchecked I/O Operations

The event loop likely contains code that:
- Polls `stdin` for user input without checking if the stream is valid
- Attempts to write to `stdout` without error handling for closed streams
- Uses blocking or busy-wait patterns when streams become unavailable

### 3. No TTY Detection

The process doesn't detect when it loses its controlling terminal:

```javascript
// MISSING check:
if (!process.stdin.isTTY) {
  // Handle non-interactive mode or exit
}
```

## Resource Impact

| Metric | Value | Impact |
|--------|-------|--------|
| CPU Time | 232+ hours | 9.7 days of single-core usage |
| Wall Time | 47+ days | Process lifetime |
| Memory | ~119 MB RSS | Persistent allocation |
| Power | Significant | Continuous M4 efficiency core usage |
| Thermal | Elevated | Sustained CPU load |

### Estimated Energy Cost

At ~5W for M4 efficiency core under load:
- 232 hours x 5W = 1,160 Wh = **1.16 kWh wasted**

### 1. Add Signal Handlers (Critical)

```javascript
// In cli.js or main entry point

const cleanup = () => {
  // Close API connections
  if (activeSession) {
    activeSession.abort();
  }
  // Close file handles
  // Clear timeouts/intervals
};

const gracefulShutdown = (signal) => {
  console.error(`\nReceived ${signal}, shutting down gracefully...`);
  cleanup();
  process.exit(0);
};

process.on('SIGHUP', () => gracefulShutdown('SIGHUP'));
process.on('SIGTERM', () => gracefulShutdown('SIGTERM'));
process.on('SIGINT', () => gracefulShutdown('SIGINT'));

// Handle uncaught exceptions that might cause spin loops
process.on('uncaughtException', (err) => {
  console.error('Uncaught exception:', err);
  cleanup();
  process.exit(1);
});
```

### 2. Add TTY Monitoring

```javascript
// Detect terminal disconnection
process.stdin.on('end', () => {
  console.error('stdin closed, exiting');
  cleanup();
  process.exit(0);
});

process.stdout.on('error', (err) => {
  if (err.code === 'EPIPE' || err.code === 'EIO') {
    cleanup();
    process.exit(0);
  }
});

// Periodic TTY check for long-running sessions
setInterval(() => {
  if (!process.stdin.isTTY && !process.env.GEMINI_NON_INTERACTIVE) {
    console.error('Lost controlling terminal, exiting');
    cleanup();
    process.exit(0);
  }
}, 5000);
```

### 3. Add Watchdog Timer (Defense in Depth)

```javascript
// If no activity for extended period with no TTY, exit
let lastActivity = Date.now();

const watchdog = setInterval(() => {
  const idleMinutes = (Date.now() - lastActivity) / 60000;
  if (idleMinutes > 30 && !process.stdin.isTTY) {
    console.error('Watchdog: No activity with detached terminal, exiting');
    cleanup();
    process.exit(0);
  }
}, 60000);

watchdog.unref(); // Don't block process exit
```

## Workaround (For Affected Users)

Until fixed, users can:

```bash
# Find and kill orphaned gemini processes
pkill -f "gemini-cli"

# Or more specifically
ps aux | grep gemini | grep -v grep | awk '{print $2}' | xargs kill -9

# Add to ~/.zshrc or ~/.bashrc for periodic cleanup
alias gemini-cleanup='pkill -9 -f "gemini-cli.*node"'
```

## Related Issues

- #5942 - Process hangs after API timeout (potentially related event loop issue)
- #5950 - High CPU usage during idle sessions
- Node.js issue: https://github.com/nodejs/node/issues/... (stdin handling after terminal close)

## Version Information

```bash
$ gemini --version
@google/gemini-cli v0.15.4 (affected version)

$ node --version
v22.9.0

$ sw_vers
ProductName:    macOS
ProductVersion: 15.x
BuildVersion:   24xxxxx
```

## Checklist for Fix Verification

- [ ] `SIGHUP` properly terminates the process
- [ ] `SIGTERM` properly terminates the process
- [ ] Closing terminal window terminates child gemini process
- [ ] No orphaned processes after 1 hour of terminal closures
- [ ] CPU usage drops to 0% within 5 seconds of terminal closure
- [ ] Graceful cleanup of API connections on signal
- [ ] Test on macOS (arm64 and x86_64) and Linux

## Additional Context

This bug has significant implications for:

1. **Developer machines** - Accumulated orphan processes over time
2. **CI/CD environments** - Processes may persist after job completion
3. **Server deployments** - Resource exhaustion over time
4. **Battery-powered devices** - Significant power drain

The 47-day runtime demonstrates that this is not a transient issue but a fundamental architectural problem with signal handling in the CLI.

---

**Labels:** `bug`, `high-priority`, `signal-handling`, `resource-leak`, `macos`

**Assignees:** @gemini-cli-team

---

Ahmed Adel Bakr Alderai

### PR DESCRIPTION
**Pull request by yuvrajangadsingh**
## Summary

This PR fixes issues #15874 and #15873 where closing the terminal window causes orphaned Gemini CLI processes to spin at 100% CPU, making the system unresponsive.

### Root Cause
When a terminal is closed, the shell sends SIGHUP to child processes. Without proper signal handling, the CLI process continues running but loses its controlling terminal, causing it to spin in a tight loop trying to read from a closed TTY.

### Solution

This PR implements a two-layer defense:

1. **Signal Handlers** (`setupSignalHandlers`): Handles SIGHUP, SIGTERM, and SIGINT signals with graceful shutdown
2. **TTY Check** (`setupTtyCheck`): Periodic check (every 5s) as defense-in-depth for cases where SIGHUP is not received (e.g., certain terminal emulators, tmux detach)

### Key improvements over PR #15889:
- **Race condition fix**: Uses `isShuttingDown` flag to prevent concurrent shutdown attempts
- **Proper cleanup sequencing**: Clears TTY check interval BEFORE starting cleanup
- **Comprehensive tests**: Adds unit tests for signal handling functions
- **Both modes covered**: Works in both interactive and non-interactive modes

## Changes

- Add `setupSignalHandlers()` function with proper signal handling
- Add `setupTtyCheck()` function with race condition prevention
- Use `registerSyncCleanup` for raw mode restoration
- Register TTY check cleanup in interactive mode
- Add comprehensive unit tests in `gemini.test.ts`
- Update existing test to expect 4 cleanup registrations (was 3)

## Test Plan

- [x] Unit tests pass for signal handling functions
- [x] TypeScript compiles without errors
- [x] Existing tests still pass with updated cleanup count
- [ ] Manual testing: Start CLI, close terminal window → process should exit cleanly
- [ ] Manual testing: Start CLI in tmux, detach → process should exit after ~5s

## Related Issues

Fixes #15874
Fixes #15873
Related to PR #15889 (addresses gaps in that implementation)

### CODE REVIEW

**Comment by yuvrajangadsingh** [comment]
@gemini-code-assist Added the test case for TTY loss scenario in d358abbf4. Thanks for the suggestion!

**Review by iqbalbhatti49 — APPROVED** [review]

File: packages/cli/src/gemini.tsx [hunk 1]
```diff
@@ -176,6 +176,104 @@ ${reason.stack}`
...
+  // Don't keep the process alive just for this interval
+  intervalId.unref();
+
+  return () => {
+    if (intervalId) {
+      clearInterval(intervalId);
+      intervalId = null;
+    }
+  };
+}
```
[the remark this answers is not in the document]
Comment (yuvrajangadsingh) [reply packages/cli/src/gemini.tsx]: Refactored — extracted `gracefulShutdown` to module level so both `setupSignalHandlers` and `setupTtyCheck` share the same shutdown logic. This eliminates the duplicated shutdown code and ensures consistent race condition prevention through the shared `isShuttingDown` guard.

**Comment by yuvrajangadsingh** [comment]
Hey @Adib234 — would you be able to take a look at this one when you get a chance? It fixes orphaned child processes that spike to 100% CPU when the terminal closes. Has a community approval already and all checks pass. Thanks!

File: packages/cli/src/gemini.tsx [hunk 2]
```diff
@@ -181,6 +181,90 @@ ${reason.stack}`
...
+ * processes from consuming 100% CPU when the terminal is closed.
+ *
+ * Handles:
+ * - SIGHUP: Terminal hangup (terminal window closed)
+ * - SIGTERM: Termination request
+ * - SIGINT: Interrupt (Ctrl+C) - as fallback, Ink handles this in interactive mode
+ *
+ * @see https://github.com/google-gemini/gemini-cli/issues/15874
+ */
+let isShuttingDown = false;
```
Comment (scidomino) [inline packages/cli/src/gemini.tsx]: Move as much of this into cleanup.js as you can. gemini.tsx is already big enough as it is.

File: packages/cli/src/gemini.tsx [hunk 3]
```diff
@@ -181,6 +181,90 @@ ${reason.stack}`
...
+}
+
+/**
+ * Sets up periodic TTY check to detect lost controlling terminal.
+ * This is a defense-in-depth measure for cases where SIGHUP is not received
+ * or not processed correctly (e.g., certain terminal emulators, tmux detach).
+ *
+ * @returns Cleanup function to stop the TTY check interval
+ */
+export function setupTtyCheck(): () => void {
```
Comment (scidomino) [inline packages/cli/src/gemini.tsx]: ditto. Move this out of here.

**Review by scidomino — CHANGES_REQUESTED** [review]

File: packages/cli/src/gemini.tsx (hunk 2 above)
Comment (yuvrajangadsingh) [reply packages/cli/src/gemini.tsx]: done — moved all of it (gracefulShutdown, isShuttingDown, setupSignalHandlers, setupTtyCheck) into utils/cleanup.ts

File: packages/cli/src/gemini.tsx (hunk 3 above)
Comment (yuvrajangadsingh) [reply packages/cli/src/gemini.tsx]: done

File: packages/cli/src/utils/cleanup.ts [hunk 4]
```diff
@@ -100,6 +103,90 @@ async function drainStdin() {
...
+ * processes from consuming 100% CPU when the terminal is closed.
+ *
+ * Handles:
+ * - SIGHUP: Terminal hangup (terminal window closed)
+ * - SIGTERM: Termination request
+ * - SIGINT: Interrupt (Ctrl+C) - as fallback, Ink handles this in interactive mode
+ *
+ * @see https://github.com/google-gemini/gemini-cli/issues/15874
+ */
+let isShuttingDown = false;
```
Comment (scidomino) [inline packages/cli/src/utils/cleanup.ts]: Please declare this at the top with the other variables.

File: packages/cli/src/utils/cleanup.ts [hunk 5]
```diff
@@ -100,6 +103,90 @@ async function drainStdin() {
...
+ * Sets up signal handlers to ensure graceful shutdown and prevent orphaned
+ * processes from consuming 100% CPU when the terminal is closed.
+ *
+ * Handles:
+ * - SIGHUP: Terminal hangup (terminal window closed)
+ * - SIGTERM: Termination request
+ * - SIGINT: Interrupt (Ctrl+C) - as fallback, Ink handles this in interactive mode
+ *
+ * @see https://github.com/google-gemini/gemini-cli/issues/15874
+ */
```
Comment (scidomino) [inline packages/cli/src/utils/cleanup.ts:112]: GCLI tends to be very verbose on comments. Most of this is unnecessary. Instead, make this part of doc for the gracefulShutdown function

File: packages/cli/src/utils/cleanup.ts [hunk 6]
```diff
@@ -100,6 +103,90 @@ async function drainStdin() {
...
+let isShuttingDown = false;
+
+const gracefulShutdown = async (reason: string) => {
```
Comment (scidomino) [inline packages/cli/src/utils/cleanup.ts]: Is there a reason this is declared as a variable instead of as a function?

File: packages/cli/src/utils/cleanup.ts [hunk 7]
```diff
@@ -100,6 +103,90 @@ async function drainStdin() {
...
+  // Prevent multiple concurrent shutdown attempts
+  if (isShuttingDown) {
+    return;
+  }
+  isShuttingDown = true;
+
+  debugLogger.debug(`Shutting down gracefully due to ${reason}...`);
```
Comment (scidomino) [inline packages/cli/src/utils/cleanup.ts]: This log seems unnecessary. remove it and simplify your code accordingly.

File: packages/cli/src/utils/cleanup.ts [hunk 8]
```diff
@@ -100,6 +103,90 @@ async function drainStdin() {
...
+  try {
+    await runExitCleanup();
+  } catch (err) {
+    debugLogger.debug(`Error during cleanup for ${reason}:`, err);
```
Comment (scidomino) [inline packages/cli/src/utils/cleanup.ts]: Not clear what value we get from catching this error. Can we just not catch it?

File: packages/cli/src/utils/cleanup.ts [hunk 9]
```diff
@@ -100,6 +103,90 @@ async function drainStdin() {
...
+  }
+  process.exit(ExitCodes.SUCCESS);
+};
+
+export function setupSignalHandlers() {
+  // SIGHUP is sent when terminal is closed - critical for preventing orphans
```
Comment (scidomino) [inline packages/cli/src/utils/cleanup.ts]: This comment seems unnecessary

File: packages/cli/src/utils/cleanup.ts [hunk 10]
```diff
@@ -100,6 +103,90 @@ async function drainStdin() {
...
+  let isCheckingTty = false;
+
+  intervalId = setInterval(async () => {
+    // Prevent concurrent TTY checks
+    if (isCheckingTty || isShuttingDown) {
+      return;
+    }
+
+    // Skip check in sandbox mode or if explicitly running non-interactively
+    if (process.env['SANDBOX'] || process.env['GEMINI_NON_INTERACTIVE']) {
```
Comment (scidomino) [inline packages/cli/src/utils/cleanup.ts]: "GEMINI_NON_INTERACTIVE" is hallucinated. That string does not appear in our code base.

Similarly, are we sure SANDBOX is the right way to check for sandbox mode?

File: packages/cli/src/gemini.tsx [hunk 11]
```diff
@@ -319,6 +321,11 @@ export async function startInteractiveUI(
     });
 
   registerCleanup(() => instance.unmount());
+
+  // Set up TTY check for interactive mode as defense-in-depth
```
Comment (scidomino) [inline packages/cli/src/gemini.tsx]: This comment seems unnecessary

File: packages/cli/src/gemini.tsx [hunk 12]
```diff
@@ -319,6 +321,11 @@ export async function startInteractiveUI(
...
+  // against orphaned processes when terminal closes without sending SIGHUP
+  const stopTtyCheck = setupTtyCheck();
```
Comment (scidomino) [inline packages/cli/src/gemini.tsx]: Nit: inline this variable.

File: packages/cli/src/gemini.tsx [hunk 13]
```diff
@@ -645,11 +654,9 @@ export async function main() {
       // input showing up in the output.
       process.stdin.setRawMode(true);
 
-      // This cleanup isn't strictly needed but may help in certain situations.
-      process.on('SIGTERM', () => {
-        process.stdin.setRawMode(wasRaw);
-      });
-      process.on('SIGINT', () => {
+      // Register raw mode restoration for cleanup on exit
```
Comment (scidomino) [inline packages/cli/src/gemini.tsx]: Why did you change this comment?

File: packages/cli/src/utils/cleanup.ts (hunk 4 above)
Comment (yuvrajangadsingh) [reply packages/cli/src/utils/cleanup.ts]: done

File: packages/cli/src/utils/cleanup.ts (hunk 5 above)
Comment (yuvrajangadsingh) [reply packages/cli/src/utils/cleanup.ts:112]: done

File: packages/cli/src/utils/cleanup.ts (hunk 6 above)
Comment (yuvrajangadsingh) [reply packages/cli/src/utils/cleanup.ts]: done

File: packages/cli/src/utils/cleanup.ts (hunk 7 above)
Comment (yuvrajangadsingh) [reply packages/cli/src/utils/cleanup.ts]: done

File: packages/cli/src/utils/cleanup.ts (hunk 8 above)
Comment (yuvrajangadsingh) [reply packages/cli/src/utils/cleanup.ts]: done

File: packages/cli/src/utils/cleanup.ts (hunk 9 above)
Comment (yuvrajangadsingh) [reply packages/cli/src/utils/cleanup.ts]: done

File: packages/cli/src/gemini.tsx (hunk 11 above)
Comment (yuvrajangadsingh) [reply packages/cli/src/gemini.tsx]: done

File: packages/cli/src/gemini.tsx (hunk 12 above)
Comment (yuvrajangadsingh) [reply packages/cli/src/gemini.tsx]: done

File: packages/cli/src/utils/cleanup.ts (hunk 10 above)
Comment (yuvrajangadsingh) [reply packages/cli/src/utils/cleanup.ts]: you're right, removed it. SANDBOX is valid — used in gemini.tsx:510 and test files. kept that check only.

File: packages/cli/src/gemini.tsx (hunk 13 above)
Comment (yuvrajangadsingh) [reply packages/cli/src/gemini.tsx]: reverted to original wording — was an unnecessary change on my part.

File: packages/cli/src/utils/cleanup.ts (hunk 6 above)
Comment (yuvrajangadsingh) [reply packages/cli/src/utils/cleanup.ts]: no good reason, just a habit. changed it to a function declaration.

File: packages/cli/src/utils/cleanup.ts (hunk 8 above)
Comment (yuvrajangadsingh) [reply packages/cli/src/utils/cleanup.ts]: yeah, no real value. removed the try/catch — runExitCleanup already handles errors internally for each cleanup function.

**Review by scidomino — APPROVED** [review]

**Comment by yuvrajangadsingh** [comment]
the lint failure is a pre-existing issue with `gemini.test.tsx` — the typescript-eslint projectService can't resolve it. it passes on main only because of the eslint cache. since we modified the file (added mock entries for the new exports), the cache busts and the error surfaces.

i verified by checking out main's version of the file and running eslint on it locally — same error. all tests pass across all platforms.

want me to add `allowDefaultProject` to the eslint config to fix it, or can this be merged as-is?

**Review by scidomino — APPROVED** [review]
