### PR TITLE
fix(hooks): support 'ask' decision for BeforeTool hooks

### LINKED ISSUE #15732: feat(hooks): support 'decision: ask' to force user confirmation
## Description
Support a new hook decision `ask` that allows a hook to force a user confirmation prompt, even if a tool is currently allowlisted or the user is running in 'YOLO' mode. This is useful for sensitive operations that require manual oversight regardless of general security policies.

## Proposed Behavior
When a `BeforeTool` hook returns `decision: 'ask'`:
1. The `CoreToolScheduler` should interrupt its normal auto-approval logic.
2. The user should be presented with the standard interactive confirmation prompt for that tool.
3. The hook's `systemMessage` (if provided) should be displayed to explain why the confirmation is being forced.

## Implementation Details
1. Move the `BeforeTool` hook trigger point from `executeToolWithHooks` into `CoreToolScheduler._processNextInQueue`.
2. Fire the hook before the `isAutoApproved` check.
3. Update `isAutoApproved` (or the logic surrounding it) to respect the hook's decision, prioritizing `ask` as a requirement for manual confirmation.

### PR DESCRIPTION
**Pull request by gundermanc**
## Summary

This PR adds support for a new hook decision `ask` for `BeforeTool` hooks.

image

## Details

- Implemented `isAskDecision` for hook outputs.
- Track `hasAskDecision` in `HookAggregator`.
- Refactored `BeforeTool` execution from `ToolExecutor` (`coreToolHookTriggers.ts`) into the main `MessageBus` loop in `scheduler.ts`'s `_processToolCall`. This ensures `BeforeTool` hooks run prior to policy checks and the confirmation loop, preventing double execution.
- If a hook decides `ask`, it overrides the `ALLOW` policy to `ASK_USER`.
- Injected `systemMessage` from hooks directly into `ToolCallConfirmationDetails` and `SerializableConfirmationDetails` so it can be surfaced to the user.
- Updated `ToolExecutor` to append the system modification message to the LLM context if the hook modified parameters, as this logic was moved out of `executeToolWithHooks`.

## Related Issues

Closes #15732
Replaces #16463

## How to Validate

Create a dummy `BeforeTool` hook that returns `{ decision: 'ask', systemMessage: 'Are you sure?' }`. Execute the tool and verify it stops auto-execution and prompts you with the system message.

## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [ ] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [x] Validated on required platforms/methods:
  - [x] MacOS
    - [x] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

File: packages/cli/src/ui/hooks/useGeminiStream.ts [hunk 1]
```diff
@@ -548,11 +548,9 @@ export const useGeminiStream = (
...
         return false;
       }
-      return (
-        tc.status !== 'scheduled' &&
-        tc.status !== 'validating' &&
-        tc.status !== 'awaiting_approval'
-      );
+      // ToolGroupMessage now shows all non-canceled tools, so they are visible
+      // in pending and we need to draw the closing border for them.
+      return true;
```
Comment (gundermanc) [inline packages/cli/src/ui/hooks/useGeminiStream.ts:553]: I think this fixes an unrelated bug where two tool result boxes intersect.

File: packages/core/src/core/coreToolScheduler.ts [hunk 2]
```diff
@@ -49,6 +49,7 @@ import { ToolExecutor } from '../scheduler/tool-executor.js';
 import { DiscoveredMCPTool } from '../tools/mcp-tool.js';
 import { getPolicyDenialError } from '../scheduler/policy.js';
 import { GeminiCliOperation } from '../telemetry/constants.js';
+import { evaluateBeforeToolHook } from '../scheduler/hook-utils.js';
```
Comment (joshualitt) [inline packages/core/src/core/coreToolScheduler.ts:52]: hmm, I thought the coreToolScheduler was no longer used? Wonder if maybe we should just delete this... anyway, need not be in this pr.

**Review by joshualitt — APPROVED** [review]
