### PR TITLE
Fix alt+left on ghostty

### LINKED ISSUE #12489: `opt+left` prints "b" in ghostty
### What happened?

On terminal keyboard logging shows:

```
[DEBUG] Keystroke: {"sequence":"\u001bb","name":"b","ctrl":false,"meta":true,"shift":false,"paste":false} 
```

On Ghostty:

```
[DEBUG] Kitty buffer accumulating: "\u001bb"
[DEBUG] Not a kitty sequence, flushing: "\u001bb"
[DEBUG] Keystroke: {"sequence":"\u001bb","name":"","ctrl":false,"meta":false,"shift":false,"paste":false}
```

### What did you expect to happen?

should move cursor to the left.

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
# paste output here
```

</details>

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by scidomino**
## Summary

Be smarter about which codes we attempt to parse as kitty codes.

## Details

Previously, we were trying to parse sequences that were not kitty codes at all and ended up breaking them.

## Related Issues

Fixes #12489

## How to Validate

Run in ghostty and verify that alt+left moves the cursor instead of printing "b".

## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [x] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [ ] Validated on required platforms/methods:
  - [ ] MacOS
    - [ ] npm run
    - [x] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

File: packages/cli/src/ui/contexts/KeypressContext.tsx [hunk 1]
```diff
@@ -688,9 +688,9 @@ export function KeypressProvider({
       // Always check if this could start a sequence we need to buffer (Kitty or Mouse)
       // We only want to intercept if it starts with ESC[ (CSI) or is EXACTLY ESC (waiting for more).
       // Other ESC sequences (like Alt+Key which is ESC+Key) should be let through if readline parsed them.
-      const isCSI = key.sequence.startsWith(`${ESC}[`);
+      const couldBeKitty = couldBeKittySequence(key.sequence);
       const isExactEsc = key.sequence === ESC;
-      const shouldBuffer = isCSI || isExactEsc;
+      const shouldBuffer = couldBeKitty || isExactEsc;
```
Comment (abhipatel12) [inline packages/cli/src/ui/contexts/KeypressContext.tsx]: `couldBeKittySequence` should cover both of these!

**Review by abhipatel12 — APPROVED** [review]
LGTM with one question!
