### PR TITLE
Enable write_todo tool and fix output function schema

### LINKED ISSUE #12675: write_todo tool is seeing MALFORMED_FUNCTION_CALL errors
This has resulted in a regression because we exit after a malformed function call error. This is because the json output by the model is incorrect. Update the output format such that we see a lower number of these errors.

### PR DESCRIPTION
**Pull request by anj-s**
## Summary
Enable write_todo tool and fix schema regression.

## Details
* Tool Enablement: The write_todos tool is now enabled by default. This was done by updating the default configuration in
     packages/core/src/config/config.ts and updating the corresponding settings schemas in
 packages/cli/src/config/settingsSchema.ts and schemas/settings.schema.json.
 * Schema Correction: The responseJsonSchema for the write_todos tool has been fixed in packages/core/src/tools/write-todos.ts. The schema now correctly defines the response as an object containing a todos array, where each item is an object with description and status properties.
* Documentation: The documentation has been updated to reflect that the write_todos tool is now enabled by default.

## Related Issues

Fixes #12675 

## How to Validate

Start gemini-cli and verify that you can use the ToDo tool successfully. Evals show no regression.

## Pre-Merge Checklist

- [x] Updated relevant documentation and README (if needed)
- [x] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [ ] Validated on required platforms/methods:
  - [ ] MacOS
    - [x] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

**Review by SandyTao520 — APPROVED** [review]

File: packages/core/src/tools/write-todos.ts [hunk 1]
```diff
@@ -156,31 +156,60 @@ export class WriteTodosTool extends BaseDeclarativeTool<
         properties: {
           todos: {
             type: 'array',
```
Comment (scidomino) [inline packages/core/src/tools/write-todos.ts:158]: Was removing the param descriptions intentional? I think that will break things.

**Review by scidomino — APPROVED** [review]
