### PR TITLE
fix(core): replace custom binary detection with isbinaryfile to correctly handle UTF-8 (U+FFFD)

### LINKED ISSUE #24547: '�' character in Rust source file crashes gemini-cli
### What happened?

When gemini-cli uses various tools to read or write this character '�' in a .rs file, it crashes severely.

### What did you expect to happen?

I expected it not to crash. Rust toolchain and claude-code have no issues w/ this character.

### Probably cause

The issue is likely that Gemini CLI's file reading/editing tools are choking on the raw U+FFFD byte sequence (0xEF 0xBF 0xBD in UTF-8). Some tools treat this character as a signal that the file contains "invalid" data, since U+FFFD is what decoders emit when they encounter malformed bytes. The tool probably can't distinguish between "this file literally contains U+FFFD" and "this file has encoding errors."

Gemini CLI is written in TypeScript/Node.js. Node.js uses UTF-16 internally for strings, and U+FFFD is the character that TextDecoder emits when it encounters malformed bytes. So the file reading code likely has a check like "if the decoded string contains U+FFFD, the file must be binary/corrupt" — which is a false positive when the source file literally contains that character. 

It's a naive heuristic and a sloppy check without considering that it can appear intentionally in source code. And it should be fixed. Rust's char type and the Rust toolchain handle Unicode correctly by design.

### Client information

* **CLI Version:** 0.36.0
* **Git Commit:** 8b1e649c2
* **Session ID:** 92d14c5d-5be1-456a-92d0-e6c4cdc22692
* **Operating System:** linux v22.22.0
* **Sandbox Environment:** no sandbox
* **Model Version:** auto-gemini-3
* **Auth Type:** oauth-personal
* **Memory Usage:** 251.3 MB
* **Terminal Name:** WezTerm 20260321_093732_eea9aa79
* **Terminal Background:** #282a36
* **Kitty Keyboard Protocol:** Unsupported

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by Anjaligarhwal**
## Summary
Fixes #24547. Replaces the hand-rolled UTF-8 byte heuristic in `isBinaryFile()` with a delegation to the `isbinaryfile` npm package, so source files that legitimately contain the Unicode replacement character U+FFFD (`EF BF BD` in UTF-8) are no longer misclassified as binary.

## Details
- Adds `isbinaryfile@^5.0.7` as a `packages/core` dependency (Node ≥20 compatible, zero transitive deps, MIT-licensed, same library used by ESLint / Turborepo).
- `isBinaryFile()` in `packages/core/src/utils/fileUtils.ts` becomes a thin wrapper over `isbinaryfile`'s async API. Public signature is unchanged, so no call sites need updating.
- The library handles Unicode BOMs (UTF-8/16/32/GB-18030), PDF magic, NULL bytes, valid UTF-8 multibyte sequences, and an invalid-byte ratio (overlong encodings, post-U+10FFFF, DEL character).
- `detectBOM()` is kept in place because `readFileWithEncoding` and `isEmpty` still use it for BOM-aware decoding.
- Error semantics preserved: I/O errors (ENOENT, path-is-directory, etc.) still resolve to `false` with a `debugLogger.warn`, matching previous behavior for callers downstream.

## Related Issues
- Closes #24547

## How to Validate
1. `cd packages/core && npm run typecheck && npm run lint`
2. `cd packages/core && npx vitest run src/utils/fileUtils.test.ts` — 16 `isBinaryFile` tests pass (5 existing + 3 new regression tests for U+FFFD, mixed UTF-8, and invalid high-byte sequences, plus 8 BOM tests).
3. `cd packages/core && npx vitest run src/tools/read-file.test.ts src/tools/read-many-files.test.ts` — all downstream consumers clean.
4. Manual: create a file containing `'\uFFFD'`, run `read_file` / `replace` against it — content preserved, no hexdump corruption.

## Pre-Merge Checklist
- [x] `npm run typecheck` passes
- [x] `npm run lint` passes
- [x] `npx prettier --check` passes
- [x] Unit tests pass (including 3 new regression guards)
- [x] No behavior change for callers; function signature identical

### CODE REVIEW

File: packages/core/src/utils/fileUtils.ts [hunk 1]
```diff
@@ -345,53 +346,30 @@ export async function isEmpty(filePath: string): Promise<boolean> {
 
 /**
  * Heuristic: determine if a file is likely binary.
```
Comment (scidomino) [inline packages/core/src/utils/fileUtils.ts:348]: Delete the vast majority of this comment. It shouldn't be more than one or two sentences long now that we removed most of the logic.

File: packages/core/src/utils/fileUtils.test.ts [hunk 2]
```diff
@@ -286,6 +286,35 @@ describe('fileUtils', () => {
       }
       expect(await isBinaryFile(filePathForBinaryTest)).toBe(false);
     });
+
+    it('should return false for a source file containing literal U+FFFD (replacement character)', async () => {
+      // U+FFFD is a valid Unicode codepoint that legitimately appears in source
```
Comment (scidomino) [inline packages/core/src/utils/fileUtils.test.ts]: Remove this comment. The test title tells us enough.

File: packages/core/src/utils/fileUtils.test.ts [hunk 3]
```diff
@@ -286,6 +286,35 @@ describe('fileUtils', () => {
...
+      // not treat these bytes as evidence of a binary file. Regression guard
+      // for issue #24547.
+      const content =
+        '// Rust-style source\npub const UNICODE_REPLACEMENT_CHAR: char = \'\uFFFD\';\nlet s = "\uFFFD\uFFFD\uFFFD";\n';
+      actualNodeFs.writeFileSync(filePathForBinaryTest, content, 'utf8');
+      expect(await isBinaryFile(filePathForBinaryTest)).toBe(false);
+    });
+
+    it('should return false for a file with mixed CJK, emoji, and U+FFFD content', async () => {
+      // Valid UTF-8 multibyte sequences (2/3/4-byte) must not trip the binary
```
Comment (scidomino) [inline packages/core/src/utils/fileUtils.test.ts]: ditto

File: packages/core/src/utils/fileUtils.test.ts [hunk 4]
```diff
@@ -286,6 +286,35 @@ describe('fileUtils', () => {
...
+      // heuristic. This exercises 3-byte (CJK, U+FFFD) and 4-byte (emoji via
+      // surrogate pair) sequences together.
+      const content = '\uFFFD\uFFFD hello \u4e16\u754c \uD83D\uDE00\n';
+      actualNodeFs.writeFileSync(filePathForBinaryTest, content, 'utf8');
+      expect(await isBinaryFile(filePathForBinaryTest)).toBe(false);
+    });
+
+    it('should return true for a file with dense invalid UTF-8 byte sequences', async () => {
+      // Raw high bytes that do not form valid UTF-8 continuation sequences
```
Comment (scidomino) [inline packages/core/src/utils/fileUtils.test.ts]: ditto

**Review by scidomino — CHANGES_REQUESTED** [review]

**Comment by Anjaligarhwal** [comment]
Thanks for the review @scidomino, all four items addressed in `126ea0e` -Trimmed JSDoc on isBinaryFile() to two sentences, removed inline comments from all three new test cases
PTAL when you get a chance

**Review by scidomino — APPROVED** [review]

**Comment by scidomino** [comment]
Note: don't push any updates now or we will have to restart the CI checks

**Comment by Anjaligarhwal** [comment]
Understood, i won't push anything thanks for handling this!
