### PR TITLE
fix(core): Provide compact, actionable errors for agent delegation failures

### LINKED ISSUE #16429: [Task] Return more informative message to model for failed delegation
Subagent delegation occurs via the `delegate_agent` tool. In some cases, 2.5 models are more likely to make a mistake during the function request formation. 

We should return a more informative error message back to the model so that it can self-heal from this and correctly call the subagent tool

### PR DESCRIPTION
**Pull request by SandyTao520**
## TLDR

This PR changes the validation logic for the `delegate_to_agent` tool to provide ultra-compact, LLM-friendly error messages when incorrect agent names or parameters are used. This allows the model to self-heal and retry successfully.

## Dive Deeper

Currently, if the model hallucinates an agent name or misses a required argument, the framework returns a generic Zod schema error (e.g., `"params must match a schema in anyOf"`) before the tool executes. The model cannot recover from this.

This PR:
1. Bypasses the default `anyOf` schema validation in `validateToolParams`.
2. Adds explicit checks inside `execute` for agent existence and Zod schema validation for specific agent inputs. 
3. Formats resulting errors into single-line strings that maximize token efficiency while giving the LLM exact instructions on how to self-heal (e.g. `"objective: Required. Expected inputs: 'objective' (required string)."`).

## Reviewer Test Plan

1. Run the CLI.
2. Trigger the `delegate_to_agent` tool manually by asking the CLI to do something that requires delegation (e.g. `@gemini explore codebase for x`).
3. Intercept or force a bad tool call (e.g. forget the `objective` parameter).
4. Verify the CLI returns the compact string: `"objective: Required. Expected inputs: 'objective' (required string)."` instead of the raw JSON schema error.

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | ✅  | ❓  | ❓ |
| npx      | ✅  | ❓  | ❓  |
| Docker   | ❓  | ❓  | ❓  |
| Podman   | ❓  | -   | -   |
| Seatbelt | ❓  | -   | -   |

## Linked issues / bugs

Resolves #16429

### CODE REVIEW

File: packages/core/src/agents/delegate-to-agent-tool.ts [hunk 1]
```diff
@@ -126,6 +126,14 @@ export class DelegateToAgentTool extends BaseDeclarativeTool<
     );
   }
 
+  override validateToolParams(_params: DelegateParams): string | null {
+    // We override the default schema validation because the generic JSON schema validation
```
Comment (scidomino) [inline packages/core/src/agents/delegate-to-agent-tool.ts:130]: I'm confused. Why can't the validation logic go here? You should be able to reference this.registry.getAllDefinitions() from inside this method.

Comment (SandyTao520) [reply packages/core/src/agents/delegate-to-agent-tool.ts:130]: You raise an excellent point. Since `DelegateToAgentTool` has access to `this.registry`, we technically *could* have put the validation logic directly into `validateToolParams`.

However, putting it in `execute` was a deliberate design choice for a few key reasons:

1. **Avoiding Duplicate Work (The Main Reason):** 
   `validateToolParams` can only return an error string or `null`—it cannot return the *parsed* and *validated* object. If we validated the agent definition and Zod schema in `validateToolParams`, we would have to look up the agent in the registry *again* and separate the `agentArgs` *again* inside the `execute` method to actually run the sub-agent. By doing it all in `execute`, we validate and consume the data in one clean step.

2. **Dynamic State vs. Static Structure:**
   Typically, `validateToolParams` is reserved for static structural checks (like standard JSON schema validation). The `AgentRegistry`, however, is a dynamic runtime state (agents can theoretically be registered or unregistered). It's a best practice in this framework to check dynamic runtime state during the `execute` phase.

3. **Sub-Agent Invocation:**
   In `execute`, we use the specific agent definition to build the `SubagentToolWrapper`. If the specific agent's Zod schema validation fails here, it is directly tied to the *execution* of that sub-agent failing, which correctly routes the error through the execution pipeline.

So while it absolutely could work in `validateToolParams`, placing it in `execute` keeps the code DRY (Don't Repeat Yourself) and aligns better with how dynamic tool execution is handled in the framework.

**Review by scidomino — APPROVED** [review]
