### PR TITLE
fix: exclude DEBUG and DEBUG_MODE from project .env files by default

### LINKED ISSUE #2900: Gemini CLI cannot work with correct AI model when my project root has .env GEMINI_MODEL=gemma-3-12b-it
### What happened?

Gemini CLI cannot work with correct AI model when my project root has .env GEMINI_MODEL=gemma-3-12b-it

Gemini CLI will show the model is gemma-3-12b-it, instead of gemini-2.5-pro or gemini-2.5-flash.
This is reproducible by setting up .env file with GEMINI_MODEL=gemma-3-12b-it in project root. Then, start "gemini" at root folder.

### What did you expect to happen?

I expect Gemini CLI can use correct model.

### Client information

<details>

```console
$ gemini /about
About Gemini CLI                       ?
?                                        ?
? CLI Version  0.1.7                     ?
? Git Commit   55cc809                   ?
? Model        gemini-2.5-pro            ?
? Sandbox      no sandbox                ?
? OS           linux                     ?
? Auth Method  OAuth         
```

</details>

### Login information

Google Account

### Anything else we need to know?

_No response_

### LINKED ISSUE #4770: gemini cli loads DEBUG=True from local .env file
### What happened?

Launching gemini in a directory that has an `.env` file with `DEBUG=True` launched the gemini cli tool in a debug state. 

Image

### What did you expect to happen?

I expect gemini to launch normally. The local .env file is related to the current project directory and is not for gemin-cli to evaluate and use. 

### Client information

<details>

```console
$ gemini /about
| CLI Version              0.1.13                                         │
│ Git Commit               412b78c5 (local modifications)                 │
│ Model                    gemini-2.5-pro                                 │
│ Sandbox                  sandbox-exec (permissive-open)                 │
│ OS                       darwin                                         │
│ Auth Method              OAuth                  
```

</details>

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by gotgelf**
## TLDR
This PR fixes an issue where project-specific `.env` files (e.g., containing `DEBUG=true`) unexpectedly trigger debug mode in gemini-cli. The solution adds an `excludedProjectEnvVars` setting to `settings.json` that automatically excludes problematic variables like `DEBUG` and `DEBUG_MODE` from project `.env` files, while preserving variables from .gemini/.env files.

**Key changes:**
- Add environment variable exclusion logic in `settings.ts`
- Default exclusions for `DEBUG` and `DEBUG_MODE`
- Documentation updates
- Unit tests for the new functionality

### Problem Context
When users have project-specific `.env` files (common in development workflows), variables like `DEBUG=true` were being loaded by gemini-cli and causing it to launch in debug mode unexpectedly. This created confusion as users expected normal CLI operation.

### Solution 
The solution implements a three-tier approach:
- Global configuration (~/.gemini/.env) for shared variables
- Project configuration (.gemini/.env in project root) for project-specific overrides
- Exclusion list in settings.json to filter problematic variables from regular project .env files

### Setup
- Clone the branch and run npm install
- Run npm run test to verify all tests pass
- Create test scenarios with different .env file configurations

### Validation Steps
**Test 1: Shell Environment Variables Are Respected**
```bash
# Set shell environment variable
DEBUG=1 npm start

# Should start in debug mode regardless of project .env files
# Verify DEBUG=1 is preserved and not overwritten
```

**Test 2: Default Exclusion Behavior**
```bash
# Create a project .env file
echo "DEBUG=true" > .env
echo "GOOGLE_CLOUD_PROJECT=test-project" >> .env

# Run gemini-cli
npm run start

# Verify DEBUG is not set in process
# Verify GOOGLE_CLOUD_PROJECT is still loaded
```

**Test 3: Custom Exclusion List**
```bash
# Create settings.json with custom exclusions
echo '{"excludedProjectEnvVars": ["DEBUG"]}' > .gemini/settings.json

# Create project .env
echo "DEBUG=true" >> .env

# Run gemini-cli and verify both are excluded
npm run start
```
**Test 4: .gemini/.env Files Are Never Excluded**
```bash
# Create .gemini/.env with DEBUG
echo "DEBUG=true" > .gemini/.env

# Run gemini-cli and verify DEBUG is loaded
npm run start
```
## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | ✅  | ❓  | ❓  |
| npx      | ❓  | ❓  | ❓  |
| Docker   | ❓  | ❓  | ❓  |
| Podman   | ❓  | -   | -   |
| Seatbelt | ❓  | -   | -   |

## Linked issues / bugs

- Fixes #4770
- Fixes #2900

### CODE REVIEW

File: packages/cli/src/config/settings.ts [hunk 1]
```diff
@@ -262,6 +265,13 @@ function findEnvFile(startDir: string): string | null {
   }
 }
 
+/**
+ * Get default excluded environment variables that should not be loaded from project .env files
+ */
+function getDefaultExcludedEnvVars(): string[] {
```
Comment (jacob314) [inline packages/cli/src/config/settings.ts]: nit: make this a  top level constant instead of a getter.

File: packages/cli/src/config/settings.ts [hunk 2]
```diff
@@ -284,15 +294,44 @@ export function setUpCloudShellEnvironment(envFilePath: string | null): void {
...
 }
 
-export function loadEnvironment(): void {
+export function loadEnvironment(settings?: Settings): void {
   const envFilePath = findEnvFile(process.cwd());
 
-  if (process.env.CLOUD_SHELL === 'true') {
-    setUpCloudShellEnvironment(envFilePath);
+  // Cloud Shell environment variable handling
+  if (process.env.CLOUDSHELL_ENVIRONMENT) {
```
Comment (jacob314) [inline packages/cli/src/config/settings.ts]: can you continue to use the setupCloudShellEnvironment? this change seems unrelated to the fix in this pr. sorry if I am missing something.
if changes need to be made to setUpCloudShellEnvironment please make them in that method.

File: packages/cli/src/config/settings.ts [hunk 3]
```diff
@@ -284,15 +294,44 @@ export function setUpCloudShellEnvironment(envFilePath: string | null): void {
...
+    try {
+      const envFileContent = fs.readFileSync(envFilePath, 'utf-8');
+      const parsedEnv = dotenv.parse(envFileContent);
+
+      const excludedVars =
+        settings?.excludedProjectEnvVars || getDefaultExcludedEnvVars();
+      const isProjectEnvFile = !envFilePath.includes(GEMINI_DIR);
+
+      for (const key in parsedEnv) {
+        if (Object.prototype.hasOwnProperty.call(parsedEnv, key)) {
```
Comment (jacob314) [inline packages/cli/src/config/settings.ts]: here and elsewhere, `Object.hasOwn` is now the new way to do this that is a bit easier to read.

File: packages/cli/src/config/settings.ts [hunk 4]
```diff
@@ -375,6 +414,16 @@ export function loadSettings(workspaceDir: string): LoadedSettings {
     });
   }
 
+  // Create temporary merged settings for environment loading
+  const tempMergedSettings = {
```
Comment (jacob314) [inline packages/cli/src/config/settings.ts]: rather than doing this, can we move creating LoadedSettings to before we call loadEnvironment. That should be possible and will be cleaner than creating this temp settings object which I would worry someone might accidentally save a reference to within loadEnvironment resulting in confusing duplicate settings..

**Review by jacob314 — COMMENTED** [review]
Thanks for addressing this high priority issue! I will approve once these hopefully minor issues are addressed. If any of these comments are hard to address please let me know.

File: packages/cli/src/config/settings.ts (hunk 2 above)
Comment (gotgelf) [reply packages/cli/src/config/settings.ts]: Hi @jacob314 , done.

File: packages/cli/src/config/settings.ts (hunk 3 above)
Comment (gotgelf) [reply packages/cli/src/config/settings.ts]: Nice catch, addressed.

File: packages/cli/src/config/settings.ts (hunk 4 above)
Comment (gotgelf) [reply packages/cli/src/config/settings.ts]: Totally agree, done

File: packages/cli/src/config/settings.ts (hunk 1 above)
Comment (gotgelf) [reply packages/cli/src/config/settings.ts]: done

**Comment by gotgelf** [comment]
Hi @jacob314, I’ve addressed the issues and also added a commit for an edge case I found today — excludedProjectEnvVars wasn’t being respected when loadEnvironment() was called without settings.

> Thanks for addressing this high priority issue! I will approve once these hopefully minor issues are addressed. If any of these comments are hard to address please let me know.

**Review by jacob314 — APPROVED** [review]
Thanks for thislgtm clean fix to an issue that was impacting a bunch of users!

**Comment by gotgelf** [comment]
> Thanks for thislgtm clean fix to an issue that was impacting a bunch of users!

Hi @jacob314, I’ve resolved the conflicts blocking merge. Let me know if there’s anything else I should take care of.

File: packages/cli/src/config/settings.ts [hunk 5]
```diff
@@ -366,6 +369,21 @@ export function loadSettings(workspaceDir: string): LoadedSettings {
   const settingsErrors: SettingsError[] = [];
   const systemSettingsPath = getSystemSettingsPath();
 
+  // FIX: Resolve paths to their canonical representation to handle symlinks
```
Comment (jacob314) [inline packages/cli/src/config/settings.ts:372]: nit: as a followup cleanup can you remove the word `FIX: `

File: packages/cli/src/config/settings.ts [hunk 6]
```diff
@@ -406,21 +424,24 @@ export function loadSettings(workspaceDir: string): LoadedSettings {
...
-      ) as Settings;
-      workspaceSettings = resolveEnvVarsInObject(parsedWorkspaceSettings);
-      if (workspaceSettings.theme && workspaceSettings.theme === 'VS') {
-        workspaceSettings.theme = DefaultLight.name;
-      } else if (
-        workspaceSettings.theme &&
-        workspaceSettings.theme === 'VS2015'
-      ) {
-        workspaceSettings.theme = DefaultDark.name;
+  // This comparison is now much more reliable.
```
Comment (jacob314) [inline packages/cli/src/config/settings.ts:427]: nit: remove this comment as well as it describes how code changed not what it does

**Review by jacob314 — APPROVED** [review]
lgtm
