### PR TITLE
fix(cli): prioritize configured auth over env vars in non-interactive mode

### LINKED ISSUE #10933: Inconsistent auth handling between Interactive and Non-interactive mode
### What happened?

In non-interactive mode, if GEMINI_API_KEY is set, it overrides any previously configured OAuth method.

### What did you expect to happen?

use oauth if GEMINI_API_KEY is set

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
# paste output here
```

</details>

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by SandyTao520**
## TLDR

Fixes authentication precedence in non-interactive mode so that configured settings in `settings.json` take priority over environment variables.

## Dive Deeper

Previously, if environment variables like `GEMINI_API_KEY` were set, they would override any authentication configuration in `settings.json` during non-interactive runs. This change ensures that `configuredAuthType` (from settings) is checked first. `enforcedType` remains a constraint.

## Reviewer Test Plan

1. Login to OAuth.
2. Set `GEMINI_API_KEY` to a different/fake value in the environment.
3. Run a non-interactive command `gemini -p hi`
4. Verify it uses the configured OAuth credentials and not the API key from the environment.
5. Unset auth in settings, keep the environment variable, run again, and verify it uses the environment variable.

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | ✅  | ❓  | ❓ |
| npx      | ✅  | ❓  | ❓  |
| Docker   | ❓  | ❓  | ❓  |
| Podman   | ❓  | -   | -   |
| Seatbelt | ❓  | -   | -   |

## Linked issues / bugs
Fixes #10933

### CODE REVIEW

File: packages/cli/src/validateNonInterActiveAuth.ts [hunk 1]
```diff
@@ -31,18 +31,18 @@ export async function validateNonInteractiveAuth(
...
 ) {
   try {
+    const effectiveAuthType = configuredAuthType || getAuthTypeFromEnv();
+
     const enforcedType = settings.merged.security?.auth?.enforcedType;
     if (enforcedType) {
-      const currentAuthType = getAuthTypeFromEnv();
-      if (currentAuthType !== enforcedType) {
-        const message = `The configured auth type is ${enforcedType}, but the current auth type is ${currentAuthType}. Please re-authenticate with the correct type.`;
+      if (effectiveAuthType !== enforcedType) {
```
Comment (scidomino) [inline packages/cli/src/validateNonInterActiveAuth.ts]: nit, combine this with the above "if"

**Review by scidomino — APPROVED** [review]
