### PR TITLE
fix(ui): prevent escape key from cancelling requests in shell mode

### LINKED ISSUE #20615: Bug: Pressing Escape in '!' shell mode cancels ongoing agent request instead of exiting shell mode
### What happened?
When the AI agent is currently thinking or executing tools in the background, entering shell mode by typing an exclamation mark (`!`) works as expected. The UI indicates that pressing `Escape` will leave shell mode. 

However, pressing `Escape` does not actually exit shell mode. Instead, it seems to propagate the interrupt signal up, causing the ongoing background agent request to be cancelled ("Request cancelled"), while the input field remains stuck in shell mode.

### What did you expect to happen?
Pressing `Escape` while in the `!` shell input mode should clear the input field and return the user to the standard chat input mode, without cancelling the agent's ongoing background execution.

### Client information
<details>
<summary>Client Information</summary>

```console
CLI Version: 0.30.0
OS: darwin
```

</details>

### Login information
N/A

### Anything else we need to know?
**Reproduction Steps:**
1. Send a complex request to the Gemini CLI that will take some time to process.
2. While the agent is working, type `!` to enter shell mode.
3. Observe the UI prompt indicating to press Escape to exit.
4. Press `Escape`.
5. Notice that the shell mode is not exited, but the agent's background task is terminated with a "Request cancelled" message.

### PR DESCRIPTION
**Pull request by PrasannaPal21**
## Summary

This fixes an issue where pressing the Escape key while in shell mode (`!`) incorrectly cancelled ongoing background agent requests instead of just exiting shell mode. 

## Details

The bug was caused by the Escape event propagating and triggering `cancelOngoingRequest` in `useGeminiStream`. I've updated both the `useKeypress` hook and [InputPrompt](cci:1://file:///c:/Users/prasa/OneDrive/Desktop/GSOC%2026/gemini%20cli/gemini-cli/packages/cli/src/ui/components/InputPrompt.tsx:183:0-1674:2)'s event handling to explicitly check `shellModeActive`. Now, if a user is in shell mode and hits Escape, it simply exits shell mode and lets the background generation continue uninterrupted.

I also added tests in [useGeminiStream.test.tsx](cci:7://file:///c:/Users/prasa/OneDrive/Desktop/GSOC%2026/gemini%20cli/gemini-cli/packages/cli/src/ui/hooks/useGeminiStream.test.tsx:0:0-0:0) to ensure this behavior is covered and won't regress.

## Related Issues

Fixes #20615

## How to Validate

1. Run `npm run start` and trigger a long-running prompt (e.g. `tell me a long story about a space adventure`).
2. While the agent is responding, immediately type `!` to enter shell mode.
3. Press the [Escape](cci:1://file:///c:/Users/prasa/OneDrive/Desktop/GSOC%2026/gemini%20cli/gemini-cli/packages/cli/src/ui/hooks/useGeminiStream.test.tsx:1346:4-1350:6) key.
4. Verify that shell mode exits (the `! ` disappears), the prompt generation continues smoothly, and no "Request cancelled" error appears.

## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [x] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [x] Validated on required platforms/methods:
  - [ ] MacOS
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [x] Windows
    - [x] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

File: packages/cli/src/ui/components/InputPrompt.tsx [hunk 1]
```diff
@@ -655,11 +655,13 @@ export const InputPrompt: React.FC<InputPromptProps> = ({
...
-        (streamingState === StreamingState.Responding ||
-          streamingState === StreamingState.WaitingForConfirmation)
-      ) {
+      const isGenerating =
+        streamingState === StreamingState.Responding ||
+        streamingState === StreamingState.WaitingForConfirmation;
+
+      // Only skip Escape handling during generation if we are NOT in shell mode
+      // If we are in shell mode, we still need to process Escape to exit shell mode.
+      if (key.name === 'escape' && isGenerating && !shellModeActive) {
```
Comment (mrpmohiburrahman) [inline packages/cli/src/ui/components/InputPrompt.tsx]: Here, this successfully protects shell mode, but it inadvertently ignores other
interactive overlays in the exact same view.

If a user is waiting for a background generation and decides to open history search (`Ctrl+R` / `reverseSearchActive`) or the slash-command autocomplete dropdown (`shouldShowSuggestions`), pressing `Escape` to close them still evaluates to `!shellModeActive === true`.

The UI returns `false` early, traps the user in the dropdown/search, and allows the event to propagate up to `packages/cli/src/ui/hooks/useGeminiStream.ts`, triggering `cancelOngoingRequest()`.


### Possible Solution

To make this fix completely robust against all "Escape to dismiss" UI states, we
can calculate if _any_ interactive overlay is active before returning `false`,
and revert the logic in `useGeminiStream.ts` to fully trust the UI propagation
layer.

**1. In  line 658:**

```typescript
const isGenerating =
  streamingState === StreamingState.Responding ||
  streamingState === StreamingState.WaitingForConfirmation;

// Define ALL states where the user is trapped in an overlay they might want to escape
const isOverlayActive =
  shellModeActive ||
  reverseSearchActive ||
  commandSearchActive ||
  (completion.showSuggestions && isShellSuggestionsVisible);

// Only allow Escape to fall through during generation if the user is trying to close an overlay
if (key.name === 'escape' && isGenerating && !isOverlayActive) {
  return false;
}
```

**2. In `packages/cli/src/ui/hooks/useGeminiStream.ts` (revert lines 706-714 to
original):**

```typescript
useKeypress(
  (key) => {
    // Revert to trusting the propagation layer
    if (key.name === 'escape' && !isShellFocused) {
      cancelOngoingRequest();
    }
  },
  {
    /* ... */
  },
);
```

This ensures `useGeminiStream` doesn't need to know about every new UI overlay added to the app in the future.

Comment (PrasannaPal21) [reply packages/cli/src/ui/components/InputPrompt.tsx]: understood, and fixed..
thank you

File: packages/cli/src/ui/components/InputPrompt.tsx [hunk 2]
```diff
@@ -683,11 +683,20 @@ export const InputPrompt: React.FC<InputPromptProps> = ({
...
-          streamingState === StreamingState.WaitingForConfirmation)
-      ) {
+      const isGenerating =
+        streamingState === StreamingState.Responding ||
+        streamingState === StreamingState.WaitingForConfirmation;
+
+      // Check if any interactive overlay is active that the user might want
+      // to dismiss with Escape. If so, let the keypress be handled locally
+      // instead of falling through to the global cancellation handler.
+      const isOverlayActive =
```
Comment (scidomino) [inline packages/cli/src/ui/components/InputPrompt.tsx]: KeypressHandler has a system to stop events from being propagated to other handlers. Have you investigated that? if we have separate listeners handling the other ones, we could jsut have them return true to indicate that no other handler should receive them.

Comment (PrasannaPal21) [reply packages/cli/src/ui/components/InputPrompt.tsx]: I checked KeypressHandler propagation (returning true stops it).
Refactored InputPrompt so ESC is handled locally first (overlays return true), and only falls through to global cancel if nothing consumes it.
Removed the isOverlayActive check and now rely on the built-in propagation.

**Review by scidomino — APPROVED** [review]
