### PR TITLE
fix(plan): persist the approval mode in UI even when agent is thinking

### LINKED ISSUE #18758: [UI] Persist the approval mode in UI even when agent is thinking
Today, thoughts overwrite the current approval mode in the UI. We should place the thoughts above the approval mode line so that we current approval mode is always visible.

Image

### PR DESCRIPTION
**Pull request by Adib234**
## Summary

This PR ensures that a critical UI element the  Approval Mode indicator remains visible while the model is responding (streaming). Previously, Approval Mode Indicator was hidden.
## Related Issues

Fixes https://github.com/google-gemini/gemini-cli/issues/18758

## How to Validate

https://github.com/user-attachments/assets/116770bf-e798-4515-ae10-9ec21783e735

## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [ ] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [ ] Validated on required platforms/methods:
  - [ ] MacOS
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

File: packages/cli/src/ui/components/Composer.tsx [hunk 1]
```diff
@@ -189,7 +188,7 @@ export const Composer = ({ isFocused = true }: { isFocused?: boolean }) => {
             marginLeft={1}
             marginRight={isNarrow ? 0 : 1}
             flexDirection="row"
-            alignItems="center"
+            alignItems={isNarrow ? 'flex-start' : 'center'}
```
Comment (jacob314) [inline packages/cli/src/ui/components/Composer.tsx:191]: why did this change to flex-start from center?

**Review by jacob314 — APPROVED** [review]
LGTM! The changes correctly fulfill the requirement to persist the `ApprovalModeIndicator` during streaming while maintaining the expected layout behavior. By restoring the nested `<Box flexGrow={1}>` for the `LoadingIndicator`, you've neatly resolved the previously observed layout shift with the `ShortcutsHint`. Permitting the `ShortcutsHint` to remain visible while the agent loads provides a more stable layout and prevents visual flickering, which is a nice improvement. The new test coverage and snapshot updates look solid.

File: packages/cli/src/ui/components/Composer.tsx (hunk 1 above)
Comment (Adib234) [reply packages/cli/src/ui/components/Composer.tsx:191]: I thought this would help with if the screen size was narrow
