### PR TITLE
fix(auth): update terminology to 'sign in' and 'sign out'

### LINKED ISSUE #20891: feat: update customer-facing strings from 'login'/'logout' to 'sign in'/'sign out'
## What would you like to be added?

Update all customer-facing strings, including CLI command names, UI labels, and documentation, to use 'sign in' and 'sign out' instead of 'login' and 'logout' for Google accounts. This includes renaming the /login command to /signin and /logout to /signout.

## Why is this needed?

Google-branded account authentication should use 'sign in' and 'sign out' terminology to align with Google's design and branding standards. This improves clarity for users and ensures consistency with other Google services.

## Additional context

This change involves updates to:
- Slash commands: /login -> /signin, /logout -> /signout
- UI labels: 'Login with Google' -> 'Sign in with Google', 'Logged in' -> 'Signed in'
- Documentation: README.md and all docs in docs/
- All related tests.

### PR DESCRIPTION
**Pull request by clocky**
## Summary

This PR updates the terminology from "login" and "logout" to "sign in" and "sign out" across the Gemini CLI, its documentation, and its user interface. This change ensures consistency with modern Google authentication standards and improves clarity for users.

## Details

- **Renamed slash commands:** `/login` is now `/signin` and `/logout` is now `/signout`.
- **Backward Compatibility:** Added `altNames` support so that `/login` and `/logout` continue to work while pointing to the new commands.
- **UI String Updates:** Updated all UI labels from "Login with Google" to "Sign in with Google" and from "Logged in" to "Signed in".
- **Improved UI Messaging:** Refined several UI messages for clarity (e.g., "Waiting for auth..." is now "Waiting for authentication...", and "CTRL+C" is now "Ctrl+C").
- **Documentation:** Updated the `README.md` and extensive documentation in the `docs/` directory to reflect the new terminology.
- **Testing:** Updated unit and integration tests to align with the new command names and strings, including verification of `altNames`.

## Related Issues

Fixes #20891

## How to Validate

1. Run the Gemini CLI and verify that the new `/signin` and `/signout` commands are available.
2. **Verify altNames:** Confirm that `/login` and `/logout` still function as aliases for the new commands.
3. Initiate the authentication flow to confirm the updated "Sign in with Google" label.
4. Review the `README.md` and documentation for consistency.

## Pre-Merge Checklist

- [x] Updated relevant documentation and README (if needed)
- [x] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [x] Validated on MacOS (npm run, npx)

### CODE REVIEW

File: packages/cli/src/ui/commands/authCommand.ts [hunk 1]
```diff
@@ -14,8 +14,8 @@ import { clearCachedCredentialFile } from '@google/gemini-cli-core';
 import { SettingScope } from '../../config/settings.js';
 
 const authLoginCommand: SlashCommand = {
```
Comment (scidomino) [inline packages/cli/src/ui/commands/authCommand.ts:16]: SlashCommand supports a field "altNames" which gives alternative names for commands. Please put the old names as altNames here so users who memorized the old command don't have to change if they don't want to.

File: packages/cli/src/ui/commands/authCommand.ts [hunk 2]
```diff
@@ -25,8 +25,8 @@ const authLoginCommand: SlashCommand = {
 };
 
 const authLogoutCommand: SlashCommand = {
-  name: 'logout',
-  description: 'Log out and clear all cached credentials',
+  name: 'signout',
```
Comment (scidomino) [inline packages/cli/src/ui/commands/authCommand.ts:29]: ditto

File: packages/cli/src/ui/commands/authCommand.ts (hunk 1 above)
Comment (clocky) [reply packages/cli/src/ui/commands/authCommand.ts:16]: Awesome; that was the one breaking change, and I love that we can handle it gracefully. Will fix.

**Review by scidomino — APPROVED** [review]
