### PR TITLE
fix(core): Sanitize tool parameters to fix 400 API errors

### LINKED ISSUE #2141: Persistent 400 API error
### What happened?

Since yesterday I am unable to use gemini-cli with similar 400 API errors. In essence `only 'enum' and 'date-time' are supported for STRING type`

```
[API Error: {"error":{"message":"{\n  \"error\": {\n    \"code\": 400,\n    \"message\": \"* 
  GenerateContentRequest.tools[0].function_declarations[15].parameters.properties[file_paths].items: missing 
  field.\\n* GenerateContentRequest.tools[0].function_declarations[63].parameters.properties[url].format: 
  only 'enum' and 'date-time' are supported for STRING type\\n\",\n    \"status\": \"INVALID_ARGUMENT\"\n  
  }\n}\n","code":400,"status":"Bad Request"}}]
```

[gemini-client-error-Turn.run-sendMessageStream-2025-06-27T07-22-37-705Z.json](https://github.com/user-attachments/files/20941928/gemini-client-error-Turn.run-sendMessageStream-2025-06-27T07-22-37-705Z.json)

### What did you expect to happen?

That after asking question I will get assistant action or answer not API error 400.

### Client information

<details>

```console
$ gemini /about
# paste output here
```

</details>

### Login information

_No response_

### Anything else we need to know?

_No response_

### LINKED ISSUE #2237: GenerateContentRequest.tools[0].function_declarations[22].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type
### What happened?

✕ [API Error: got status: 400 Bad Request. {"error":{"message":"{\n  \"error\": {\n    \"code\": 400,\n    \"message\": \"* 
  GenerateContentRequest.tools[0].function_declarations[22].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n\",\n    \"status\": \"INVALID_ARGUMENT\"\n  
  }\n}\n","code":400,"status":"Bad Request"}}]

### What did you expect to happen?

No error

### Client information

*   **CLI Version:** 0.1.5
*   **Git Commit:** N/A
*   **Operating System:** darwin v20.19.2
*   **Sandbox Environment:** no sandbox
*   **Model Version:** gemini-2.5-pro
*   **Memory Usage:** 92.8 MB

### Login information

Both

### Anything else we need to know?

_No response_

### LINKED ISSUE #2522: CLI crashing when running commands after setting up mcp servers
### What happened?

I ran few mcp servers and then cli started to crash, logs were following 

```
{
  "error": {
    "message": "{\"error\":{\"message\":\"{\\n  \\\"error\\\": {\\n    \\\"code\\\": 400,\\n    \\\"message\\\": \\\"* GenerateContentRequest.tools[0].function_declarations[28].parameters.properties[abi].items: missing field.\\\\n* GenerateContentRequest.tools[0].function_declarations[28].parameters.properties[args].items: missing field.\\\\n* GenerateContentRequest.tools[0].function_declarations[29].parameters.properties[args].items: missing field.\\\\n* GenerateContentRequest.tools[0].function_declarations[29].parameters.properties[abi].items: missing field.\\\\n\\\",\\n    \\\"status\\\": \\\"INVALID_ARGUMENT\\\"\\n  }\\n}\\n\",\"code\":400,\"status\":\"Bad Request\"}}",
    "stack": "ApiError: {\"error\":{\"message\":\"{\\n  \\\"error\\\": {\\n    \\\"code\\\": 400,\\n    \\\"message\\\": \\\"* GenerateContentRequest.tools[0].function_declarations[28].parameters.properties[abi].items: missing field.\\\\n* GenerateContentRequest.tools[0].function_declarations[28].parameters.properties[args].items: missing field.\\\\n* GenerateContentRequest.tools[0].function_declarations[29].parameters.properties[args].items: missing field.\\\\n* GenerateContentRequest.tools[0].function_declarations[29].parameters.properties[abi].items: missing field.\\\\n\\\",\\n    \\\"status\\\": \\\"INVALID_ARGUMENT\\\"\\n  }\\n}\\n\",\"code\":400,\"status\":\"Bad Request\"}}\n    at throwErrorIfNotOK (file:///C:/Users/91831/AppData/Roaming/npm/node_modules/@google/gemini-cli/node_modules/@google/genai/dist/node/index.mjs:13101:30)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async file:///C:/Users/91831/AppData/Roaming/npm/node_modules/@google/gemini-cli/node_modules/@google/genai/dist/node/index.mjs:12892:13\n    at async Models.generateContentStream (file:///C:/Users/91831/AppData/Roaming/npm/node_modules/@google/gemini-cli/node_modules/@google/genai/dist/node/index.mjs:14217:24)\n    at async retryWithBackoff (file:///C:/Users/91831/AppData/Roaming/npm/node_modules/@google/gemini-cli/node_modules/@google/gemini-cli-core/dist/src/utils/retry.js:61:20)\n    at async GeminiChat.sendMessageStream (file:///C:/Users/91831/AppData/Roaming/npm/node_modules/@google/gemini-cli/node_modules/@google/gemini-cli-core/dist/src/core/geminiChat.js:287:36)\n    at async Turn.run (file:///C:/Users/91831/AppData/Roaming/npm/node_modules/@google/gemini-cli/node_modules/@google/gemini-cli-core/dist/src/core/turn.js:37:36)\n    at async GeminiClient.sendMessageStream (file:///C:/Users/91831/AppData/Roaming/npm/node_modules/@google/gemini-cli/node_modules/@google/gemini-cli-core/dist/src/core/client.js:175:26)\n    at async file:///C:/Users/91831/AppData/Roaming/npm/node_modules/@google/gemini-cli/dist/src/ui/hooks/useGeminiStream.js:276:26\n    at async file:///C:/Users/91831/AppData/Roaming/npm/node_modules/@google/gemini-cli/dist/src/ui/hooks/useGeminiStream.js:343:38"
  },
  "context": [
    {
      "role": "user",
      "parts": [
        {
          "text": "This is the Gemini CLI. We are setting up the context for our chat.\n  Today's date is Sunday 29 June, 2025.\n  My operating system is: win32\n  I'm currently working in the directory: C:\\Users\\91831\n  Showing up to 200 items (files + folders). Folders or files indicated with ... contain more items not shown, were ignored, or the display limit (200 items) was reached. ..........."
        }
      ]
    },
    {
      "role": "model",
      "parts": [
        {
          "text": "Got it. Thanks for the context!"
        }
      ]
    },
    "Tell me how much eth does vitalik.eth own?"
  ]
}
```
it threw this error when my mcp server was configured as 
```
"evm-mcp-server": {
      "display_name": "EVM MCP Server",
      "command": "powershell.exe",
      "args": [
        "-Command",
        "cd 'C:\\Users\\91831\\Desktop\\important\\blockchain\\mcp\\modelcontextprotocol\\evm-mcp-server'; & 'C:\\Users\\91831\\.bun\\bin\\bun.exe' run start"
      ]
    }
```

### What did you expect to happen?

cli to work properly.

### Client information

*   **CLI Version:** 0.1.7
*   **Git Commit:** 55cc809
*   **Operating System:** win32 v20.18.1
*   **Sandbox Environment:** no sandbox
*   **Model Version:** gemini-2.5-pro
*   **Memory Usage:** 144.1 MB

### Login information

With API Key

### Anything else we need to know?

when I removed the server it works

### LINKED ISSUE #2706: short, simple questions causing invalid argument / bad request errors
### What happened?

This is in- and out-put:

> /about

╭───────────────────────────────────────────────────────────────────────╮
│                                                                       │
│ About Gemini CLI                                                      │
│                                                                       │
│ CLI Version             0.1.7                                         │
│ Git Commit              55cc809                                       │
│ Model                   gemini-2.5-pro                                │
│ Sandbox                 no sandbox                                    │
│ OS                      darwin                                        │
│ Auth Method             gemini-api-key                                │
│                                                                       │
╰───────────────────────────────────────────────────────────────────────╯

> research EV battery degradation when long term parking

✕ [API Error: {"error":{"message":"{\n  \"error\": {\n    \"code\": 400,\n    \"message\": \"* 
  GenerateContentRequest.tools[0].function_declarations[12].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[13].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[15].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[16].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[17].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[18].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[19].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[20].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[21].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[22].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[23].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[24].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[25].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[26].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[27].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[28].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[29].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[30].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[31].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[32].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[33].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[34].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[35].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[36].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[37].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[38].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[39].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[40].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[41].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[42].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[43].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[44].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[45].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[46].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[47].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[48].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[49].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[50].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[51].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[52].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[53].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[54].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[55].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[56].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n* 
  GenerateContentRequest.tools[0].function_declarations[57].parameters.properties[url].format: only 'enum' and 'date-time' are supported for STRING type\\n\",\n    
  \"status\": \"INVALID_ARGUMENT\"\n  }\n}\n","code":400,"status":"Bad Request"}}]

### What did you expect to happen?

Receiving an answer of what ever quality but not an invalid argument error. I don't understand what is bod about this request.

### Client information

*   **CLI Version:** 0.1.7
*   **Git Commit:** 55cc809
*   **Operating System:** darwin v22.17.0; OSX 15.5, M4 chip
*   **Sandbox Environment:** no sandbox
*   **Model Version:** gemini-2.5-pro
*   **Memory Usage:** 126.0 MB

### Login information

_No response_

### Anything else we need to know?

_No response_

### LINKED ISSUE #3178: API Error
### What happened?

I'm getting this error when running any prompt locally:
```
✕ [API Error: {"error":{"message":"{\n  \"error\": {\n    \"code\": 400,\n    \"message\": \"*
  GenerateContentRequest.tools[0].function_declarations[93].parameters.properties[links].items.properties[url].format: only 'enum' and 'date-time' are
  supported for STRING type\\n* GenerateContentRequest.tools[0].function_declarations[94].parameters.properties[links].items.properties[url].format:
  only 'enum' and 'date-time' are supported for STRING type\\n\",\n    \"status\": \"INVALID_ARGUMENT\"\n  }\n}\n","code":400,"status":"Bad Request"}}]
```

### What did you expect to happen?

I expected gemini to be called and return some answers.

### Client information

<details>

About Gemini CLI                                                     │
│                                                                      │
│ CLI Version             0.1.7                                        │
│ Git Commit              55cc809                                      │
│ Model                   gemini-2.5-pro                               │
│ Sandbox                 no sandbox                                   │
│ OS                      darwin                                       │
│ Auth Method             gemini-api-key                               │
│ GCP Project             dovetail-internal

</details>

### Login information

API Key

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by BigUncle**
> **Note**
> This PR depends on the test stabilization fix in **#3296**. Please review and merge that PR first. This PR includes the same test fix temporarily to pass CI checks, and it will be removed by rebasing onto `main` once #3296 is merged.

## TLDR

This pull request provides a robust fix for a persistent 400 API error caused by improper tool parameter schemas being sent to the Gemini API. It directly resolves issue #2141 and several duplicates by sanitizing tool function declarations before they are sent, ensuring compatibility with the API's requirements.

**Key Fixes:**

- **Sanitizes `format` property:** For `STRING` type parameters, it removes any `format` value that is not `enum` or `date-time`, which was the primary cause of the 400 errors.
- **Improves Tool Registry Robustness:** Adds `Array.isArray` checks to ensure `function_declarations` are correctly structured, which likely prevents the `missing field` errors also reported.

**This PR closes:** #2141, #2706, #3178, #2237
**This PR likely also resolves:** #2522

## Dive Deeper

The root cause of the `Persistent 400 API error` was that the tool discovery mechanism would generate function declarations with `format` properties (e.g., `uri`, `email`) that are not supported by the Gemini API for `STRING` parameters. The API strictly requires that the `format` for a string be either `enum` or `date-time`.

This PR introduces a `sanitizeParameters` function that recursively traverses the tool schema. It inspects every `STRING` parameter and sets its `format` to `undefined` if it's not one of the allowed values. This sanitization happens right before the tool is registered, ensuring that any request sent to the Gemini API contains a valid tool definition.

Additionally, issue #2141 and the related #2522 also reported errors like `...items: missing field.`. This often happens when an expected array structure is malformed. The secondary fix in this PR, which validates that `function_declarations` and `functionDeclarations` are indeed arrays before processing them, adds a layer of type safety that should prevent these malformed definitions from causing API errors.

## Reviewer Test Plan

1.  Pull down this branch.
2.  Run `npm run preflight`. All tests should pass consistently.
3.  To manually verify, one could set up a local tool discovery command that produces a tool with an unsupported string format (e.g., `"format": "uri"`).
    - **Before this PR:** Running a prompt that uses this tool would result in a 400 API error.
    - **After this PR:** The command should execute successfully without any API errors, as the unsupported format is sanitized before the request is made.

## Testing Matrix

|          | Local (WSL2) | CI  | Notes                                                            |
| -------- | :----------: | :-: | :--------------------------------------------------------------- |
| npm run  |      ✅      | ✅  | All checks pass. The rebase onto `upstream/main` was successful. |
| npx      |     N/A      | N/A | Not applicable for this change.                                  |
| Docker   |     N/A      | N/A | Not applicable for this change.                                  |
| Podman   |      -       |  -  | Not applicable for this change.                                  |
| Seatbelt |      -       |  -  | Not applicable for this change.                                  |

## Linked issues / bugs

- **Depends on #3296**
- Fixes #2141
- Fixes #2706
- Fixes #3178
- Fixes #2237
- Likely resolves #2522

### CODE REVIEW

File: packages/core/src/tools/tool-registry.ts [hunk 1]
```diff
@@ -160,27 +160,49 @@ export class ToolRegistry {
...
+          // Sanitize the parameters before registering the tool.
+          sanitizeParameters(func.parameters);
+          this.registerTool(
+            new DiscoveredTool(
+              this.config,
+              func.name,
+              func.description ?? '',
+              (func.parameters ?? {}) as Record<string, unknown>,
+            ),
+          );
```
[the remark this answers is not in the document]
Comment (BigUncle) [reply packages/core/src/tools/tool-registry.ts]: /gemini review

File: package.json [hunk 2]
```diff
@@ -87,5 +88,7 @@
     "typescript-eslint": "^8.30.1",
     "yargs": "^17.7.2"
   },
-  "dependencies": {}
+  "dependencies": {
+    "shell-quote": "^1.8.3"
```
Comment (NTaylorMullen) [inline package.json]: This will need to be added to the core package I believe instead of here.

File: packages/cli/src/ui/hooks/useLoadingIndicator.test.ts [hunk 3]
```diff
@@ -41,14 +41,12 @@ describe('useLoadingIndicator', () => {
     expect(WITTY_LOADING_PHRASES).toContain(
       result.current.currentLoadingPhrase,
     );
-    const initialPhrase = result.current.currentLoadingPhrase;
```
Comment (NTaylorMullen) [inline packages/cli/src/ui/hooks/useLoadingIndicator.test.ts:44]: Intentional removals?

File: packages/core/src/tools/tool-registry.ts [hunk 4]
```diff
@@ -160,27 +162,121 @@ export class ToolRegistry {
...
-          new DiscoveredTool(
-            this.config,
-            func.name!,
-            func.description!,
-            func.parameters! as Record<string, unknown>,
-          ),
+        if (cmdParts.some((part) => typeof part !== 'string')) {
+          throw new Error(
+            `Tool discovery command contains shell operators which are not supported. Please wrap complex commands in 'sh -c "..."'.`,
+          );
```
[the remark this answers is not in the document]
Comment (NTaylorMullen) [reply packages/core/src/tools/tool-registry.ts]: This is done via the `parse` above.

File: packages/core/src/tools/tool-registry.ts [hunk 5]
```diff
@@ -160,27 +162,121 @@ export class ToolRegistry {
...
-      // execute discovery command and extract function declarations (w/ or w/o "tool" wrappers)
-      const functions: FunctionDeclaration[] = [];
-      for (const tool of JSON.parse(execSync(discoveryCmd).toString().trim())) {
-        if (tool['function_declarations']) {
-          functions.push(...tool['function_declarations']);
-        } else if (tool['functionDeclarations']) {
-          functions.push(...tool['functionDeclarations']);
-        } else if (tool['name']) {
-          functions.push(tool);
+      try {
```
Comment (NTaylorMullen) [inline packages/core/src/tools/tool-registry.ts]: Could you extract this block into a specific function to resolve tools for readability?

**Review by NTaylorMullen — COMMENTED** [review]
@BigUncle we're super close! Thank you for the updates. Left a few more comments

**Comment by BigUncle** [comment]
> @BigUncle we're super close! Thank you for the updates. Left a few more comments

Hi @NTaylorMullen,

Thank you so much for your detailed feedback! I've addressed all your points in the latest commit:

*   **`shell-quote` dependency**: You were right, I've moved the `shell-quote` dependency to `packages/core/package.json`. Thanks for catching that!
*   **`useLoadingIndicator.test.ts`**: The code removal was indeed unintentional. I've restored it in the latest version.
*   **Redundant check in `tool-registry.ts`**: I've removed the extra check as you suggested, since `parse` already handles it.
*   **Readability of `tool-registry.ts`**: I've extracted the tool resolution logic into a new `discoverAndRegisterToolsFromCommand` function to improve readability.

I really appreciate you taking the time to review my code. Your suggestions have made it much better!

File: package.json (hunk 2 above)
Comment (BigUncle) [reply package.json]: I've moved the `shell-quote` dependency to `packages/core/package.json`. Thank you!

File: packages/cli/src/ui/hooks/useLoadingIndicator.test.ts (hunk 3 above)
Comment (BigUncle) [reply packages/cli/src/ui/hooks/useLoadingIndicator.test.ts:44]: I made a mistake in the operation. I have restored it.

File: packages/core/src/tools/tool-registry.ts (hunk 5 above)
Comment (BigUncle) [reply packages/core/src/tools/tool-registry.ts]: I have extracted it into a new function called `discoverAndRegisterToolsFromCommand`, thank you!

**Review by NTaylorMullen — APPROVED** [review]

**Comment by NTaylorMullen** [comment]
@BigUncle it looks like you may need to rebase your branch on latest main. It wont let me do it on your behalf because it looks like there are some merge conflicts. Almost there!

**Review by NTaylorMullen — APPROVED** [review]

**Comment by NTaylorMullen** [comment]
Thank you for all the back and forth and the contribution @BigUncle !

**Comment by BigUncle** [comment]
> Thank you for all the back and forth and the contribution @BigUncle !

Thank you so much, @NTaylorMullen!

I really appreciate you taking the time for such a detailed review and for all the guidance. A special thanks for helping get this over the finish line by resolving the final merge conflict.

As this is my first PR to be merged in a major open-source project, I'm absolutely thrilled. I learned a ton from the process.

Looking forward to contributing more in the future!
