### PR TITLE
Fix /chat list  not write terminal escape codes directly 

### LINKED ISSUE #10408: ANSI Color Codes Escaped as Unicode in `/chat list` Output  in `/chat list` in Gemini CLI Version: 0.8.0-preview.1
### What happened?

 When running `gemini /chat list` in Terminator on Ubuntu 22.04.5, ANSI color codes are displayed as Unicode escape sequences (`\u001b[36m`) instead of rendering as colored text. This behavior does not occur in other CLI tools like `fastfetch` or in simple ANSI tests (`echo -e`). Attempts to force `--output-format=text` result in the Gemini AI misinterpreting the command and responding as if in a chat session rather than displaying chat list.

This appears to be a bug in how the CLI handles ANSI output for `/chat list`, especially in interactive terminal sessions.

### Steps to Reproduce

1. Open Terminator (or another terminal supporting ANSI colors).
2. Run:

```bash
$ gemini /chat list
```

3. Observe that color sequences are printed literally:

```text
\u001b[36mOS1     \u001b[0m  \u001b[90m(saved on 2025-06-28 13:01:55)\u001b[0m
\u001b[36mmongrel1\u001b[0m  \u001b[90m(saved on 2025-10-02 11:27:40)\u001b[0m
\u001b[36mmongrel2\u001b[0m  \u001b[90m(saved on 2025-10-02 12:32:27)\u001b[0m
```

 
Results in Gemini AI misinterpreting the command and responding with chat-like output rather than the list.

### Expected Behavior

* ANSI color codes should render properly in the terminal.
* `--output-format=text` should suppress JSON/escaped output but still list chats with colors.

### Observed Behavior

* ANSI codes are escaped as `\u001b` sequences.
* `--output-format=text` triggers AI interpretation rather than listing saved sessions.

### Environment

```text
---------------------
OS: Ubuntu 22.04.5 LTS x86_64
Terminal: Terminator
Shell: bash 5.1.16
Font: Sarai (28pt)
DE: GNOME 42.9
WM: Mutter (X11)
Locale: en_US.UTF-8
CPU: Intel(R) Core(TM) i5-8265U @ 3.90 GHz
Memory: 7.64 GiB
Disk: ext4 and external drives
Gemini CLI Version: 0.8.0-preview.1
Model: gemini-2.5-pro
```

### Additional Notes

* `echo -e "\e[36mHello\e[0m"` displays colors correctly.
* `fastfetch` output is colored correctly.
* The problem appears specific to `/chat list` in Gemini CLI.

### Suggested Action

* Investigate why `/chat list` outputs escaped ANSI sequences in interactive terminal sessions.
* Ensure `--output-format=text` properly outputs raw ANSI colors without triggering AI responses.

### What did you expect to happen?

Colored, non-escaped chars, or no color

### Client information

gemini --version
0.8.0-preview.1

### Login information

_No response_

### Anything else we need to know?

First time it has happened, since version 1.*

### PR DESCRIPTION
**Pull request by adamfweidman**
## TLDR

https://github.com/google-gemini/gemini-cli/pull/8636 causes ansi ctrl codes to get esaped and rendered. This PR uses Ink similar to https://github.com/google-gemini/gemini-cli/pull/10010

## Dive Deeper

Previously
Screenshot 2025-10-02 at 10 41 16 AM

With fix:
Screenshot 2025-10-02 at 3 30 45 PM

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | ❓  | ❓  | ❓  |
| npx      | ❓  | ❓  | ❓  |
| Docker   | ❓  | ❓  | ❓  |
| Podman   | ❓  | -   | -   |
| Seatbelt | ❓  | -   | -   |

## Linked issues / bugs

Fixes: https://github.com/google-gemini/gemini-cli/issues/10408

### CODE REVIEW

File: packages/cli/src/ui/components/views/ChatList.tsx [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+        const formattedDate = match
+          ? `${match[1]} ${match[2]}`
+          : 'Invalid Date';
+        return (
+          <Box key={chat.name} flexDirection="row">
+            <Text>
+              {'  '}- <Text color={theme.text.accent}>{paddedName}</Text>
+              {'  '}
+              <Text color={theme.text.secondary}>
+                (saved on {formattedDate})
```
Comment (miguelsolorio) [inline packages/cli/src/ui/components/views/ChatList.tsx]: Nit: I'd remove the `saved on` text given that the title explains these are saved chats (it's redundant)

File: packages/cli/src/ui/components/views/ChatList.tsx [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+        const paddedName = chat.name.padEnd(maxNameLength, ' ');
+        const isoString = chat.mtime;
+        const match = isoString.match(
+          /(\d{4}-\d{2}-\d{2})T(\d{2}:\d{2}:\d{2})/,
+        );
+        const formattedDate = match
+          ? `${match[1]} ${match[2]}`
+          : 'Invalid Date';
+        return (
+          <Box key={chat.name} flexDirection="row">
```
Comment (miguelsolorio) [inline packages/cli/src/ui/components/views/ChatList.tsx:34]: I don't think adding a second column for this text is necessary, we only do this for commands at the moment and I think it reads a little easier without it

File: packages/cli/src/ui/components/views/ChatList.tsx (hunk 1 above)
Comment (adamfweidman) [reply packages/cli/src/ui/components/views/ChatList.tsx]: Done

File: packages/cli/src/ui/components/views/ChatList.tsx (hunk 2 above)
Comment (adamfweidman) [reply packages/cli/src/ui/components/views/ChatList.tsx:34]: Done

**Review by jacob314 — APPROVED** [review]
lgtm
