### PR TITLE
fix: similar to policy-engine, throw error in case of requiring tool execution confirmation for non-interactive mode

### LINKED ISSUE #11459: Gemini CLI hangs with `query` command when using stdio-based MCP servers
### What happened?

Gemini CLI hangs indefinitely when using the `query` command with stdio-based MCP (Model Context Protocol) servers. The server initializes correctly and responds to `tools/list`, but Gemini CLI never sends the subsequent `tools/call` request, causing the process to hang.

### What did you expect to happen?

The MCP server should:
1. Receive `initialize` request
2. Receive `notifications/initialized` notification  
3. Receive `tools/list` request
4. Receive `tools/call` request with the tool name and arguments
5. Process the tool call and return the result

### Client information

<details>

```
───────────────────────────────────────────────────────────────────────────╮
│                                                                           │
│ About Gemini CLI                                                          │
│                                                                           │
│ CLI Version               0.9.0                                           │
│ Git Commit                a93d92a3                                        │
│ Model                     gemini-2.5-pro                                  │
│ Sandbox                   no sandbox                                      │
│ OS                        linux                                           │
│ Auth Method               OAuth                                           │
│ GCP Project               gemini-code-####                              │
│                                                                           │
╰───────────────────────────────────────────────────────────────────────────╯
```

</details>

### Login information

_No response_

### Environment
- **Gemini CLI version**: 0.9.0 (latest)
- **OS**: Linux (WSL2)
- **Node.js**: v22.20.0

### Steps to Reproduce
1. Install the reference sequential-thinking MCP server:
   ```bash
   gemini mcp add sequential-thinking npx -y @modelcontextprotocol/server-sequential-thinking
   ```

2. Run with the `query` command:
   ```bash
   gemini query "add 1 thought to our sequential-thinking mcp"
   ```

3. Observe that the command hangs indefinitely after the MCP server initializes

### Debug Logs
```
[DEBUG] CLI: Delegating hierarchical memory load to server for CWD: /home/local/projects/geminicli-usage (memoryImportFormat: tree)
[DEBUG] [MemoryDiscovery] Loading server hierarchical memory load to server for CWD: /home/local/projects/geminicli-usage (importFormat: tree)
[DEBUG] [MemoryDiscovery] Searching for GEMINI.md starting from CWD: /home/local/projects/geminicli-usage
[DEBUG] [MemoryDiscovery] Determined project root: /home/local/projects/geminicli-usage
[DEBUG] [BfsFileSearch] Scanning [1/200]: batch of 1
[DEBUG] [BfsFileSearch] Scanning [8/200]: batch of 7
[DEBUG] [BfsFileSearch] Scanning [16/200]: batch of 8
[DEBUG] [BfsFileSearch] Scanning [31/200]: batch of 15
[DEBUG] [BfsFileSearch] Scanning [46/200]: batch of 15
[DEBUG] [BfsFileSearch] Scanning [61/200]: batch of 15
[DEBUG] [BfsFileSearch] Scanning [76/200]: batch of 15
[DEBUG] [BfsFileSearch] Scanning [91/200]: batch of 15
[DEBUG] [BfsFileSearch] Scanning [104/200]: batch of 13
[DEBUG] [BfsFileSearch] Scanning [106/200]: batch of 2
[DEBUG] [MemoryDiscovery] Final ordered GEMINI.md paths to read: []
[DEBUG] [MemoryDiscovery] No GEMINI.md files found in hierarchy of the workspace.
Loaded cached credentials.
Flushing log events to Clearcut.
[AgentRegistry] Initialized with 1 agents.
[DEBUG] [MCP STDERR (sequential-thinking)]:  Sequential Thinking MCP Server running on stdio
Flushing log events to Clearcut.
Session ID: e6d5f67e-b5a7-4c12-bc6f-f1accc709771
```

### Workarounds
1. **Interactive mode works correctly**:
   ```bash
   gemini
   > add 1 thought to our sequential-thinking mcp
   ```

2. **HTTP-based MCP servers work with `query` command**:
   Servers using `mcp-remote` as a proxy/bridge (which converts stdio to HTTP transport) work correctly with the `query` command.

### Root Cause Analysis
The issue is specific to stdio-based MCP servers. The problem appears to be in how Gemini CLI handles stdio communication with MCP servers when using the `query` command, as HTTP-based servers (accessed via `mcp-remote`) work correctly.

### PR DESCRIPTION
**Pull request by MayV**
## Summary

Replicate throwing error (inspired by DENY case of policy-engine) in case of non-interactive mode and requiring user confirmation for tool execution. This avoids non-interactive gemini-cli indefinitely waiting for mcp-server tool execution confirmation. This error is caught and an error response is shown to the user.

## Details

The issue #11459 is only observed in case the [Policy Engine](https://github.com/google-gemini/gemini-cli/blob/main/docs/core/policy-engine.md) is not enabled. Code flow:

When a tool call is scheduled and processed (inside `_processNextInQueue()` method of `packages/core/src/core/coreToolScheduler.ts`), it calls `shouldConfirmExecute()` method of `packages/core/src/tools/tools.ts` to determine if user approval is needed. For determining this, the flow splits here depending on whether the policy-engine is enabled or not. In case the policy-engine is not enabled, the legacy confirmation flow is used.
- In case policy-engine is enabled via messageBus, it automatically convert ASK_USER decisions to DENY (check shouldConfirmExecute() method of packages/core/src/tools/tools.ts).
- Else, as per the legacy flow of mcp-tools,  in case the server is not trusted, user confirmation message is required (check getConfirmationDetails() method of packages/core/src/tools/mcp-tool.ts).

Finally, if the user confirmation message is required, it is checked if the tool part of `--allowedTools` list. If not, user confirmation message is triggered (check `_processNextInQueue()` method of `packages/core/src/core/coreToolScheduler.ts`).

The user confirmation is required for executing mcp-tools (in case the server is not trusted or the tool is not explicitly allowed). This causes the indefinite waiting of non-interactive gemini-cli on executing mcp-tools.

To solve this, the exact same logic defined in policy-engine of throwing error in case of tool deny is used. This error is caught and an error response is shown to the user (check _processNextInQueue() method of `packages/core/src/core/coreToolScheduler.ts`)

## Related Issues

Fixes #11459 

## How to Validate

Follow steps to reproduce #11459 

## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [ ] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [ ] Validated on required platforms/methods:
  - [ ] MacOS
    - [x] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

Working as expected without indefinite wait on invoking mcp-server tool in non-interactive mode:
Screenshot 2025-12-08 at 8 18 53 PM

### CODE REVIEW

**Review by iqbalbhatti49 — APPROVED** [review]

File: packages/core/src/core/coreToolScheduler.ts [hunk 1]
```diff
@@ -872,6 +872,17 @@ export class CoreToolScheduler {
             );
             this.setStatusInternal(reqInfo.callId, 'scheduled', signal);
           } else {
+            // Following the similar logic of policy-engine defined in
+            // shouldConfirmExecute() method of packages/core/src/tools/tools.ts
+            // i.e. throw error in case of requiring confirmation for
+            // non-interactive mode.
```
Comment (scidomino) [inline packages/core/src/core/coreToolScheduler.ts]: This comment is unnecessary. The error string tells us all we need to know.

**Review by scidomino — APPROVED** [review]

File: packages/core/src/core/coreToolScheduler.ts (hunk 1 above)
Comment (MayV) [reply packages/core/src/core/coreToolScheduler.ts]: Done!

**Review by scidomino — APPROVED** [review]
