### PR TITLE
fix: allow `ask_user` tool in interactive yolo mode

### LINKED ISSUE #18540: Ask User tool being auto-approved with empty answers in YOLO mode
Yolo mode auto-approves all tool confirmations. It is auto-approving the `ask_user` tool dialog, which submits empty answers to questions.

Need to fix so `ask_user` can be used in yolo mode when explicitly asking for questions to find a balance between allowing tool in yolo mode but also not having agent over use it blocking autonomous work.

### PR DESCRIPTION
**Pull request by jackwotherspoon**
## Summary

Allow `ask_user` in interactive yolo mode, previously tool was being auto-accepted with empty answers.

Moved `yolo` to priority `998` and made `ask_user` priority `999`.

## Details

   - **YOLO Mode Logic**: Updated `PromptProvider` to inject a new yolo section into the system prompt when
   `ApprovalMode.YOLO` is active and the session is interactive.
   - **Prompt Snippets**: Added `renderYoloMode` to both `snippets.ts` and `snippets.legacy.ts` containing the specific
   instructions for autonomous operation.
   - **Priority Management**: Ensured that while YOLO mode auto-approves most tools, the `ask_user` tool remains at `priority = 999` with a `decision = "ask_user"`. This guarantees that the model still requires explicit user confirmation when it chooses use `ask_user`, preventing it from "auto-answering" its own questions.
   - **Validation**: Added tests in `prompts.test.ts` to ensure the instructions are only included when
   appropriate (YOLO mode active + interactive).

   ## Related Issues

   Fixes #18540

   ## How to Validate

   1. Run unit tests for the prompt provider:

      ```bash
      npm test -w @google/gemini-cli-core -- src/core/prompts.test.ts
      ```
   2. Build the project:
      ```bash
      npm run build
      ```
   3. (Optional) Toggle yolo mode on and ask agent to ask you questions it will. But ask it to implement a feature and it won't unless necessary

   ## Pre-Merge Checklist

   - [ ] Updated relevant documentation and README (if needed)
   - [x] Added/updated tests (if needed)
   - [ ] Noted breaking changes (if any)
   - [ ] Validated on required platforms/methods:
     - [x] MacOS
       - [x] npm run
       - [ ] npx
       - [ ] Docker
       - [ ] Podman
       - [ ] Seatbelt
     - [ ] Windows
       - [ ] npm run
       - [ ] npx
       - [ ] Docker
     - [ ] Linux
       - [ ] npm run
       - [ ] npx
       - [ ] Docker

### CODE REVIEW

File: packages/core/src/prompts/promptProvider.ts [hunk 1]
```diff
@@ -159,6 +160,11 @@ export class PromptProvider {
           }),
         ),
         sandbox: this.withSection('sandbox', () => getSandboxMode()),
+        yoloMode: this.withSection(
```
Comment (jerop) [inline packages/core/src/prompts/promptProvider.ts]:
```suggestion
        interactiveYoloMode: this.withSection(
```

File: packages/core/src/prompts/snippets.legacy.ts [hunk 2]
```diff
@@ -263,6 +266,25 @@ You are running outside of a sandbox container, directly on the user's system. F
   }
 }
 
+export function renderYoloMode(enabled?: boolean): string {
```
Comment (jerop) [inline packages/core/src/prompts/snippets.legacy.ts]:
```suggestion
export function renderYoloInteractiveMode(enabled?: boolean): string {
```

File: packages/core/src/policy/policies/yolo.toml [hunk 3]
```diff
@@ -23,10 +23,20 @@
 #   10: Write tools default to ASK_USER (becomes 1.010 in default tier)
 #   15: Auto-edit tool override (becomes 1.015 in default tier)
 #   50: Read-only tools (becomes 1.050 in default tier)
-#   999: YOLO mode allow-all (becomes 1.999 in default tier)
+#   998: YOLO mode allow-all (becomes 1.998 in default tier)
+#   999: Ask-user tool (becomes 1.999 in default tier)
 
+# Ask-user tool always requires user interaction, even in YOLO mode.
+# This ensures the model can gather user preferences/decisions when needed.
```
Comment (jerop) [inline packages/core/src/policy/policies/yolo.toml:30]: will this not cause issues in non-interactive mode?

File: packages/core/src/prompts/snippets.ts [hunk 4]
```diff
@@ -31,6 +31,7 @@ export interface SystemPromptOptions {
   planningWorkflow?: PlanningWorkflowOptions;
   operationalGuidelines?: OperationalGuidelinesOptions;
   sandbox?: SandboxMode;
+  yoloMode?: boolean;
```
Comment (jerop) [inline packages/core/src/prompts/snippets.ts]:
```suggestion
  interactiveYoloMode?: boolean;
```

File: packages/core/src/prompts/snippets.legacy.ts [hunk 5]
```diff
@@ -31,6 +31,7 @@ export interface SystemPromptOptions {
   planningWorkflow?: PlanningWorkflowOptions;
   operationalGuidelines?: OperationalGuidelinesOptions;
   sandbox?: SandboxMode;
+  yoloMode?: boolean;
```
Comment (jerop) [inline packages/core/src/prompts/snippets.legacy.ts]:
```suggestion
  interactiveYoloMode?: boolean;
```

File: packages/core/src/prompts/snippets.ts [hunk 6]
```diff
@@ -106,6 +107,8 @@ ${
 
 ${renderOperationalGuidelines(options.operationalGuidelines)}
 
+${renderYoloMode(options.yoloMode)}
```
Comment (jerop) [inline packages/core/src/prompts/snippets.ts]:
```suggestion
${renderInteractiveYoloMode(options.yoloMode)}
```

File: packages/core/src/prompts/snippets.ts [hunk 7]
```diff
@@ -274,6 +277,25 @@ You are running outside of a sandbox container, directly on the user's system. F
   }
 }
 
+export function renderYoloMode(enabled?: boolean): string {
```
Comment (jerop) [inline packages/core/src/prompts/snippets.ts]:
```suggestion
export function renderInteractiveYoloMode(enabled?: boolean): string {
```

File: packages/core/src/prompts/promptProvider.ts [hunk 8]
```diff
@@ -159,6 +160,11 @@ export class PromptProvider {
...
+          'yoloMode',
```
Comment (jerop) [inline packages/core/src/prompts/promptProvider.ts]:
```suggestion
          'interactiveYoloMode',
```

File: packages/core/src/prompts/snippets.legacy.ts [hunk 9]
```diff
@@ -106,6 +107,8 @@ ${
 
 ${renderOperationalGuidelines(options.operationalGuidelines)}
 
+${renderYoloMode(options.yoloMode)}
```
Comment (jerop) [inline packages/core/src/prompts/snippets.legacy.ts]:
```suggestion
${renderYoloInteractiveMode(options.interactiveYoloMode)}
```

**Review by jerop — COMMENTED** [review]
left some suggestions to make it clear that this is for interactive yolo mode

File: packages/core/src/policy/policies/yolo.toml (hunk 3 above)
Comment (jackwotherspoon) [reply packages/core/src/policy/policies/yolo.toml:30]: Nope it won't, I added a comment to clarify this.

File: packages/core/src/prompts/snippets.legacy.ts [hunk 10]
```diff
@@ -114,6 +115,8 @@ ${
 
 ${renderOperationalGuidelines(options.operationalGuidelines)}
 
+${renderYoloInteractiveMode(options.interactiveYoloMode)}
```
Comment (jerop) [inline packages/core/src/prompts/snippets.legacy.ts]: nit: be consistent with `interactiveYoloMode` flag:

```suggestion
${renderInteractiveYoloMode(options.interactiveYoloMode)}
```

Comment (jerop) [reply packages/core/src/prompts/snippets.legacy.ts]: also you called it `renderInteractiveYoloMode` in snippets.ts below

**Review by jerop — APPROVED** [review]

File: packages/core/src/prompts/snippets.ts [hunk 11]
```diff
@@ -312,6 +315,25 @@ export function renderSandbox(mode?: SandboxMode): string {
   return '';
 }
 
+export function renderInteractiveYoloMode(enabled?: boolean): string {
+  if (!enabled) return '';
+  return `
+# Autonomous Mode (YOLO)
+
+You are operating in **autonomous mode**. The user has requested minimal interruption.
```
Comment (gundermanc) [inline packages/core/src/prompts/snippets.ts:323]: It'd be great to have 1-3 evals to cover the major scenarios.

- "Significant rework"
- "Ambiguous request"
- "Explicitly asked"

These can be a bit of a pain to implement so I think it's also fine if you just wanted to add one.

File: packages/core/src/prompts/snippets.ts [hunk 12]
```diff
@@ -312,6 +315,25 @@ export function renderSandbox(mode?: SandboxMode): string {
...
+
+**Only use the \`${ASK_USER_TOOL_NAME}\` tool if:**
```
Comment (gundermanc) [inline packages/core/src/prompts/snippets.ts:325]: We may find we get better behavior with at least one example.

**Review by gundermanc — APPROVED** [review]
