### PR TITLE
Make --allowed-tools work in non-interactive mode

### LINKED ISSUE #9011: --allowed-tools does not work in non-interactive mode
### What happened?

`--allowed-tools` only applies to interactive mode, but is ignored if the prompt is supplied on the command-line. The following command should work, but doesn't:

```sh
gemini --allowed-tools="ShellTool(wc)" \
    --prompt="use wc to tell me how many lines there are in /proc/meminfo"
```

### What did you expect to happen?

```sh
$ gemini --allowed-tools="ShellTool(wc)" \
    --prompt="use wc to tell me how many lines there are in /proc/meminfo"
There are 55 lines in /proc/meminfo.
$ 
```

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│ About Gemini CLI                                                                            │
│                                                                                             │
│ CLI Version                     0.7.0-nightly.20250918.2722473a-git.fa8cea17                │
│ Git Commit                      fa8cea17                                                    │
│ Model                           gemini-2.5-pro                                              │
│ Sandbox                         no sandbox                                                  │
│ OS                              linux                                                       │
│ Auth Method                     gemini-api-key                                              │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯

```

</details>

### Login information

n/a

### Anything else we need to know?

It would be good if this was also fixed for `tools.allowed` in settings.json as well.

### PR DESCRIPTION
**Pull request by mistergarrison**
## TLDR

Non-interactive mode excludes tools that can block (including ShellTool), which means that passing --allowed-tools with shell tools doesn't do anything.

This change blocks ShellTool from being excluded if it is allowed, and preemptively rejects non-allowed shell tools (so that they don't hang waiting for user approval that will never come).

This should not affect interactive behavior at all, nor should it affect the behavior of YOLO mode.

## Reviewer Test Plan

```sh
# Should print something like "There are 55 lines in /proc/meminfo"
npx github:mistergarrison/gemini-cli#fix/allowed-tools-non-interactive \
  --yolo \
  --prompt="use wc to tell me how many lines there are in /proc/meminfo"

# Should print something like "There are 55 lines in /proc/meminfo"
npx github:mistergarrison/gemini-cli#fix/allowed-tools-non-interactive \
  --allowed-tools="ShellTool(wc)" \
  --allowed-tools="ShellTool()" \
  --prompt="use wc to tell me how many lines there are in /proc/meminfo"

# Should print something like "There are 55 lines in /proc/meminfo"
npx github:mistergarrison/gemini-cli#fix/allowed-tools-non-interactive \
  --allowed-tools="run_shell_command(wc)" \
  --allowed-tools="run_shell_command()" \
  --prompt="use wc to tell me how many lines there are in /proc/meminfo"

# Should print something like "There are 55 lines in /proc/meminfo"
npx github:mistergarrison/gemini-cli#fix/allowed-tools-non-interactive \
  --allowed-tools="ShellTool(wc)" \
  --allowed-tools="ShellTool" \
  --prompt="use wc to tell me how many lines there are in /proc/meminfo"

# Should print something like "There are 55 lines in /proc/meminfo"
npx github:mistergarrison/gemini-cli#fix/allowed-tools-non-interactive \
  --allowed-tools="run_shell_command(wc)" \
  --allowed-tools="ShellTool" \
  --prompt="use wc to tell me how many lines there are in /proc/meminfo"

# Should print something like "There are 55 lines in /proc/meminfo"
npx github:mistergarrison/gemini-cli#fix/allowed-tools-non-interactive \
  --allowed-tools="ShellTool(ls)" \
  --allowed-tools="ShellTool" \
  --prompt="use wc to tell me how many lines there are in /proc/meminfo"

# Should add a line to the file
touch tmp_file.txt
npx github:mistergarrison/gemini-cli#fix/allowed-tools-non-interactive \
  --allowed-tools="write_file" \
  --prompt="Add '42' to the end of ./tmp_file.txt."
cat tmp_file.txt
rm tmp_file.txt

# Should fail
npx github:mistergarrison/gemini-cli#fix/allowed-tools-non-interactive \
  --allowed-tools="ShellTool(ls)" \
  --allowed-tools="ShellTool()" \
  --prompt="use wc to tell me how many lines there are in /proc/meminfo"

# Should fail
npx github:mistergarrison/gemini-cli#fix/allowed-tools-non-interactive \
  --allowed-tools="run_shell_command(ls)" \
  --allowed-tools="run_shell_command()" \
  --prompt="use wc to tell me how many lines there are in /proc/meminfo"

# Should fail
npx github:mistergarrison/gemini-cli#fix/allowed-tools-non-interactive \
  --prompt="use wc to tell me how many lines there are in /proc/meminfo"

```

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | ❓  | ❓  | ❓  |
| npx      | ❓ | ❓  | ✅  |
| Docker   | ❓  | ❓  | ❓  |
| Podman   | ❓  | -   | -   |
| Seatbelt | ❓  | -   | -   |

## Linked issues / bugs

Fixes #9011

### CODE REVIEW

File: packages/core/src/utils/shell-utils.ts [hunk 1]
```diff
@@ -11,7 +11,7 @@ import { quote } from 'shell-quote';
 import { doesToolInvocationMatch } from './tool-utils.js';
 import { spawn, type SpawnOptionsWithoutStdio } from 'node:child_process';
 
-const SHELL_TOOL_NAMES = ['run_shell_command', 'ShellTool'];
+export const SHELL_TOOL_NAMES = ['run_shell_command', 'ShellTool'];
```
Comment (cornmander) [inline packages/core/src/utils/shell-utils.ts:14]: Can you get this from the tool somehow? I don't like having a hardcoded constant here that's basically duplicative with the tool itself.

Comment (mistergarrison) [reply packages/core/src/utils/shell-utils.ts:14]: Could I do a cleanup as a followup? This PR is already getting pretty big. (I'll defer to you)

Comment (mistergarrison) [reply packages/core/src/utils/shell-utils.ts:14]: okay, well I went ahead and updated it to be only defined here. Let me know if that's not what you wanted.

**Review by cornmander — APPROVED** [review]

**Comment by mistergarrison** [comment]
> ## Code Review
> This pull request successfully enables the use of `--allowed-tools` in non-interactive mode, particularly for `ShellTool`. The changes correctly adjust the tool exclusion logic in `loadCliConfig` and add a preemptive check within `ShellTool` to prevent hangs on unapproved commands. The updates are well-supported by a comprehensive set of new integration and unit tests. My review includes one high-severity suggestion to refactor duplicated code in `packages/cli/src/config/config.ts` to improve long-term maintainability.

(the high-severity suggestion was addressed)

**Comment by mistergarrison** [comment]
The failing test (because it runs long) looks unrelated:

```js
  it('should not be interactive if positional prompt words are provided with other flags', async () => {
    process.stdin.isTTY = true;
    process.argv = ['node', 'script.js', '--model', 'gemini-1.5-pro', 'Hello'];
    const argv = await parseArguments({} as Settings);
    const config = await loadCliConfig({}, [], 'test-session', argv);
    expect(config.isInteractive()).toBe(false);
  });
```

**Review by cornmander — APPROVED** [review]
