### PR TITLE
fix(core): attempt compression before context overflow check

### LINKED ISSUE #16213: Context compression loop: Model attempts to compress every turn but fails to reduce context size
**What happened?**
In a long conversation, the CLI enters a state where it attempts to compress the chat history on every single turn. The user observes the "Compressing chat history..." spinner/message each time.

This indicates that either:
1. The compression is "successful" (returns `COMPRESSED`) but doesn't reduce the token count sufficiently to stay under the threshold for more than one turn.
2. The compression fails in a way that doesn't trigger the "stop trying" logic (i.e., not `COMPRESSION_FAILED_INFLATED_TOKEN_COUNT`).
3. The `hasFailedCompressionAttempt` flag is not persisting or checking correctly.

The result is a degraded user experience with unnecessary latency per turn and no effective context management.

**What did you expect to happen?**
* If compression is successful, it should reduce the context size significantly enough to avoid immediate re-compression.
* If compression yields marginal gains or fails, the system should back off and not retry on the immediate next turn.

**Client information**
* OS: macOS (Darwin)
* Version: (Dev/Source)

**Additional context**

Image

### PR DESCRIPTION
**Pull request by NTaylorMullen**
Move context window overflow check to after compression and remove the 0.95 safety buffer. This ensures that sessions nearing their context limit have a chance to free up space via compression before the request is blocked.

- Move tryCompressChat before remainingTokenCount check in processTurn
- Remove 0.95 multiplier from overflow threshold
- Add regression test for compression-then-overflow flow

Fixes https://github.com/google-gemini/gemini-cli/issues/16213

### CODE REVIEW

**Review by iqbalbhatti49 — APPROVED** [review]

File: packages/core/src/core/client.ts [hunk 1]
```diff
@@ -543,23 +543,23 @@ export class GeminiClient {
       modelForLimitCheck,
     );
 
+    const compressed = await this.tryCompressChat(prompt_id, false);
```
Comment (scidomino) [inline packages/core/src/core/client.ts:538]: By moving this to before the ContextWindowWillOverflow check are we not basically guaranteeing that when the request is too big, we will try to compress it and fail with an ugly backend error? That's what we were trying to avoid with the "estimatedRequestTokenCount > remainingTokenCount" check. If we're just going to try to compress anyways, we might as well get rid of that check entirely, no?

Comment (NTaylorMullen) [reply packages/core/src/core/client.ts:538]: So we're making a different bet. The bet we're making is that the last 70% of the history < the limit since that's what we hand off to the model for compression. Let me see if I can make that one check a bit more robust. This is a great callout!

Comment (scidomino) [reply packages/core/src/core/client.ts:538]: Are you sure? If I recall correctly the new request gets added to the context super early so I think your tryCompressChat call already has the request in it. I'd double check to make sure it works the way we're thinking.

File: packages/core/src/core/client.ts
Comment (scidomino) [inline packages/core/src/core/client.ts]: nit: Move this to after the compressed call so it's declared closer to where it is used.

**Review by scidomino — APPROVED** [review]
Approved to unblock.

**Review by mattKorwel — APPROVED** [review]
🚀

**Review by mattKorwel — APPROVED** [review]

File: packages/core/src/core/client.ts (hunk 1 above)
Comment (NTaylorMullen) [reply packages/core/src/core/client.ts:538]: Ended up adding a truncation step that ensured this to be max 50k tokens
