### PR TITLE
fix: avoid SDK warning by not accessing .text getter in logging

### LINKED ISSUE #15257: "there are non-text parts functionCall in the response, returning concatenation of all text parts."
### What happened?

I see this when running locally:

```
 npx https://github.com/google-gemini/gemini-cli#tomm_introspection_agent "use the introspection agent to find out if ctrl+j is a hotkey you support and if so, what does it do"
Hook registry initialized with 0 hook entries
[STARTUP] StartupProfiler.flush() called with 9 phases
[STARTUP] Recording metric for phase: cli_startup duration: 184.76741599999997
[STARTUP] Recording metric for phase: load_settings duration: 3.080083000000002
[STARTUP] Recording metric for phase: migrate_settings duration: 0.8034590000000321
[STARTUP] Recording metric for phase: parse_arguments duration: 9.829000000000008
[STARTUP] Recording metric for phase: load_cli_config duration: 23.64879200000007
[STARTUP] Recording metric for phase: initialize_app duration: 144.28945800000008
[STARTUP] Recording metric for phase: authenticate duration: 1.5533750000000737
[STARTUP] Recording metric for phase: discover_tools duration: 784.4320839999999
[STARTUP] Recording metric for phase: initialize_mcp_clients duration: 1469.074
I will delegate this question to the introspection agent to check for supported hotkeys.
there are non-text parts functionCall in the response, returning concatenation of all text parts. Please refer to the non text parts for a full response from model.
there are non-text parts functionCall in the response, returning concatenation of all text parts. Please refer to the non text parts for a full response from model.
there are non-text parts functionCall in the response, returning concatenation of all text parts. Please refer to the non text parts for a full response from model.
there are non-text parts functionCall in the response, returning concatenation of all text parts. Please refer to the non text parts for a full response from model.
there are non-text parts functionCall in the response, returning concatenation of all text parts. Please refer to the non text parts for a full response from model.
there are non-text parts functionCall in the response, returning concatenation of all text parts. Please refer to the non text parts for a full response from model.
there are non-text parts functionCall in the response, returning concatenation of all text parts. Please refer to the non text parts for a full response from model.
there are non-text parts functionCall in the response, returning concatenation of all text parts. Please refer to the non text parts for a full response from model.
Yes, `Ctrl+J` is a supported hotkey in Gemini CLI. It is used to insert a newline in the text input field without submitting the current prompt.
sciortino-mac:ink sciortino$
```

### What did you expect to happen?

not that

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
# paste output here
```

</details>

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by ved015**
@scidomino please have a look

## Summary

Fixes SDK warning "there are non-text parts functionCall in the response..." that appears when using the introspection agent or any tool that returns function calls. The warning was triggered by logging code accidentally accessing the `.text` getter property, not by any actual loss of content.

## Details
The `@google/genai` SDK's `GenerateContentResponse.text` is a getter that logs a warning when accessed on responses containing non-text parts (like function calls). This was being triggered in [loggingContentGenerator.ts](cci:7://file:///Users/vedantmahajan/Desktop/gemini-cli/packages/core/src/core/loggingContentGenerator.ts:0:0-0:0) when using `JSON.stringify(response)`, which accesses all enumerable properties including the `.text` getter.

We modify the JSON.stringify() and pass a simple object in it we dont pass candidates reponseId usageMetaData as they are already passed above

## Related Issues

Fixes #15257 

## How to Validate

**Before the fix:**
```bash
npm run start -- "use the introspection agent to find out if ctrl+j is a hotkey you support and if so, what does it do"
```

`there are non-text parts functionCall in the response, returning concatenation of all text parts`

After the fix the warning goes away
Screenshot 2025-12-30 at 12 51 39 PM

## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [ ] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [ ] Validated on required platforms/methods:
  - [ ] MacOS
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

collaborated with @ishaanxgupta

### CODE REVIEW

File: packages/core/src/core/loggingContentGenerator.ts [hunk 1]
```diff
@@ -213,7 +213,9 @@ export class LoggingContentGenerator implements ContentGenerator {
             response.responseId,
             response.candidates,
             response.usageMetadata,
-            JSON.stringify(response),
+            JSON.stringify({
```
Comment (scidomino) [inline packages/core/src/core/loggingContentGenerator.ts:216]: The purpose of this PR is not to remove fields from logging, but to eliminate the warning. Please put back all the fields like we discussed in the bug and ignore any suggestions by gemini to do otherwise.

Comment (ved015) [reply packages/core/src/core/loggingContentGenerator.ts:216]: ok will do that I removed rest of the fields because everything else was already being passed to logApiResponse

**Review by scidomino — APPROVED** [review]
