### PR TITLE
Fix: Preserve conversation history when changing auth methods via /auth

### LINKED ISSUE #5067: Make /auth not nuke conversation history
### What happened?

Running `/auth` clears the conversation history.

### What did you expect to happen?

Expected to run `/auth` and then continue my existing conversation.

Fixing this surprising behavior will reduce friction for users who need to change `/auth` mode in the middle of a conversation.
https://x.com/intellectronica/status/1945754994679927116

### PR DESCRIPTION
**Pull request by AjayKumbham**
## TLDR

Fixed issue where `/auth` command was clearing conversation history. Modified `Config.refreshAuth()` to preserve existing conversation history when changing authentication methods, allowing users to seamlessly continue their conversations after switching auth methods.

## Dive Deeper

The root cause was in `packages/core/src/config/config.ts` where the `refreshAuth()` method was creating a completely new `GeminiClient` instance, which starts with a fresh conversation history. This meant users lost all their conversation context when changing auth methods.

The solution preserves conversation history by:
1. **Saving current history** before creating new client
2. **Creating new client** with updated auth configuration  
3. **Restoring history** to the new client

This is a minimal, focused fix that maintains backward compatibility while solving the exact UX issue described in #5067.

## Reviewer Test Plan

1. **Start a conversation** with any auth method
2. **Add some messages** to build conversation history
3. **Run `/auth`** to change authentication method
4. **Verify conversation history is preserved** - all previous messages should still be visible
5. **Continue the conversation** - should work seamlessly with new auth method

**Key things to test:**
- Conversation history remains intact after auth change
- New messages can be sent/received after auth change
- No duplicate messages or corrupted history
- Works with all auth methods (Google login, API key, etc.)

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | ❓  | ❓  | ❓  |
| npx      | ❓  | ❓  | ❓  |
| Docker   | ❓  | ❓  | ❓  |
| Podman   | ❓  | -   | -   |
| Seatbelt | ❓  | -   | -   |

## Linked issues / bugs

Fixes #5067

### CODE REVIEW

**Comment by AjayKumbham** [comment]
Addressed code review feedback from Gemini Code Assist: improved atomicity and added tests

Fixed atomicity issue by creating a new client in a local variable first

Assigned to instance properties only after successful initialization

Added comprehensive unit tests for conversation history preservation

Tested both scenarios: with existing history and without an existing client

File: packages/core/src/config/config.ts [hunk 1]
```diff
@@ -322,13 +323,30 @@ export class Config {
   }
 
   async refreshAuth(authMethod: AuthType) {
-    this.contentGeneratorConfig = createContentGeneratorConfig(
+    // Save the current conversation history before creating a new client
+    let existingHistory: Content[] = [];
+    if (this.geminiClient && this.geminiClient.isInitialized()) {
+      existingHistory = this.geminiClient.getHistory();
```
Comment (jacob314) [inline packages/core/src/config/config.ts:339]: bad news is this causes Gemini CLI to start failing when switching from an api key to signing in with gmail.
`/chat save|resume` also has this issue so this isn't your bug specifically and we will need to track down why that is occurring.

The typical direction users will go with this functionality is likely switching from an API_KEY so I am open to allowing this even before that change is in.
If we want to be really careful we might want to clear the history for that failure case mode with a link to the the bug explaining why we had to.
https://github.com/google-gemini/gemini-cli/issues/5239

**Review by jacob314 — APPROVED** [review]
lgtm

**Comment by jacob314** [comment]
Heads up that you will need to run the formatter to fix the lint errors before I can submit.

**Comment by AjayKumbham** [comment]
Thank you for the feedback, @jacob314! The formatting has been applied and the changes are now ready for review.

**Comment by AjayKumbham** [comment]
Replaced all instances of `any` with `unknown` and proper type casting to resolve ESLint errors. The changes are now ready for re-review.

**Comment by AjayKumbham** [comment]
Hi @jacob314, all feedback has been addressed and the linting errors have been fixed. Since auto-merge is disabled due to permissions, could you please re-enable auto-merge or approve the workflow when convenient? Thank you!

**Review by jacob314 — APPROVED** [review]
lgtm

**Comment by AjayKumbham** [comment]
Thank you, @jacob314, for the review and merge! Glad to see the fix successfully integrated.
