### PR TITLE
fix(ui): add partial output to cancelled shell UI

### LINKED ISSUE #20623: Make cancelled output visible on the TUI
The partial output returned from a cancelled shell tool invocation doesn't show up on the TUI. We should show it so that users can see what the output was before cancelling.

### PR DESCRIPTION
**Pull request by devr0306**
## Summary

Added partial shell output to cancelled shell tool calls.

## Details

Added the liveOutput from the shell tool call before its status is set to cancelled and the tool's result is discarded.

## Related Issues

Fixes #20623 

## How to Validate

Ask Gemini CLI `Run npm test -w @google/gemini-cli` and cancel before it finishes running. The partial output should show in the cancelled shell.

## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [x] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [x] Validated on required platforms/methods:
  - [x] MacOS
    - [x] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

File: packages/core/src/scheduler/state-manager.ts [hunk 1]
```diff
@@ -477,13 +477,24 @@ export class SchedulerStateManager {
...
+    // Capture any existing live output so it isn't lost when forcing cancellation.
+    let existingOutput: ToolResultDisplay | undefined = undefined;
+    if (call.status === CoreToolCallStatus.Executing && call.liveOutput) {
+      existingOutput = call.liveOutput;
+    }
+
     if (isToolCallResponseInfo(reason)) {
+      const finalResponse = { ...reason };
+      if (!finalResponse.resultDisplay) {
+        finalResponse.resultDisplay = resultDisplay ?? existingOutput;
```
Comment (jacob314) [inline packages/core/src/scheduler/state-manager.ts:489]: edge case to watch out for here is when the tool output is large and so we have added a message at the end indicating we have written the full output to a file. please test that case

**Review by jacob314 — APPROVED** [review]
lgtm

File: packages/core/src/scheduler/state-manager.ts (hunk 1 above)
Comment (devr0306) [reply packages/core/src/scheduler/state-manager.ts:489]: I'll address it in a follow-up PR
