### PR TITLE
fix(core): handle unhandled promise rejection in mcp-client-manager

### LINKED ISSUE #14700: Fix unhandled promise rejection in MCP client manager
### What happened?

The `addOrUpdateServer()` method in `packages/core/src/tools/mcp-client-manager.ts` has an unhandled promise rejection issue. When errors occur during MCP client initialization (e.g., in the McpClient constructor or disconnect method), they are not properly caught, leading to unhandled promise rejections that can crash the Node.js process.

The Promise constructor receives a `_reject` parameter that is never used, and the async IIFE has no `.catch()` handler, causing errors thrown before the try block to become unhandled rejections.

### What did you expect to happen?

Errors during MCP server initialization should be caught and handled gracefully. Specifically:
- Errors should be logged with clear error messages via coreEvents.emitFeedback
- One MCP server failure should not prevent other servers from starting
- The Node.js process should not crash with UnhandledPromiseRejectionWarning
- Users should see helpful error messages indicating which server failed and why

### Client information

<details>
<summary>Client Information</summary>

Platform: **Linux (WSL2)**

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
Gemini CLI v0.21.0-nightly.20251207.025e450ac
Node.js: v20.19.3
OS: Linux 6.6.87.2-microsoft-standard-WSL2
```

</details>

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by kamja44**
- Add outer try-catch block to catch initialization errors
- Connect async IIFE rejection to Promise reject handler
- Add tests for error scenarios during client initialization
- Prevents unhandled promise rejection when McpClient constructor throws
- Ensures one server failure doesn't stop other servers from starting

Fixes #14700

## Summary

Fixes a structural issue in `McpClientManager.addOrUpdateServer()` that causes unhandled promise rejections during MCP server initialization. The Promise constructor received an unused `_reject` parameter, and the async IIFE lacked proper error handling, causing crashes when errors occurred in the McpClient constructor or disconnect method.

## Details

**Root cause:** The current implementation creates a Promise with `_reject` parameter but never uses it. The async IIFE has no `.catch()` handler, so errors thrown before the try block become unhandled rejections.

**Changes made:**
1. Changed `_reject` to `reject` and properly connected it
2. Added outer try-catch to catch initialization errors (constructor, disconnect)
3. Added `.catch(reject)` to async IIFE to handle any uncaught errors
4. Added proper error logging via `coreEvents.emitFeedback`

**Files modified:**
- `packages/core/src/tools/mcp-client-manager.ts` (lines 162-220)
- `packages/core/src/tools/mcp-client-manager.test.ts` (added 2 test cases)

**Note:** This is **NOT** a duplicate of #8365. That issue was about MCP timeout errors in `gemini.mjs` and is already closed. This PR fixes a different structural problem in `mcp-client-manager.ts` that could cause unhandled rejections during initialization.

## Related Issues

Fixes #14700

## How to Validate

1. Run unit tests:
```bash
npm run test mcp-client-manager.test.ts

## Pre-Merge Checklist

<!-- Check all that apply before requesting review or merging. -->

- [ ] Updated relevant documentation and README (if needed)
- [O] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [ ] Validated on required platforms/methods:
  - [ ] MacOS
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [O] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

File: packages/core/src/tools/mcp-client-manager.ts [hunk 1]
```diff
@@ -216,7 +223,7 @@ export class McpClientManager {
           }
           resolve();
         }
-      })();
+      })().catch(reject);
```
[the remark this answers is not in the document]
Comment (kamja44) [reply packages/core/src/tools/mcp-client-manager.ts:230]: Fixed! Changed `.then()` to `.finally()` with `void` operator to prevent floating promise.

Changes:
- Line 238: `currentPromise.then((_) => ...)` → `void currentPromise.finally(() => ...)`
- Removed eslint-disable comment
- All tests still passing ✅

[the remark this answers is not in the document]
Comment (kamja44) [reply packages/core/src/tools/mcp-client-manager.ts:230]: /gemini review

**Review by iqbalbhatti49 — APPROVED** [review]

File: packages/core/src/tools/mcp-client-manager.ts [hunk 2]
```diff
@@ -234,8 +240,7 @@ export class McpClientManager {
     }
     this.eventEmitter?.emit('mcp-client-update', this.clients);
     const currentPromise = this.discoveryPromise;
-    // eslint-disable-next-line @typescript-eslint/no-floating-promises
-    currentPromise.then((_) => {
+    void currentPromise.finally(() => {
```
Comment (Adib234) [inline packages/core/src/tools/mcp-client-manager.ts]: Can we attach a `catch` to this promise?

```js
void currentPromise
  .finally(() => {
    if (currentPromise === this.discoveryPromise) {
      this.discoveryPromise = undefined;
      this.discoveryState = MCPDiscoveryState.COMPLETED;
    }
  })
  .catch(() => {}); // Prevents unhandled rejection from the .finally branch
  ```

File: packages/core/src/tools/mcp-client-manager.ts
Comment (Adib234) [inline packages/core/src/tools/mcp-client-manager.ts:1]: We have another unhandled promise on line 234  https://github.com/google-gemini/gemini-cli/blob/d344cebc510cc9e7bb8da97e4952fe5a2f14c62f/packages/core/src/tools/mcp-client-manager.ts#L234

If the promise gets rejected there's nothing to handle this, so can we add the `catch` as well?

```js
if (this.discoveryPromise) {
  // Ensure the next discovery starts regardless of the previous one's success/failure
  this.discoveryPromise = this.discoveryPromise
    .catch(() => {}) 
    .then(() => currentDiscoveryPromise);
}
```

File: packages/core/src/tools/mcp-client-manager.ts (hunk 2 above)
Comment (kamja44) [reply packages/core/src/tools/mcp-client-manager.ts]: Added the `.catch()` to handle any errors from the finally block. Thanks!

File: packages/core/src/tools/mcp-client-manager.ts
Comment (kamja44) [reply packages/core/src/tools/mcp-client-manager.ts:1]: Without the `.catch()`, the next discovery wouldn't run if the previous one failed. Fixed by adding `.catch()` before `.then()`. Thanks for catching this important issue!

**Review by Adib234 — APPROVED** [review]
Thank you for this! LGTM 🚀
