### PR TITLE
fix(core): show descriptive error messages when saving settings fails

### LINKED ISSUE #18052: Saving system settings fails with generic error when not running as root (Linux/EACCES)
### What happened?

When using the /settings command to save system/global settings, a small error is shown:

> ✕ There was an error saving your latest settings changes.

This is not amazingly helpful (especially for folks like me who are not massively familiar with Linux).

The issue stems from the fact that `gemini-cli` is not running as root/sudo (as I imagine most users run it this way) - running a debug session gives the below error:

```bash
[Feedback Details for \"There was an error saving your latest settings changes.\"] Error: EACCES: permission denied, mkdir '/etc/gemini-cli'
    at Module.mkdirSync (node:fs:1349:26)
    at saveSettings (file:///home/dev/.nvm/versions/node/v24.12.0/lib/node_modules/@google/gemini-cli/dist/src/config/settings.js:583:16)
    at LoadedSettings.setValue (file:///home/dev/.nvm/versions/node/v24.12.0/lib/node_modules/@google/gemini-cli/dist/src/config/settings.js:199:9)
    at file:///home/dev/.nvm/versions/node/v24.12.0/lib/node_modules/@google/gemini-cli/dist/src/utils/settingsUtils.js:291:28
    at Set.forEach (<anonymous>)
    at saveModifiedSettings (file:///home/dev/.nvm/versions/node/v24.12.0/lib/node_modules/@google/gemini-cli/dist/src/utils/settingsUtils.js:282:22)
    at Object.toggle (file:///home/dev/.nvm/versions/node/v24.12.0/lib/node_modules/@google/gemini-cli/dist/src/ui/components/SettingsDialog.js:172:25)
    at SettingsDialog.useKeypress.isActive (file:///home/dev/.nvm/versions/node/v24.12.0/lib/node_modules/@google/gemini-cli/dist/src/ui/components/SettingsDialog.js:543:34)
    at file:///home/dev/.nvm/versions/node/v24.12.0/lib/node_modules/@google/gemini-cli/dist/src/ui/contexts/KeypressContext.js:573:77
    at Set.forEach (<anonymous>) {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/etc/gemini-cli'
}
```

### What did you expect to happen?

I would expect/like a better error message, or perhaps even, if `gemini-cli` can detect if it is running as root and disable the `system` tab in settings entirely.

### Client information

<details>
<summary>Client Information</summary>

| Component | Value |
| :--- | :--- |
| **CLI Version** | 0.26.0 |
| **Git Commit** | `a380b4219` |
| **Model** | `auto-gemini-3` |
| **Sandbox** | no sandbox |
| **OS** | linux |
| **Auth Method** | OAuth |
| **User Email** | readacted@redacted.com |

</details>

### Login information

Google Account

### Anything else we need to know?

I am curious if there is a better way around this. Currently, my setup is I have everything coding related running entirely on a dedicated WSL instance for coding. I also have `gemini-cli` installed there.

Having global settings would be nice, as if I do decide to say, create a new account for testing an app or something, having all my settings saved system-wide would be awesome.

### PR DESCRIPTION
**Pull request by afarber**
## Summary

When saving system settings fails (e.g., `EACCES` trying to create `/etc/gemini-cli`), users see a generic "There was an error saving your latest settings changes." This PR adds a utility that converts Node.js filesystem error codes to user-friendly messages.

## Details

Introduced `getFsErrorMessage()` in `packages/core/src/utils/fsErrorMessages.ts` to map common Node.js filesystem error codes to user-facing messages with short remedies (and path-aware formatting where available), including:

- `EACCES` / `EPERM` with permission guidance
- `ENOENT` with path-check guidance
- `ENOSPC` with disk-space guidance
- `EISDIR` / `EROFS` with write-path guidance
- `EEXIST` / `EBUSY` with conflict/lock guidance
- `EMFILE` / `ENFILE` with open-file limit guidance

Updated call sites in `packages/cli/src/config/settings.ts`:
- `saveSettings()` now emits `Failed to save settings: ${detailedErrorMessage}`
- `saveModelChange()` now emits `Failed to save preferred model: ${detailedErrorMessage}`
- renamed local variable from `friendlyMessage` to `detailedErrorMessage` per review feedback

Tests updated:
- `packages/core/src/utils/fsErrorMessages.test.ts` now validates full remedial messages for known fs codes
- `packages/cli/src/config/settings.test.ts` updated expected error feedback string for save failure

## Related Issues

Fixes #18052

## How to Validate

1. Run tests: `npm test -w @google/gemini-cli-core -- src/utils/fsErrorMessages.test.ts`
2. Run build: `npm run build`
3. Manual test: Try saving system settings without root on Linux - should show descriptive error instead of generic message    

## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [x] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [x] Validated on required platforms/methods:
  - [x] MacOS
    - [x] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

File: packages/cli/src/config/settings.ts [hunk 1]
```diff
@@ -862,9 +864,10 @@ export function saveModelChange(
...
     loadedSettings.setValue(SettingScope.User, 'model.name', model);
   } catch (error) {
+    const friendlyMessage = getFsErrorMessage(error);
     coreEvents.emitFeedback(
       'error',
-      'There was an error saving your preferred model.',
+      `Failed to save preferred model: ${friendlyMessage}`,
       error,
     );
   }
```
[the remark this answers is not in the document]
Comment (afarber) [reply packages/cli/src/config/settings.ts:1098]: Ok, fixed

**Review by devr0306 — COMMENTED** [review]
1. **Test Duplication (Strict Rules Violation):** The new test file `packages/core/src/utils/fsErrorMessages.test.ts` is over 200 lines long and highly repetitive, with the same structure copied for EACCES, ENOENT, EPERM, etc. The "Strict Development Rules" explicitly state: "Use parameterized tests where it reduces duplicated lines. Give the parameters explicit types to ensure the tests are type-safe." Please refactor the file using `it.each()` over an array of typed test cases to cut the boilerplate by more than half.

2. **Redundant Path Formatting (Observation):** In `packages/cli/src/config/settings.ts`, the UI error uses both the file path directly and the output of getFsErrorMessage(error) (which often includes the path). This results in slightly repetitive feedback like: `Failed to save settings to '/path/to/settings.json': Permission denied: cannot access '/path/to/settings.json'` While this is robust and harmless, we could simply use `Failed to save settings: ${friendlyMessage}` to avoid stating the path twice.

**Comment by afarber** [comment]
Thank you @devr0306 - I have implemented your suggestions

File: packages/core/src/utils/fsErrorMessages.ts [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+  EPERM: (path) =>
+    path ? `Operation not permitted: '${path}'` : 'Operation not permitted',
+  EEXIST: (path) =>
+    path
+      ? `File or directory already exists: '${path}'`
+      : 'File or directory already exists',
+  EBUSY: (path) =>
+    path ? `Resource busy or locked: '${path}'` : 'Resource busy or locked',
+  EMFILE: () => 'Too many open files',
+  ENFILE: () => 'Too many open files',
```
Comment (devr0306) [inline packages/core/src/utils/fsErrorMessages.ts]: Some of these aren't checking for whether the path exists. Also, could you also include a short remedy for each of these as well?


```suggestion
 EACCES: (path) =>
    (path ? `Permission denied: cannot access '${path}'. ` : 'Permission denied. ') +
    'Check file permissions or run with elevated privileges.',
  ENOENT: (path) =>
    (path
      ? `File or directory not found: '${path}'. `
      : 'File or directory not found. ') +
    'Check if the path exists and is spelled correctly.',
  ENOSPC: () => 'No space left on device. Free up some disk space and try again.',
  EISDIR: (path) =>
    (path
      ? `Path is a directory, not a file: '${path}'. `
      : 'Path is a directory, not a file. ') +
    'Please provide a path to a file instead.',
  EROFS: () => 'Read-only file system. Ensure the file system allows write operations.',
  EPERM: (path) =>
    (path ? `Operation not permitted: '${path}'. ` : 'Operation not permitted. ') +
    'Ensure you have the required permissions for this action.',
  EEXIST: (path) =>
    (path
      ? `File or directory already exists: '${path}'. `
      : 'File or directory already exists. ') +
    'Try using a different name or path.',
  EBUSY: (path) =>
    (path ? `Resource busy or locked: '${path}'. ` : 'Resource busy or locked. ') +
    'Close any programs that might be using the file.',
  EMFILE: () => 'Too many open files. Close some unused files or applications.',
  ENFILE: () => 'Too many open files in system. Close some unused files or applications.',
```

File: packages/cli/src/config/settings.ts [hunk 3]
```diff
@@ -1072,9 +1073,10 @@ export function saveSettings(settingsFile: SettingsFile): void {
       settingsToSave as Record<string, unknown>,
     );
   } catch (error) {
+    const friendlyMessage = getFsErrorMessage(error);
```
Comment (devr0306) [inline packages/cli/src/config/settings.ts]: can we name this something like `detailedErrorMessage`

**Review by devr0306 — CHANGES_REQUESTED** [review]

**Review by devr0306 — APPROVED** [review]
LGTM!
