### PR TITLE
perf(core): fix OOM crash in long-running sessions

### LINKED ISSUE #19607: Long-running sessions crash with OOM due to structuredClone and O(n) event backlog eviction
## Description

Long-running Gemini CLI sessions (e.g., extended agentic loops with many tool calls) crash with a V8 heap exhaustion error:

```
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
```

The GC trace shows `Mark-Compact` failing at ~4GB, indicating sustained memory pressure that the garbage collector can't keep up with.

## Root Cause Analysis

After investigating the codebase, I identified several compounding memory issues in `packages/core`:

### 1. `getHistory()` deep-clones the entire conversation on every call (HIGH)

`GeminiChat.getHistory()` uses `structuredClone(history)` which creates a full deep copy of the entire conversation history. This is called on the hot path of every single turn (building the API request at `geminiChat.ts:338`), plus by loop detection, error reporting, compression, edit correction, and next-speaker checking.

In a long session with large tool outputs, this means deep-cloning 50-100MB+ of data multiple times per turn, creating massive transient allocations that stress the GC.

### 2. Event backlog uses O(n) `shift()` at capacity (MEDIUM)

`CoreEventEmitter._emitOrQueue()` uses `Array.shift()` to evict old entries when the 10K backlog is full. `shift()` on a 10K-element array is O(n) — it copies ~10K elements on every new event at capacity, creating continuous GC pressure.

### 3. `Turn.getResponseText()` recomputes on every call (LOW)

`getResponseText()` does `.map().filter().join()` over all streaming chunks each time it's called, but is invoked 2x per turn with identical results.

## Proposed Fix

1. Replace `structuredClone()` in `getHistory()` with a shallow array copy (`[...history]`). Verified all 8 production callers — only one ever mutated Content objects (`nextSpeakerChecker.ts:90`), and that mutation was dead code (pushed to a clone that was immediately discarded).

2. Replace `Array.shift()` in the event backlog with a head pointer + amortized compaction. Same FIFO semantics, same 10K cap, O(1) amortized eviction instead of O(n).

3. Cache `getResponseText()` result to avoid redundant recomputation.

All changes are behavior-preserving — same outcomes, no new APIs, no functionality changes.

## Environment

- OS: Windows 11
- Node.js: v20.x
- Gemini CLI version: 0.30.0-nightly
- Session type: Long-running agentic loop with heavy tool output

### PR DESCRIPTION
**Pull request by WizardsForgeGames**
## Summary

Fixes three compounding memory issues in `packages/core` that cause V8 heap exhaustion (`FATAL ERROR: Reached heap limit`) in long-running agentic sessions.

Fixes #19607

### 1. Replace `structuredClone()` with shallow array copy in `getHistory()`

`GeminiChat.getHistory()` was deep-cloning the entire conversation history on every call via `structuredClone()`. This is called on the hot path of every turn (building the API request), plus by loop detection, error reporting, compression, and several other callers.

In a long session with large tool outputs, this means deep-cloning 50-100MB+ of data multiple times per turn, creating massive transient allocations that compound into OOM.

Replaced with `[...history]` (shallow array copy). Audited all 8 production callers:
- 6 are purely read-only — safe with shared Content references
- `ToolOutputMaskingService.mask()` already creates its own shallow copies internally — safe
- `nextSpeakerChecker` had a dead mutation (see below) — fixed

### 2. Remove dead Content mutation in `nextSpeakerChecker.ts`

Line 90 did `lastComprehensiveMessage.parts.push({ text: '' })` on the `getHistory()` result, then immediately returned. With the old `structuredClone`, this pushed to a clone that was instantly discarded — a complete no-op. Removed the dead push so it can't accidentally mutate the real history now that `getHistory()` returns shared references.

### 3. Replace O(n) `shift()` with O(1) head pointer in event backlog

`CoreEventEmitter._emitOrQueue()` used `Array.shift()` to evict old entries when the 10K backlog was full. `shift()` on a 10K array is O(n) — copies ~10K elements on every eviction. Replaced with a head pointer that advances O(1), with amortized compaction via `slice()` when dead entries exceed half capacity. Same FIFO semantics, same 10K cap.

### 4. Cache `Turn.getResponseText()` result

`getResponseText()` recomputed `.map().filter().join()` over all streaming chunks on every call, but is invoked 2x per turn with identical input. Added a cache field so the second call is free.

## Testing

- All 208 tests across the 7 affected test files pass (geminiChat, turn, events, nextSpeakerChecker, client, toolOutputMaskingService, chatCompressionService)
- TypeScript type-check passes (`tsc --noEmit`)
- ESLint passes with 0 warnings on all changed files
- Prettier formatting verified
- `npm run preflight` lint step fails on win32/x64 due to platform-unsupported binary in `scripts/lint.js` (pre-existing, unrelated)

### CODE REVIEW

**Review by jacob314 — APPROVED** [review]
Looks great! Solid optimizations to reduce V8 heap pressure. Replaced the `unknown[]` cast with strict typing for the `_eventBacklog` array to follow strict development rules.

File: packages/core/src/utils/events.ts [hunk 1]
```diff
@@ -243,8 +244,17 @@ export class CoreEventEmitter extends EventEmitter<CoreEvents> {
     ...args: CoreEvents[K]
   ): void {
     if (this.listenerCount(event) === 0) {
-      if (this._eventBacklog.length >= CoreEventEmitter.MAX_BACKLOG_SIZE) {
-        this._eventBacklog.shift();
+      const backlogSize = this._eventBacklog.length - this._backlogHead;
```
Comment (jacob314) [inline packages/core/src/utils/events.ts:247]: this is fine but not really needed as there should not be an enormous backlog in typical cases

**Review by jacob314 — APPROVED** [review]
lgtm
