### PR TITLE
fix(cli): resolve paste issue on Windows terminals.

### LINKED ISSUE #14735: Pasting ling text with line breaks causes text loss
### What happened?

When text with newlines of line breaks is copied from the file or management software and pasted to the Gemini CLI, it appears to be split in pattern of **the first line** appearing amount of times, how many line breaks the text has and request is sent immediately, leaving the Gemini CLI input with the latest part of the pasted text(that comes after the latest line break) 

Maybe main trigger is not the line break, but bellow is video example of **pasting the text two times** that causes weird behavior 

Image

https://github.com/user-attachments/assets/600bbda6-b5db-41d8-8bd5-11a2ec5ecd8e

### What did you expect to happen?

I expected the prompt be pasted as plain text respecting line breaks and newlines as whole block

### Client information

│ About Gemini CLI  
│ CLI Version                0.19.4    
│ Git Commit               935114875     
│ Model                       pro   
│ Sandbox                   no sandbox          
│ OS                            win32  
│ Auth Method           OAuth    
│ User Email                donyhp2@gmail.com 

### Login information

Login through Google Account

### Anything else we need to know?

Pasting multiple lines did not send immediate request with malformed prompt previously(couple of weeks ago),

### PR DESCRIPTION
**Pull request by scidomino**
## Summary

Fix paste issue in windows by sensing `enter` keys that quickly follow other text (within 30 ms) into line-returns.

## Details

Some terminals don't support bracketed paste and instead just dump the entire clipboard and standard text. That leads to the pasted text before the `enter` being submitted immediately. Instead, we detect these (when bracketed paste is disabled) and convert them to line-returns.

## Related Issues

Fixes https://github.com/google-gemini/gemini-cli/issues/14735

## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [ ] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [ ] Validated on required platforms/methods:
  - [ ] MacOS
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

File: packages/cli/src/ui/AppContainer.tsx [hunk 1]
```diff
@@ -394,7 +392,7 @@ export const AppContainer = (props: AppContainerProps) => {
       disableLineWrapping();
       app.rerender();
     }
-    enableBracketedPaste();
+    terminalCapabilityManager.enableBracketedPaste();
```
Comment (jacob314) [inline packages/cli/src/ui/AppContainer.tsx]: nit: lets just switch to a single method that enables all the supported protocols we want rather than one for each.

Comment (jacob314) [reply packages/cli/src/ui/AppContainer.tsx]: otherwise we will have issues where we forget to enable and disable all of them all the times they are needed. for example right now seems like we aren't disabling bracketed paste mode when we should. 
Seems like we probably also need to be re-enabling bracketed paste mode after we launch external editors, etc.

File: packages/cli/src/ui/utils/terminalCapabilityManager.ts [hunk 2]
```diff
@@ -209,6 +218,23 @@ export class TerminalCapabilityManager {
     });
   }
 
+  enableSupportedModes() {
+    if (this.kittySupported) {
+      this.enableKittyProtocol();
```
Comment (jacob314) [inline packages/cli/src/ui/utils/terminalCapabilityManager.ts:238]: nit: add a single listener for exit and SIGTERM rather than adding identical listeners for all 3 cases.  The other existing bug here is if we call enableSupportedModes multiple times we end up with multiple listeners causing repeated calls on exit.

**Review by jacob314 — APPROVED** [review]
lgtm
