### PR TITLE
fix(client): get model from config in flashFallbackHandler

### LINKED ISSUE #2602: Rate Limiting error - cant continue
## Describe the bug
IN the middle of working the system suddenly just starts spamming this message and is unable to continue to work at all. It cant recover it just spits this out filling up the screen. 

ℹ ⚡ Rate limiting detected. Automatically switching from gemini-2.5-pro to gemini-2.5-flash for faster responses for 
  the remainder of this session.

ℹ ⚡ Rate limiting detected. Automatically switching from gemini-2.5-pro to gemini-2.5-flash for faster responses for 
  the remainder of this session.

ℹ ⚡ Rate limiting detected. Automatically switching from gemini-2.5-pro to gemini-2.5-flash for faster responses for 
  the remainder of this session.

ℹ ⚡ Rate limiting detected. Automatically switching from gemini-2.5-pro to gemini-2.5-flash for faster responses for 
  the remainder of this session.

ℹ ⚡ Rate limiting detected. Automatically switching from gemini-2.5-pro to gemini-2.5-flash for faster responses for 
  the remainder of this session.

ℹ ⚡ Rate limiting detected. Automatically switching from gemini-2.5-pro to gemini-2.5-flash for faster responses for 
  the remainder of this session.

ℹ ⚡ Rate limiting detected. Automatically switching from gemini-2.5-pro to gemini-2.5-flash for faster responses for 
  the remainder of this session.

ℹ ⚡ Rate limiting detected. Automatically switching from gemini-2.5-pro to gemini-2.5-flash for faster responses for 
  the remainder of this session.

ℹ ⚡ Rate limiting detected. Automatically switching from gemini-2.5-pro to gemini-2.5-flash for faster responses for 
  the remainder of this session.

ℹ ⚡ Rate limiting detected. Automatically switching from gemini-2.5-pro to gemini-2.5-flash for faster responses for 
  the remainder of this session.

## Additional context
Unrecoverable it just falls right back into the same mess and I can no longer use the session 

> something has gone wrong can you tell what you are supposed to be working on?

ℹ ⚡ Rate limiting detected. Automatically switching from gemini-2.5-pro to gemini-2.5-flash for faster responses for 
  the remainder of this session.

ℹ Request cancelled.

## Diagnostic Information
*   **CLI Version:** 0.1.3
*   **Git Commit:** 382486e (local modifications)
*   **Operating System:** darwin v24.1.0
*   **Sandbox Environment:** no sandbox
*   **Model Version:** gemini-2.5-flash
*   **Memory Usage:** 251.4 MB

### PR DESCRIPTION
**Pull request by SunskyXH**
## TLDR

Use `this.config.getModel()` in favor of `this.model`. The later method might get stale value.

## Dive Deeper

`GeminiClient` get currentModel from its private member in `handleFlashFallback` function. There is an issue when current model is changed in other place (e.g. `handleFlashFallback`in`geminiChat.ts`), then the `model` property is stale.
And in above situation, user will still see fallback message even if they already change to fallbackModel.

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | ❓  | ❓  | ✅  |
| npx      | ❓  | ❓  | ❓  |
| Docker   | ❓  | ❓  | ✅  |
| Podman   | ❓  | -   | -   |
| Seatbelt | ❓  | -   | -   |

## Linked issues / bugs

fixes #2602

### CODE REVIEW

File: packages/core/src/core/client.ts [hunk 1]
```diff
@@ -508,7 +508,7 @@ export class GeminiClient {
       return null;
     }
 
-    const currentModel = this.model;
+    const currentModel = this.config.getModel();
```
Comment (jacob314) [inline packages/core/src/core/client.ts:509]: there may be a bigger bug to fix. I would worry the client is still using the wrong model if this.model is not the flash model.

Note that line 526-527 is setting this.model and this.config.setModel
so it is surprising the two would get out of sync unless some other code is calling config.setModel

Comment (SunskyXH) [reply packages/core/src/core/client.ts:509]: Yeah, in this case I think it is the `handleFlashCallback` in `GeminiChat` at line 198 in `geminiChat.ts` (not `GeminiClient`) changed the `config.model`, and of course without changing the model property of client.

**Comment by SunskyXH** [comment]
Hi reviewers! Thanks for the reply!
I tweaked the code and use `this.config.getModel()` instead of using `this.model` in `GeminiClient` class, and also remove `model` property. Since this is a private property, I think it is safe to remove it beacuse we have replace all `this.model` inside `GeminiClient` class.
I think we will not face the inconsistency issue anymore.

**Review by jacob314 — COMMENTED** [review]
Thanks for tracking this down! The behavior now makes a lot of sense to me. 
I'll approve once there is a little bit of test coverage.
The ideal test coverage would probably be to add a regression test that would have failed without this change but now passes with this change. I'm also open to less ambitious tests if that is not feasible.

**Comment by SunskyXH** [comment]
> Thanks for tracking this down! The behavior now makes a lot of sense to me. I'll approve once there is a little bit of test coverage. The ideal test coverage would probably be to add a regression test that would have failed without this change but now passes with this change. I'm also open to less ambitious tests if that is not feasible.

Thanks for the reply!
I added some test cases to check if we are using the newset `model` value when config has changed. Please take a look.

**Review by jacob314 — DISMISSED** [review]
Thanks again for fixing this and adding robust tests!
lgtm

**Comment by SunskyXH** [comment]
@jacob314 @umairidris Thanks for the review! I solved the conflict so would you mind giving it another quick look when you have a sec?
And currently the workflow run is still awaiting approval. Could you please approve it so the checks can complete? Really appreciate your help!

**Comment by SunskyXH** [comment]
Hi @allenhutchison , I saw you worked on issue related with this pull request. When you have a moment, could you please give the approval for running GitHub Action CI.
And if possible, could you plsease give it a quick code review as well? It was already approved before I resolved the conflicts, so it just needs a re-review.
Thank you so much for your help!

**Review by jacob314 — DISMISSED** [review]
lgtm

**Comment by SunskyXH** [comment]
Hi @jacob314 .Thanks for your previous reviews and approvals on this PR. I've rebased my code to resolve conflicts with the current main branch, so I wish you can review the changes once more when you have a chance.
Also, I wanted to mention that after your last approval, the GitHub Actions CI didn't automatically trigger. Have you encountered this before? Could you let me know what steps I should take to get the CI running, or if there's something specific I need to do on my end?
Thanks again for your help with this!

**Review by jacob314 — APPROVED** [review]
lgtm

**Comment by jacob314** [comment]
I have to manually click to approve that workflows are run. Sorry about forgetting that last time!

**Review by NTaylorMullen — APPROVED** [review]

**Comment by SunskyXH** [comment]
@jacob314 @NTaylorMullen 
Thanks for the code review! When you have a moment, could you please help merge this? Much appreciated!
