### PR TITLE
Cleanup useSelectionList and fix infinite loop in debug mode issues.

### LINKED ISSUE #10247: Radio buttons trigger infinite loop in with DEBUG=true
### What happened?

Trigger any UI with radio buttons when DEBUG=1
Notice a constant stream of "Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render." errors.

### What did you expect to happen?

No Maximum update depth exceeded errors.
This surfaces as performance issues for the theme dialog.

This issue has not made it to the preview branch so does not need to be hotfixed if fixed today.

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
# paste output here
```

</details>

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by jacob314**
## TLDR

Unconditionally dispatching events in useEffect from useSelectionList triggers an infinite loop of updates.

## Dive Deeper

The reducer and core logic in useSelectionList never had to depend on the actual elements in the list only their keys and whether they were disabled. Refactored so that was clear making it more obvious when the update logic could be short circuited for cases where the keys and disabled state didn't change.

Some methods in the reducer also passed in the items when the items didn't change further causing confusion about what needed to be updated when.

## Reviewer Test Plan

set DEBUG=true
note the errors without this change
open the /theme dialog and other ui with radio buttons.
Verify UI is responsive and no errors are thrown.

## Linked issues / bugs

Fixes: #10247
Fixes: #10242

### CODE REVIEW

File: packages/cli/src/ui/hooks/useSelectionList.ts [hunk 1]
```diff
@@ -228,20 +244,38 @@ export function useSelectionList<T>({
...
+
+    if (baseItemsChanged || initialIndexChanged) {
+      dispatch({
+        type: 'INITIALIZE',
+        payload: { initialIndex, items: baseItems },
+      });
+      prevBaseItemsRef.current = baseItems;
+      prevInitialIndexRef.current = initialIndex;
+    }
+  });
```
Comment (abhipatel12) [inline packages/cli/src/ui/hooks/useSelectionList.ts:278]: Do we not need a dependency array?

File: packages/cli/src/ui/hooks/useSelectionList.test.ts [hunk 2]
```diff
@@ -915,6 +915,39 @@ describe('useSelectionList', () => {
...
+      // Initial render
+      expect(renderCount).toBe(1);
+
+      // Create new items with the same keys but different object references
+      const newItems = [
+        { value: 'A', key: 'A' },
+        { value: 'B', key: 'B' },
+      ];
+
+      rerender({ items: newItems });
```
Comment (abhipatel12) [inline packages/cli/src/ui/hooks/useSelectionList.test.ts:948]: Should we also assert that the current active index is also preserved (i.e user's choice is preserved)?

File: packages/cli/src/ui/hooks/useSelectionList.ts (hunk 1 above)
Comment (abhipatel12) [inline packages/cli/src/ui/hooks/useSelectionList.ts:278]: Just curious, we can omit the dependency array here?

**Review by abhipatel12 — APPROVED** [review]
LGTM with a couple of questions

File: packages/cli/src/ui/hooks/useSelectionList.ts (hunk 1 above)
Comment (jacob314) [reply packages/cli/src/ui/hooks/useSelectionList.ts:278]: because the one dep will always change each frame so there is no point.

File: packages/cli/src/ui/hooks/useSelectionList.test.ts (hunk 2 above)
Comment (jacob314) [reply packages/cli/src/ui/hooks/useSelectionList.test.ts:948]: i'd keep this test validating one thing. other tests validate that. this test isn't messing with the activeIndex so regardless of re-renders it would be the same value.

**Comment by JayadityaGit** [comment]
lgtm

**Comment by JayadityaGit** [comment]
It’s been a while since this PR was approved: https://github.com/google-gemini/gemini-cli/pull/8006

Could you guys please review the documentation update for the Custom Witty Phrases feature? I’m really eager to get this documented, and your feedback would mean a lot. Thanks! 🙏

File: packages/cli/src/ui/hooks/useSelectionList.ts (hunk 1 above)
Comment (jacob314) [reply packages/cli/src/ui/hooks/useSelectionList.ts:278]: chatted offline. because we intentionally run the useEffect after each render.
