### PR TITLE
fix(cli): list installed extensions when update target missing

### LINKED ISSUE #16820: Feature: List installed extensions when 'gemini update <name>' fails
I'm working on improving the gemini update command. Currently, if a user tries to update a non-existent extension, it just says "not found".

Proposal: Update the command to list all installed extensions when the requested extension is not found. This helps users quickly see the correct name they might have meant.

I have a fix implemented and tested locally.

### PR DESCRIPTION
**Pull request by tt-a1i**
Fixes #16820

## Summary
When `gemini extensions update <name>` can't find the requested extension, also print the list of installed extensions (or `No extensions installed.`) so the user can quickly recover.

## Test Plan
- `cd packages/cli && npx vitest run src/commands/extensions/update.test.ts`

## AI Assistance Disclosure

I used Codex to review the changes, sanity-check the implementation against existing patterns, and help spot potential edge cases.

### CODE REVIEW

**Review by iqbalbhatti49 — APPROVED** [review]

File: packages/cli/src/commands/extensions/update.ts [hunk 1]
```diff
@@ -46,7 +46,19 @@ export async function handleUpdate(args: UpdateArgs) {
         (extension) => extension.name === args.name,
       );
       if (!extension) {
-        debugLogger.log(`Extension "${args.name}" not found.`);
+        if (extensions.length === 0) {
+          debugLogger.log(
```
Comment (galdawave) [inline packages/cli/src/commands/extensions/update.ts]: We should be using coreEvents.emitFeedback for user-facing errors or warnings

**Review by galdawave — APPROVED** [review]

**Comment by tt-a1i** [comment]
fixed: switched missing-extension message to coreEvents.emitFeedback + updated tests. mind rechecking? @galz10

**Review by galdawave — APPROVED** [review]
