### PR TITLE
Fix(core): retry additional OpenSSL 3.x SSL errors during streaming (#16075)

### LINKED ISSUE #16075: Intermittent SSL error breaks streaming (SSE): ssl3_read_bytes "alert bad record mac" requires typing "continue"
### What happened?

Gemini CLI intermittently fails mid-stream during SSE generation. When it happens, the response stream stops and the session does not continue until I manually type 'continue'. After typing continue, the session usually proceeds, but it interrupts the workflow and can cause partial output.

Error observed:
`[API Error: request to https://cloudcode-pa.googleapis.com/v1internal:streamGenerateContent?alt=sse failed, reason: D84E0000:error:0A0003FC:SSL routines:ssl3_read_bytes:sslv3 alert bad record mac:c:\ws\deps\openssl\openssl\ssl\record\rec_layer_s3.c:1605:SSL alert number 20]`

This has happened across multiple sessions (intermittent). I haven’t found a fully deterministic trigger yet.

### What did you expect to happen?

The CLI should recover from transient TLS/SSE stream errors without manual intervention.

Expected behavior:
- Automatically retry the streaming request (with backoff) and resume output.
- If recovery is not possible, present an explicit retry prompt (or fail the request cleanly) without requiring the user to guess to type continue.
- The session should not appear stalled.

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
 About Gemini CLI                                                                                                                                                             │
│                                                                                                                                                                              │
│ CLI Version                                                 0.23.0                                                                                                           │
│ Git Commit                                                  3ff055840                                                                                                        │
│ Model                                                       auto-gemini-3                                                                                                    │
│ Sandbox                                                     no sandbox                                                                                                       │
│ OS                                                          win32                                                                                                            │
│ Auth Method                                                 OAuth
```

</details>

### Login information

Google Account

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by rcleveng**
## Summary

  OpenSSL 3.x changed the TLS alert reason string format, producing error code
  `ERR_SSL_SSL/TLS_ALERT_BAD_RECORD_MAC` instead of `ERR_SSL_SSLV3_ALERT_BAD_RECORD_MAC`.
  This code wasn't in the retryable error list, causing mid-stream SSL failures to surface
  to users as a stalled session requiring manual "continue" input.

  (and note that the changing in strings even is causing issues when moving to 4.0  [https://github.com/nodejs/node/pull/62410](https://github.com/nodejs/node/pull/62410))
  
  This builds on top of https://github.com/google-gemini/gemini-cli/pull/18310 and handles `ERR_SSL_SSL/TLS_ALERT_BAD_RECORD_MAC` in addition to what was there already.

  ## Changes

  ### Fixes

  - **Error code mismatch** (`packages/core/src/utils/retry.ts`): Added
    `ERR_SSL_SSL/TLS_ALERT_BAD_RECORD_MAC` (OpenSSL 3.x format) to `RETRYABLE_NETWORK_CODES`.
    Added a substring-based fallback (`isRetryableSslErrorCode`) that matches any
    `ERR_SSL*BAD_RECORD_MAC` code to handle future OpenSSL version variations without
    code changes. Node.js constructs these codes by prepending `ERR_SSL_` to the uppercased
    OpenSSL reason string (see `TLSWrap::ClearOut` in `node/src/crypto/crypto_tls.cc`),
    so the format depends on the linked OpenSSL version.

  - **Missing UI retry feedback** (`packages/cli/src/ui/hooks/useGeminiStream.ts`): The
    `ServerGeminiEventType.Retry` case had a placeholder `break;` with no user feedback.
    Now displays "Network error during streaming. Retrying..." so users know recovery is
    in progress rather than seeing a stalled session.

  ### Test updates

  - `packages/core/src/utils/retry.test.ts`: Added tests for the OpenSSL 3.x error code
    and the substring fallback matching.
  - `packages/core/src/core/geminiChat_network_retry.test.ts`: Added mid-stream retry test
    for `ERR_SSL_SSL/TLS_ALERT_BAD_RECORD_MAC`.

  ## Test Plan

  - All 40 tests in `retry.test.ts` pass
  - All 8 tests in `geminiChat_network_retry.test.ts` pass
  - Manual verification: build with `npm run bundle`, run `node bundle/gemini.js`, and
    confirm the CLI starts correctly. The SSL error is intermittent and server-side, so
    full end-to-end reproduction requires a flaky network or a mock proxy that injects
    TLS alert 20.

  Fixes https://github.com/google-gemini/gemini-cli/issues/16075

### CODE REVIEW

File: packages/core/src/utils/retry.ts [hunk 1]
```diff
@@ -53,14 +53,29 @@ const RETRYABLE_NETWORK_CODES = [
   'ENOTFOUND',
   'EAI_AGAIN',
   'ECONNREFUSED',
-  // SSL/TLS transient errors
-  'ERR_SSL_SSLV3_ALERT_BAD_RECORD_MAC',
+  // SSL/TLS transient errors. Node.js constructs these codes by prepending
```
Comment (scidomino) [inline packages/core/src/utils/retry.ts]: These aren't necessary since they're picked up by your isRetryableSslErrorCode

File: packages/core/src/utils/retry.ts [hunk 2]
```diff
@@ -53,14 +53,29 @@ const RETRYABLE_NETWORK_CODES = [
...
   'EPROTO', // Generic protocol error (often SSL-related)
 ];
 
+/**
+ * Checks if an error code looks like a retryable SSL error, even if
+ * not in the exact RETRYABLE_NETWORK_CODES list. OpenSSL version
+ * differences cause the error code format to vary (e.g. SSLV3 vs SSL/TLS).
+ */
+function isRetryableSslErrorCode(code: string): boolean {
+  const upper = code.toUpperCase();
```
Comment (scidomino) [inline packages/core/src/utils/retry.ts]: this would be more elegant as a regex:

return /^ERR_SSL_.*BAD_RECORD_MAC/i.test(code);

File: packages/core/src/utils/retry.ts [hunk 3]
```diff
@@ -53,14 +53,29 @@ const RETRYABLE_NETWORK_CODES = [
...
   'ERR_SSL_BAD_RECORD_MAC',
   'EPROTO', // Generic protocol error (often SSL-related)
 ];
 
+/**
+ * Checks if an error code looks like a retryable SSL error, even if
+ * not in the exact RETRYABLE_NETWORK_CODES list. OpenSSL version
+ * differences cause the error code format to vary (e.g. SSLV3 vs SSL/TLS).
+ */
+function isRetryableSslErrorCode(code: string): boolean {
```
Comment (scidomino) [inline packages/core/src/utils/retry.ts]: Move this: RETRYABLE_NETWORK_CODES.includes(errorCode) 

into this function.

**Review by scidomino — CHANGES_REQUESTED** [review]
>Missing UI retry feedback (packages/cli/src/ui/hooks/useGeminiStream.ts): The
ServerGeminiEventType.Retry case had a placeholder break; with no user feedback.
Now displays "Network error during streaming. Retrying..." so users know recovery is
in progress rather than seeing a stalled session.

This part of the description does not seem accurate.

File: packages/core/src/utils/retry.ts (hunk 1 above)
Comment (rcleveng) [reply packages/core/src/utils/retry.ts]: Done

File: packages/core/src/utils/retry.ts (hunk 2 above)
Comment (rcleveng) [reply packages/core/src/utils/retry.ts]: great idea - done

File: packages/core/src/utils/retry.ts (hunk 3 above)
Comment (rcleveng) [reply packages/core/src/utils/retry.ts]: done

**Comment by rcleveng** [comment]
@scidomino thanks for the review - updated based on feedback.

**Review by scidomino — APPROVED** [review]
