### PR TITLE
fix: fatal hard-crash on loop detection via unhandled AbortError

### LINKED ISSUE #20106: Bug: Fatal CLI Crash on Loop Detection via Unhandled AbortError
## What happened?
The Gemini CLI hard-crashes with a synchronous `AbortError` when the LLM generates repetitive content that triggers the internal `LoopDetectionService`. This occurs in both interactive and non-interactive (headless) modes.

The crash is caused by a synchronous call to `controller.abort()` within the streaming loop of `GeminiClient.processTurn`. The `@google/genai` SDK wraps the underlying `node-fetch` stream in a custom async iterator (`ReadableStreamToAsyncIterable`). This custom wrapper detaches its `'error'` listeners from the stream during yield suspensions (i.e., while the consuming loop is processing a chunk).

When `abort()` is called in this state, `node-fetch` synchronously emits an `'error'` event. Finding no active listeners, Node.js triggers a fatal uncaught exception. Node's native `AbortSignal` (via `EventTarget`) intercepts this throw and schedules a fatal `process.nextTick` error, which bypasses all high-level `try...catch` blocks and terminates the process (Exit Code 1).

Furthermore, this crash renders the CLI's interactive confirmation logic unreachable, as the process terminates before the `LoopDetected` event can be effectively rendered by the UI layer.

### Reproduction Steps
1. Clone the repository and install dependencies (`npm install`).
2. Run the initial build: `npm run build`.
3. Execute the following command to trigger the crash:
```bash
npm start -- -p "Repeat the following sequence exactly 50 times: la li lu le lo"
```

### Stack Trace
```
AbortError: The operation was aborted.
    at AbortController.abort (node:internal/abort_controller:507:5)
    at GeminiClient.processTurn (packages/core/src/core/client.ts)
    ...
```

## What did you expect to happen?
The application should identify the loop, yield a `LoopDetected` event to the UI, and either:
1. Stop the stream gracefully without crashing the process.
2. Allow the CLI's interactive confirmation dialog to appear, enabling the user to choose whether to continue or disable loop detection for the session.

## Client information
- **CLI Version:** 0.30.0-nightly.20260210.a2174751d
- **Platform:** Linux
- **Node.js Version:** v20.x+

## Login information
Authenticated via cached credentials (OAuth/API Key).

## Anything else we need to know?
This issue is a regression introduced in Commit `5a05fb0` ([PR #8377](https://github.com/google-gemini/gemini-cli/pull/8377)), which added the `controller.abort()` call to save tokens but omitted the necessary safeguards for the resulting signal propagation in mixed-environment dependencies.

### Related Issues
- **[Issue #10952](https://github.com/google-gemini/gemini-cli/issues/10952):** Documents the emergence of the `AbortError` crash in v0.8.1+.
- **[Issue #18028](https://github.com/google-gemini/gemini-cli/issues/18028):** Highlights the Ink UI's vulnerability to hard crashes when encountering unhandled exceptions like this one.
- **[Issue #4878](https://github.com/google-gemini/gemini-cli/issues/4878):** Confirms that the system previously handled loops gracefully in v0.1.13 without crashing.

I have identified an approach that resolves this crash by ensuring the system exits the streaming loop before any abort logic is triggered. I'll be opening a PR shortly to implement this fix and am looking forward to discussing the implementation and any potential improvements with the team there!

### PR DESCRIPTION
**Pull request by hsm207**
## Summary

This PR fixes a fatal hard-crash in the `GeminiClient` that occurs when the loop detection service identifies repetitive content and attempts to stop the stream. It resolves a synchronous `AbortError` race condition that can crash the Node.js process by bypassing high-level error handling.

## Details

The crash is caused by a race condition within the `@google/genai` SDK's async iterator when an abort is triggered during yield suspensions. To resolve this, the `GeminiClient` now immediately `break`s the streaming loop upon detection of a loop or reaching a turn limit. This ensures the system exits the unmonitored SDK state safely before any abort-related cleanup occurs.

**Key Changes:**
- **Loop Termination:** Refactored `processTurn` to immediately `break` the `for await` loop when a loop is detected.
- **Cleanup:** Removed unused `AbortController` and `linkedSignal` declarations to simplify the logic.
- **Graceful Exit:** Ensured the CLI exits with Code 0 in headless mode when a loop is detected.
- **Regression Tests:** Verified the fix using the updated regression tests in `packages/core/src/services/loopDetectionService.test.ts`.

## Related Issues

Fixes #20106.
Related to:
- [#10952](https://github.com/google-gemini/gemini-cli/issues/10952): "Reason: AbortError: The operation was aborted." (Same underlying race condition).
- [#18028](https://github.com/google-gemini/gemini-cli/issues/18028): "Prevent hard UI crashes on render errors" (Addressing the hard-crash aspect of this bug).

## How to Validate

1. Install dependencies: `npm install`
2. Perform an initial build: `npm run build`
3. Execute the reproduction command:
```bash
npm start -- -p "Repeat the following sequence exactly 50 times: la li lu le lo"
```
**Expected Result:** The loop is detected, the generation stops gracefully, and the application exits with Code 0 instead of crashing with a stack trace.

## Pre-Merge Checklist

- [x] Updated relevant documentation and README (Finalized code comments)
- [x] Added/updated tests (Verified in `loopDetectionService.test.ts`)
- [ ] Noted breaking changes (if any)
- [x] Validated on required platforms/methods:
  - [x] Linux
    - [x] npm run
    - [x] npx

### CODE REVIEW

File: packages/core/src/core/client.ts [hunk 1]
```diff
@@ -631,11 +631,26 @@ export class GeminiClient {
...
+      try {
+        controller.abort();
+      } catch (e) {
+        debugLogger.debug(
+          'Error aborting internal controller from parent signal',
+          e,
+        );
+      }
+    };
+    signal.addEventListener('abort', onAbort, { once: true });
```
[the remark this answers is not in the document]
Comment (hsm207) [reply packages/core/src/core/client.ts]: Thanks for the feedback! I've refined the implementation to ensure signal linking happens within the safety of the try-catch block and added explicit pre-abort checks to prevent any potential leaks or unhandled exceptions from the underlying SDK's custom iterator.

**Comment by hsm207** [comment]
@bdmorgan can i get some human feedback about this pr, please?

File: packages/cli/src/acp/fileSystemService.ts [hunk 2]
```diff
@@ -14,7 +14,7 @@ export class AcpFileSystemService implements FileSystemService {
   constructor(
     private readonly connection: acp.AgentSideConnection,
     private readonly sessionId: string,
-    private readonly capabilities: acp.FileSystemCapabilities,
+    private readonly capabilities: acp.FileSystemCapability,
```
Comment (scidomino) [inline packages/cli/src/acp/fileSystemService.ts]: Is this intended? how is this related to the fix?

File: packages/core/src/core/loopAbortNakedTruth.test.ts [hunk 3]
```diff
@@ -0,0 +1,43 @@
+/**
```
Comment (scidomino) [inline packages/core/src/core/loopAbortNakedTruth.test.ts]: I'm not a fan of adding a single new test file. Can this not fit into an existing test file somewhere?

File: packages/core/src/core/client.ts [hunk 4]
```diff
@@ -1237,10 +1236,8 @@ export class GeminiClient {
     boundedTurns: number,
     isInvalidStreamRetry: boolean,
     displayContent?: PartListUnion,
-    controllerToAbort?: AbortController,
+    _controllerToAbort?: AbortController,
```
Comment (scidomino) [inline packages/core/src/core/client.ts]: If the controller is no longer needed, it should not be an argument at all.

**Comment by hsm207** [comment]
@scidomino  Thanks for the review. The upstream has evolved significantly since the original PR was opened, rendering many of the previous implementation details (and related comments) obsolete. 

I have redone the fix against the latest `main`  branch. The new implementation is much simpler.

**Current Behavior:**
- **Headless:** The CLI now halts gracefully (Exit Code 0) instead of crashing when a persistent loop is detected.
- **Interactive:** The circuit-breaker prompt now functions correctly. Selecting "Keep" safely halts the turn, while "Disable" allows the model to continue (until hit by the Gemini API's recitation policy).

I've cleaned up the code and removed the unused parameters as suggested.

**Comment by scidomino** [comment]
ok. you only have two issues:

1. update the PR description since much of it is no longer accurate.
2. Fix the leftover unused variables (controller and linkedSignal). If we don't need them, don't declare them.

Make sure `npm run preflight` passes

**Comment by hsm207** [comment]
Done! addressed both points:

1. **PR Description**: Updated to accurately reflect the refactored implementation and the new technical rationale.
2. **Unused Variables**: Removed the redundant `controller` and `linkedSignal` variables in `GeminiClient`.

Verified that `npm run preflight` passes clean. Ready for another look! @scidomino

**Comment by scidomino** [comment]
You had changes to package-lock that I reverted. I will merge now. Please don't update the code as that will require rerunning the tests.

**Review by scidomino — APPROVED** [review]
