### PR TITLE
fix(mcp): clear prompt registry on refresh to prevent duplicates

### LINKED ISSUE #5294: mcp refresh command duplicates prompts
### What happened?

I am currently working on a MCP server that exposes a few prompts. The MCP server is called `speedgrapher` and implements the stdio transport.

I had initially one prompt exposed:
Image

After adding 3 more prompts (at the same time) I asked the CLI to do a refresh using `/mcp refresh`. I noticed it duplicated the `haiku` prompt with `speedgrapher_kaiku`. The other prompts were added without a prefix:
Image

I decided to refresh it again to see what happened (no code changes):

After 2nd refresh:
Image

The source code for my server is pretty simple:

```go
package main

import (
	"context"
	"fmt"
	"os"
	"os/signal"
	"syscall"

	"github.com/danicat/speedgrapher/internal/prompts"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

func main() {
	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()
	if err := run(ctx, os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(ctx context.Context, args []string) error {
	server := mcp.NewServer(
		&mcp.Implementation{Name: "speedgrapher"},
		nil,
	)
	server.AddPrompt(prompts.Haiku(), prompts.HaikuHandler)
	server.AddPrompt(prompts.Interview(), prompts.InterviewHandler)
	server.AddPrompt(prompts.Localize(), prompts.LocalizeHandler)
	server.AddPrompt(prompts.Review(), prompts.ReviewHandler)
	return server.Run(ctx, mcp.NewStdioTransport())
}
```

### What did you expect to happen?

The tool refresh the available prompts without duplicating them.

### Client information

* **CLI Version:** 0.1.15
* **Git Commit:** c45c14ee (local modifications)
* **Operating System:** darwin v22.16.0
* **Sandbox Environment:** no sandbox
* **Model Version:** gemini-2.5-pro
* **Memory Usage:** 252.9 MB

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by rmedranollamas**
## TLDR

Clear prompts too when refreshing the MCP.

## Dive deeper
The /mcp refresh command was duplicating prompts because the prompt registry was not being cleared before adding the new prompts. This change adds a clear() method to the PromptRegistry and calls it before refreshing the prompts to prevent duplicates.

## Reviewer Test Plan

Add an MCP with a prompt and /mcp refresh — it should not sit duplicate after.

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | ❓  | ❓  | ✅  |
| npx      | ❓  | ❓  | ✅  |
| Docker   | ❓  | ❓  | ❓  |
| Podman   | ❓  | -   | -   |
| Seatbelt | ❓  | -   | -   |

## Linked issues / bugs

Closes: #5294

### CODE REVIEW

File: packages/core/src/tools/tool-registry.ts [hunk 1]
```diff
@@ -163,6 +163,8 @@ export class ToolRegistry {
       }
     }
```
Comment (jacob314) [inline packages/core/src/tools/tool-registry.ts:169]: lines 159-167 and lines 186-193 are identical. Please move them to a single clear helper called in both places.

File: packages/core/src/tools/tool-registry.test.ts
Comment (jacob314) [inline packages/core/src/tools/tool-registry.test.ts:1]: please add a test that verifies the new behavior.

**Review by jacob314 — COMMENTED** [review]
Thanks for this cleanup.
Approved once there is tests to verify that behavior is correct. ideally the tests you add would fail without your change for each of thecases where we clear and succeed with it.
tests should also verify that we only clear for the specified server and not accidentally for all servers.

**Review by jacob314 — APPROVED** [review]
lgtm
Looks good. Merge when you are ready.

**Comment by rmedranollamas** [comment]
ping on this, you need to approve the workflows prior to merge.
