### PR TITLE
fix(settings): prevent j/k navigation keys from intercepting edit buffer input

### LINKED ISSUE #21746: Cannot enter 'j' or 'k' into Settings where the value is a string
### What happened?

If you try to edit a Setting (via the /settings command in the UI) like `Plan Directory` and use the letters j or k when inputting the string, it won't work. So you can't have a plan directory with the letters j or k.

### What did you expect to happen?

Instead of navigating, the edit buffer should take priority.

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
# paste output here
```

</details>

### Login information

oauth

### Anything else we need to know?

I would be delighted if someone else wants to contribute and resolve this issue. In other words, please feel free to assign yourself as soon as you can.

### PR DESCRIPTION
**Pull request by student-ankitpandit**
## Summary
Fixes the keybinding conflict in the settings edit mode where pressing 'j' or 'k' while typing in a string input field (e.g. Plan Directory) would trigger vim-style navigation instead of inserting the character into the edit buffer.

## Details
When a settings field has a string value type (e.g. Plan Directory), pressing 'j' or 'k' while in edit mode was being intercepted by the vim-style navigation handler before reaching the input buffer.

The fix adds `!key.insertable` check to both DIALOG_NAVIGATION_UP and DIALOG_NAVIGATION_DOWN handlers in edit mode, so that:

- Arrow keys (↑↓) → still navigate between settings
- Letter keys (j/k) → now correctly type into the input field

This mirrors the existing fix already in place for the search box, where the same `!key.insertable` pattern was already being used.

## Related Issues
Fixes #21746

## How to Validate
1. Run gemini-cli: `gemini`
2. Open settings: `/settings`
3. Navigate to **Plan Directory** using arrow keys
4. Press Enter to enter edit mode
5. Type a path containing 'j' or 'k' e.g. `/projects/jekyll`
6. Verify that 'j' and 'k' appear in the input field instead of triggering navigation
7. Verify that arrow keys ↑↓ still navigate correctly between settings

## Edge Case (uppercase J and K)
9. Press Enter on Plan Directory again to edit
10. Type a path containing 'J' or 'K' e.g. `/Projects/Jekyll`
11. Verify that 'J' and 'K' appear in the input field instead of triggering navigation
12. Verify that arrow keys ↑↓ still navigate correctly between settings

## Pre-Merge Checklist
- [] Updated relevant documentation and README (if needed)
- [X] Added/updated tests (if needed)
- [] Noted breaking changes (if any)
- [X] Validated on required platforms/methods:
  - [] MacOS
    - [] npm run
    - [] npx
    - [] Docker
    - [] Podman
    - [] Seatbelt
  - [] Windows
    - [] npm run
    - [] npx
    - [] Docker
  - [X] Linux
    - [X] npm run
    - [] npx
    - [] Docker

NOTE: Tested on Ubuntu (Linux) via WSL on Windows.
Fix is platform-independent as it only modifies 
keyboard event logic.

### CODE REVIEW

**Comment by psinha40898** [comment]
fyi you might be better off re applying the change on an up to date branch and force pushing b/c basesettings was refactored heavily

File: packages/cli/src/ui/components/shared/BaseSettingsDialog.tsx [hunk 1]
```diff
@@ -349,13 +354,21 @@ export function BaseSettingsDialog({
...
-      if (effectiveFocusSection === 'settings') {
-        // Up/Down navigation with wrap-around
-        if (keyMatchers[Command.DIALOG_NAVIGATION_UP](key)) {
+      if (focusSection === 'settings') {
+        // Up/Down navigation with wrap-around.
+        // Skip vim-style k/j shortcuts when search is enabled so those characters
+        // can be typed into the search box instead. Arrow keys always work.
+        if (
+          keyMatchers[Command.DIALOG_NAVIGATION_UP](key) &&
+          !(searchEnabled && key.insertable)
```
Comment (psinha40898) [inline packages/cli/src/ui/components/shared/BaseSettingsDialog.tsx]: any reason we're not using effectiveFocusSection?

**Review by psinha40898 — CHANGES_REQUESTED** [review]
IMO the cleanest solution here is to confine your change to just the inline edit buffer if possible.

After that, I think we should be using effectiveFocusSection or else your changes won't work when the UI conditionally hides the Scope menu and the user presses tab

deferring to the assigned reviewer @Adib234 from here

Good luck

File: packages/cli/src/ui/components/shared/BaseSettingsDialog.tsx [hunk 2]
```diff
@@ -350,12 +355,20 @@ export function BaseSettingsDialog({
...
       // Not in edit mode - handle navigation and actions
       if (effectiveFocusSection === 'settings') {
-        // Up/Down navigation with wrap-around
-        if (keyMatchers[Command.DIALOG_NAVIGATION_UP](key)) {
+        // Up/Down navigation with wrap-around.
+        // Skip vim-style k/j shortcuts when search is enabled so those characters
+        // can be typed into the search box instead. Arrow keys always work.
+        if (
+          keyMatchers[Command.DIALOG_NAVIGATION_UP](key) &&
+          !(searchEnabled && key.insertable)
```
Comment (psinha40898) [inline packages/cli/src/ui/components/shared/BaseSettingsDialog.tsx]: this will not pass cli ci unless you revert this change. the solution here is beyond the scope of your PR. fix edit buffer not search

Comment (student-ankitpandit) [reply packages/cli/src/ui/components/shared/BaseSettingsDialog.tsx]: Got it, I thought for search.

**Comment by psinha40898** [comment]
there's no issue. you don't need to update the branch if there are no merge conflicts detected. just add a regression test (confer with llm and use it as learning exp if u never did this before)

after that the pr should be good to go

**Review by GlatnahHapa — APPROVED** [review]

**Review by GlatnahHapa — CHANGES_REQUESTED** [review]
Update

**Review by psinha40898 — APPROVED** [review]

**Review by Adib234 — APPROVED** [review]
