### PR TITLE
fix(plan): make question type required in AskUser tool

### LINKED ISSUE #18930: Make question type required in `AskUser` tool
Today, it's optional then defaults to `Choice` - https://github.com/google-gemini/gemini-cli/blob/099aa9621c530885fd69687953f5b1fe4bf006df/packages/core/src/confirmation-bus/types.ts#L151

Remember to update telemetry in https://github.com/google-gemini/gemini-cli/blob/main/packages/core/src/tools/ask-user.ts when this change is made 

 _Originally posted by @jerop in [#18820](https://github.com/google-gemini/gemini-cli/pull/18820/changes#r2800133272)_

### PR DESCRIPTION
**Pull request by Adib234**
## Summary

This PR makes the type property required in the Question interface for the ask_user tool. Previously, this property was optional and defaulted to 'choice' in the implementation. Making it required ensures explicit intent from the model, improves type safety across the codebase, and aligns the implementation with its telemetry requirements.
## Related Issues

Fixes https://github.com/google-gemini/gemini-cli/issues/18930
## How to Validate

AskUser tool should be working as expected with the set of changes

## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [ ] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [ ] Validated on required platforms/methods:
  - [ ] MacOS
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

File: packages/core/src/confirmation-bus/types.ts [hunk 1]
```diff
@@ -147,9 +147,9 @@ export enum QuestionType {
 export interface Question {
   question: string;
   header: string;
-  /** Question type: 'choice' renders selectable options, 'text' renders free-form input, 'yesno' renders a binary Yes/No choice. Defaults to 'choice'. */
-  type?: QuestionType;
-  /** Selectable choices. REQUIRED when type='choice' or omitted. IGNORED for 'text' and 'yesno'. */
+  /** Question type: 'choice' renders selectable options, 'text' renders free-form input, 'yesno' renders a binary Yes/No choice. */
+  type: QuestionType;
```
Comment (gundermanc) [inline packages/core/src/confirmation-bus/types.ts:151]: Is the goal to change the behavior at all? If so, is it worth having a behavioral eval test that validates that the agent passes the value you expect in the target scenario?

Comment (jerop) [reply packages/core/src/confirmation-bus/types.ts:151]: Not changing behavior, just improving the interface as was discussed when adding telemetry for AskUser tool in https://github.com/google-gemini/gemini-cli/pull/18820#discussion_r2796198553

**Review by jerop — APPROVED** [review]
