### PR TITLE
Fix(noninteractive) - Add message when user uses deprecated flag

### LINKED ISSUE #11435: Add a log message about the deprecation of --prompt
Before we remove --prompt add a log message to the current release to warn people.

### PR DESCRIPTION
**Pull request by shishu314**
## TLDR

Add a warning message when users use `--prompt` flag

## Dive Deeper

No tests atm since there is just too much test pollution in the file and I could not figure out how to solve the problem. Gemini had a lot of issues as well.

## Reviewer Test Plan

Run `npm start -- --prompt="my prompt"`, see that the message is printed

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | ❓  | ❓  | ❓  |
| npx      | ❓  | ❓  | ❓  |
| Docker   | ❓  | ❓  | ❓  |
| Podman   | ❓  | -   | -   |
| Seatbelt | ❓  | -   | -   |

## Linked issues / bugs

Fixes #11435

### CODE REVIEW

File: packages/cli/src/gemini.tsx [hunk 1]
```diff
@@ -477,6 +477,11 @@ export async function main() {
       debugLogger.log('Session ID: %s', sessionId);
     }
 
+    if (process.argv.findIndex((arg) => arg === '--prompt') > -1) {
+      console.warn(
+        'Use the positional prompt instead. --prompt will be removed in a future version.',
+      );
+    }
```
[the remark this answers is not in the document]
Comment (allenhutchison) [reply packages/cli/src/gemini.tsx]: I think this is worth doing.

**Comment by allenhutchison** [comment]
I am unable to trigger this on your branch:

```
main on  ss/promptMsg [$] is 󰏗 v0.12.0-nightly.20251022.0542de95 via  v22.16.0 on ☁️  adh@google.com
❯ npm run start -- --prompt hi

> @google/gemini-cli@0.12.0-nightly.20251022.0542de95 start
> cross-env NODE_ENV=development node scripts/start.js --prompt hi

Checking build status...
Build is up-to-date.
Error during discovery for server 'google-workspace': Connection failed for 'google-workspace': MCP error -32000: Connection closed
Hello! How can I help you today?

main on  ss/promptMsg [$] is 󰏗 v0.12.0-nightly.20251022.0542de95 via  v22.16.0 on ☁️  adh@google.com took 6s
❯ npm run start -- --prompt "Hi gemini"

> @google/gemini-cli@0.12.0-nightly.20251022.0542de95 start
> cross-env NODE_ENV=development node scripts/start.js --prompt Hi gemini

Checking build status...
Build is up-to-date.
Error during discovery for server 'google-workspace': Connection failed for 'google-workspace': MCP error -32000: Connection closed
Hello! I'm ready for your first command.

main on  ss/promptMsg [$] is 󰏗 v0.12.0-nightly.20251022.0542de95 via  v22.16.0 on ☁️  adh@google.com
❯ node scripts/start.js --prompt "Hi Gemini"
Checking build status...
Build is up-to-date.
Error during discovery for server 'google-workspace': Connection failed for 'google-workspace': MCP error -32000: Connection closed
Hello! I'm ready for your first command.

main on  ss/promptMsg [$] is 󰏗 v0.12.0-nightly.20251022.0542de95 via  v22.16.0 on ☁️  adh@google.com took 5s
❯ node scripts/start.js --prompt="Hi Gemini"
Checking build status...
Build is up-to-date.
Error during discovery for server 'google-workspace': Connection failed for 'google-workspace': MCP error -32000: Connection closed
Hello! I'm ready for your first command.

main on  ss/promptMsg [$] is 󰏗 v0.12.0-nightly.20251022.0542de95 via  v22.16.0 on ☁️  adh@google.com took 5s
❯ npm start -- --prompt="hi gemini"

> @google/gemini-cli@0.12.0-nightly.20251022.0542de95 start
> cross-env NODE_ENV=development node scripts/start.js --prompt=hi gemini

Checking build status...
Build is up-to-date.
Error during discovery for server 'google-workspace': Connection failed for 'google-workspace': MCP error -32000: Connection closed
Hello! How can I help you today?
```

**Comment by shishu314** [comment]
> I am unable to trigger this on your branch:
> 
> ```
> main on  ss/promptMsg [$] is 󰏗 v0.12.0-nightly.20251022.0542de95 via  v22.16.0 on ☁️  adh@google.com
> ❯ npm run start -- --prompt hi
> 
> > @google/gemini-cli@0.12.0-nightly.20251022.0542de95 start
> > cross-env NODE_ENV=development node scripts/start.js --prompt hi
> 
> Checking build status...
> Build is up-to-date.
> Error during discovery for server 'google-workspace': Connection failed for 'google-workspace': MCP error -32000: Connection closed
> Hello! How can I help you today?
> 
> main on  ss/promptMsg [$] is 󰏗 v0.12.0-nightly.20251022.0542de95 via  v22.16.0 on ☁️  adh@google.com took 6s
> ❯ npm run start -- --prompt "Hi gemini"
> 
> > @google/gemini-cli@0.12.0-nightly.20251022.0542de95 start
> > cross-env NODE_ENV=development node scripts/start.js --prompt Hi gemini
> 
> Checking build status...
> Build is up-to-date.
> Error during discovery for server 'google-workspace': Connection failed for 'google-workspace': MCP error -32000: Connection closed
> Hello! I'm ready for your first command.
> 
> main on  ss/promptMsg [$] is 󰏗 v0.12.0-nightly.20251022.0542de95 via  v22.16.0 on ☁️  adh@google.com
> ❯ node scripts/start.js --prompt "Hi Gemini"
> Checking build status...
> Build is up-to-date.
> Error during discovery for server 'google-workspace': Connection failed for 'google-workspace': MCP error -32000: Connection closed
> Hello! I'm ready for your first command.
> 
> main on  ss/promptMsg [$] is 󰏗 v0.12.0-nightly.20251022.0542de95 via  v22.16.0 on ☁️  adh@google.com took 5s
> ❯ node scripts/start.js --prompt="Hi Gemini"
> Checking build status...
> Build is up-to-date.
> Error during discovery for server 'google-workspace': Connection failed for 'google-workspace': MCP error -32000: Connection closed
> Hello! I'm ready for your first command.
> 
> main on  ss/promptMsg [$] is 󰏗 v0.12.0-nightly.20251022.0542de95 via  v22.16.0 on ☁️  adh@google.com took 5s
> ❯ npm start -- --prompt="hi gemini"
> 
> > @google/gemini-cli@0.12.0-nightly.20251022.0542de95 start
> > cross-env NODE_ENV=development node scripts/start.js --prompt=hi gemini
> 
> Checking build status...
> Build is up-to-date.
> Error during discovery for server 'google-workspace': Connection failed for 'google-workspace': MCP error -32000: Connection closed
> Hello! How can I help you today?
> ```

We mentioned in standup that we don't want to use `console.warn` so I removed it. When you tested you were on that commit. It's fixed and ready to be tested again now.

File: packages/cli/src/nonInteractiveCli.ts [hunk 2]
```diff
@@ -130,6 +140,25 @@ export async function runNonInteractive(
...
+            type: JsonStreamEventType.MESSAGE,
+            timestamp: new Date().toISOString(),
+            role: 'assistant',
+            content: deprecateText,
+            delta: true,
+          });
+        } else if (config.getOutputFormat() === OutputFormat.JSON) {
+          const formatter = new JsonFormatter();
+          const stats = uiTelemetryService.getMetrics();
+          process.stdout.write(formatter.format(deprecateText, stats));
```
Comment (shishu314) [inline packages/cli/src/nonInteractiveCli.ts]: Not sure if we need to call JSON formatter if we're just outputting to stdout, but I do not have context on this code. Open to thoughts

**Comment by allenhutchison** [comment]
We'll need to update the e2e tests with the new output.

File: packages/cli/src/nonInteractiveCli.ts [hunk 3]
```diff
@@ -151,6 +160,21 @@ export async function runNonInteractive(
       let currentMessages: Content[] = [{ role: 'user', parts: query }];
 
       let turnCount = 0;
+      const deprecateText =
+        'Use the positional prompt instead. This flag will be removed in a future version.\n';
```
Comment (allenhutchison) [inline packages/cli/src/nonInteractiveCli.ts]: Let's make this text a little more descriptive for the user: "The --prompt (-p) flag has been deprecated and will be removed in a future version. Please use a positional argument for your prompt. See gemini --help for more information."

File: packages/cli/src/nonInteractiveCli.ts [hunk 4]
```diff
@@ -151,6 +160,21 @@ export async function runNonInteractive(
...
+        if (streamFormatter) {
+          streamFormatter.emitEvent({
+            type: JsonStreamEventType.MESSAGE,
+            timestamp: new Date().toISOString(),
+            role: 'assistant',
+            content: deprecateText,
+            delta: true,
+          });
+        } else {
+          process.stdout.write(deprecateText);
```
Comment (allenhutchison) [inline packages/cli/src/nonInteractiveCli.ts]: Would this make more sense to write to stderr?

**Review by allenhutchison — COMMENTED** [review]
Looks pretty good. A couple of questions for you.

**Review by scidomino — APPROVED** [review]
