### PR TITLE
Work around bracketed paste support for node < 20

### LINKED ISSUE #2474: Bracketed paste not working on node < 20
### What happened?

Bracketed paste mode doesn't work on node before node's readline added support for detecting the paste start/end characters.

### What did you expect to happen?

Paste should work, instead it shows blank.

### Client information

macos

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by bbiggs**
## TLDR

Prior to this commit, node did not support bracketed paste mode:

https://github.com/nodejs/node/commit/87af913b66eab78088acfd7f3b57d35e22c5f1ba

To work around this, we can detect the sequences in a handler prior to readline seeing the sequence.

## Reviewer Test Plan

Please try in as many terminals and operating systems as you can :)

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | ❓  | ❓  | ❓  |
| npx      | ❓  | ❓  | ❓  |
| Docker   | ❓  | ❓  | ❓  |
| Podman   | ❓  | -   | -   |
| Seatbelt | ❓  | -   | -   |

## Linked issues / bugs

Fixes #2474

### CODE REVIEW

File: packages/cli/src/ui/hooks/useKeypress.ts [hunk 1]
```diff
@@ -48,7 +49,20 @@ export function useKeypress(
 
     setRawMode(true);
 
-    const rl = readline.createInterface({ input: stdin });
+    const keypressStream = new PassThrough();
+    let usePassthrough = false;
+    const nodeMajorVersion = parseInt(process.versions.node.split('.')[0], 10);
+    // Example of how you might use it
```
Comment (jacob314) [inline packages/cli/src/ui/hooks/useKeypress.ts]: Nit. Remove this comment

File: packages/cli/src/ui/hooks/useKeypress.ts [hunk 2]
```diff
@@ -48,7 +49,20 @@ export function useKeypress(
...
+    if (
+      nodeMajorVersion < 20 ||
+      process.env['PASTE_WORKAROUND'] === '1' ||
+      process.env['PASTE_WORKAROUND'] === 'true'
```
Comment (jacob314) [inline packages/cli/src/ui/hooks/useKeypress.ts:58]: Nit: dupe paste workaround lines

**Review by jacob314 — DISMISSED** [review]
Thank you so much for the quick fix! Curious on your thoughts on whether we should unittest this or test with proper integration tests in the future.

File: packages/cli/src/ui/hooks/useKeypress.ts [hunk 3]
```diff
@@ -79,11 +92,79 @@ export function useKeypress(
...
+          prefixPos !== -1 && (suffixPos === -1 || prefixPos < suffixPos);
+        const isSuffixNext =
+          suffixPos !== -1 && (prefixPos === -1 || suffixPos < prefixPos);
+
+        let nextMarkerPos = -1;
+        let markerLength = 0;
+
+        if (isPrefixNext) {
+          nextMarkerPos = prefixPos;
+          markerLength = PASTE_MODE_PREFIX.length;
```
Comment (jacob314) [inline packages/cli/src/ui/hooks/useKeypress.ts]: code setting markerLength is the same in both branches

Comment (bbiggs) [reply packages/cli/src/ui/hooks/useKeypress.ts]: fixed

File: packages/cli/src/ui/hooks/useKeypress.ts (hunk 1 above)
Comment (bbiggs) [reply packages/cli/src/ui/hooks/useKeypress.ts]: fixed

**Review by jacob314 — DISMISSED** [review]
lgtm
Can you add a basic test?
I'm a little worried about some of the edge cases like PASTE_MODE_SUFFIX getting split across a couple of data buffer blocks resulting in the user being stuck in paste mode forever but I think it is generally alright given we are warning users that they should use node 20+

File: packages/cli/src/ui/hooks/useKeypress.ts [hunk 4]
```diff
@@ -79,11 +92,79 @@ export function useKeypress(
...
+          sequence: '',
+        });
+        if (isPrefixNext) {
+          handleKeypress(undefined, createPasteKeyEvent('paste-start'));
+        } else if (isSuffixNext) {
+          handleKeypress(undefined, createPasteKeyEvent('paste-end'));
+        }
+        pos = nextMarkerPos + markerLength;
+      }
+    };
```
[the remark this answers is not in the document]
Comment (jacob314) [reply packages/cli/src/ui/hooks/useKeypress.ts]: this is correct but likely acceptable given the limited degree we are trying to support node 18.

**Review by jacob314 — APPROVED** [review]
lgtm

**Review by NTaylorMullen — APPROVED** [review]
