### PR TITLE
fix(plan): allowlist get_internal_docs in Plan Mode

### LINKED ISSUE #22374: cli_help agent is not able to access get_internal_docs tool in Plan mode
### What happened?

While using gemini-cli in Plan mode and asking questions about the CLI itself, the cli_help agent is not able to use the get_internal_docs tool.

### What did you expect to happen?

Since cli_help is enabled by default in Plan mode, and get_internal_docs is a read-only tool, the agent should be able to use the tool in Plan mode.

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about

```
│ About Gemini CLI                                                                                                                                                                                                                          
│ CLI Version                                                                       0.33.1                                                                                                                                                  
│ Git Commit                                                                        f59f9e931                                                                                                                                               
│ Model                                                                             Auto (Gemini 3)                                                                                                                                         
│ Sandbox                                                                           no sandbox                                                                                                                                              
│ OS                                                                                linux                                                                                                                                                   
│ Auth Method                                                                       Logged in with Google (---)                                                                                                   
│ Tier                                                                              Gemini Code Assist                                                                                                                                      
│ GCP Project                                                                       ---     
</details>

### Login information

Google Account

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by Adib234**
## Summary

This PR allowlists the `get_internal_docs` tool in Plan Mode. This tool was previously blocked by the default Plan Mode policy, preventing the `cli_help` agent from accessing documentation to answer user questions while in research phases.

## Details

- Added `get_internal_docs` to the explicitly allowed tools in `packages/core/src/policy/policies/plan.toml` with priority 70.
- Added `get_internal_docs` to the `read-only.toml` policy to ensure it's automatically allowed across all modes.
- Included `get_internal_docs` in the `PLAN_MODE_TOOLS` list in `packages/core/src/tools/tool-names.ts` for consistent metadata and prompting.
- Updated integration tests in `packages/cli/src/config/policy-engine.integration.test.ts` to verify that `get_internal_docs` and `cli_help` are allowed in Plan Mode.

## Related Issues

Fixes #22374

## How to Validate

1. Run Gemini CLI.
2. Enter Plan Mode: `enter_plan_mode(reason="testing cli_help")`.
3. Ask a question about the CLI (e.g., "What tools are available?") which triggers the `cli_help` agent.
4. Verify that the agent successfully uses `get_internal_docs` to answer without being blocked or prompted.

Alternatively, run the updated integration tests:
`npm test -w @google/gemini-cli -- src/config/policy-engine.integration.test.ts`

## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [x] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [x] Validated on required platforms/methods:
  - [x] MacOS
    - [x] npm run

### CODE REVIEW

File: packages/core/src/tools/tool-names.ts [hunk 1]
```diff
@@ -266,6 +266,7 @@ export const PLAN_MODE_TOOLS = [
   WEB_SEARCH_TOOL_NAME,
   ASK_USER_TOOL_NAME,
   ACTIVATE_SKILL_TOOL_NAME,
+  GET_INTERNAL_DOCS_TOOL_NAME,
```
Comment (jerop) [inline packages/core/src/tools/tool-names.ts:269]: just noticed that the subagent tool names are not on this list...

**Review by jerop — COMMENTED** [review]
pls update the docs: https://geminicli.com/docs/cli/plan-mode/#tool-restrictions

File: packages/core/src/tools/tool-names.ts (hunk 1 above)
Comment (Adib234) [reply packages/core/src/tools/tool-names.ts:269]: Added subagent tool names

File: packages/core/src/tools/tool-names.ts [hunk 2]
```diff
@@ -266,6 +266,9 @@ export const PLAN_MODE_TOOLS = [
...
+  'codebase_investigator',
+  'cli_help',
```
Comment (jerop) [inline packages/core/src/tools/tool-names.ts:271]: are there constants for these that we can use, like the other ones?

**Review by jerop — APPROVED** [review]

File: packages/core/src/tools/tool-names.ts (hunk 2 above)
Comment (Adib234) [reply packages/core/src/tools/tool-names.ts:271]: there doesn't seem to be in base-declaration.ts, but I can add if needed

Comment (jerop) [reply packages/core/src/tools/tool-names.ts:271]: it's ok if it doesn't exist, can be cleaned up later -- @abhipatel12 @joshualitt would be great to refactor references to these built-in subagents into consts
