### PR TITLE
fix: update google/genai to v1.9.0 and switch to parametersJsonSchema for MCP related tools

### LINKED ISSUE #1481: MCP servers fail to start with TypeError: fieldValue.toUpperCase is not a function
**Describe the bug**
Some MCP servers (including the older Notion MCP server https://github.com/makenotion/notion-mcp-server) fail to load with `TypeError: fieldValue.toUpperCase is not a function`. I'm assuming this is an issue in the CLI as the config for these servers work on other MCP clients.

**Client information**
Please paste the full text from the /about command run from Gemini CLI. Also include which platform (MacOS, Windows, Linux)
Platform - MacOS (Apple Silicon)
```

╭──────────────────────────────────────────────────────────────╮
│                                                              │
│ About Gemini CLI                                             │
│                                                              │
│ CLI Version          0.1.1                                   │
│ Git Commit           852210e1 (local modifications)          │
│ Model                gemini-2.5-pro                          │
│ Sandbox              no sandbox                              │
│ OS                   darwin                                  │
│                                                              │
╰──────────────────────────────────────────────────────────────╯

```

### LINKED ISSUE #4301: inputSchema of MCP tool is dropped due to mistake in property name
### What happened?

When `gemini-cli` is discovering MCP tools, MCP server will give back `inputSchema` object as part of [MCP tool structure](https://modelcontextprotocol.io/docs/concepts/tools#tool-definition-structure)

`gemini-cli` then uses [`@google/genai`](https://github.com/googleapis/js-genai) module to parse MCP tool structure.

In particular,

```ts
export function mcpToGeminiTool(
  mcpTool: McpTool,
  config: types.CallableToolConfig = {},
): types.Tool {
  const mcpToolSchema = mcpTool as Record<string, unknown>;
  const functionDeclaration: Record<string, unknown> = {
    name: mcpToolSchema['name'],
    description: mcpToolSchema['description'],
    parametersJsonSchema: mcpToolSchema['inputSchema'],
  };
  if (config.behavior) {
    functionDeclaration['behavior'] = config.behavior;
  }

  const geminiTool = {
    functionDeclarations: [
      functionDeclaration as unknown as types.FunctionDeclaration,
    ],
  };

  return geminiTool;
}
```

from https://github.com/googleapis/js-genai/blob/5337cff2bb9225382c62d1278b14cb25ebaacb68/src/_transformers.ts#L724-L745
shows that `inputSchema` is mapped to `parametersJsonSchema` in the items of `functionDeclarations`.

However, when `gemini-cli` is accessing item of `functionDeclarations`, it tries to access `.parameters` instead. This can be see below:

```js
    for (const funcDecl of tool.functionDeclarations) {
      if (!isEnabled(funcDecl, mcpServerName, mcpServerConfig)) {
        continue;
      }

      const toolNameForModel = generateValidName(funcDecl, mcpServerName);

      sanitizeParameters(funcDecl.parameters);

      discoveredTools.push(
        new DiscoveredMCPTool(
          mcpCallableTool,
          mcpServerName,
          toolNameForModel,
          funcDecl.description ?? '',
          funcDecl.parameters ?? { type: Type.OBJECT, properties: {} },
          funcDecl.name!,
          mcpServerConfig.timeout ?? MCP_DEFAULT_TIMEOUT_MSEC,
          mcpServerConfig.trust,
        ),
      );
    }
```

from https://github.com/google-gemini/gemini-cli/blob/cba272082d15a6b9fb4e21bc27ed1d56fa5b9a56/packages/core/src/tools/mcp-client.ts#L271-L292

Because `.parameters` doesn't exists, it defaulted to empty object.

This will result in `gemini-cli` having no information on how to set input value for MCP tool.

The problem can also be confirmed by asking `gemini-cli` to explain what it knows about input schema of connected MCP tool. An example response from `gemini-cli` effected by this bug is like this:

```
  Based on the tool definitions I have access to, I believe I have found the root cause. The definition for the loader_set function that I am working with is malformed.
  Here is the exact definition I have in my context:


   1 def loader_set(
   2     loader_config: ,
   3 ) -> dict:
   4   """Specify source of data to be processed.
   5   ...
   6   """



  As you can see, the type annotation for the loader_config parameter is completely missing. It's just a comma. Without the schema for loader_config, I have no information
   about the structure of the object I need to create and pass to the tool. I don't know what fields, nested objects, or data types it requires. This is why I have been
  unable to use the tool correctly.
```

### What did you expect to happen?

`gemini-cli` should be able to

- get input schema of MCP tool,
- explain what the input schema for that tool is,
- and use that infomation to call tool correctly.

### Client information

<details>

```
About Gemini CLI

CLI Version               0.1.5
Git Commit                bf873a1
Model                     gemini-2.5-flash
Sandbox                   no sandbox
OS                        linux
```

</details>

### Login information

Logged in with Google Account. Free tier.

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by wanlin31**
## TLDR

google/genai v1.9.0 had introduced a behavior change:
- Before: `parameters` field from the returns of McpTool.
- After:  populating `parametersJsonSchema`

The goal of this change is only to move MCP related tool path to use the `parametersJsonSchema`, will leave all other FunctionDeclaration as it is,.

## Dive Deeper

## Reviewer Test Plan

<!-- when a person reviews your code they should ideally be pulling and running that code. How would they validate your change works and if relevant what are some good classes of example prompts and ways they can exercise your changes -->

Test steps:

```
npm pack 
RELEASE_TARBALL=$(pwd)/google-gemini-cli-0.1.12.tgz
ls -lh $RELEASE_TARBALL
npm install $RELEASE_TARBALL
./node_modules/.bin/gemini
```

The config I used to test the local build:
```
{
  "selectedAuthType": "gemini-api-key",
  "theme": "Dracula",
  "mcpServers": {
    "context7": {
      "command": "npx",
      "args": ["-y", "@upstash/context7-mcp"]
    },
    "git": {
      "command": "uvx",
      "args": [
        "mcp-server-git",
        "--repository",
        "/usr/local/google/home/wanlindu/gemini_cli_test"
      ]
    },
    "playwright": {
      "command": "npx",
      "args": ["@playwright/mcp@latest"]
    },
    "sequential-thinking": {
      "command": "npx",
      "args": ["-y","@modelcontextprotocol/server-sequential-thinking"]
    },
    "memory": {
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-memory"]
    },
    "time": {
      "command": "uvx",
      "args": ["mcp-server-time"]
    },
    "everything": {
      "command": "npx",
      "args": [
        "-y",
        "@modelcontextprotocol/server-everything"
      ]
    }
  },
  "preferredEditor": "nano"
}

```

All tool are ready:
```
 Configured MCP servers:

  🟢 context7 - Ready (2 tools)
    - context7__get-library-docs
    - context7__resolve-library-id

  🟢 git - Ready (13 tools)
    - git__git_add
    - git__git_branch
    - git__git_checkout
    - git__git_commit
    - git__git_create_branch
    - git__git_diff
    - git__git_diff_staged
    - git__git_diff_unstaged
    - git__git_init
    - git__git_log
    - git__git_reset
    - git__git_show
    - git__git_status

  🟢 playwright - Ready (25 tools)
    - playwright__browser_click
    - playwright__browser_close
    - playwright__browser_console_messages
    - playwright__browser_drag
    - playwright__browser_file_upload
    - playwright__browser_generate_playwright_test
    - playwright__browser_handle_dialog
    - playwright__browser_hover
    - playwright__browser_install
    - playwright__browser_navigate
    - playwright__browser_navigate_back
    - playwright__browser_navigate_forward
    - playwright__browser_network_requests
    - playwright__browser_pdf_save
    - playwright__browser_press_key
    - playwright__browser_resize
    - playwright__browser_select_option
    - playwright__browser_snapshot
    - playwright__browser_tab_close
    - playwright__browser_tab_list
    - playwright__browser_tab_new
    - playwright__browser_tab_select
    - playwright__browser_take_screenshot
    - playwright__browser_type
    - playwright__browser_wait_for

  🟢 sequential-thinking - Ready (1 tools)
    - sequential-thinking__sequentialthinking

  🟢 memory - Ready (9 tools)
    - memory__add_observations
    - memory__create_entities
    - memory__create_relations
    - memory__delete_entities
    - memory__delete_observations
    - memory__delete_relations
    - memory__open_nodes
    - memory__read_graph
    - memory__search_nodes

  🟢 time - Ready (2 tools)
    - time__convert_time
    - time__get_current_time

  🟢 everything - Ready (8 tools)
    - everything__add
    - everything__annotatedMessage
    - everything__echo
    - everything__getResourceReference
    - everything__getTinyImage
    - everything__longRunningOperation
    - everything__printEnv
    - everything__sampleLLM
   ```

Was able to conduct FunctionCalls using sequentialthinking and add(everything), seems like all tool calls are successful.
```
                                                                                                                                                                                                                                                   │
│  Agent powering down. Goodbye!                                                                                                                                                                                                                    │
│                                                                                                                                                                                                                                                   │
│  Interaction Summary                                                                                                                                                                                                                              │
│  Tool Calls:                 11 ( ✔ 11 ✖ 0 )                                                                                                                                                                                                      │
│  Success Rate:               100.0%                                                                                                                                                                                                               │
│  User Agreement:             100.0% (4 reviewed)                                                                                                                                                                                                  │
│                                                                                                                                                                                                                                                   │
│  Performance                                                                                                                                                                                                                                      │
│  Wall Time:                  9m 24s                                                                                                                                                                                                               │
│  Agent Active:               2m 19s                                                                                                                                                                                                               │
│    » API Time:               1m 56s (83.4%)                                                                                                                                                                                                       │
│    » Tool Time:              23.2s (16.6%)                                                                                                                                                                                                        │
│                                                                                                                                                                                                                                                   │
│                                                                                                                                                                                                                                                   │
│  Model Usage                  Reqs   Input Tokens  Output Tokens                                                                                                                                                                                  │
│  ───────────────────────────────────────────────────────────────                                                                                                                                                                                  │
│  gemini-2.5-pro                 15        234,591          5,278                                                                                                                                                                                  │
│                                                                                                                                                                                                                                                   │
│  Savings Highlight: 171,665 (73.2%) of input tokens were served from the cache, reducing costs.                                                                                                                                                   │
│                                                                                                                                                                                                                                                   │
│  » Tip: For a full token breakdown, run `/stats model`.                                                                                                                                                                                           │
│
```

## Testing Matrix

<!-- Before submitting please validate your changes on as many of these options as possible -->

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | ❓  | ❓  |  ✅   |
| npx      | ❓  | ❓  | ❓  |
| Docker   | ❓  | ❓  | ❓  |
| Podman   | ❓  | -   | -   |
| Seatbelt | ❓  | -   | -   |

## Linked issues / bugs

Fixes #4301 
Fixes #1481

### CODE REVIEW

File: packages/core/src/tools/mcp-client.ts [hunk 1]
```diff
@@ -261,15 +261,13 @@ export async function discoverTools(
...
-      sanitizeParameters(funcDecl.parameters);
-
       discoveredTools.push(
         new DiscoveredMCPTool(
           mcpCallableTool,
           mcpServerName,
           toolNameForModel,
           funcDecl.description ?? '',
-          funcDecl.parameters ?? { type: Type.OBJECT, properties: {} },
+          funcDecl.parametersJsonSchema ?? { type: 'object', properties: {} },
```
[the remark this answers is not in the document]
Comment (wanlin31) [reply packages/core/src/tools/mcp-client.ts:285]: Updated

**Comment by iwakitakuma33** [comment]
@wanlin31 

related issue https://github.com/google-gemini/gemini-cli/issues/1481

Many users are unable to use mcp via gemini cli in this issue. Once you upgrade genai to version 1.9.0, the error on the genai side when using mcp will be resolved and you will be able to use mcp.

**Comment by iwakitakuma33** [comment]
@wanlin31 
Will this be released soon?

Does upgrading only v1.9.0 affect other features?

related issue closed. https://github.com/google-gemini/gemini-cli/pull/4196



I will close [PR](https://github.com/google-gemini/gemini-cli/pull/4253) if this PR is addressed.

File: packages/core/src/tools/mcp-tool.ts [hunk 2]
```diff
@@ -32,10 +39,22 @@ export class DiscoveredMCPTool extends BaseTool<ToolParams, ToolResult> {
       name,
       `${serverToolName} (${serverName} MCP Server)`,
       description,
-      parameterSchema,
+      { type: Type.OBJECT }, // this is a dummy Schema for MCP, will be removed when construct the FunctionDeclaration
```
Comment (wanlin31) [inline packages/core/src/tools/mcp-tool.ts]: We either give it a dummy Schema to make the BaseTool constructor happy or we need to change BaseTool constructor's API to allow us not setting the parameterSchema. I feel this way is less impact on Gemini_cli, but open to other ideas.

File: packages/core/src/tools/tools.ts [hunk 3]
```diff
@@ -97,7 +97,7 @@ export abstract class BaseTool<
    * @param description Description of what the tool does
    * @param isOutputMarkdown Whether the tool's output should be rendered as markdown
    * @param canUpdateOutput Whether the tool supports live (streaming) output
-   * @param parameterSchema JSON Schema defining the parameters
+   * @param parameterSchema Open API 3.0 Schema defining the parameters
```
Comment (wanlin31) [inline packages/core/src/tools/tools.ts:100]: I think parameterSchema has a Schema type, which is a subset of openAPI v3.0.3 https://spec.openapis.org/oas/v3.0.3#schema. I am also open to leave it as it is.

File: packages/cli/src/ui/commands/mcpCommand.ts [hunk 4]
```diff
@@ -170,11 +170,13 @@ const getMcpStatus = async (
           // Use cyan color for the tool name even when not showing descriptions
           message += `  - ${COLOR_CYAN}${tool.name}${RESET_COLOR}\n`;
         }
-        if (showSchema && tool.parameterSchema) {
+        const parameters =
```
Comment (wanlin31) [inline packages/cli/src/ui/commands/mcpCommand.ts:173]: schema is a BaseTool property ([ref](https://github.com/google-gemini/gemini-cli/blob/f4cd0055fd7fcb86bc7dddfd72aa8c6ed78a923e/packages/core/src/tools/tools.ts#L34)) and it can be populated differently, may be more stable than parameterSchema ([ref](https://github.com/google-gemini/gemini-cli/blob/f4cd0055fd7fcb86bc7dddfd72aa8c6ed78a923e/packages/core/src/tools/tools.ts#L100)), which is a transient value to populated the schema field.

File: packages/core/src/tools/mcp-client.ts [hunk 5]
```diff
@@ -275,15 +276,13 @@ export async function discoverTools(
 
       const toolNameForModel = generateValidName(funcDecl, mcpServerName);
 
-      sanitizeParameters(funcDecl.parameters);
-
       discoveredTools.push(
         new DiscoveredMCPTool(
```
Comment (wanlin31) [inline packages/core/src/tools/mcp-client.ts:280]: This is change that was introduced by v1.9.0, instead of populating the `parameters`, now populating `parametersJsonSchema`, this require changes in DiscoveredMCPTool class to adapt.

**Review by NTaylorMullen — APPROVED** [review]
