### PR TITLE
fix: optimize height calculations for ask_user dialog

### LINKED ISSUE #18907: Enable long plans to use the space available
When not in alternate buffer mode, users have to type `Ctrl+O` to expand a plan even though terminal had enough height to show it

### PR DESCRIPTION
**Pull request by jackwotherspoon**
## Summary

Fixes "ghost space" in the `ask_user` and `exit_plan_mode` dialogs by optimizing terminal height calculations. This change reclaims approximately 8 lines of vertical space that were previously being redundantly subtracted, allowing for more visible content in interactive prompts.

 ## Details

   The investigation revealed that height was being over-subtracted in two layers:
   1.  **ToolConfirmationQueue**: Previously subtracted 6 lines for overhead. Since `ask_user` hides the "Tool Identity" section, it now correctly only subtracts 4  lines, giving 2 lines back.
   2.  **ToolConfirmationMessage**: Previously subtracted ~6 lines for elements (question prompt, radio options) that it *assumes* it will render. Since `ask_user` handles its own UI, these subtractions were redundant and have been removed for tools that manage their own layout.

   ## Related Issues

Related to https://github.com/google-gemini/gemini-cli/issues/18907

   ## How to Validate

   1. Run any tool that triggers an `ask_user` dialog (e.g., a prompt that requires clarification).
   2. Observe that the dialog utilizes more of the available terminal height.
   3. Verify that truncation logic (scroll arrows or "lines hidden" messages) correctly adapts to the increased space.
   4. Run the UI tests to ensure snapshot consistency:
      `npm test -w @google/gemini-cli -- src/ui/components/ToolConfirmationQueue.test.tsx`

   ## Pre-Merge Checklist

   - [x] Updated relevant documentation and README (if needed)
   - [x] Added/updated tests (if needed)
   - [ ] Noted breaking changes (if any)
   - [x] Validated on MacOS

### CODE REVIEW

File: packages/cli/src/ui/components/ToolConfirmationQueue.tsx [hunk 1]
```diff
@@ -60,22 +60,22 @@ export const ToolConfirmationQueue: React.FC<ToolConfirmationQueueProps> = ({
       ? Math.max(uiAvailableHeight - 1, 4)
       : Math.floor(terminalHeight * 0.5);
 
+  const isRoutine =
```
Comment (jacob314) [inline packages/cli/src/ui/components/ToolConfirmationQueue.tsx:63]: should this file just be reverted? The changes seem like they are just file churn for no reason.

**Review by jacob314 — APPROVED** [review]

File: packages/cli/src/ui/components/ToolConfirmationQueue.tsx (hunk 1 above)
Comment (jackwotherspoon) [reply packages/cli/src/ui/components/ToolConfirmationQueue.tsx:63]: had to move declaration of `hideTooldentity` above `availableContentHeight` since I am now using it in below

**Review by jacob314 — APPROVED** [review]
lgtm
