### PR TITLE
fix(cli): Add delimiter before printing tool response in non-interactive mode

### LINKED ISSUE #9048: No delimiter between outputs in non-interactive mode
### What happened?

When I run `gemini -p "..."` and it involves more than one step it  just keeps writing outputs without separating them with newlines and tool calls if they a used not show in any way.

### What did you expect to happen?

I expect it to put some delimeters, i.e. double newline, between output parts. 

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
╭──────────────────────────────────────────────────────────────────────────────╮
│                                                                              │
│ About Gemini CLI                                                             │
│                                                                              │
│ CLI Version                0.6.0-preview.4                                   │
│ Git Commit                 85409d73                                          │
│ Model                      gemini-2.5-pro                                    │
│ Sandbox                    no sandbox                                        │
│ OS                         linux                                             │
│ Auth Method                OAuth                                             │
│ GCP Project                wired-benefit-470703-b6                           │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯
```

</details>

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by krishna-kb**
## TLDR

This pull request fixes #9048 by adding a newline delimiter between outputs in non-interactive mode. This improves readability for multi-step sessions involving tool calls. A new unit test has been added to verify the correct spacing between consecutive tool call turns.

## Dive Deeper

The core change is a single line in
packages/cli/src/nonInteractiveCli.ts that writes a newline to stdout
after the tool execution loop finishes for a given turn.
Initially, I settled on a single newline (\n) for a cleaner, more standard command-line experience
that avoids excessive whitespace.

The bulk of the work was in ensuring this was properly tested. I added
 a new unit test in packages/cli/src/nonInteractiveCli.test.ts (should
 write a newline between multiple tool call turns) that simulates a
multi-turn conversation with two consecutive tool calls before a final
 text response. It asserts that a newline is printed after each tool
turn.

## Reviewer Test Plan
To manually validate the change, you can run a prompt in non-interactive mode 
that forces a tool call. A good example is using a command that requires 
listing files.
Example Prompt:
`gemini -p "List the files in the 'packages/cli/src' directory and then tell me 
what the 'runNonInteractive' function does."`

Before this change, the output would look something like this, with the final answer immediately following the tool output:
```
[...tool output...]Final answer is...
```

After this change, you should see a clean separation:
```
[...tool output...]

Final answer is...
```

This confirms the delimiter is being added correctly between the tool turn and the final text response turn.

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | ❓  | ❓  | ❓  |
| npx      | ❓  | ❓  | ❓  |
| Docker   | ❓  | ❓  | ❓  |
| Podman   | ❓  | -   | -   |
| Seatbelt | ❓  | -   | -   |

### CODE REVIEW

File: packages/cli/src/nonInteractiveCli.ts [hunk 1]
```diff
@@ -198,6 +198,9 @@ export async function runNonInteractive(
         }
 
         if (toolCallRequests.length > 0) {
+          if (config.getOutputFormat() !== OutputFormat.JSON) {
+            process.stdout.write('\n');
+          }
```
[the remark this answers is not in the document]
Comment (krishna-kb) [reply packages/cli/src/nonInteractiveCli.ts]: There is a text response before the tool response is printed. If we move it to afterwards, the bug would still exist.
I think the description might be unclear, will update the same.

File: packages/cli/src/nonInteractiveCli.ts [hunk 2]
```diff
@@ -198,6 +198,9 @@ export async function runNonInteractive(
         }
 
         if (toolCallRequests.length > 0) {
+          if (config.getOutputFormat() !== OutputFormat.JSON) {
```
Comment (jacob314) [inline packages/cli/src/nonInteractiveCli.ts]: I think it would be more robust if tracked the blocks of output we are writing and ensured that there are line breaks between the blocks.  As is, how do we ensure we don't add an un-needed line break before the very first output for example?

File: packages/cli/src/nonInteractiveCli.test.ts [hunk 3]
```diff
@@ -262,6 +262,86 @@ describe('runNonInteractive', () => {
...
+      mockConfig,
+      mockSettings,
+      'Use multiple tools',
+      'prompt-id-multi',
+    );
+
+    // Verify that sendMessageStream was called three times
+    expect(mockGeminiClient.sendMessageStream).toHaveBeenCalledTimes(3);
+
+    // Count how many times the newline was written
```
Comment (jacob314) [inline packages/cli/src/nonInteractiveCli.test.ts]: need tests that verify exactly the output rendered rather than just the number of newlines. otherwise the newlines might be in odd places.

**Review by jacob314 — COMMENTED** [review]
Looks promising. Added some comments on how to do this in a more robust way,.

File: packages/cli/src/nonInteractiveCli.test.ts (hunk 3 above)
Comment (krishna-kb) [reply packages/cli/src/nonInteractiveCli.test.ts]: Agreed. Updated the test to check for the exact response containing newlines combined with mock tool responses.

File: packages/cli/src/ui/utils/textOutput.ts [hunk 4]
```diff
@@ -0,0 +1,49 @@
+/**
+ * @license
+ * Copyright 2025 Google LLC
+ * SPDX-License-Identifier: Apache-2.0
+ */
+
+// Internal state for the singleton
+let lastChar = '\n';
```
Comment (jacob314) [inline packages/cli/src/ui/utils/textOutput.ts]: nit: change this to 
bool 
atStartOfLine or column. Having this be '\n' to start is otherwise misleading.

File: packages/cli/src/ui/utils/textOutput.ts [hunk 5]
```diff
@@ -0,0 +1,49 @@
...
+export const textOutput = {
+  /**
+   * Writes a string to stdout.
+   * @param str The string to write.
+   */
+  write(str: string): void {
+    if (str.length === 0) {
+      return;
+    }
+    process.stdout.write(str);
```
Comment (jacob314) [inline packages/cli/src/ui/utils/textOutput.ts:25]: nit: strip ascii escape codes here when determining whether we are still on the start of the line. There are other parts of the code base where we strip that you can find where we do this.

File: packages/cli/src/ui/utils/textOutput.ts [hunk 6]
```diff
@@ -0,0 +1,49 @@
...
+  },
+
+  /**
+   * Writes a string to stdout, ensuring it starts on a new line.
+   * If the previous output did not end with a newline, one will be added.
+   * This prevents adding extra blank lines if a newline already exists.
+   * If no string is provided, it just ensures the output ends with a newline.
+   * @param str The optional string to write.
+   */
+  writeOnNewLine(str?: string): void {
```
Comment (jacob314) [inline packages/cli/src/ui/utils/textOutput.ts]: why is string nullable? would simplify and require the string. why do we need to write when we might not have something to write?

File: packages/cli/src/ui/utils/textOutput.ts [hunk 7]
```diff
@@ -0,0 +1,49 @@
...
+    if (lastChar !== '\n') {
+      this.write('\n');
+    }
+    if (str !== undefined) {
+      this.write(str);
+    }
+  },
+
+  /**
```
Comment (jacob314) [inline packages/cli/src/ui/utils/textOutput.ts:45]: if this wasn't a singleton you wouldn't have this issue testing. I would make this an instance so you can test easily. Given you are only using this in nonInteractiveCli there is no need to have it be a singleton. you can always pass it around or change it to a singleton later if that is needed.

File: packages/cli/src/nonInteractiveCli.ts [hunk 8]
```diff
@@ -199,6 +201,7 @@ export async function runNonInteractive(
         }
 
         if (toolCallRequests.length > 0) {
+          textOutput.writeOnNewLine();
```
Comment (jacob314) [inline packages/cli/src/nonInteractiveCli.ts]: nit: rather than making this a bare call, make the actual output of the toolCallRequests that occurs a bit later do the actual writeOnNewLine

File: packages/cli/src/ui/utils/textOutput.test.ts [hunk 9]
```diff
@@ -0,0 +1,77 @@
...
+
+  it('write() should not call process.stdout.write for empty strings', () => {
+    textOutput.write('');
+    expect(stdoutSpy).not.toHaveBeenCalled();
+  });
+
+  it('writeOnNewLine() should not add a newline if the last char was a newline', () => {
+    // Default state starts with a newline
+    textOutput.writeOnNewLine('hello');
+    expect(stdoutSpy).toHaveBeenCalledWith('hello');
```
Comment (jacob314) [inline packages/cli/src/ui/utils/textOutput.test.ts]: for these tests the easiest way is to just check that the final output to the fae stdout matches an expected snapshot. that is simpler for people to verify the output in the tests. See examples in the codebase of that.

**Review by jacob314 — COMMENTED** [review]
Looks good once these comments are addressed!

File: packages/cli/src/nonInteractiveCli.ts (hunk 8 above)
Comment (krishna-kb) [reply packages/cli/src/nonInteractiveCli.ts]: The actual output of toolCallRequests is processed by the model and then written at a generic place which also prints contagious texts from model.
I have added a new ensureNewLine method to the utility to solve for this.

File: package-lock.json [hunk 10]
```diff
@@ -621,6 +622,7 @@
         }
       ],
       "license": "MIT",
+      "peer": true,
```
Comment (jacob314) [inline package-lock.json:625]: revert this file. it isn't related to your PR

**Review by jacob314 — APPROVED** [review]
lgtm
