### PR TITLE
use debugLogger instead of console

### LINKED ISSUE #11864: Refactor: Migrate console.error in glob.ts to debugLogger.warn
## Context
We are standardizing our logging and error handling. This file, `packages/core/src/tools/glob.ts`, implements the file globbing tool.

## Task
Review the `console.error` call within the `catch` block of the `execute` method.
- The tool's return value already surfaces a user-facing error message via the `returnDisplay` field.
- The purpose of this log is to record the details of the unexpected exception for debugging, not to create a second user-facing error.
- Please migrate the `console.error` call to `debugLogger.warn`. This will ensure the internal failure is logged appropriately without creating redundant error messages in the UI.

Reference PR #11803 for examples.

Parent Issue: #10761

### LINKED ISSUE #11868: Refactor: Logging review for console.error in ls.ts
## Context
We are standardizing our logging and error handling. This file, `packages/core/src/tools/ls.ts`, implements the directory listing tool.

## Task
Review the `console.error` call within the `for` loop of the `execute` method. This log is triggered when `fs.stat` fails for a single file in a directory, after which the tool continues processing other files.

### Recommendation
Our analysis suggests this is a non-critical, handled error that is useful for diagnostics but should not be a user-facing error or a high-level warning.

We recommend migrating the `console.error` call to `debugLogger.debug`.

**Please evaluate this recommendation and course-correct as you see fit.** The goal is to ensure the log level matches the error's severity and context.

Reference PR #11803 for examples.

Parent Issue: #10761

### PR DESCRIPTION
**Pull request by scidomino**
## TLDR

use debugLogger instead of console

## Linked issues / bugs

Fixes #11890 
Fixes #11868 
Fixes #11865 
Fixes #11864

### CODE REVIEW

File: packages/core/src/tools/ls.ts [hunk 1]
```diff
@@ -205,7 +206,7 @@ class LSToolInvocation extends BaseToolInvocation<LSToolParams, ToolResult> {
           });
         } catch (error) {
           // Log error internally but don't fail the whole listing
-          console.error(`Error accessing ${fullPath}: ${error}`);
+          debugLogger.debug(`Error accessing ${fullPath}: ${error}`);
```
Comment (jacob314) [inline packages/core/src/tools/ls.ts:209]: nit: maybe make this a warn instead of debug. but fine either way.

**Review by jacob314 — APPROVED** [review]
lgtm
