### PR TITLE
feat(core): Fix bug with incorrect model overriding.

### LINKED ISSUE #13475: Requests Routed to gemini-3-pro-preview Despite Explicit --model gemini-2.5-pro Setting
### What happened?

When I launched the Gemini CLI using the command gemini --model gemini-2.5-pro, the application started correctly. However, upon sending the very first message ("hi"), the request was incorrectly routed to the gemini-3-pro-preview model.
This misrouting immediately resulted in a "Quota limit exceeded" error, as the rate limits for the preview model are lower than those for the specified model.
Steps to Reproduce:
Run the command: gemini --model gemini-2.5-pro
In the CLI prompt, enter any message (e.g., hi).
The request fails with a quota limit error specific to gemini-3-pro-preview.

Image

### What did you expect to happen?

I expected the CLI to respect the explicitly passed --model gemini-2.5-pro argument and route the request to the specified model.
The expected behavior was:
The request is made to the gemini-2.5-pro model.
A response is successfully received from gemini-2.5-pro.

Environment
Target Model in CLI: gemini-2.5-pro
Actual Model Used (Observed via Error): gemini-3-pro-preview

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
│ About Gemini CLI                                                                      
│                                                                                       
│ CLI Version                   0.16.0                                                  
│ Git Commit                    56f9e597c                                               
│ Model                         gemini-2.5-pro                                          
│ Sandbox                       no sandbox                                             
│ OS                            android                                                 
│ Auth Method                   gemini-api-key                                        
```

</details>

### Login information

I'm using API key method to login

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by joshualitt**
Fixes #13475

### CODE REVIEW

File: packages/core/src/routing/modelRouterService.ts [hunk 1]
```diff
@@ -72,7 +72,7 @@ export class ModelRouterService {
       if (
```
Comment (sehoon38) [inline packages/core/src/routing/modelRouterService.ts]: I think we can remove this entire block. We are already checking which model to use in classifierStrategy, thus this override is prob not needed.

**Review by sehoon38 — APPROVED** [review]
LGTM!
