### PR TITLE
Fix bottom border color

### LINKED ISSUE #19265: Bottom borders for tool groups are inconsistent with the rest of the border
The bottom border is rendered as a separate chunk so gets rendered with an inconsistent background from the rest of the border as the list of tools for it does not match.

### PR DESCRIPTION
**Pull request by jacob314**
## Summary

Before:
image

After:
Screenshot 2026-02-17 at 11 26 55 AM

Fixes #19265

Details:
Properly testing requires pending changes to use xterm to extract terminal colors correctly.

### CODE REVIEW

File: packages/cli/src/ui/components/messages/ToolGroupMessage.tsx [hunk 1]
```diff
@@ -31,6 +28,8 @@ interface ToolGroupMessageProps {
   onShellInputSubmit?: (input: string) => void;
   borderTop?: boolean;
   borderBottom?: boolean;
+  borderColor: string;
```
Comment (jacob314) [inline packages/cli/src/ui/components/messages/ToolGroupMessage.tsx]: made these required even though it churns the tests because that caught a bug where Gemini failed to apply the color to absolutely every call site

File: packages/cli/src/ui/components/HistoryItemDisplay.tsx [hunk 2]
```diff
@@ -181,6 +185,8 @@ export const HistoryItemDisplay: React.FC<HistoryItemDisplayProps> = ({
           embeddedShellFocused={embeddedShellFocused}
           borderTop={itemForDisplay.borderTop}
           borderBottom={itemForDisplay.borderBottom}
+          borderColor={borderColor ?? ''}
```
Comment (galdawave) [inline packages/cli/src/ui/components/HistoryItemDisplay.tsx]: Nit: should we set a default borderColor? Or is this meant to conditionally render boarder coolers when we pass them ?

File: packages/cli/src/ui/components/MainContent.tsx [hunk 3]
```diff
@@ -49,49 +124,77 @@ export const MainContent = () => {
     staticAreaMaxItemHeight,
     availableTerminalHeight,
     cleanUiDetailsVisible,
+    activePtyId,
```
Comment (galdawave) [inline packages/cli/src/ui/components/MainContent.tsx]: The historyItems and pendingItems memoizations now depend on activePtyId, embeddedShellFocused, and backgroundShells. While necessary for the dynamic styling, activePtyId and embeddedShellFocused can change frequently during shell interactions. Re-mapping the entire uiState.history on every change to these values might be expensive if the history grows large. 

Consider if the border color calculation could be scoped more tightly or if the performance impact has been measured for large sessions.

File: packages/cli/src/ui/components/MainContent.tsx [hunk 4]
```diff
@@ -19,10 +19,85 @@ import { useMemo, memo, useCallback, useEffect, useRef } from 'react';
...
+} from '../types.js';
+import type { UIState } from '../contexts/UIStateContext.js';
 
 const MemoizedHistoryItemDisplay = memo(HistoryItemDisplay);
 const MemoizedAppHeader = memo(AppHeader);
 
+/**
+ * Calculates the border color and dimming state for a tool group message.
+ */
+export function getToolGroupBorderAppearance(
```
Comment (galdawave) [inline packages/cli/src/ui/components/MainContent.tsx]: To keep MainContent.tsx focused on layout and orchestration, consider moving this utility to a separate styling or utility file (e.g., packages/cli/src/ui/utils/borderStyles.ts).

File: packages/cli/src/ui/components/MainContent.test.tsx [hunk 5]
```diff
@@ -76,6 +77,208 @@ vi.mock('./shared/ScrollableList.js', () => ({
...
+      item,
+      activeShellPtyId,
+      true,
+      [],
+      mockBackgroundShells,
+    );
+    // Since there are no tools to inspect, it falls back to empty pending, but isCurrentlyInShellTurn=true
+    // so it counts as pending shell.
+    expect(result.borderColor).toEqual(theme.ui.symbol);
+    // It shouldn't be dim because there are no tools to say it isEmbeddedShellFocused = false
```
Comment (galdawave) [inline packages/cli/src/ui/components/MainContent.test.tsx:279]: The comment mentions isCurrentlyInShellTurn=true but doesn't explicitly verify the borderDimColor expectation, which would be helpful for clarity.

**Comment by jacob314** [comment]
LGTM! I have extracted the utility and fixed the `activeShellPtyId` variable declaration bug.

File: packages/cli/src/ui/components/MainContent.test.tsx (hunk 5 above)
Comment (jacob314) [reply packages/cli/src/ui/components/MainContent.test.tsx:279]: done

File: packages/cli/src/ui/components/MainContent.tsx (hunk 3 above)
Comment (jacob314) [reply packages/cli/src/ui/components/MainContent.tsx]: fantastic suggestion. I've implemented this.

**Review by galdawave — APPROVED** [review]

**Review by krsjenmt — APPROVED** [review]
