### PR TITLE
fix(config): treat system settings as read-only during migration and warn user

### LINKED ISSUE #18123: [UX] Failed to save to system_default scope while migrating deprecated settings.
### What happened?

When running in an environment without write access to the system_default directory (e.g., in Cloud Shell), users encounter the error: "There was an error saving your latest settings changes." This occurs because the system attempts to migrate deprecated settings but cannot write to the file. The error repeats on every start-up without providing additional detail, creating a poor user experience.

Image

### What did you expect to happen?

Not have the error on the start up.

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
# paste output here
```

</details>

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by spencer426**
## Summary
  This PR prevents the CLI from crashing when attempting to automatically migrate deprecated configuration settings in the system and system_default scopes. These scopes are now treated as
  read-only, and the CLI will instead warn the user to perform manual updates for these files.

## Details
   - Read-Only Enforcement: Modified LoadedSettings.setValue to automatically redirect any updates to System or SystemDefaults scopes to an in-memory-only store (setValueInMemory). This
     prevents EACCES errors when the CLI doesn't have write permissions to system-wide configuration directories.
   - Migration Logic Update: Enhanced the migration functions to track deprecated flags found in system scopes. While migrations are still applied in-memory for the current session, the
     changes are no longer persisted to disk for these specific scopes.
   - Actionable Warnings: Implemented a notification system using coreEvents.emitFeedback that alerts the user (in yellow) if their system configuration contains deprecated settings, listing
     the specific flags that require manual intervention.

## Related Issues
   - Fixes #18123 

## How to Validate
   1. Create Mock System Config:
      echo '{"general": {"disableUpdateNag": true}}' > /tmp/mock-system.json
   2. Run Development CLI:
      GEMINI_CLI_SYSTEM_SETTINGS_PATH=/tmp/mock-system.json npm run start
   3. Verify Behavior:
       - Confirm the CLI starts without crashing.
       - Look for the yellow warning message: "The system configuration contains deprecated settings: [disableUpdateNag]. These could not be migrated automatically..."
       - Verify that /tmp/mock-system.json has not been modified by the CLI.
   4. Verify User Migration:
       - Add a deprecated flag to your local ~/.gemini/settings.json.
       - Run the CLI normally and verify that the local file is automatically updated.

## Pre-Merge Checklist

   - [ ] Updated relevant documentation and README (if needed)
   - [x] Added/updated tests (if needed)
   - [ ] Noted breaking changes (if any)
   - [x] Validated on required platforms/methods:
     - [ ] MacOS
       - [ ] npm run
       - [ ] npx
       - [ ] Docker
       - [ ] Podman
       - [ ] Seatbelt
     - [ ] Windows
       - [ ] npm run
       - [ ] npx
       - [ ] Docker
     - [x] Linux
       - [x] npm run
       - [ ] npx
       - [ ] Docker

### CODE REVIEW

File: packages/cli/src/config/settings.ts [hunk 1]
```diff
@@ -400,6 +407,30 @@ export class LoadedSettings {
     coreEvents.emitSettingsChanged();
   }
 
+  /**
```
Comment (jacob314) [inline packages/cli/src/config/settings.ts]: there is too much duplicated logic with the regular setValue. We should just instead avoid saving the file if it is a system settings file

File: packages/cli/src/config/settings.ts [hunk 2]
```diff
@@ -799,18 +838,25 @@ export function migrateDeprecatedSettings(
...
           newGeneral,
           'disableUpdateNag',
           'enableAutoUpdateNotification',
+          foundDeprecated,
         ) || modified;
 
       if (modified) {
         loadedSettings.setValue(scope, 'general', newGeneral);
-        anyModified = true;
+        if (!isSystemScope) {
```
Comment (jacob314) [inline packages/cli/src/config/settings.ts]: having system scope specific checks here is a little scary. why is this needed?

File: packages/cli/src/config/settings.ts [hunk 3]
```diff
@@ -941,6 +1015,9 @@ function migrateExperimentalSettings(
 
     // Migrate codebaseInvestigatorSettings -> agents.overrides.codebase_investigator
     if (experimentalSettings['codebaseInvestigatorSettings']) {
+      if (foundDeprecated) {
```
Comment (jacob314) [inline packages/cli/src/config/settings.ts]: refactor so we don't have to repeat strings like codeBaseInvestigatorSettings in these migrate blocks. Add a shared helper.

Comment (spencer426) [reply packages/cli/src/config/settings.ts]: Done. Combined setValue and setValueInMemory using a new helper that checks if a scope needs to be saved or just kept in memory. I also cleaned up the migration code to remove duplicate strings.

File: packages/cli/src/config/settings.ts (hunk 1 above)
Comment (spencer426) [reply packages/cli/src/config/settings.ts]: Done.

File: packages/cli/src/config/settings.ts (hunk 2 above)
Comment (spencer426) [reply packages/cli/src/config/settings.ts]: Refactored to use the `SettingsFile` interface to include a readOnly flag instead.

**Review by jacob314 — APPROVED** [review]
lgtm
