### PR TITLE
fix(core): gracefully handle disk full errors in chat recording

### LINKED ISSUE #16266: When disk is full, gemini-cli constantly spams with an error message
### What happened?

│ ✖  =========================================                                                                                                                                                                                         │
│    This is an unexpected error. Please file a bug report using the /bug tool.                                                                                                                                                        │
│    CRITICAL: Unhandled Promise Rejection!                                                                                                                                                                                            │
│    =========================================                                                                                                                                                                                         │
│    Reason: Error: ENOSPC: no space left on device, open '/Users/ryan.gardner/.gemini/tmp/cbd36cec41b49928423b93471ebb28e15444511db2d9a7edffa119595f949bf1/chats/session-2026-01-09T18-46-a6550cf0.json'                              │
│    Stack trace:                                                                                                                                                                                                                      │
│    Error: ENOSPC: no space left on device, open '/Users/ryan.gardner/.gemini/tmp/cbd36cec41b49928423b93471ebb28e15444511db2d9a7edffa119595f949bf1/chats/session-2026-01-09T18-46-a6550cf0.json'                                      │
│        at Object.writeFileSync (node:fs:2426:20)                                                                                                                                                                                     │
│        at ChatRecordingService.writeConversation                                                                                                                                                                                     │
│    (file:///Users/ryan.gardner/.nvm%20/versions/node/v22.16.0/lib/node_modules/@google/gemini-cli/node_modules/@google/gemini-cli-core/dist/src/services/chatRecordingService.js:300:20)                                             │
│        at ChatRecordingService.updateConversation                                                                                                                                                                                   █│
│    (file:///Users/ryan.gardner/.nvm%20/versions/node/v22.16.0/lib/node_modules/@google/gemini-cli/node_modules/@google/gemini-cli-core/dist/src/services/chatRecordingService.js:315:14)                                            █│
│        at ChatRecordingService.recordMessage (file:///Users/ryan.gardner/.nvm%20/versions/node/v22.16.0/lib/node_modules/@google/gemini-cli/node_modules/@google/gemini-cli-core/dist/src/services/chatRecordingService.js:101:18)  █│
│        at file:///Users/ryan.gardner/.nvm%20/versions/node/v22.16.0/lib/node_modules/@google/gemini-cli/dist/src/ui/hooks/useHistoryManager.js:60:43                                                                                █│
│        at file:///Users/ryan.gardner/.nvm%20/versions/node/v22.16.0/lib/node_modules/@google/gemini-cli/dist/src/ui/hooks/useGeminiStream.js:641:21    

### What did you expect to happen?

It should detect it and prompt me that the disk is full, and I can free up space and then let it keep going. (instead it just enters into an endless loop) 

### Client information


* **CLI Version:** 0.23.0
* **Git Commit:** 3ff055840
* **Session ID:** a6550cf0-865f-492d-86bb-8742e2d4f194
* **Operating System:** darwin v22.16.0
* **Sandbox Environment:** no sandbox
* **Model Version:** auto-gemini-3
* **Memory Usage:** 284.8 MB
* **Terminal Name:** Unknown
* **Terminal Background:** #1e1e1e
* **Kitty Keyboard Protocol:** Unsupported


### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by godwiniheuwa**
## Summary
- When the disk is full (ENOSPC error), the `ChatRecordingService` now gracefully disables recording instead of causing an infinite loop of error spam
- Adds circuit breaker pattern: detects ENOSPC, logs a warning once, then silently skips all further recording operations
- Allows the conversation to continue without being saved to disk

## Changes
- Added `recordingDisabled` and `disabledReason` private fields to track recording state
- Handle ENOSPC errors in `initialize()` and `writeConversation()` methods
- Added early returns in all public recording methods when recording is disabled
- Added `isRecordingDisabled()` and `getDisabledReason()` public methods for status checking
- Added comprehensive tests for ENOSPC handling (5 new test cases)

## Test plan
- [x] All existing tests pass (17 tests)
- [x] New tests verify:
  - ENOSPC during initialize() disables recording without throwing
  - ENOSPC during writeConversation() disables recording without throwing
  - Subsequent recording operations are no-ops when disabled
  - getConversation() and getConversationFilePath() return null when disabled
  - Non-ENOSPC errors (like EACCES) still throw as expected

Fixes #16266

Co-authored-by: ruintheextinct <deepkarma001@gmail.com>

### CODE REVIEW

File: packages/core/src/services/chatRecordingService.ts [hunk 1]
```diff
@@ -118,6 +118,13 @@ export class ChatRecordingService {
   private queuedTokens: TokensSummary | null = null;
   private config: Config;
 
+  /**
+   * When true, recording is disabled due to an unrecoverable error (e.g., disk full).
+   * All recording methods will return early without throwing.
+   */
+  private recordingDisabled = false;
+  private disabledReason: string | null = null;
```
Comment (scidomino) [inline packages/core/src/services/chatRecordingService.ts]: Remove this as this is always set to the same value when it's not null. recordingDisabled should be sufficient to track this.

File: packages/core/src/services/chatRecordingService.ts [hunk 2]
```diff
@@ -173,6 +180,21 @@ export class ChatRecordingService {
...
+        error instanceof Error &&
+        'code' in error &&
+        (error as NodeJS.ErrnoException).code === 'ENOSPC'
+      ) {
+        this.recordingDisabled = true;
+        this.disabledReason = 'No space left on device (ENOSPC)';
+        debugLogger.warn(
+          'Chat recording disabled: No space left on device. ' +
+            'The conversation will continue but will not be saved to disk. ' +
+            'Free up disk space to enable recording in future sessions.',
```
Comment (scidomino) [inline packages/core/src/services/chatRecordingService.ts]: "Free up diskspace *and restart*"

File: packages/core/src/services/chatRecordingService.ts [hunk 3]
```diff
@@ -425,6 +447,21 @@ export class ChatRecordingService {
...
+        );
```
Comment (scidomino) [inline packages/core/src/services/chatRecordingService.ts]: This duplicates code from above. Please use a constant or something for the message so you can reuse it.

File: packages/core/src/services/chatRecordingService.ts [hunk 4]
```diff
@@ -118,6 +118,13 @@ export class ChatRecordingService {
   private queuedTokens: TokensSummary | null = null;
   private config: Config;
 
+  /**
+   * When true, recording is disabled due to an unrecoverable error (e.g., disk full).
+   * All recording methods will return early without throwing.
+   */
+  private recordingDisabled = false;
```
Comment (scidomino) [inline packages/core/src/services/chatRecordingService.ts]: instead of having "recordingDisabled" track your state, consider just setting conversationFile to null instead. As far as I can tell, it has the same effect everywhere in the code.

**Review by scidomino — CHANGES_REQUESTED** [review]

**Review by scidomino — APPROVED** [review]
