### PR TITLE
Fix compression issues

### LINKED ISSUE #3709: Failed to compress chat history
### What happened?

Failed to compress chat history: Please ensure that the number of  function response parts is equal to the number of function call  parts of the function call turn.
[API Error: [{
    "error": {
      "code": 400,
      "message": "Please ensure that the number of function response 
  parts is equal to the number of function call parts of the function 
  call turn.",
      "errors": [
        {
          "message": "Please ensure that the number of function 
  response parts is equal to the number of function call parts of the 
  function call turn.",
          "domain": "global",
          "reason": "badRequest"
        }
      ],
      "status": "INVALID_ARGUMENT"
    }
  }
  ]]

### What did you expect to happen?

 /compress 
compress chat history

### Client information

*   **CLI Version:** 0.1.9
*   **Git Commit:** 34935d6
*   **Operating System:** win32 v22.17.0
*   **Sandbox Environment:** no sandbox
*   **Model Version:** gemini-2.5-pro
*   **Memory Usage:** 158.2 MB

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by scidomino**
## TLDR

Fixes it to `compress` always compresses *at least* 70% of the history rather than *at most*. Also simplified how we create the summary so there is no possibility of a tool call.

## Dive Deeper

This removes `GeminiChat.sendMessage()` which was only used by compress but which had a lot of complicated support for stuff that compress definitely does not need (like function calling).

## Reviewer Test Plan

Ask: `How are you? Take a look at @packages/core. Isn't it beautiful?`
Then: `/compress`

Verify that the token count goes down by a lot.

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | x  | ❓  | ❓  |
| npx      | ❓  | ❓  | ❓  |
| Docker   | ❓  | ❓  | ❓  |
| Podman   | ❓  | -   | -   |
| Seatbelt | ❓  | -   | -   |

## Linked issues / bugs

Fixes #3709

### CODE REVIEW

File: packages/core/src/core/geminiChat.ts [hunk 1]
```diff
@@ -704,35 +572,18 @@ export class GeminiChat {
...
   }
 
-  private recordHistory(
-    userInput: Content,
-    modelOutput: Content[],
-    automaticFunctionCallingHistory?: Content[],
-  ) {
+  private recordHistory(userInput: Content, modelOutput: Content[]) {
     // Part 1: Handle the user's turn.
-    if (
```
Comment (anj-s) [inline packages/core/src/core/geminiChat.ts:713]: why don't we need this anymore?

Comment (scidomino) [reply packages/core/src/core/geminiChat.ts:713]: automaticFunctionCallingHistory was only passed by sendMessage() which we are removing.

**Review by jacob314 — COMMENTED** [review]
The diff in geminiChat.ts and test.ts seems a bit larger than needed. if those are intentional let me know and I'll review.

On the plus side I am now finally able to compress my chat history after user `@packages/cli` to fill the context window.

**Comment by scidomino** [comment]
> The diff in geminiChat.ts and test.ts seems a bit larger than needed. if those are intentional let me know and I'll review.
> 
> On the plus side I am now finally able to compress my chat history after user `@packages/cli` to fill the context window.

So really, this fixes two different bugs:

1. off-by-one error causing it to not compress as much as it should.
2. sometimes compress would return a tool call instead of a summary which would break everything.

Fixing 2. removed the last usage of sendMessage() which required deleting a bunch of code. And to be clear, I did that manually (not with GCLI).

**Review by anj-s — APPROVED** [review]
