### PR TITLE
fix(plan): prevent plan truncation in approval dialog by supporting unconstrained heights

### LINKED ISSUE #20716: Document how to view full plan when it's truncated in the approval dialog
### What happened?

When exiting plan mode, the plan approval dialog only shows up to 15 lines of the plan content. Any lines beyond that are hidden with a "... X lines hidden" message. For example, a 20-line plan only shows 15 lines, cutting off the last 5.

### What did you expect to happen?

The full plan content should be visible (or at least use more of the available terminal height). It seems like a pretty common workflow to read the entire plan, especially with a lot of terminal real estate.

In [packages/cli/src/ui/components/AskUserDialog.tsx#L792-L795](https://github.com/google-gemini/gemini-cli/blob/main/packages/cli/src/ui/components/AskUserDialog.tsx#L792-L795), the question height for choice dialogs is hard-capped at 15 lines. Not sure if it's better to modify that (since is affects all dialogs) or something specific for plan mode.

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
# paste output here
```

</details>

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by Adib234**
## Summary

Fixes the plan approval dialog so that it displays the full plan without truncating it at 15 lines. This improves the workflow for reviewing long plans by letting the plan content take up the maximum vertical space available.

## Details

- Adds an `unconstrainedHeight?: boolean;` property to the `Question` interface in `packages/core/src/confirmation-bus/types.ts`.
- Updates `ChoiceQuestionView` in `packages/cli/src/ui/components/AskUserDialog.tsx` to utilize `unconstrainedHeight`. When true, it dynamically calculates the maximum question height based on the available terminal height and the number of selection items, bypassing the hard-coded 15-line limit.
- Sets `unconstrainedHeight: true` on the question object inside `ExitPlanModeDialog.tsx`.
- Updates `ExitPlanModeDialog` snapshot tests to reflect the new un-truncated UI.

## Related Issues

Fixes #20716

## How to Validate

1. Run the CLI and enter plan mode: `gemini` -> `/plan`
2. Give a broad prompt that generates a plan longer than 15 lines.
3. Once the plan finishes, attempt to exit plan mode (`/act` or `Ctrl+C`).
4. Ensure the plan dialog fully expands to show the majority of the plan text, without unnecessarily truncating at 15 lines.
5. Verify regular `AskUserDialog` instances (like multi-choice settings dialogs) remain unaffected.

## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [x] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [x] Validated on required platforms/methods:
  - [x] MacOS
    - [x] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

File: packages/cli/src/ui/components/AskUserDialog.tsx [hunk 1]
```diff
@@ -789,9 +789,13 @@ const ChoiceQuestionView: React.FC<ChoiceQuestionViewProps> = ({
   const listHeight = availableHeight
     ? Math.max(1, availableHeight - overhead)
     : undefined;
+  const maxQuestionHeight =
+    question.unconstrainedHeight && listHeight
+      ? Math.max(1, listHeight - DIALOG_PADDING - selectionItems.length * 2)
+      : 15;
```
[the remark this answers is not in the document]
Comment (Adib234) [reply packages/cli/src/ui/components/AskUserDialog.tsx]: updated code

File: packages/cli/src/ui/components/ExitPlanModeDialog.tsx [hunk 2]
```diff
@@ -247,6 +247,7 @@ export const ExitPlanModeDialog: React.FC<ExitPlanModeDialogProps> = ({
             ],
             placeholder: 'Type your feedback...',
             multiSelect: false,
+            unconstrainedHeight: true,
```
[the remark this answers is not in the document]
Comment (Adib234) [reply packages/cli/src/ui/components/ExitPlanModeDialog.tsx]: planContent is not related to this PR

**Review by jacob314 — CHANGES_REQUESTED** [review]
### Code Review from `/review-frontend` (Reviewed by Jacob)

This PR successfully adds dynamic height measuring for `AskUserDialog` items and configures `ExitPlanModeDialog` to take advantage of it. However, there is a **critical logic regression** in `AskUserDialog.tsx` where the `unconstrainedHeight` property is introduced but entirely ignored, applying the unconstrained height logic globally to all questions.

## Findings

### Critical
* **Logic Bug / Unused Property**: In `packages/cli/src/ui/components/AskUserDialog.tsx`, the newly added `unconstrainedHeight` property is never actually referenced. The calculation for `maxQuestionHeight` is applied unconditionally for all dialogs:
  ```typescript
  // Modulo the fixed overflow (overhead + 4 lines reserved for list), use all remaining height.
  const maxQuestionHeight = listHeight ? Math.max(5, listHeight - 4) : 15;
  ```
  This means **all** multi-choice questions that are longer than 15 lines will now expand to take up almost the entire terminal height, squashing the options list to just 4 lines. This violates the PR's own testing requirement ("Verify regular AskUserDialog instances remain unaffected").

### Improvements
* **Restore Conditional Logic or Remove Property**: In an earlier commit, you had a conditional check using `question.unconstrainedHeight`. You must restore a conditional approach to ensure only specific dialogs use dynamic height. For example:
  ```typescript
  const maxQuestionHeight =
    question.unconstrainedHeight && listHeight
      ? Math.max(5, listHeight - 4)
      : 15; // default 15-line limit
  ```
  *Note: If we ultimately decide we don't need the `unconstrainedHeight` property and want this new dynamic sizing everywhere, it is fine to remove the property from the `Question` interface entirely. However, it shouldn't be left in the interface if it remains unused.*

### Note on Bot Review
* The security vulnerability mentioned by the `gemini-code-assist` bot (regarding terminal escape sequence injection) is out of scope for this PR. The plan text is passed to `MarkdownDisplay` natively. Any issues with rendering unsanitized LLM output are systemic to the markdown renderer, and this PR only adjusts vertical layout properties (`maxHeight`), thus introducing no new vulnerabilities.

## Conclusion
**Request Changes.** The core intent is correct, but the height calculation in `AskUserDialog.tsx` must be wrapped in a check for `question.unconstrainedHeight` (or the property should be removed if this global change is actually intended, though that seems to contradict the PR description).

File: packages/cli/src/ui/components/__snapshots__/ExitPlanModeDialog.test.tsx.snap [hunk 3]
```diff
@@ -74,13 +74,16 @@ Implementation Steps
...
+ 9. Implement session timeout handling in src/auth/SessionManager.ts
+ 10. Add audit logging for auth events in src/auth/AuditLogger.ts
+... last 20 lines hidden (Ctrl+O to show) ...
 
+▲
 ● 1.  Yes, automatically accept edits                                           
       Approves plan and allows tools to run automatically                       
   2.  Yes, manually accept edits
       Approves plan but requires confirmation for each tool
-  3.  Type your feedback...
```
Comment (Jefftree) [inline packages/cli/src/ui/components/__snapshots__/ExitPlanModeDialog.test.tsx.snap:83]: This seems like a pretty common workflow to use the feedback option to iterate on the plan instead of approving right away. In fact I would argue that it's probably used more often than the other two options. Is the UX intentional to now hide it? 

Thank you for fixing https://github.com/google-gemini/gemini-cli/issues/20716 btw!

Comment (jackwotherspoon) [reply packages/cli/src/ui/components/__snapshots__/ExitPlanModeDialog.test.tsx.snap:83]: +1 adding the up and down arrows is more lines taken up than just showing the 3rd option 😄

Comment (Adib234) [reply packages/cli/src/ui/components/__snapshots__/ExitPlanModeDialog.test.tsx.snap:83]: not intentional, my latest commit to this branch should address this

**Comment by jackwotherspoon** [comment]
Tested and works for me, will let Jacob do proper review as it is his wheelhouse

File: packages/cli/src/ui/components/ExitPlanModeDialog.tsx [hunk 4]
```diff
@@ -226,7 +226,7 @@ export const ExitPlanModeDialog: React.FC<ExitPlanModeDialogProps> = ({
   const editHint = formatCommand(Command.OPEN_EXTERNAL_EDITOR);
 
   return (
-    <Box flexDirection="column" width={width}>
+    <Box flexDirection="column" width={width} minHeight={availableHeight}>
```
Comment (jacob314) [inline packages/cli/src/ui/components/ExitPlanModeDialog.tsx]: setting minHeight here seems very odd. why is this needed?

Comment (Adib234) [reply packages/cli/src/ui/components/ExitPlanModeDialog.tsx]: I thought we always had to make use of the available height in exit plan mode dialog

File: packages/cli/src/ui/components/ToolConfirmationQueue.tsx [hunk 5]
```diff
@@ -55,13 +55,25 @@ export const ToolConfirmationQueue: React.FC<ToolConfirmationQueueProps> = ({
...
       : Math.floor(terminalHeight * 0.5);
 
+  if (isExitPlanMode && uiAvailableHeight !== undefined) {
+    // For exit plan mode, we want to cover almost everything except 1 line of history.
+    // Based on the calculation of availableTerminalHeight in AppContainer.tsx:
+    // availableTerminalHeight = terminalHeight - controlsHeight - staticExtraHeight - 2 - backgroundShellHeight
+    // where staticExtraHeight = 3.
+    // So, terminalHeight - controlsHeight - backgroundShellHeight - 1 (the space we want to take)
+    // is equal to availableTerminalHeight + 3 + 2 - 1 = availableTerminalHeight + 4.
+    maxHeight = Math.max(uiAvailableHeight + 4, 4);
```
Comment (jacob314) [inline packages/cli/src/ui/components/ToolConfirmationQueue.tsx]: major code smell. we should not be setting height to more than the uiAvailableHeight. this indicates that either uiAvailableHeight is wrong or we have incorrect calculations within AskUserDialog resulting in us needing mroe space. we also cannot be hard coding the height for exitPlan mode. that is a major code smell.

File: packages/core/src/confirmation-bus/types.ts [hunk 6]
```diff
@@ -162,6 +162,8 @@ export interface Question {
   multiSelect?: boolean;
   /** Placeholder hint text. For type='text', shown in the input field. For type='choice', shown in the "Other" custom input. */
   placeholder?: string;
+  /** Allow the question to consume more vertical space instead of being strictly capped. */
```
Comment (jacob314) [inline packages/core/src/confirmation-bus/types.ts:170]: this isn't needed

Comment (Adib234) [reply packages/core/src/confirmation-bus/types.ts:170]: Removed this

File: packages/cli/src/ui/components/ToolConfirmationQueue.tsx (hunk 5 above)
Comment (Adib234) [reply packages/cli/src/ui/components/ToolConfirmationQueue.tsx]: Removed this, thought we were making sure that only exit plan mode dialog should use as much space possible if it has the content to do so. My changes now also make sure that any component that uses the AskUser dialog will fit content to screen if there's space.

**Comment by jacob314** [comment]
I completely agree with the goal of this PR! Expanding the vertical space for the `ExitPlanModeDialog` is a great improvement for readability without squishing the dialog options.

However, looking at the code, I noticed the addition of a magic number (`+ 4`) to artificially increase the `maxHeight` specifically for `exit_plan_mode`.

**Root Cause:**
In `AppContainer.tsx`, the `availableTerminalHeight` context value—which `ToolConfirmationQueue` and `HistoryArea` rely on to constrain item heights—was artificially shortened. It was previously subtracting 5 lines: `staticExtraHeight` (3 lines for the `AppHeader`) + 2 padding lines. But the `AppHeader` renders *inside* the scrollable list container, meaning it natively scrolls out of view and doesn't permanently occupy viewport space!

By artificially subtracting those 5 lines from the available container height, *all* history items (and dialogs within them) were being forced to truncate 5 lines shorter than necessary, leading to the need for the `+ 4` hack specifically for `ExitPlanMode` just to reclaim that lost space.

**The Fix:**
We should fix this at the root by correcting `availableTerminalHeight` in `AppContainer.tsx` to precisely represent the scrollable view: `terminalHeight - controlsHeight - backgroundShellHeight - 1` (where the 1 is for the bottom margin). Once that is corrected, we can remove the `isExitPlanMode` `+ 4` `maxHeight` conditional block from `ToolConfirmationQueue.tsx`. Because `availableTerminalHeight` will accurately model the taller viewport, `ToolConfirmationQueue` will naturally allocate those 4/5 extra lines to `ExitPlanModeDialog` *and* any other dialog or tool result that needs it, without relying on special case logic.

Let me know if you agree with this approach! I have a fix ready locally and can push it to this PR if needed.

File: packages/core/src/confirmation-bus/types.ts (hunk 6 above)
Comment (Adib234) [reply packages/core/src/confirmation-bus/types.ts:170]: Does this still need to get removed? I see in the latest push this was brought back

**Review by jacob314 — APPROVED** [review]
lgtm
