### PR TITLE
fix: Show experiment values in settings UI for compressionThreshold

### LINKED ISSUE #13346: /settings shows hardcoded "compress threshold" default instead of experiment default
### What happened?

Oauth users are getting the default value of `0.7` from the experiment but `/settings` still shows hardcoded "compress threshold" default of `0.2` instead.

### What did you expect to happen?

It should show whatever value is being taken from the experiment.

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
# paste output here
```

</details>

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by ishaanxgupta**
### 1. Added `getEffectiveDefaultValue()` Function
Created a new async utility function that:
- Checks experiment values when config is available
- Falls back to schema defaults if experiments aren't loaded or fail
- Extensible for other experiment-aware settings in the future

### 2. Updated Settings Dialog
Modified `SettingsDialog` to:
- Load effective defaults (including experiment values) when config is available
- Cache effective defaults in component state
- Display experiment values instead of schema defaults

## Related Issues

Closes #13346

## Pre-Merge Checklist

- [X] Updated relevant documentation and README (if needed)
- [X] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [X] Validated on required platforms/methods:
  - [ ] MacOS
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [X] Windows
    - [X] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

**collaborated with @ved015** 

image

### CODE REVIEW

File: packages/cli/src/ui/components/SettingsDialog.tsx [hunk 1]
```diff
@@ -174,6 +175,50 @@ export function SettingsDialog({
...
+            const schemaDefault = getDefaultValue(key);
+            defaults.set(key, schemaDefault);
+          }
+        } else {
+          defaults.set(key, getDefaultValue(key));
+        }
+      }
+
+      setEffectiveDefaults(defaults);
+    };
```
[the remark this answers is not in the document]
Comment (ishaanxgupta) [reply packages/cli/src/ui/components/SettingsDialog.tsx]: done!

File: packages/cli/src/ui/components/SettingsDialog.tsx [hunk 2]
```diff
@@ -174,6 +175,43 @@ export function SettingsDialog({
...
+  useEffect(() => {
+    if (!config) {
+      return;
+    }
+
+    const loadEffectiveDefaults = async () => {
+      const keys = getDialogSettingKeys();
+      const entries = await Promise.all(
+        keys.map(async (key) => {
+          if (key === 'model.compressionThreshold') {
```
Comment (scidomino) [inline packages/cli/src/ui/components/SettingsDialog.tsx]: Is there a specific reason to only do this for the model.compressionThreshold setting?

File: packages/cli/src/ui/components/SettingsDialog.tsx [hunk 3]
```diff
@@ -174,6 +175,43 @@ export function SettingsDialog({
...
+            try {
+              const value = await getEffectiveDefaultValue(key, config);
+              return [key, value] as [string, SettingsValue];
```
Comment (scidomino) [inline packages/cli/src/ui/components/SettingsDialog.tsx]: Could you avoid all this casting if your function signature included it:

async (key):[string, SettingsValue] =>

File: packages/cli/src/ui/components/SettingsDialog.tsx [hunk 4]
```diff
@@ -174,6 +175,43 @@ export function SettingsDialog({
...
+            } catch (_error) {
+              // Fall back to schema default if experiment check fails
+              debugLogger.log(
+                `[SettingsDialog] Error loading effective default for ${key}, using schema default`,
+              );
+              return [key, getDefaultValue(key)] as [string, SettingsValue];
```
Comment (scidomino) [inline packages/cli/src/ui/components/SettingsDialog.tsx]: why are you falling back to getDefaultValue() here but also falling back to getDefaultValue() on line 786? Feels like it would be safe to return undefined here and let the second fallback do all the work.

**Comment by scidomino** [comment]
I'm not a fan of this way of organizing the code. Right now we're doing the experiment lookup in Config.getCompressThreshold() and that feels like not the right place to do it. Instead, we should move the defaulting behavior to the settings code. That way, we could just have settings tell the config what the threshold to use without having it mess with experiments.

Does that make sense?

File: packages/cli/src/ui/components/SettingsDialog.tsx (hunk 3 above)
Comment (ishaanxgupta) [reply packages/cli/src/ui/components/SettingsDialog.tsx]: Sure!

File: packages/cli/src/ui/components/SettingsDialog.tsx [hunk 5]
```diff
@@ -174,6 +175,38 @@ export function SettingsDialog({
...
+  // Load effective default values when config is available
+  useEffect(() => {
+    if (!config) {
+      return;
+    }
+
+    const loadEffectiveDefaults = async () => {
+      const keys = getDialogSettingKeys();
+      const defaultValueMap = new Map<string, SettingsValue>();
+      await Promise.all(
```
Comment (scidomino) [inline packages/cli/src/ui/components/SettingsDialog.tsx]: This is more complicated than it needs to be. Instead:


const keys = getDialogSettingKeys();
const defaultValueMap = new Map<string, SettingsValue>();

for (const key in keys) {
  defaultValueMap.set(key, getDefaultValue(key));
}

for(const key in ['model.compressionThreshold']) {
  const value = await getEffectiveDefaultValue(key, config);
  defaultValueMap.set(key, value);
}

File: packages/cli/src/ui/components/SettingsDialog.tsx [hunk 6]
```diff
@@ -174,6 +175,38 @@ export function SettingsDialog({
     Set<string>
   >(new Set());
 
+  // Cache effective default values (including experiment values)
+  const [effectiveDefaults, setEffectiveDefaults] = useState<
```
Comment (scidomino) [inline packages/cli/src/ui/components/SettingsDialog.tsx]: Why do we need to cache these? Why not revert all the changes to this file and just replace calls to getDefaultValue with calls to getEffectiveDefaultValue?

File: packages/cli/src/utils/settingsUtils.ts [hunk 7]
```diff
@@ -96,6 +98,30 @@ export function getDefaultValue(key: string): SettingsValue {
...
+/**
+ * Get the effective default value for a setting, checking experiment values when available.
+ * For settings like compressionThreshold, this will return the experiment value if set,
+ * otherwise falls back to the schema default.
+ */
+export async function getEffectiveDefaultValue(
+  key: string,
+  config?: Config,
+): Promise<SettingsValue> {
+  const schemaDefault = getDefaultValue(key);
```
Comment (scidomino) [inline packages/cli/src/utils/settingsUtils.ts]: Don't fetch a value until you need it. Inline this variable so that we don't search for the default unless we know we're not fetching the value from the experiment.

File: packages/core/src/config/config.ts [hunk 8]
```diff
@@ -1533,19 +1533,7 @@ export class Config {
...
-    await this.ensureExperimentsLoaded();
-
-    const remoteThreshold =
-      this.experiments?.flags[ExperimentFlags.CONTEXT_COMPRESSION_THRESHOLD]
-        ?.floatValue;
-    if (remoteThreshold === 0) {
-      return undefined;
-    }
-    return remoteThreshold;
+    return this.compressionThreshold;
```
Comment (scidomino) [inline packages/core/src/config/config.ts]: You still need all this code. Without it, the experimental default does not actually apply since the changes you made in the other classes all take place *after* config is initialized and this compressionThreshold is set *before* the config is initialized.

Comment (ishaanxgupta) [reply packages/core/src/config/config.ts]: resolved

File: packages/cli/src/utils/settingsUtils.ts (hunk 7 above)
Comment (ishaanxgupta) [reply packages/cli/src/utils/settingsUtils.ts]: makes sense

File: packages/cli/src/ui/components/SettingsDialog.tsx (hunk 6 above)
Comment (ishaanxgupta) [reply packages/cli/src/ui/components/SettingsDialog.tsx]: yes done

File: packages/core/src/config/config.ts [hunk 9]
```diff
@@ -1542,19 +1542,15 @@ export class Config {
   }
 
   async getCompressionThreshold(): Promise<number | undefined> {
```
Comment (scidomino) [inline packages/core/src/config/config.ts:1578]: Please revert 100% of changes to this file and the test. We do *not* want the experiment to always override the manually set compression threshold. Remember, all the changes you made in CLI take effect *after* this code is already done executing.

**Review by scidomino — COMMENTED** [review]
Sorry. I was waiting for you to @ ping me. the github inboxes for gcli maintainers are overflowing so I won't see it unless you actually @ my name.

File: packages/core/src/config/config.ts (hunk 9 above)
Comment (ishaanxgupta) [reply packages/core/src/config/config.ts:1578]: Done, I thought that experiements had to always overide the manually set compression threshold as it was mentioned in the issue

**Review by scidomino — APPROVED** [review]
