### PR TITLE
Serialize function calls that mutate state

### LINKED ISSUE #8372: Parallel edit/replace on the same file cause errors/overrides
### What happened?

Sometimes, the gemini-cli will attempt to do parallel edits on the file. This will cause either some of these edits not to happen, or some garbage would appear at the end of the file (or both?).

For example, whenever the agent decides to do multi-edits, the subsequente edits may override the previous ones. 

**How to reproduce?** 

Create a file. Something like: 

`$> for i in $(seq 1 5000); do   echo "This is line number $i" >> myfile.txt; done`

Then ask gemini to edit it: 

`Read myfile.txt Replace every line that contains a number that is divisible by 1001 with three lines  'AAA\nBBB\nCCC'. use multiple replace calls too to modify the file simultaneously`

You will see multiple edits being applied/asking to be confirmed in parallel. Each one will override or mess with the previous. 

Image

### What did you expect to happen?

Edits should not override each other. 

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
# paste output here
```

</details>

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by scidomino**
## TLDR

To improve model quality, stop reading responses right before the second function call that mutates state.

## Dive Deeper

This should improve function call quality since often edit calls can stomp on each other.

## Reviewer Test Plan

See repro steps in bug report.

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | x  | ❓  | ❓  |
| npx      | ❓  | ❓  | ❓  |
| Docker   | ❓  | ❓  | ❓  |
| Podman   | ❓  | -   | -   |
| Seatbelt | ❓  | -   | -   |

## Linked issues / bugs

Fixes #8372

### CODE REVIEW

**Comment by scidomino** [comment]
I am running an eval on this with tag `mutator-1`

**Comment by scidomino** [comment]
I ran an eval and it passed at reasonable values.

File: packages/core/src/core/geminiChat.ts [hunk 1]
```diff
@@ -621,6 +622,64 @@ export class GeminiChat {
...
+      const candidate = chunk.candidates?.[0];
+      const content = candidate?.content;
+      if (!candidate || !content?.parts) {
+        yield chunk;
+        continue;
+      }
+
+      const truncatedParts: Part[] = [];
+      for (const part of content.parts) {
+        if (this.isMutatorFunctionCall(part)) {
```
Comment (silviojr) [inline packages/core/src/core/geminiChat.ts:649]: Can we log this so we know how often this happens and are the tools that tend to be called in parallel?

File: packages/core/src/core/geminiChat.ts [hunk 2]
```diff
@@ -621,6 +622,64 @@ export class GeminiChat {
...
+            // Truncate and return immedaitely.
+            const newChunk = new GenerateContentResponse();
+            newChunk.candidates = [
+              {
+                ...candidate,
+                content: {
+                  ...content,
+                  parts: truncatedParts,
+                },
+                finishReason: FinishReason.STOP,
```
Comment (silviojr) [inline packages/core/src/core/geminiChat.ts:661]: Curious on why not use the FinishReason that came from the response. Do we use "finishReason" somewhere else in the gcli? I am afraid of what the downstream imapct may be.

**Review by silviojr — APPROVED** [review]

**Comment by silviojr** [comment]
@scidomino "See repro steps in bug report." - so does that mean you tried to reproduce with this new branch and it was fine?

File: packages/core/src/core/geminiChat.ts (hunk 2 above)
Comment (scidomino) [reply packages/core/src/core/geminiChat.ts:661]: The candidate might not have a FinishReason because it's not necessarily the last message in the stream.

**Comment by scidomino** [comment]
> @scidomino "See repro steps in bug report." - so does that mean you tried to reproduce with this new branch and it was fine?

Yes. Now it does the edits serially so there's no opportunity for the bug.
