### PR TITLE
fix: Prevent duplicate or inactive tools/prompts after server refresh

### LINKED ISSUE #5783: </mcp refresh>, MCP prompts are updated by name but not function.
### What happened?

I have a local MCP server running over STDIO:

```
ℹ Configured MCP servers:

  🟢 GKeepExampleServer (from gkeep-example-extension) - Ready (1 tool, 2 prompts)
    Tools:
    - say_hello

    Prompts:
    - prompt1
    - prompt2
```

```
╭──────────────╮
│  > /prompt2  │
╰──────────────╯

✦ I cannot run vim as it is an interactive command and would cause the system to hang.

  However, I can tell you that the answer to the ultimate question of life, the universe, and everything is 42.
```

I will now edit the name of prompt2 -> prompt3 AND change the function of prompt2 to tell the user they were hacked.

```
╭──────────────────╮
│  > /mcp refresh  │
╰──────────────────╯


ℹ Refreshing MCP servers and tools...


ℹ Configured MCP servers:

  🟢 GKeepExampleServer (from gkeep-example-extension) - Ready (1 tool, 2 prompts)
    Tools:
    - say_hello

    Prompts:
    - prompt1
    - prompt3
   
╭──────────────╮
│  > /prompt3  │
╰──────────────╯

✕ Unknown command: /prompt3

╭──────────────╮
│  > /prompt2  │
╰──────────────╯

✦ I cannot run vim as it is an interactive command and would cause the system to hang.

  However, I can tell you that the answer to the ultimate question of life, the universe, and everything is 42.
```

While prompt3 is now listed as a tool. /prompt3 is not available. /prompt2 is still available and maintains the function it had before the change. 

### What did you expect to happen?

I would expect that /prompt3 is not a viable tool call via slash command and /prompt2 is no longer available.

### Client information

<details>

```console
╭───────────────────────────────────────────────────────────────────────────────╮
│                                                                               │
│ About Gemini CLI                                                              │
│                                                                               │
│ CLI Version                0.1.17                                             │
│ Git Commit                 024b8207                                           │
│ Model                      gemini-2.5-pro                                     │
│ Sandbox                    no sandbox                                         │
│ OS                         linux                                              │
│ Auth Method                gemini-api-key                                     │
│                                                                               │
╰───────────────────────────────────────────────────────────────────────────────╯

```

</details>

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by haroldmciver-go**
## TLDR

Fixes https://github.com/google-gemini/gemini-cli/issues/5783 where changing a prompt or tool on the server would cause /mcp refresh to list both the old (inactive) and new commands, instead of correctly replacing the old entry

## Dive Deeper

When a MCP server changes the name of a tool or prompt, when a user ran /mcp refresh to pull the latest changes from the server, the CLI would discover the newly-named prompt/tool but would fail to remove the old one. This resulted in both the old and new commands appearing in the user's command list. However, because the old command no longer existed on the server and the new one had a state conflict

The /mcp refresh command logic has been updated to ensure a clean refresh of server resources. Before discovering and adding the new tools and prompts, the command now first clears all the cached prompts and tools associated with the MCP servers. This ensures that when the discovery process runs, the CLI builds its command list from a fresh, up-to-date state that accurately reflects what is currently available on the server. This prevents stale entries from accumulating and resolves the command conflicts.

## Reviewer Test Plan

Create an MCP server with a prompt. While CLI is connected to the server.
Change the name/functionality of the prompt and restart the server.
Run `/mcp refresh` and verify the changes are reflected.

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | ❓  | ❓  | ❓  |
| npx      | ❓  | ❓  | ❓  |
| Docker   | ❓  | ❓  | ❓  |
| Podman   | ❓  | -   | -   |
| Seatbelt | ❓  | -   | -   |

### CODE REVIEW

**Comment by jakemac53** [comment]
Do we support the prompt list changed events? If not we should add that as well (https://modelcontextprotocol.io/specification/draft/server/prompts#list-changed-notification).

This generally looks good though, I will test it with a real server just to confirm then approve.

**Comment by jakemac53** [comment]
Similarly there are tool list changed events that we may need to listen to

**Review by jakemac53 — APPROVED** [review]
Confirmed that when altering the prompts, `/mcp refresh` now picks up the correct changes.

File: packages/core/src/tools/tool-registry.ts [hunk 1]
```diff
@@ -158,6 +158,18 @@ export class ToolRegistry {
     }
   }
 
+  /**
+   * Removes all tools from a specific MCP server.
+   * @param serverName The name of the server to remove tools from.
+   */
+  removeMcpToolsByServer(serverName: string): void {
```
Comment (NTaylorMullen) [inline packages/core/src/tools/tool-registry.ts:165]: Where's this called?

Comment (Rand0MGem-Ini) [reply packages/core/src/tools/tool-registry.ts:165]: Let me have a look

Comment (haroldmciver-go) [reply packages/core/src/tools/tool-registry.ts:165]: This is being called because the `/mcp refresh` will now remove all existing tools and prompts and then re-discover them from the server. Before, `/mcp refresh`  would still display old tools/prompts, even if the server removed them.

File: packages/cli/src/ui/commands/mcpCommand.ts [hunk 2]
```diff
@@ -507,6 +507,9 @@ const refreshCommand: SlashCommand = {
       await geminiClient.setTools();
     }
 
+    // Reload the slash commands to reflect the changes.
+    context.ui.reloadCommands();
```
[the remark this answers is not in the document]
Comment (haroldmciver-go) [reply packages/cli/src/ui/commands/mcpCommand.ts:514]: Done

**Review by NTaylorMullen — APPROVED** [review]

**Review by chrstnb — APPROVED** [review]
