### PR TITLE
refactor(cli): fully remove React anti patterns, improve type safety and fix UX oversights in SettingsDialog.tsx

### LINKED ISSUE #18980: /settings restart prompt shows even when no restart required settings are different
### What happened?

/settings
Toggle a restart required setting
Observe the restart prompt
Toggle it back to what it was
Observe the restart prompt does not go away

### What did you expect to happen?

users should only be prompted to restart if it will do something for their user experience.

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
#│                                                                                                                                                  │
│ CLI Version                                       0.30.0-nightly.20260212.207ac6f2d                                                              │
│ Git Commit                                        207ac6f2d                                                                                      │
│ Model                                             gemini-3-flash-preview                                                                         │
│ Sandbox                                           no sandbox                                                                                     │
│ OS                                                linux                                                                                          │
│ Auth Method                                       Logged in with Google (***@gmail.com)                                                │
│ Tier                                              Gemini Code Assist for individuals   
```

</details>

### Login information

Oauth

### Anything else we need to know?

_No response_

### LINKED ISSUE #19093: SettingsDialog does not save settings where the value type is not primitive
### What happened?

context.fileFiltering.customIgnoreFilePaths and security.allowedExtensions cannot be edited through the UI

### What did you expect to happen?

Any setting that is shown in the UI should be able to be modified in the UI

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
# │ About Gemini CLI                                                                                                                                              │
│                                                                                                                                                               │
│ CLI Version                                            0.30.0-nightly.20260210.a2174751d                                                                      │
│ Git Commit                                             78130d4bb                                                                                              │
│ Model                                                  gemini-3-flash-preview                                                                                 │
│ Sandbox                                                no sandbox                                                                                             │
│ OS                                                     linux                                                                                                  │
│ Auth Method                                            Logged in with Google (pyushsinha20@gmail.com)                                                         │
│ Tier                                                   Gemini Code Assist for individuals                                                                     │
│                                                                                               
```

</details>

### Login information

_No response_

### Anything else we need to know?

_No response_

### LINKED ISSUE #20077: Settings control + L to clear does not work for restart-required settings
### What happened?

Set respectGitIgnore to false in settings.json
Open gemini cli
Open /Settings
Go to respectGitIgnore 
Press control L
Notice it changes to true
Notice no restart required prompt appear
Exit or dialog or restart app
Open /Settings
Notice it is still false.

### What did you expect to happen?

Should reset to default, remove it from settings.json and save that, and ideally show the restart prompt too.

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about

╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                                        │
│ About Gemini CLI                                                                                                                                       │
│                                                                                                                                                        │
│ CLI Version                                          0.30.0-nightly.20260223.c537fd5ae                                                                 │
│ Git Commit                                           c537fd5ae                                                                                         │
│ Model                                                Auto (Gemini 3)                                                                                   │
│ Sandbox                                              no sandbox                                                                                        │
│ OS                                                   linux                                                                                             │
│ Auth Method                                          Logged in with Google (*@gmail.com)                                                   │
│ Tier                                                 Gemini Code Assist for individuals                                                                │
│                                                                                                 
```

</details>

### Login information

oauth

### Anything else we need to know?

part of the settings dialog having unfortunate react patterns, it makes it hard to define the UX neatly 

related to #18963

### LINKED ISSUE #20795: Vim Mode through /settings always modifies the user scope
### What happened?

Open /settings
Go to workspace scope
Modify vim mode
Go to user scope -- notice it has ALSO been modified here.

### What did you expect to happen?

Should not modify user scope unless we are IN user scope (or use /vim)


### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
│ About Gemini CLI                                                                                                                                                                                             │
│                                                                                                                                                                                                              │
│ CLI Version                                                            0.33.0-nightly.20260228.1ca5c05d0                                                                                                     │
│ Git Commit                                                             703759cfa                                                                                                                             │
│ Model                                                                  Auto (Gemini 3)                                                                                                                       │
│ Sandbox                                                                no sandbox                                                                                                                            │
│ OS                                                                     linux                                                                                                                                 │
│ Auth Method                                                            Logged in with Google (pyushsinha20@gmail.com)                                                                                        │
│ Tier                                                                   Gemini Code Assist for individuals    
```

</details>

### Login information

oauth

### Anything else we need to know?

Identified by @mrpmohiburrahman  [here](https://github.com/google-gemini/gemini-cli/pull/18963#discussion_r2869799526)

### PR DESCRIPTION
**Pull request by psinha40898**
## Summary

Next step from #14915
Removes excessive state and implements maintainable React and type safety patterns in the SettingsDialog component

The approach of synchronizing loose states and batching saves results in code that has hard to read concerns and becomes hard to maintain.

Examples of this can be seen in the restart required prompt which currently
does not toggle off if you toggle the setting back to what it was
does toggle off if you change a default setting to a written value and then press control L
does not toggle on if you use control L to change a non default restart required setting to default

The new dialog would be really easy to follow:

**user changes Setting in the UI -> useSettingsStore triggers a re render -> the component diffs the initial restart required keys with the current -> user sees updated view**

## Details

The SettingsDialog and its corresponding settingsUtil are extremely bloated. Some of this stems from the reliance of a React Anti Pattern that can be removed after #14915 

Instead of managing and syncing many loose React states the SettingsDialog now works in a sensible way.

- The Dialog captures the effective state of all restart required settings that show in the dialog on mount. This represents the current session's instantiation of these settings which require a restart to change.
- The Reactive store hook instantly updates settings and re renders the component which calculates the diff
- From there it derives whether a restart required prompt should show

This removed many inconsistencies like
- Previously asterisks were checked against redundant logic where stars rendered if a setting exists in scope or if it differed from default, but any setting that differs from default must exist in scope in order to do so.
- Not only was the showRestartPrompt state not properly reactive, it was unecessarily held in React state when it could be derived. The same was true for many other React States
- Previously restart required changes were saved as a batch on exit contributing to UX bugs like #18980 and #19232 and #20077
- It lets us remove a bunch of object related utils in settingUtils

Notes:
This retains the current scope-aligned UX, so the restart required prompt will remain active if you add something to scope and toggle it back because that does not remove it from scope. But if you press Control L it will remove the prompt.
Similarly, asterisks continue to show next to Settings that exist in scope (same as main)

Aside from the above improvements, the SettingsDialog retains UX parity with the old implementation.
So stars still appear next to Settings that exist in scope.

final side notes:
**this PR simplifies and improves the type safety and the three es-lint ignores.**
**It has some very sparse changes to AgentConfigDialog to support the new setNestedValue util for similar dialogs** 
**i renamed settingValueExistsInScope to isInSettingsScope** 

## Related Issues

RELATED TO #15840
Fixes #18980
Fixes #19093
Fixes #19232
Fixes #20077
Fixes #20795
## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [ ] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [ ] Validated on required platforms/methods:
  - [ ] MacOS
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

File: packages/cli/src/ui/components/SettingsDialog.tsx [hunk 1]
```diff
@@ -53,13 +44,31 @@ interface SettingsDialogProps {
...
+  merged: Record<string, unknown>,
+): Map<string, string> {
+  const snapshot = new Map<string, string>();
+  // Only track dialog-visible restart settings — non-dialog keys (parent
+  // container objects like mcpServers, tools) can't be changed here.
+  // JSON.stringify for value comparison in case a future showInDialog setting
+  // has an object value (structuredClone breaks reference equality).
+  for (const key of getDialogRestartRequiredSettings()) {
+    const value = getEffectiveValue(key, {}, merged);
+    snapshot.set(key, JSON.stringify(value));
```
Comment (psinha40898) [inline packages/cli/src/ui/components/SettingsDialog.tsx]: JSON.stringify is required because some Settings (that are both restart required AND show in dialog) have Arrays as values. It's also defensive against future settings that may be both restart-required AND show in dialog and have Objects or Arrays as values.

**Review by krsjenmt — APPROVED** [review]

File: packages/cli/src/ui/components/SettingsDialog.tsx (hunk 1 above)
Comment (psinha40898) [reply packages/cli/src/ui/components/SettingsDialog.tsx]: In general this refactor seeks to fully implement UI functionality for settings that have non primitives as values. 

It's included in this refactor because the functionality is kind of a side effect of improved type safety ergonomics just like the reactive restart prompt. It would be messy to split them up IMO. (related #19093)

**Review by psinha40898 — COMMENTED** [review]
Review from Gemini

Excellent work on this refactoring! Transitioning to a centralized settings store significantly simplifies the `SettingsDialog` component and eliminates several React anti-patterns. The code is much cleaner, more maintainable, and the improved type safety for complex types like arrays and objects is a great addition. All tests passed locally, and the logic for handling immediate saves while tracking restart-required settings is robust. Once you're ready to take this out of draft, it's safe to merge.

File: packages/cli/src/ui/components/shared/BaseSettingsDialog.tsx [hunk 2]
```diff
@@ -33,15 +34,17 @@ export interface SettingsDialogItem {
...
   /** Pre-formatted display value (with * if modified) */
   displayValue: string;
   /** Grey out value (at default) */
   isGreyedOut?: boolean;
   /** Scope message e.g., "(Modified in Workspace)" */
   scopeMessage?: string;
   /** Raw value for edit mode initialization */
-  rawValue?: string | number | boolean;
+  rawValue?: SettingsValue;
+  /** Optional pre-formatted edit buffer value for complex types */
```
Comment (psinha40898) [inline packages/cli/src/ui/components/shared/BaseSettingsDialog.tsx:49]: A simple conversion of `rawValue` to string works for primitives but some settings in the UI have values that are not primitives, like arrays

`editValue` allows SettingsDialog to handle the parsing and pass it down to BaseSettingsDialog which allows for non primitive settings like arrays to work through the UI.

File: packages/cli/src/ui/components/SettingsDialog.tsx [hunk 3]
```diff
@@ -53,13 +45,122 @@ interface SettingsDialogProps {
...
+): string | undefined {
+  if (rawValue === undefined) {
+    return undefined;
+  }
+
+  if (type === 'array' && Array.isArray(rawValue)) {
+    return rawValue.join(', ');
+  }
+
+  if (type === 'object' && rawValue !== null && typeof rawValue === 'object') {
```
Comment (psinha40898) [inline packages/cli/src/ui/components/SettingsDialog.tsx]: This ships with support for Settings values that are objects, but no such setting exists in the UI _yet_

File: packages/cli/src/utils/settingsUtils.test.ts [hunk 4]
```diff
@@ -483,7 +480,9 @@ describe('SettingsUtils', () => {
         expect(dialogKeys.length).toBeGreaterThan(0);
       });
 
-      it('should handle nested settings display correctly', () => {
```
Comment (psinha40898) [inline packages/cli/src/utils/settingsUtils.test.ts]: The problem here is that we had a bunch of assertions for the display here and then later in the file we had a bunch more assertions for display.

File: packages/cli/src/utils/settingsUtils.test.ts [hunk 5]
```diff
@@ -938,90 +836,70 @@ describe('SettingsUtils', () => {
...
           'ui.requiresRestart',
           settings,
           mergedSettings,
-          modifiedSettings,
+          restartChangedKeys,
         );
         expect(result).toBe('true*');
       });
 
-      it('should show default value without * when setting does not exist in scope', () => {
```
Comment (psinha40898) [inline packages/cli/src/utils/settingsUtils.test.ts:991]: This all entirely depends on when we want to see the star.

Comments in the series of PRs that introduced this dialog seem contradictory. Some comments suggest the star should only be shown when the setting differs from default. Some comments suggest the star should also be shown when the setting exists in scope.

Chain of comments here suggest that we decided to show the star when a setting is in scope:
https://github.com/google-gemini/gemini-cli/pull/6202/changes#r2281384899

But the PR description itself suggests that we should not do that:
https://github.com/google-gemini/gemini-cli/pull/6202

> Fixed this bug

> this has a default value of false, and you change it to true then back to false, the key now exists in the JSON file with value false, so it shows false* even though false is the default. The * should only appear when the value is actually different from the default, not just when the key exists.

**Review by krsjenmt — APPROVED** [review]

**Review by krsjenmt — APPROVED** [review]

File: packages/cli/src/ui/components/SettingsDialog.tsx [hunk 6]
```diff
@@ -136,52 +162,34 @@ export function SettingsDialog({
...
+  // It checks whether a proposed change from this UI to a settings.json file requires a restart to take effect in the app
+  const pendingRestartRequiredSettings = useMemo(() => {
+    const changed = new Set<string>();
+    const scopes: Array<[string, Settings]> = [
+      ['User', settings.user.settings],
+      ['Workspace', settings.workspace.settings],
+      ['System', settings.system.settings],
+    ];
+
+    // Iterate through the nested map snapshot in activeRestartRequiredSettings, diff with current settings
```
Comment (psinha40898) [inline packages/cli/src/ui/components/SettingsDialog.tsx:170]: The diffing of restart required settings across scope here is the heart of the UX. This diffs the settings files on component mount with the current settings (updated as soon as a user toggles)

The purpose of the diff is to handle the user experience for restart required settings

**Alternatively, we could read the restart required settings that are currently active to use changes pending against application restart instead of changes pending against component re mount, but this would require some greater code changes.**

File: packages/cli/src/utils/settingsUtils.test.ts [hunk 7]
```diff
@@ -22,18 +22,10 @@ import {
   getDialogSettingsByCategory,
   getDialogSettingsByType,
   getDialogSettingKeys,
-  // Business logic utilities
-  getSettingValue,
-  isSettingModified,
+  // Business logic utilities,
   TEST_ONLY,
-  settingExistsInScope,
```
Comment (psinha40898) [inline packages/cli/src/utils/settingsUtils.test.ts:29]: Utils that were designed to interact with bloated react states and mutable objects were all removed

File: packages/cli/src/utils/settingsUtils.ts [hunk 8]
```diff
@@ -120,45 +104,62 @@ export function getEffectiveDefaultValue(
...
 
 /**
- * Get the effective value for a setting, considering inheritance from higher scopes
- * Always returns a value (never undefined) - falls back to default if not set anywhere
+ * Get the effective value for a setting falling back to the default value
  */
 export function getEffectiveValue(
   key: string,
   settings: Settings,
-  mergedSettings: Settings,
```
Comment (psinha40898) [inline packages/cli/src/utils/settingsUtils.ts:161]: this guy was never called with this parameter in the component code. he was always called with an empty mergedSettings which meant it never checked for an inherited value.

File: packages/cli/src/utils/settingsUtils.ts [hunk 9]
```diff
@@ -120,45 +104,62 @@ export function getEffectiveDefaultValue(
...
+export function getDialogRestartRequiredSettings(): string[] {
+  return Object.values(getFlattenedSchema())
+    .filter(
+      (definition) =>
+        definition.requiresRestart && definition.showInDialog !== false,
+    )
+    .map((definition) => definition.key);
+}
+
+export function isRecord(value: unknown): value is Record<string, unknown> {
```
Comment (psinha40898) [inline packages/cli/src/utils/settingsUtils.ts:127]: Instead of eslint ignoring lines this allows us to tell Typescript 
"If value returns true then it is certainly" a `SettingsValue` (or a `Record<string, unknown>` for isRecord)
Zod runtime validation would be better because isRecord is sloppy, but for this PR it was fine. (because u should use zod runtime validation in these situations or if its not crossing boundaries, then ur types should be defined in a way where u dont need predicates)

File: packages/cli/src/utils/settingsUtils.ts [hunk 10]
```diff
@@ -120,45 +104,62 @@ export function getEffectiveDefaultValue(
...
+    type === 'number' ||
+    type === 'boolean' ||
+    type === 'object'
+  );
+}
+
+/**
+ * Gets a value from a nested object using a key path array iteratively.
+ */
+export function getNestedValue(obj: unknown, path: string[]): unknown {
```
Comment (psinha40898) [inline packages/cli/src/utils/settingsUtils.ts:146]: This removes type assertions by accepting unknown. Notably iterating down a type of the previous unsafe assertion Record<string, unknown> results in iterating into unknown anyway.

The type predicate in isRecord removes the eslint disable because our type predicate narrows the type instead of an assertion

I think there has got to be a better way with purely Typescript compile but it might require changes to the settings schemas and could be done separately.

For now replacing eslint ignores and type assertions with two type predicates seems to at least document whats going on much better

File: packages/cli/src/utils/settingsUtils.ts [hunk 11]
```diff
@@ -168,33 +169,19 @@ export function getEffectiveValue(
...
-    // eslint-disable-next-line @typescript-eslint/no-unsafe-type-assertion
-    return value as SettingsValue;
-  }
-
-  // Check the merged settings for an inherited value
-  value = getNestedValue(mergedSettings as Record<string, unknown>, path);
-  if (value !== undefined) {
-    // eslint-disable-next-line @typescript-eslint/no-unsafe-type-assertion
-    return value as SettingsValue;
+  const value = getNestedValue(settings, path);
```
Comment (psinha40898) [inline packages/cli/src/utils/settingsUtils.ts:172]: Same thing here, the type predicate replaces the eslint disables and type assertions potentially pending larger scale changes

File: packages/cli/src/ui/components/AgentConfigDialog.tsx [hunk 12]
```diff
@@ -111,45 +112,30 @@ interface AgentConfigDialogProps {
   onSave?: () => void;
 }
 
-/**
- * Get a nested value from an object using a path array
```
Comment (psinha40898) [inline packages/cli/src/ui/components/AgentConfigDialog.tsx:115]: The changes here can be reverted to reduce the scope of the PR.

**Review by jacob314 — APPROVED** [review]
lgtm

Approved once fix for alternate buffer mode lands.

File: packages/cli/src/ui/components/SettingsDialog.tsx [hunk 13]
```diff
@@ -292,303 +298,81 @@ export function SettingsDialog({
...
-        // Record pending change globally
-        setGlobalPendingChanges((prev) => {
-          const next = new Map(prev);
-          // eslint-disable-next-line @typescript-eslint/no-unsafe-type-assertion
-          next.set(key, newValue as PendingValue);
-          return next;
+      // Special handling for vim mode to sync with VimModeContext
+      if (key === 'general.vimMode' && newValue !== vimEnabled) {
+        toggleVimEnabled().catch((error) => {
+          coreEvents.emitFeedback('error', 'Failed to toggle vim mode:', error);
```
Comment (mrpmohiburrahman) [inline packages/cli/src/ui/components/SettingsDialog.tsx]: @psinha40898 @jacob314 

While testing locally, I caught a subtle edge case
that breaks the intended `general.vimMode` scope isolation!

In here (line 313 ) and line 348 calling `toggleVimEnabled()` successfully updates the runtime Vim UI state.

However, it unintentionally writes the setting to the user's global scope
because the pre-existing `toggleVimEnabled` function in`VimModeContext.tsx`
hardcodes `SettingScope.User` at [`L56`](https://github.com/google-gemini/gemini-cli/blob/703759cfaec1ccb545c5c4e6381cf74577d9d6ca/packages/cli/src/ui/contexts/VimModeContext.tsx#L56).

 **The resulting bug:**

 1. User opens Settings, correctly selects the `Workspace` scope.
 2. User toggles `general.vimMode`.
 3. `SettingsDialog.tsx` rightly targets the Workspace:
    `setSetting('Workspace', ...)`
 4. `SettingsDialog` then explicitly calls `toggleVimEnabled()` to update the
    UI on the fly.
 5. `VimModeContext.tsx` strictly executes `settings.setValue('User', ...)`
 6. _Result:_ The user intended to update their local workspace, but
    accidentally overwrote their global configuration too.

### Suggested Minimal Fix

Since `SettingsDialog` already handles the correct scoped file write perfectly,
we just need `VimModeContext` to update its React state without touching the
disk again.

**1. Export a new UI-only method in `VimModeContext.tsx`:**

```diff
 interface VimModeContextType {
   vimEnabled: boolean;
   vimMode: VimMode;
   toggleVimEnabled: () => Promise<boolean>;
+   setRuntimeVimEnabled: (newValue: boolean) => void;
   setVimMode: (mode: VimMode) => void;
 }

// ... inside VimModeProvider (around line 60) ...

+  const setRuntimeVimEnabled = useCallback((newValue: boolean) => {
+    setVimEnabled(newValue);
+    if (newValue) {
+      setVimMode('INSERT');
+    }
+  }, []);
+
   const value = {
     vimEnabled,
     vimMode,
     toggleVimEnabled,
+     setRuntimeVimEnabled,
     setVimMode,
   };
```

**2. Swap the calls in `SettingsDialog.tsx`:** Instead of calling
`toggleVimEnabled()`, grab the new method from the context:

```tsx
const { vimEnabled, setRuntimeVimEnabled } = useVimMode();
```

And replace the calls at line `313` and line `348` with
`setRuntimeVimEnabled(newValue);`.

Comment (psinha40898) [reply packages/cli/src/ui/components/SettingsDialog.tsx]: Thank you for testing this out! I think the best solution might actually be removing the special case from the dialog, treating vim as a regular setting. The store pattern should take care of the rest. 

[edited]

Notably this is not any regression it's just an oversight, another case where a UX bug can be fixed by simply removing code and letting the store pattern do its thing. So this bug is actually on main too

Thank you
