### PR TITLE
fix(mcp): fix MCP server removal not persisting to settings

### LINKED ISSUE #9766: MCP Removal not working correctly
### What happened?

```
> gemini mcp remove playwright
Server "playwright" not found in project settings.

> gemini mcp remove playwright -s user
Server "playwright" removed from user settings.

> gemini mcp list

...playwright - Connected
```
It reported removed every time, but the mcp list always showed it there

### What did you expect to happen?

The MCP server to not be on the list 

(Replacing it with chrome-devtools is why)

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
╭────────────────────────────────────────╮
│                                        │
│ About Gemini CLI                       │
│                                        │
│ CLI Version  0.6.1                     │
│ Git Commit   f3078136                  │
│ Model        gemini-2.5-pro            │
│ Sandbox      no sandbox                │
│ OS           darwin                    │
│ Auth Method  OAuth                     │
│                                        │
╰────────────────────────────────────────╯
```

</details>

### Login information

Google Account

### Anything else we need to know?

Upgraded from a prev version about a month or so ago, unsure which version, that's about when I added playwright.

I had it installed on MacOS host AND Windows under parallels, both reported the same success message but neither actually removed anything.

### PR DESCRIPTION
**Pull request by lifefloating**
## TLDR

Fixed issue where `gemini mcp remove` command would report success but the MCP server would still appear in `gemini mcp list`. The problem was in the JSON settings update logic not properly removing keys from nested objects like `mcpServers`.

## Dive Deeper

The issue was in `commentJson.ts` where the `applyUpdates` function wasn't properly handling key deletion for nested objects. When removing an MCP server, the settings update would merge the new object but wouldn't delete keys that were no longer present in the desired state.

Key changes:
- Added `applyKeyDiff` function that properly handles object key deletion by first removing keys not present in the desired state
- Special handling for `mcpServers` field to ensure proper key removal
- Enhanced array handling to preserve comments while updating content in-place
- Added comprehensive tests covering various deletion scenarios

The fix ensures that when an MCP server is removed from settings, it's actually deleted from the configuration file rather than just being reported as removed.

## Reviewer Test Plan

1. Add an MCP server: `node bundle/gemini.js mcp add playwright`
2. Verify it appears: `node bundle/gemini.js mcp list`
3. Remove the server: `node bundle/gemini.js mcp remove playwright -s user`
4. Verify it's gone: `node bundle/gemini.js mcp list` (should not show playwright)
5. Check the settings file to confirm the server entry is actually removed

Test with both project (`-s project`) and user (`-s user`) settings scopes.

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | ✅  | ❓  | ❓  |

## Linked issues / bugs

Fixes #9766

### CODE REVIEW

File: packages/cli/src/utils/commentJson.ts [hunk 1]
```diff
@@ -44,8 +44,69 @@ function applyUpdates(
...
+      if (isValObj && isResultObj) {
+        applyKeyDiff(
+          result[key] as Record<string, unknown>,
+          value as Record<string, unknown>,
+        );
+      } else {
+        result[key] = value;
+      }
+      continue;
+    }
```
Comment (Lyonk71) [inline packages/cli/src/utils/commentJson.ts]: It looks like you're being surgical by special-casing `mcpServers`, but this bug isn't unique to that key. Consider using `applyKeyDiff` universally in `applyUpdates` and removing the special case. That keeps the utility generic, prevents future special cases, and enforces consistent "sync by omission" (add/update/delete) semantics across all nested objects. Tests that assume merge-only behavior would need updates, and we should verify no callers rely on preserving unspecified keys.

**Review by Lyonk71 — CHANGES_REQUESTED** [review]

File: packages/cli/src/utils/commentJson.ts (hunk 1 above)
Comment (jacob314) [reply packages/cli/src/utils/commentJson.ts]: +1 to handling this generically rather than for just mcpServers.

Comment (lifefloating) [reply packages/cli/src/utils/commentJson.ts]: Okay, thank you for your review. You're absolutely right. My change was only limited to the mcpServers, which was a bit too cautious.

**Comment by lifefloating** [comment]
hi, I have re-adjusted the code, and here are some notes I've organized. Here, we need to delete the normal parts while keeping the annotated JSON sections. Regarding the issue with annotated JSON, someone has raised it before: https://github.com/google-gemini/gemini-cli/issues/8077

### **Unified sync semantics**
- Removed the special-case for `mcpServers`. All nested objects now follow "sync-by-omission" (add/update/delete) consistently.

### **Preserve comments on key deletion**
Before deleting a property, we migrate its comments so they aren't lost:
- Prefer moving to the next sibling's `before` comments.
- If no next sibling, move to the previous sibling's `after` comments.
- If no siblings, attach to the container-level `before/after`.
- This ensures commented-out sibling blocks remain (e.g., removing `mcpServers.playwright` does not remove the commented `sleep` block).

### **Arrays keep comments**
Arrays are updated in-place (clear + push) so array-level comments are preserved.

### **Safe failure behavior**
If parsing fails, we log errors and do not write back, avoiding content loss.

### **Test coverage**
- **Added**: deleting a key preserves sibling-level commented blocks.
- **Updated**: nested object sync-by-omission expectations.
- **Retained/covered**: basic comment preservation, complex scenarios, corrupted JSON handling, arrays, and type conversion.

File: packages/cli/src/utils/commentJson.ts [hunk 2]
```diff
@@ -38,12 +38,115 @@ export function updateSettingsFilePreservingFormat(
...
+ *
+ * This function re-attaches comments to the next sibling's leading comments if
+ * available, otherwise to the previous sibling's trailing comments, otherwise
+ * to the container's leading/trailing comments.
+ */
+function preserveCommentsOnPropertyDeletion(
+  container: Record<string, unknown>,
+  propName: string,
+): void {
+  // eslint-disable-next-line @typescript-eslint/no-explicit-any
```
Comment (galdawave) [inline packages/cli/src/utils/commentJson.ts]: Can we add typing for this, if the target is the same type as container we can set it to `Record<string, unknown>`

File: packages/cli/src/utils/commentJson.ts [hunk 3]
```diff
@@ -38,12 +38,115 @@ export function updateSettingsFilePreservingFormat(
...
+  }
+}
+
 function applyUpdates(
   current: Record<string, unknown>,
   updates: Record<string, unknown>,
 ): Record<string, unknown> {
   const result = current;
 
+  function applyKeyDiff(
```
Comment (galdawave) [inline packages/cli/src/utils/commentJson.ts]: Nit: for readability can we move this out of the applyUpdates function

File: packages/cli/src/utils/commentJson.ts [hunk 4]
```diff
@@ -38,12 +38,115 @@ export function updateSettingsFilePreservingFormat(
...
+    base: Record<string, unknown>,
+    desired: Record<string, unknown>,
+  ): void {
+    for (const existingKey of Object.getOwnPropertyNames(base)) {
```
Comment (galdawave) [inline packages/cli/src/utils/commentJson.ts]: It looks like there's a difference in how top-level properties and nested properties are updated. Omitted keys get deleted from nested objects (a sync), but at the top level, they're preserved (a merge).

For example, if I have a config like 
```
{ "top": 1, "nested": { "a": 2, "b": 3 } } 
```
and I apply an update like
```
{ "nested": { "a": 2 } }
``` 
the nested.b key is removed, but the top key is kept. I think this could lead to some subtle bugs if a caller expects the same behavior everywhere.

I think we should make applyKeyDiff logic consistent for both nested and not nested objects.

**Review by galdawave — CHANGES_REQUESTED** [review]

File: packages/cli/src/utils/commentJson.test.ts [hunk 5]
```diff
@@ -178,5 +181,146 @@ describe('commentJson', () => {
...
+        mcpServers: {},
+      });
+
+      const updatedContent = fs.readFileSync(testFilePath, 'utf-8');
+      expect(updatedContent).toContain('// "sleep": {');
+      expect(updatedContent).toContain('"mcpServers"');
+      expect(updatedContent).not.toContain('"playwright"');
+    });
+
+    it('should handle type conversion from object to array', () => {
```
Comment (galdawave) [inline packages/cli/src/utils/commentJson.test.ts:307]: one last thing :), can you add a test to validate that both nested and non nested objects will be removed

**Review by galdawave — APPROVED** [review]

File: packages/cli/src/utils/commentJson.test.ts (hunk 5 above)
Comment (lifefloating) [reply packages/cli/src/utils/commentJson.test.ts:307]: ok  later i add

Comment (lifefloating) [reply packages/cli/src/utils/commentJson.test.ts:307]: ok i added it @galz10

**Review by jackwotherspoon — COMMENTED** [review]
@lifefloating I think we also probably want to update the `gemini mcp remove` tests so that they would catch this kind of regression in the future. As right now the command is broken and there are no tests indicating that... which means the tests may be a bit shallow.


Tests in question: https://github.com/google-gemini/gemini-cli/blob/main/packages/cli/src/commands/mcp/remove.test.ts

I can do this as a follow-up PR if needed but this PR is fixing the broken command so would be nice to have a test that fails on main and is passing against this branch 😄

**Comment by lifefloating** [comment]
> @lifefloating I think we also probably want to update the `gemini mcp remove` tests so that they would catch this kind of regression in the future. As right now the command is broken and there are no tests indicating that... which means the tests may be a bit shallow.
> 
> Tests in question: https://github.com/google-gemini/gemini-cli/blob/main/packages/cli/src/commands/mcp/remove.test.ts
> 
> I can do this as a follow-up PR if needed but this PR is fixing the broken command so would be nice to have a test that fails on main and is passing against this branch 😄

  Good point! I'll add an integration test for `gemini mcp remove` that:

  1. Creates a real settings file with multiple MCP servers
  2. Runs the remove command
  3. Verifies the file content after deletion (server removed, others preserved, comments kept)

  This will indeed catch regressions where the command appears to work but doesn't actually modify the file.

  I'll push this update shortly.

**Comment by lifefloating** [comment]
> @lifefloating I think we also probably want to update the `gemini mcp remove` tests so that they would catch this kind of regression in the future. As right now the command is broken and there are no tests indicating that... which means the tests may be a bit shallow.
> 
> Tests in question: https://github.com/google-gemini/gemini-cli/blob/main/packages/cli/src/commands/mcp/remove.test.ts
> 
> I can do this as a follow-up PR if needed but this PR is fixing the broken command so would be nice to have a test that fails on main and is passing against this branch 😄

thanks, i have updated it

**Review by jackwotherspoon — APPROVED** [review]

**Review by jacob314 — APPROVED** [review]
