### PR TITLE
fix(cli): exclude update_topic from confirmation queue count

### LINKED ISSUE #24944: [BUG] update_topic tool inflates confirmation queue count
---
name: Bug report
about: Create a report to help us improve
title: "[BUG] update_topic tool inflates confirmation queue count"
labels: ["🔒 maintainer only", "bug"]
assignees: []

---

**Describe the bug**
The `update_topic` tool is an auto-executing background operation that does not require user interaction. However, it is currently included in the calculation of the tool confirmation queue size. This causes the UI to show misleading counts (e.g., "1 of 2") when only one actionable tool (like a shell command) is actually pending.

**To Reproduce**
1. Trigger a turn that includes both an `update_topic` call and a tool requiring approval (e.g., `run_shell_command`).
2. Observe the tool confirmation dialogue.
3. The dialogue shows "1 of 2" instead of "1 of 1".

**Expected behavior**
Background tools like `update_topic` should be excluded from the confirmation queue count.

**Screenshots**
(Provided by user)

**Desktop (please complete the following information):**
 - OS: darwin
 - Version: 0.36.0-nightly

### PR DESCRIPTION
**Pull request by Abhijit-2592**
## Summary

This PR centralizes tool visibility logic to fix UI inconsistencies, such as the `update_topic` tool inflating the confirmation queue count ("X of Y").

## Details

The logic that dictates whether a tool call should be visible in the chat history, the active tool group, or the confirmation queue was previously fragmented across the codebase (`ToolGroupMessage.tsx`, `confirmingTool.ts`, `useGeminiStream.ts`). 

Specifically, the `update_topic` tool is an auto-executing background operation that does not require user interaction. Because it was included in the calculation of the tool confirmation queue size in `confirmingTool.ts`, the UI showed misleading counts (e.g., "1 of 2") when only one actionable tool was actually pending.

This PR introduces a unified `tool-visibility` utility in the core package that exposes three semantic methods:
- `isRenderedInHistory`
- `requiresUserConfirmation`
- `isVisibleInToolGroup`

This cleanly resolves UI inconsistencies by providing a single source of truth for tool visibility state, removing the need for the UI to manually check against specific tool names like `update_topic`.

### Before
Queue count shows "1 of 2" when an `update_topic` tool is executing alongside another actionable tool.

### After
Queue count accurately shows "1 of 1", excluding background narrative updates.

## Related Issues

Fixes #24944

## How to Validate

1. Run `npm test -w @google/gemini-cli-core -- src/utils/tool-visibility.test.ts` to ensure the core rules are functioning correctly.
2. Run `npm test -w @google/gemini-cli` to ensure existing UI tests pass.
3. Manually verify by triggering a turn with `update_topic` and another tool; the count should only reflect actionable tools.

## Pre-Merge Checklist

[ ] Updated relevant documentation and README (if needed)
[x] Added/updated tests (if needed)
[ ] Noted breaking changes (if any)
[x] Validated on required platforms/methods:
  [x] MacOS
    [x] npm run

### CODE REVIEW

File: packages/cli/src/ui/utils/confirmingTool.ts [hunk 1]
```diff
@@ -33,14 +37,20 @@ export function getConfirmingToolState(
     return null;
   }
 
+  const filteredPendingTools = allPendingTools.filter(
+    (tool) =>
+      tool.name !== UPDATE_TOPIC_TOOL_NAME &&
+      tool.name !== UPDATE_TOPIC_DISPLAY_NAME,
+  );
```
[the remark this answers is not in the document]
Comment (Abhijit-2592) [reply packages/cli/src/ui/utils/confirmingTool.ts]: Mmm this is the simplest solution to the problem. As long as we aren't directly using the string, we should be Good. Any other solution will add unnecessary extra code affecting readability. I think the logic is very clear here in-terms of readability. I don't want to add an unnecessary interface just for one tool. In the future, if there is another similar tool then we can think about generalizing it.

[the remark this answers is not in the document]
Comment (jacob314) [reply packages/cli/src/ui/utils/confirmingTool.ts]: there is already some other filtering logic. please find and add to that rather than adding additional filter logic

**Review by scidomino — APPROVED** [review]

File: packages/cli/src/ui/utils/confirmingTool.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (Abhijit-2592) [reply packages/cli/src/ui/utils/confirmingTool.ts]: Not relevant anymore as I completely re-wrote this

File: packages/core/src/utils/tool-visibility.ts [hunk 2]
```diff
@@ -0,0 +1,119 @@
...
+      // In Plan Mode, edits are redundant because the plan shows the diffs.
+      return ctx.approvalMode !== ApprovalMode.PLAN;
+
+    default:
+      return true;
+  }
+}
+
+/**
+ * Determines if a tool belongs in the Awaiting Approval confirmation queue.
```
Comment (jacob314) [inline packages/core/src/utils/tool-visibility.ts:92]: nit: this comment is a better method name than the method name.

File: packages/cli/src/ui/utils/confirmingTool.ts [hunk 3]
```diff
@@ -33,14 +36,26 @@ export function getConfirmingToolState(
     return null;
   }
 
+  const actionablePendingTools = allPendingTools.filter((tool) =>
+    requiresUserConfirmation({
```
Comment (jacob314) [inline packages/cli/src/ui/utils/confirmingTool.ts]: optional nit: all these parmeters are directly from the tool. Can we pass in the tool directly or have the tool implement an interface so we can just pass in the tool. it would make calling this api a little cleaner

File: packages/cli/src/ui/utils/historyUtils.ts [hunk 4]
```diff
@@ -79,5 +80,16 @@ export function getAllToolCalls(
 ): IndividualToolCallDisplay[] {
   return historyItems
     .filter((item): item is HistoryItemToolGroup => item.type === 'tool_group')
-    .flatMap((group) => group.tools);
+    .flatMap((group) => group.tools)
+    .filter((tool) =>
+      isRenderedInHistory({
+        name: tool.name,
```
Comment (jacob314) [inline packages/cli/src/ui/utils/historyUtils.ts]: another case where all params are just from a tool so we should be able to just pass in the tool

File: packages/core/src/utils/tool-visibility.ts [hunk 5]
```diff
@@ -0,0 +1,119 @@
...
+import { CoreToolCallStatus } from '../scheduler/types.js';
+import {
+  ASK_USER_DISPLAY_NAME,
+  WRITE_FILE_DISPLAY_NAME,
+  EDIT_DISPLAY_NAME,
+  UPDATE_TOPIC_TOOL_NAME,
+  UPDATE_TOPIC_DISPLAY_NAME,
+} from '../tools/tool-names.js';
+
+export interface ToolVisibilityContext {
```
Comment (jacob314) [inline packages/core/src/utils/tool-visibility.ts:17]: nit: can we make this just be a subset of the Tool interface and maybe a couple extra params?

**Comment by jacob314** [comment]
Overall, the logic centralization into `packages/core` looks solid and adheres nicely to the architectural boundaries. The cleanup in the React components makes the codebase much easier to read!

One point of potential improvement I noticed:
**Code Duplication (DRY):** The `ToolVisibilityContext` object is constructed inline in four different files (`ToolGroupMessage.tsx`, `useGeminiStream.ts`, `confirmingTool.ts`, and `historyUtils.ts`).

*Suggestion:* Consider creating a small helper function in `packages/cli` (e.g., `buildToolVisibilityContext(tool: IndividualToolCallDisplay)`) to map a tool instance to the context object. This would reduce the boilerplate currently duplicated across these files.

Besides that minor point, I've verified that the extracted logic matches what was previously there, so there don't appear to be any unintended side-effects or behavior changes.

File: packages/core/src/utils/tool-visibility.ts (hunk 2 above)
Comment (Abhijit-2592) [reply packages/core/src/utils/tool-visibility.ts:92]: Done. Renamed the method to `belongsInConfirmationQueue` for better semantic clarity.

File: packages/cli/src/ui/utils/confirmingTool.ts (hunk 3 above)
Comment (Abhijit-2592) [reply packages/cli/src/ui/utils/confirmingTool.ts]: Done. Implemented `buildToolVisibilityContext` (core) and `buildToolVisibilityContextFromDisplay` (cli) helpers. All call sites now pass tool objects directly through these translators, which also centralized the mapping logic and removed the duplication across the UI.

File: packages/cli/src/ui/utils/historyUtils.ts (hunk 4 above)
Comment (Abhijit-2592) [reply packages/cli/src/ui/utils/historyUtils.ts]: Done. Unified the call sites to use the new visibility context helpers.

File: packages/core/src/utils/tool-visibility.ts (hunk 5 above)
Comment (Abhijit-2592) [reply packages/core/src/utils/tool-visibility.ts:17]: Done. Refactored `ToolVisibilityContext` to be a subset of the standard tool call interface (using `parentCallId` instead of `hasParent`, etc.).

**Comment by Abhijit-2592** [comment]
I have addressed all of the review feedback:
1. **Centralized Visibility Logic**: Refactored the core visibility rules to use a unified `ToolVisibilityContext`.
2. **Reduced Boilerplate (DRY)**: Implemented helper methods in both Core and CLI to map complex tool objects to the visibility context. All call sites now pass tool objects directly through these helpers.
3. **Improved Naming**: Renamed `requiresUserConfirmation` to `belongsInConfirmationQueue`.
4. **Interface Alignment**: Refactored the visibility context to be a clean subset of the standard tool call interface.

All tests are passing locally and the branch has been rebased onto main.

**Review by jacob314 — APPROVED** [review]
lgtm
