### PR TITLE
fix(core)!: Force policy config to specify toolName

### LINKED ISSUE #20635: Typo in policy inadvertently allows all tools
### What would you like to be added?

a policy entry with a typo like:

```
[[rule]]
toolname = "glob"
decision = "allow"
priority = 200
```

will inadvertently allow all tools (notice the lower case `toolname` vs `toolName`).

Suggestion is to reject policy entries with unexpected fields.

### Why is this needed?

It is very subtle and seems like dangerous behavior to parse this policy as "allow all tools"

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kschaab**
This prevents accidental configuration of all tools by misconfiguring a rule without a toolname.

## Summary

This prevents a possible issue where a user can accidentally misconfigure a policy rule by not specifying toolName.  Note this can break existing policies!

## Details

This change forces toolName to be specified requiring all policies that will match all tools to specifying `*` as the toolName.  This provides protection against accidental policy configuration to apply to too many tools by either not specifying toolName or by misconfiguring it via typo.  While this change provides safety it also can break existing policy configurations.  This could be due to misconfiguration in the case of #20635 or an intentional configuration implying all tools by not specifying `toolName`.

## Related Issues

Fixes #20635

## How to Validate

This can be validated by providing a policy that is configured without `toolName`.

## Pre-Merge Checklist

- [X] Updated relevant documentation and README (if needed)
- [X] Added/updated tests (if needed)
- [X] Noted breaking changes (if any)
- [X] Validated on required platforms/methods:
  - [ ] MacOS
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [X] Linux
    - [X] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

File: packages/cli/src/test-utils/AppRig.tsx [hunk 1]
```diff
@@ -433,7 +433,7 @@ export class AppRig {
   ) {
     if (!this.config) throw new Error('AppRig not initialized');
     this.config.getPolicyEngine().addRule({
-      toolName,
+      toolName: toolName ?? '*',
```
Comment (jacob314) [inline packages/cli/src/test-utils/AppRig.tsx]: nit: can we just change the tests to pass in toolName or '*' rather than having tests align more with the previous behavior than the new behavior.

**Review by jacob314 — APPROVED** [review]
lgtm

File: packages/cli/src/test-utils/AppRig.tsx (hunk 1 above)
Comment (kschaab) [reply packages/cli/src/test-utils/AppRig.tsx]: Sure this seems like it reduces the amount of changed code, thanks!

**Review by Abhijit-2592 — APPROVED** [review]
Not sure why this needs Prompt-Mode Approvers as I don't see any prompt changes. Approving to unblock @kschaab
