### PR TITLE
fix: /help remove flickering and respect clear shortcut (ctr+l)

### LINKED ISSUE #3224: cli jumping each keystroke after /help request
### What happened?

The cli interface is jumping on every keystroke (flickers, twitches) after the /help request until the next request is executed or fullscreen mode is enabled

### What did you expect to happen?

stable behavior w/o reactions on keystrokes

### Client information

*   **CLI Version:** 0.1.9
*   **Git Commit:** 34935d6
*   **Operating System:** win32 v24.3.0
*   **Sandbox Environment:** no sandbox
*   **Model Version:** gemini-2.5-pro
*   **Memory Usage:** 142.1 MB

### Login information

Google account, Workspace.

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by psinha40898**
## TLDR
Currently, from a UX perspective the keyboard shortcut to clear does not clear the output from the help command.

## Dive Deeper
Help is changed from its own component in App.tsx outside of Static to a regular history item like /about

### Clear
Before, the help dialog was its own React component in App.tsx, and the state it was attached to was not incorporated in the clear shortcut.

Now, help is rendered just like about -- into the HistoryItemDisplay under Static.

All those items are already respecting ctrl + l, so now help does too.

### Flickering

For components rendered outside of Static in Ink:
From Ink:
```
174		if (outputHeight >= this.options.stdout.rows) {
			this.options.stdout.write(
				ansiEscapes.clearTerminal + this.fullStaticOutput + output,
			);
			this.lastOutput = output;
			return;
		}
```
`outputHeight` represents only the dynamic (non-static) content,

reference: https://github.com/vadimdemedes/ink
https://github.com/vadimdemedes/ink/blob/a31d76d0/src/ink.tsx

If the `outputHeight ` (the height of the rendered content) is greater than or equal to `this.options.stdout.rows` (the number of rows in the terminal), Ink will clear the entire terminal using `ansiEscapes.clearTerminal` before writing the new output. ink.tsx:173-176 

This full clear and redraw is what causes the visible flickering, especially for larger components like Help that occupy a significant portion of the terminal height. 

## Reviewer Test Plan

Pull the code
Run the branch
Type /help
Use the command control+L to clear the screen
It should set the state to false and provide the intended UX

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | ✅  | ✅  | ✅  |
| npx      | ✅  | ✅  | ✅  |
| Docker   | ❓  | ❓  | ❓  |
| Podman   | ❓  | -   | -   |
| Seatbelt | ❓  | -   | -   |

## Linked issues / bugs

Fixes #3453 
Fixes #3224

### CODE REVIEW

File: packages/cli/src/ui/components/InputPrompt.tsx [hunk 1]
```diff
@@ -208,6 +210,7 @@ export const InputPrompt: React.FC<InputPromptProps> = ({
 
       if (key.ctrl && key.name === 'l') {
         onClearScreen();
+        setShowHelp(false);
         return;
       }
```
[the remark this answers is not in the document]
Comment (psinha40898) [reply packages/cli/src/ui/components/InputPrompt.tsx]: `onClearScreen()` clears the rendered history. The help command is not within the rendered history and exists within its own React State in `App.tsx`. This is beneficial because it would be wasteful to consistently add the help command's results to the CLI's history.

**Comment by jacob314** [comment]
Sorry for the slow review. I'd suggest we resolve this by fixing how help is rendered. help should just render is a message rather than its own ui. that way it can just be included in the history and will clear normally. That will also resolve flickering in the history.

**Comment by psinha40898** [comment]
> Sorry for the slow review. I'd suggest we resolve this by fixing how help is rendered. help should just render is a message rather than its own ui. that way it can just be included in the history and will clear normally. That will also resolve flickering in the history.

Sorry I totally accidentally commented on the issue instead of replying here. Deleted that 

If /help should render in the Static HistoryItemDisplay just like /about (as a message) I pushed those changes and will resolve conflicts when home. Ty for checking

**Comment by jacob314** [comment]
> > Sorry for the slow review. I'd suggest we resolve this by fixing how help is rendered. help should just render is a message rather than its own ui. that way it can just be included in the history and will clear normally. That will also resolve flickering in the history.
> 
> Sorry I totally accidentally commented on the issue instead of replying here. Deleted that
> 
> If /help should render in the Static HistoryItemDisplay just like /about (as a message) I pushed those changes and will resolve conflicts when home. Ty for checking

Fantastic! It looks great now. I will approve as soon as conflicts are resolved.

**Comment by psinha40898** [comment]
> > > Sorry for the slow review. I'd suggest we resolve this by fixing how help is rendered. help should just render is a message rather than its own ui. that way it can just be included in the history and will clear normally. That will also resolve flickering in the history.
> > 
> > 
> > Sorry I totally accidentally commented on the issue instead of replying here. Deleted that
> > If /help should render in the Static HistoryItemDisplay just like /about (as a message) I pushed those changes and will resolve conflicts when home. Ty for checking
> 
> Fantastic! It looks great now. I will approve as soon as conflicts are resolved.

Resolved. As always, thank you so much for the review!

**Comment by psinha40898** [comment]
@jacob314 It should be good now. 

I had to push a change (automerge off) b.c of new tests in main that relied on the old help -- my mistake to not update the branch earlier.

Thank you and sorry about that

**Comment by psinha40898** [comment]
Can I get some clarification if we are going with this PR or #5196 instead, since they overlap? 
This PR was meant to be atomic as possible and opened 3 weeks ago if that matters
I hope this friendly tag for the reviewer of that PR is okay

Thank you
@allenhutchison

File: packages/cli/src/ui/commands/helpCommand.ts [hunk 2]
```diff
@@ -4,18 +4,19 @@
  * SPDX-License-Identifier: Apache-2.0
  */
 
-import { CommandKind, OpenDialogActionReturn, SlashCommand } from './types.js';
+import { CommandKind, SlashCommand } from './types.js';
+import { MessageType, type HistoryItemHelp } from '../types.js';
 
 export const helpCommand: SlashCommand = {
   name: 'help',
-  altNames: ['?'],
```
Comment (jacob314) [inline packages/cli/src/ui/commands/helpCommand.ts:11]: please add back altNames and then I'll approve

**Review by jacob314 — COMMENTED** [review]
Thanks for the fix! Everything looks good except for altNames being missing.
You can repro by testing whether typing `/? works.

Like how small and simple this change ended up.

File: packages/cli/src/ui/commands/helpCommand.ts (hunk 2 above)
Comment (psinha40898) [reply packages/cli/src/ui/commands/helpCommand.ts:11]: Thank you!

**Review by jacob314 — APPROVED** [review]
lgtm
