### PR TITLE
fix: expand paste placeholders in TextInput on submit

### LINKED ISSUE #19238: Collapsed paste doesn't work in Ask User
### What happened?

I had an open "Ask User" where the model wanted to know if I wanted to do anything else. I pasted an error message as a response, but it seemed to be sent through as a literal:

```console
╭──────────────────────────────────────────────────────────────────────────────────────────╮
│ ✓  Ask User                                                                              │
│                                                                                          │
│ User answered:                                                                           │
│   Task Completed → [Pasted Text: 19 lines]                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────╯
✦ I am unable to see the content you pasted; it appears as "[Pasted Text: 19 lines]". could you
  please provide the text again?
```

### What did you expect to happen?

It expands the text when sent like with the normal prompt box.

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
╭──────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                              │
│ About Gemini CLI                                                                             │
│                                                                                              │
│ CLI Version                     0.30.0-nightly.20260212.207ac6f2d                            │
│ Git Commit                      207ac6f2d                                                    │
│ Model                           auto-gemini-3                                                │
│ Sandbox                         no sandbox                                                   │
│ OS                              darwin                                                       │
│ Auth Method                     gemini-api-key                                               │
│                                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────╯
```

</details>

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by Jefftree**
## Summary
Fixes large pastes in `TextInput` (used by action-required dialogs like "suggest changes") being submitted as literal placeholder strings (e.g. `[Pasted Text: 9 lines]`) instead of the actual pasted content.

## Details
When a paste exceeds 5 lines or 500 chars, gemini-cli stores the real content in `buffer.pastedContent` and shows a compact placeholder in the input. `InputPrompt` already expanded these placeholders before submit, but `TextInput` was calling `onSubmit(text)` directly, sending the raw placeholder string to the model.

The fix expands placeholders in `TextInput.handleKeyPress` before calling `onSubmit`, using the keys from `buffer.pastedContent` directly — no new imports or shared utilities needed.

## Related Issues
Closes #19944
Closes #19238

## How to Validate
1. `npm run build && npm start`
2. Ask gemini to edit a file, wait for the action-required approval prompt
3. Choose "suggest changes"
4. Paste 5+ lines into the input and submit
5. Gemini should receive and respond to the actual pasted content, not `[Pasted Text: N lines]`

## Pre-Merge Checklist
- [x] Updated relevant documentation and README (if needed)
- [x] Added/updated tests (if needed)
- [x] Noted breaking changes (if any)
- [x] Validated on required platforms/methods:
  - [x] MacOS
    - [x] npm run

### CODE REVIEW

File: packages/cli/src/ui/components/shared/TextInput.tsx [hunk 1]
```diff
@@ -47,14 +47,18 @@ export function TextInput({
       }
 
       if (keyMatchers[Command.SUBMIT](key) && onSubmit) {
-        onSubmit(text);
+        const processedText = text.replace(
```
Comment (scidomino) [inline packages/cli/src/ui/components/shared/TextInput.tsx]: Do we not already have a function to do this somewhere?

File: packages/cli/src/ui/components/shared/TextInput.test.tsx [hunk 2]
```diff
@@ -298,6 +298,60 @@ describe('TextInput', () => {
     unmount();
   });
 
+  it('expands paste placeholder to real content on submit', async () => {
+    const placeholder = '[Pasted Text: 6 lines]';
```
Comment (scidomino) [inline packages/cli/src/ui/components/shared/TextInput.test.tsx:305]: Is there not a way to trigger this behavior naturally? I don't like having to manually reach inside of class and messing with it's internal state.

**Review by scidomino — DISMISSED** [review]

File: packages/cli/src/ui/components/shared/TextInput.tsx (hunk 1 above)
Comment (Jefftree) [reply packages/cli/src/ui/components/shared/TextInput.tsx]: not a function but there's something similar in [InputPrompt](https://github.com/google-gemini/gemini-cli/blob/main/packages/cli/src/ui/components/InputPrompt.tsx#L326-L330) that uses a const regex. I can duplicate that or refactor into somewhere common?

Comment (jackwotherspoon) [reply packages/cli/src/ui/components/shared/TextInput.tsx]: Can we make this into a shared helper within `text-buffer.ts`?

As we are now hitting the rule of three, with this PR there are now 3 call sites.

1. **InputPrompt.tsx:327-330** — on submit
  2. **text-buffer.ts:3092-3095** — when opening in external editor
  3. **TextInput.tsx** (this PR) — on submit

  All three do the same thing: `text.replace(PASTED_TEXT_PLACEHOLDER_REGEX, (match) => pastedContent[match] || match)`. 

A shared helper is probably justified here to make sure things don't drift in the future.

Something like an `expandPastePlaceholders(text, pastedContent)` function exported from `text-buffer.ts` (where the regex and
  pastedContent already live)

**Review by jackwotherspoon — CHANGES_REQUESTED** [review]
I think a small shared helper for the paste expansion will help reduce the tests and make sure things don't drift in the future.

File: packages/cli/src/ui/components/shared/TextInput.test.tsx (hunk 2 above)
Comment (Jefftree) [reply packages/cli/src/ui/components/shared/TextInput.test.tsx:305]: TextInput doesn't handle pasting, and its passed from buffer props. I was trying to follow the same pattern that other tests in this file use for setting up buffer state. Open to suggestions if you have another approach in mind.

File: packages/cli/src/ui/components/shared/TextInput.tsx (hunk 1 above)
Comment (Jefftree) [reply packages/cli/src/ui/components/shared/TextInput.tsx]: Done. Added `expandPastePlaceholders(text, pastedContent)` in `text-buffer.ts`

**Review by jackwotherspoon — DISMISSED** [review]
Feedback on plan worked great and expanded! 👍 

I think we may be missing one spot though. The ask user tool is not expanding the pastes... @Jefftree can you see if there is one more call site that needs to use the new helper function?

The file in question is `AskUserDialog.tsx` to update.

Image

File: packages/cli/src/ui/components/AskUserDialog.tsx
Comment (SandyTao520) [inline packages/cli/src/ui/components/AskUserDialog.tsx]: need to expand here as well

Comment (SandyTao520) [inline packages/cli/src/ui/components/AskUserDialog.tsx]: and expand here

**Review by SandyTao520 — APPROVED** [review]
