### PR TITLE
fix(ui): removed background color for input

### LINKED ISSUE #18315: `useBackgroundColor` on `tmux` on `alacritty`: Can't See Prompt Text
### What happened?

Hi all,

After updating to gemini-cli 0.27.0 this morning, I found that I was unable to read the text in the prompt. Here is an example of what I was seeing:

<img width="1709" height="313" alt="Image" src="https://github.com/user-attachments/assets/85a00e2a-b7df-4703-bdbf-4b5232fe37d4" />

After a moment of panic I decided to go through all of the changenotes and PRs and luckily stumbled upon https://github.com/google-gemini/gemini-cli/pull/16563. Then, I was able to change the `ui.useBackgroundColor` to `false` and voila, usable again.

Some additional notes. I use tmux in alacritty. This only happens when I'm in tmux. So yes, this likely only impact a very few individuals but figured it was worth noting. Even if it only helps me and a few others now and in the future.

### What did you expect to happen?

I did not expect to have my workflow break and only luckily find the problem and fix.

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
│ About Gemini CLI                                                                                                                                                                                                  │
│                                                                                                                                                                                                                   │
│ CLI Version                                                              0.27.0                                                                                                                                   │
│ Git Commit                                                               ec10a7692                                                                                                                                │
│ Model                                                                    auto-gemini-3                                                                                                                            │
│ Sandbox                                                                  no sandbox                                                                                                                               │
│ OS                                                                       linux                                                                                                                                    │
│ Auth Method                                                              gemini-api-key
```

</details>

### Login information

_No response_

### Anything else we need to know?

tmux 3.5a  on alacritty 0.16.1

### PR DESCRIPTION
**Pull request by devr0306**
## Summary

Adding background color for inputs was messing up the UI on tmux. Removed it to improve the UI for all terminals that use true color.

## Details

1. **Terminal Capability Detection**
   - Core Utility: Integrated `supportsTrueColor()` into the UI layer to detect if the terminal supports 24-bit color.

  2. **UI Rendering Refactor (`HalfLinePaddedBox.tsx`)**
  The PR completely flips the rendering strategy to prioritize True Color support:
   - **True Color Supported (New Standard):**
       - Switched the border characters: Top border now uses ▄ (foreground colored) and bottom border uses ▀.
       - Applies the background color directly to the content Box.
       - This is now the default path for most modern terminals (iTerm2, VS Code, Kitty, etc.).
   - **True Color Not Supported (Compatibility Mode):**
       - This path is mainly used for the Apple Terminal.
       - Removes the blocks on the border(Top ▀, Bottom ▄) and just renders an empty line with a background on the top and the bottom.

  3. **Global Snapshot Updates**
   - Because the "standard" rendering path (used by the test runner) changed its character set and background application, the PR updates dozens of snapshots
     across the CLI package.
   - This includes `.snap` and `.snap.svg` files for `InputPrompt`, `MainContent`, `UserMessage`, and `ToolConfirmation`.

  4. **Test Coverage**
   - Core Tests: Added new test cases in `compatibility.test.ts` to verify Apple Terminal detection logic.
   - UI Tests: Refactored `HalfLinePaddedBox.test.tsx` to test capability-based branches (`True Color` vs `Low Color`) instead of terminal-specific strings.

## Related Issues

Fixes #18315

## How to Validate

Start the CLI in any terminal. The input box should look normal in it(proper color, no broken lines, etc). Screenshots from various terminals:

#### Default Linux with tmux
linux-default-tmux

#### Default Linux
linux-default

#### Default mac with tmux(same as without tmux)
Screenshot 2026-04-16 at 3 05 46 PM

## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [x] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [x] Validated on required platforms/methods:
  - [x] MacOS
    - [x] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

**Comment by jacob314** [comment]
### PR Review

**Summary**
This PR aims to fix UI rendering issues in `tmux` by updating `HalfLinePaddedBox` to use a compatibility rendering mode when true color is not supported, relying on `supportsTrueColor()` rather than terminal-specific checks.

**Review Notes & Issues**

1. **Bug in Compatibility Mode Implementation:**
   The PR description states:
   > *"Removes the background color from the content box to prevent rendering artifacts and 'broken lines'. Uses the background-colored block method (Top ▀, Bottom ▄) to simulate padding without painting a solid background over the children."*
   
   However, in the `if (noTrueColor)` block in `HalfLinePaddedBox.tsx`, the parent container `<Box>` still has the `backgroundColor={backgroundColor}` prop. In Ink, applying `backgroundColor` to a parent `<Box>` applies that background color to all of its children. Therefore, a solid background is still being painted over the content, contrary to the PR's stated intent.
   
   **Suggested Fix:** Remove `backgroundColor={backgroundColor}` from the container `<Box>` in the `noTrueColor` fallback path so that only the `Text` components containing the block characters have the background color applied.

2. **True Color Standard Path:**
   Flipping the default rendering path to use the `▄`/`▀` method (previously reserved for iTerm2) when `supportsTrueColor()` is true is a good refactor and correctly uses capability detection rather than hardcoded terminal names.

3. **InputPrompt Updates:**
   The changes in `InputPrompt.tsx` that switch to using `theme.background.input` with 100% opacity instead of `theme.text.secondary` with partial opacity are solid and integrate well with the new capability checks.

4. **Testing:**
   The snapshot updates and test refactors in `HalfLinePaddedBox.test.tsx` accurately reflect the new logic.

**Conclusion**
The overall approach is sound and correctly leverages terminal capabilities. However, the `noTrueColor` fallback block needs to be updated to actually remove the background color from the container `<Box>` to resolve the tmux rendering artifacts as intended. Please update `HalfLinePaddedBox.tsx` accordingly.

File: packages/cli/src/ui/components/shared/HalfLinePaddedBox.tsx [hunk 1]
```diff
@@ -73,36 +62,34 @@ const HalfLinePaddedBoxInternal: React.FC<HalfLinePaddedBoxProps> = ({
...
-        </Box>
-        <Box
-          width={terminalWidth}
-          flexDirection="column"
-          alignItems="stretch"
-          backgroundColor={backgroundColor}
-        >
-          {children}
+          <Text backgroundColor={backgroundColor}>
+            {' '.repeat(terminalWidth)}
```
Comment (jacob314) [inline packages/cli/src/ui/components/shared/HalfLinePaddedBox.tsx]: don't add a line filled with spaces. remove everything including the box around the text and 1 line of vertical padding. Should achieve the same effect.

File: packages/cli/src/ui/components/InputPrompt.tsx [hunk 2]
```diff
@@ -1789,8 +1775,8 @@ export const InputPrompt: React.FC<InputPromptProps> = ({
           borderStyle={useLineFallback ? 'round' : undefined}
           borderTop={false}
           borderBottom={false}
-          borderLeft={!useBackgroundColor}
-          borderRight={!useBackgroundColor}
+          borderLeft={!useBackgroundColor || useLineFallback}
```
Comment (jacob314) [inline packages/cli/src/ui/components/InputPrompt.tsx]: do not add borderLeft and borderRight when in NO_COLOR mode. 
border top and bottom is sufficient.

**Review by jacob314 — COMMENTED** [review]
Approved after these comments are addressed

**Review by jacob314 — APPROVED** [review]
looks good! thanks for all the iteration. The one remaining issue that can be fixed in a follow up is in no-color mode there is insufficient padding around user messages in the history.

Example:
Image
