### PR TITLE
fix(cli): hide scrollbars when in alternate buffer copy mode

### LINKED ISSUE #18344: Alternate buffer "copy mode" doesn't hide scroll bars
### What happened?

When I enter copy mode with alternate buffer enabled, there are still scroll bars displayed on the screen. This means that I get the scroll bar in my copied text, which kinda defeats the purpose of copy mode.

### What did you expect to happen?

Scroll bars disappear when I enter copy mode in alternate buffer

### Client information

<details>
<summary>Client Information</summary>

Google internal user

</details>

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by werdnum**
## Summary

In alternate buffer copy mode, we display scroll bars still. This defeats the purpose – the scroll bars leak into the copied content.

## Details

Now hide scroll bars when copy mode is on.

## Related Issues

Fixes #18344

## How to Validate

Turn on alternate buffer

`npm run start`

do some stuff to create scroll bars

Enter copy mode

## Pre-Merge Checklist

- [x] Updated relevant documentation and README (if needed)
- [x] Added/updated tests (if needed)
- [x] Noted breaking changes (if any)
- [ ] Validated on required platforms/methods:
  - [ ] MacOS
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [x] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

File: packages/cli/src/ui/components/shared/VirtualizedList.tsx [hunk 1]
```diff
@@ -474,16 +475,21 @@ function VirtualizedList<T>(
   return (
     <Box
       ref={containerRef}
-      overflowY="scroll"
+      overflowY={props.copyModeEnabled ? 'hidden' : 'scroll'}
```
Comment (jacob314) [inline packages/cli/src/ui/components/shared/VirtualizedList.tsx]: to minimize the amount of prop drilling required for this, have 
Virtualized props grab
the props directly from useUIState rather than passing it through. Will keep the PR small making this easier to revert once it isn't needed. Its fine if this causes a few tests to need to be updated to use the test helper to inject all the standard providers.

**Review by jacob314 — COMMENTED** [review]
Approved once this comment is addressed.

**Review by jacob314 — APPROVED** [review]
lgtm

**Review by jacob314 — APPROVED** [review]
lgtm
