### PR TITLE
test(evals): fix overlapping act() deadlock in app-test-helper

### LINKED ISSUE #23624: evals: ask_user behavioral evaluations hang indefinitely on Initializing screen
## Description
The `ask_user` behavioral evaluations in `evals/ask_user.eval.ts` are currently hanging indefinitely and timing out. The simulated terminal gets stuck displaying the `Initializing...` spinner and never renders the `Type your message` prompt.

## Root Cause
The test helper `rig.render()` in `evals/app-test-helper.ts` is an `async` function that uses React's `act()` internally. In the test setup, it was being called synchronously (without `await`), immediately followed by an `await rig.waitForIdle()` call, which also heavily relies on `act()`. 

React 18's test renderer does not support overlapping `act()` calls. This overlap causes a deadlock in the test environment's UI update queue. Even though the background `CommandService` successfully finishes loading all slash commands and calls `setCommands()`, the state update is never flushed to the UI. Because the UI never re-renders with the loaded commands, `isInputActive` remains false, and the app freezes on the initialization spinner.

## Fix
Add `await` before `rig.render()` in `evals/app-test-helper.ts` to ensure the initial render and its `act()` call are fully resolved before proceeding to `waitForIdle()`. Additionally, the `configOverrides` structure in `evals/ask_user.eval.ts` was incorrectly nesting `approvalMode` inside a `general` block, which has also been corrected.

### PR DESCRIPTION
**Pull request by Adib234**
## Summary

This PR fixes a deadlock in `evals/app-test-helper.ts` that caused the `ask_user` behavioral evaluations to time out indefinitely while stuck on the `Initializing...` spinner.

## Details

The test helper `rig.render()` is an async function that uses React's `act()` internally. Because it was called synchronously (without `await`), its `act()` call overlapped with the immediate `await rig.waitForIdle()` call that follows it. React 18's test renderer does not support overlapping `act()` calls and deadlocks the UI update queue, preventing state updates (like `setCommands()`) from flushing to the simulated terminal.

By adding `await` before `rig.render()`, the UI queue resolves properly, the commands finish loading, and the tests run to completion.

## Related Issues

Fixes #23624

## How to Validate

1. Check out the branch.
2. Run `npm run test:always_passing_evals -- evals/ask_user.eval.ts`
3. Verify that the 4 evaluation tests pass successfully without timing out.

## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [x] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [ ] Validated on required platforms/methods:
  - [ ] MacOS
    - [x] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

File: evals/app-test-helper.ts [hunk 1]
```diff
@@ -79,7 +79,7 @@ export function appEvalTest(policy: EvalPolicy, evalCase: AppEvalCase) {
       }
 
       // Render the app!
-      rig.render();
+      await rig.render();
```
Comment (gundermanc) [inline evals/app-test-helper.ts:82]: FWIW there's a 'no floating promises' linter I enabled in the rest of the codebase to catch issues like this. You could consider enabling in the evals directory as well.

**Review by gundermanc — APPROVED** [review]
