### PR TITLE
fix(cli): prevent terminal escape sequences from leaking on exit

### LINKED ISSUE #16801: Gemini CLI often shows 9;5u on exit in Ghostty
When Gemini CLI exits, 9;5u is often written to the terminal.

### PR DESCRIPTION
**Pull request by mattKorwel**
## Summary

This PR prevents terminal escape sequences (especially mouse tracking events) from leaking into the shell prompt after the Gemini CLI exits.

## Details

1.  **Reordered `runExitCleanup`**: Updated the cleanup sequence in `packages/cli/src/utils/cleanup.ts` to execute `cleanupFunctions` (which disable terminal modes and unmount the UI) *before* draining `stdin`. This ensures "in-flight" terminal sequences are cleared while the terminal is still in raw mode.
2.  **Increased Drain Timeout**: Increased the `drainStdin` timeout from 50ms to 100ms for better reliability on slower terminals or during high-activity sessions.
3.  **Enhanced Synchronous Cleanup**: Updated `TERMINAL_CLEANUP_SEQUENCE` in `packages/cli/src/ui/utils/terminalCapabilityManager.ts` to include mouse tracking disable sequences. This provides a fallback if the process exits hard without running the full cleanup.
4.  **Added Verification Test**: Added a test case in `packages/cli/src/utils/cleanup.test.ts` to verify the execution order of cleanup functions relative to stdin draining.

## Related Issues

Fixes #16801 (Partial)
Related to mouse/terminal stability issues in alternate buffer mode.

## How to Validate

1.  Enable alternate buffer in settings.
2.  Start an interactive session.
3.  Move the mouse vigorously or scroll rapidly while typing `/exit` or `/quit`.
4.  Verify that no escape sequences (e.g., `^[[<65;...`) appear in the shell prompt after exit.
5.  Run tests: `npm test -w @google/gemini-cli -- src/utils/cleanup.test.ts`

## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [x] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [x] Validated on required platforms/methods:
  - [x] MacOS
    - [x] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

**Review by jacob314 — APPROVED** [review]
Looks great! This is a solid fix for the escape sequences leaking on exit. The reordering of the cleanup sequence and the added mouse disabling sequences to the fallback are very robust. 

One minor note: in `packages/cli/src/utils/cleanup.ts` and the PR description, you reference issue `#1680`, but the correct issue number for the garbage on exit bug is `#16801`. Could you update the PR description and the code comment? 

Otherwise, the changes look excellent and the test successfully validates the cleanup order.

File: packages/cli/src/ui/utils/terminalCapabilityManager.ts [hunk 1]
```diff
@@ -33,6 +35,7 @@ export function cleanupTerminalOnExit() {
   disableKittyKeyboardProtocol();
   disableModifyOtherKeys();
   disableBracketedPasteMode();
+  disableMouseEvents();
```
Comment (jacob314) [inline packages/cli/src/ui/utils/terminalCapabilityManager.ts:38]: disableMouseEvents is getting called from AppContainer. that is likely not needed if we are doing it here.
as a follow up we should also track whether we have called enableMouseEvents and make disableMouseEvents a no-op if we have not enabled it. unless you are in alternate buffer mode we have not enabled mouse events.

File: packages/cli/src/utils/cleanup.ts [hunk 2]
```diff
@@ -72,6 +67,12 @@ export async function runExitCleanup() {
   }
   cleanupFunctions.length = 0; // Clear the array
 
+  // drain stdin to prevent printing garbage on exit
+  // https://github.com/google-gemini/gemini-cli/issues/1680
```
Comment (jacob314) [inline packages/cli/src/utils/cleanup.ts]: not a new bug but wrong issue. should be 16801

File: packages/cli/src/utils/cleanup.ts [hunk 3]
```diff
@@ -100,7 +101,7 @@ async function drainStdin() {
     .removeAllListeners('data')
     .on('data', () => {});
   // Give it a moment to flush the OS buffer.
-  await new Promise((resolve) => setTimeout(resolve, 50));
+  await new Promise((resolve) => setTimeout(resolve, 100));
```
Comment (jacob314) [inline packages/cli/src/utils/cleanup.ts]: do we really need this change? hopefully your other changes were really what fixed it.

**Review by jacob314 — APPROVED** [review]
lgtm

File: packages/cli/src/utils/cleanup.ts (hunk 2 above)
Comment (mattKorwel) [reply packages/cli/src/utils/cleanup.ts]:
```suggestion
  // https://github.com/google-gemini/gemini-cli/issues/1681
```

File: packages/cli/src/utils/cleanup.ts (hunk 3 above)
Comment (mattKorwel) [reply packages/cli/src/utils/cleanup.ts]: lets leave it in and see... maybe we can tune it as a fllow on?
