### PR TITLE
fix(core): prevent redundant remote agent loading on model switch

### LINKED ISSUE #23575: Duplicate remote agent loading errors on model switch
When changing the model in gemini-cli with `/model`, `AgentRegistry.refreshAgents` inappropriately refetches all remote agents. If a remote agent is offline or fails to authenticate, it emits a new error to the UI every time the model changes. \n\nWe need to add a `scope` option to `refreshAgents` so that `onModelChanged` only refreshes local agents, since remote agents do not inherit local model configurations.

### PR DESCRIPTION
**Pull request by adamfweidman**
## Summary

Fixes the issue where remote agents are needlessly re-fetched from the network every time the user switches the active model via `/model`.

## Details

AgentRegistry's `onModelChanged` responds by refreshing the registered agents. It was previously doing this by iterating over *all* registered agents. For remote agents, this triggers an asynchronous network request to reload their Agent Card. If the remote agent is offline or fails to authenticate, it emits an `error` via `CoreEvent.UserFeedback` on *every* model switch, causing phantom errors to continuously print to the console.

This PR modifies `refreshAgents()` to take an optional `scope` parameter and updates `onModelChanged` to explicitly pass `scope: 'local'`, safely avoiding redundant network requests for remote agents.

## Related Issues

Fixes #23575

## How to Validate

1. Configure an offline or failing remote agent in your settings.
2. Run `gemini-cli` and observe the initial load failure.
3. Switch the model with `/model gemini-2.5-pro`.
4. Verify that the agent error is *not* reprinted.
5. Verify `npm test -w @google/gemini-cli-core` passes.

## Pre-Merge Checklist

- [x] Added/updated tests (if needed)

### CODE REVIEW

**Review by anowardear062-svg — APPROVED** [review]

**Review by anowardear062-svg — APPROVED** [review]

**Review by anowardear062-svg — APPROVED** [review]

File: packages/core/src/agents/registry.ts [hunk 1]
```diff
@@ -270,12 +270,16 @@ export class AgentRegistry {
     }
   }
 
-  private async refreshAgents(): Promise<void> {
+  private async refreshAgents(
+    scope: 'local' | 'remote' | 'all' = 'all',
```
Comment (abhipatel12) [inline packages/core/src/agents/registry.ts]: Do we have a type that we use already within the definition or no? Totally fine if we dont.

File: packages/core/src/agents/registry.test.ts [hunk 2]
```diff
@@ -1206,6 +1206,37 @@ describe('AgentRegistry', () => {
...
+      vi.spyOn(mockConfig, 'getA2AClientManager').mockReturnValue({
+        loadAgent: loadAgentSpy,
+        clearCache: vi.fn(),
+      } as unknown as A2AClientManager);
+
+      await registry.testRegisterAgent(remoteAgent);
+
+      // Initial registration calls loadAgent once
+      expect(loadAgentSpy).toHaveBeenCalledTimes(1);
+
```
Comment (abhipatel12) [inline packages/core/src/agents/registry.test.ts:1227]: Let's clean up some of these comments. I dont think they're all necessary

**Review by abhipatel12 — APPROVED** [review]
LGTM, couple of nits
