### PR TITLE
Fix: make ctrl+x use preferred editor

### LINKED ISSUE #16278: "Ctrl + X" in WSL opens only Vim editor window
### What happened?

I have configured gemini cli inside WSL - Ubuntu 24.04 for the native support of the cli (and it works faster and better).
Using Powershell 7.5.

When I attemp to open the prompt in an "external editor" or whatether editor, except Vim (the window you can move out of only using ":wq") — no any trick works to overcome this:
- changing default system editor with _sudo update-alternatives --config editor_
- wrapping Vim to open Micro
- changing Vim aliases
- setup the cli's /editor to Vs Code or None

ALSO: I cannot safely copy-paste anything from the system buffer.

### What did you expect to happen?

When I press Ctrl + X, I expect to open the prompt in nano/micro/vs code — anything except Vim (or Vm). 
In windows I used to see it in the default Notepad.

I'd expect to have a safe way to copy-paste multiline texts/logs (so it doesn't exec the prompt) (via external editor).

### Client information

* **CLI Version:** 0.23.0
* **Git Commit:** 3ff055840
* **Session ID:** b8a2314f-de62-4a3b-81e8-410a4d5f6b0b
* **Operating System:** linux v24.12.0
* **Sandbox Environment:** no sandbox
* **Model Version:** auto-gemini-3
* **Memory Usage:** 250.6 MB
* **Terminal Name:** Unknown
* **Terminal Background:** Unknown
* **Kitty Keyboard Protocol:** Unsupported

### Login information

Google Account

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by scidomino**
## Summary

Make `ctrl+x` (Open external editor) use preferred editor

## Details

Previously, we only looked at `EDITOR` and `VISUAL` env vars. This changes it to look for the preferred editor first and the other only if there is no preferred editor.

Note: Up till now the preferred editor was only used for diffs as far as I can tell. So this is a bit of a change.

## Related Issues

Fixes #16278

## How to Validate

Set a preferred editor and test it out.

## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [ ] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [ ] Validated on required platforms/methods:
  - [ ] MacOS
    - [ ] npm run
    - [x] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

File: packages/cli/src/ui/components/shared/text-buffer.ts [hunk 1]
```diff
@@ -2152,55 +2157,64 @@ export function useTextBuffer({
...
-    },
-    [text, stdin, setRawMode],
-  );
+      try {
+        fs.rmdirSync(tmpDir);
+      } catch {
+        /* ignore */
+      }
+    }
+  }, [text, stdin, setRawMode, getPreferredEditor]);
```
[the remark this answers is not in the document]
Comment (scidomino) [reply packages/cli/src/ui/components/shared/text-buffer.ts:2220]: This is intentional as we want the app to freeze while editing is happening.

**Review by jacob314 — APPROVED** [review]
Please add a test for the changes so we don't regress the order we handle theselgtm.lgtm

File: packages/cli/src/ui/components/shared/text-buffer.ts [hunk 2]
```diff
@@ -2152,55 +2157,67 @@ export function useTextBuffer({
...
+    }
 
-      dispatch({ type: 'create_undo_snapshot' });
+    dispatch({ type: 'create_undo_snapshot' });
 
-      const wasRaw = stdin?.isRaw ?? false;
+    const wasRaw = stdin?.isRaw ?? false;
+    try {
+      setRawMode?.(false);
+      const { status, error } = spawnSync(command, args, {
```
Comment (galdawave) [inline packages/cli/src/ui/components/shared/text-buffer.ts:2190]: While the previous implementation also used spawnSync, explicitly supporting GUI editors (like VS Code with --wait) using spawnSync will block the entire Node.js event loop while the editor is open. If the user keeps the editor open for a long time, any background tasks (timers, network listeners) in the CLI will be frozen.

The openDiff implementation in packages/core/src/utils/editor.ts correctly handles this by using spawn (async) for GUI editors and spawnSync for terminal editors.

Recommendation: Consider adopting the openDiff pattern: use spawnSync for terminal editors (to correctly handle TTY/stdio) and spawn (wrapped in a Promise) for GUI editors to keep the event loop alive, since openInExternalEditor is already async.

```typescript
     // Example adaptation (pseudo-code)
     if (isGuiEditor(preferredEditorType) || (!isTerminalEditor(command) /* logic needed */)) {
        // use await spawn(...)
     } else {
        // use spawnSync(...)                                                                                                               
     }
```

**Review by galdawave — APPROVED** [review]

File: packages/cli/src/ui/components/shared/text-buffer.ts (hunk 2 above)
Comment (scidomino) [reply packages/cli/src/ui/components/shared/text-buffer.ts:2190]: Going to address this in a follow up PR.
