### PR TITLE
Fix dollar sign replacement bug in file editing 

### LINKED ISSUE #7550: Gemini-cli often has a problem with generated dollar signs being interpreted as line breaks
### What happened?

If gemini-cli generates something with a dollar sign, the dollar sign is replaced by a line break in the finished result.

It can probably be recreated if you ask Gemini-cli to generate a file with a regular expression that includes the end of line character. This is how I have encountered the issue every time.

In the last instance of this bug gemini was supposed to generate the following text in a file;

```yaml
- name: Find the first unformatted disk that is not the root device
  ansible.builtin.set_fact:
    data_disk: >
      {{
        ansible_devices.keys()
        | select('match', '^[sv]d[a-z]$')
        | map('extract', ansible_devices)
        | selectattr('partitions', 'eq', {})
        | selectattr('filesystem', 'none')
        | map(attribute='name')
        | first
      }}
```

Instead this is what was written to the file;

```yaml
- name: Find the first unformatted disk that is not the root device
  ansible.builtin.set_fact:
    data_disk: >
      {{
        ansible_devices.keys()
        | select('match', '^[sv]d[a-z]
)
        | map('extract', ansible_devices)
        | selectattr('partitions', 'eq', {})
        | selectattr('filesystem', 'none')
        | map(attribute='name')
        | first
      }}
```

Notice the line break has replaced the last two characters of the regex which should be $'. Gemini web has no problem generating this as an example.

### What did you expect to happen?

A dollar sign to appear in the text that gemini writes to a file.

### Client information

* **CLI Version:** 0.2.2
* **Git Commit:** 32204dca
* **Session ID:** 4d964db2-e0f6-49cb-8838-b37f6aa13e49
* **Operating System:** linux v22.17.1
* **Sandbox Environment:** no sandbox
* **Model Version:** gemini-2.5-pro
* **Memory Usage:** 229.4 MB

### Login information

API key

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by lifefloating**
## TLDR

fix e2e test
Fixed GitHub issue #7550 where dollar signs (`$`) in generated content were being replaced with line breaks during file editing operations. The root cause was `String.prototype.replaceAll()` interpreting `$` as replacement template placeholders. Replaced `replaceAll` with `split/join` for literal string replacement across three core files.

## Dive Deeper

**Root Cause**: `String.prototype.replaceAll()` treats the second parameter as a "replacement template" that interprets `$` placeholders:
- `$'` means "insert all text after the match"
- When LLM generates regex patterns like `'^[sv]d[a-z]$'`, the trailing `$'` gets interpreted
- Results in dollar signs being replaced with subsequent text (including newlines)

**Solution**: Replace `replaceAll(oldString, newString)` with `split(oldString).join(newString)`:
- Pure literal operation with no template parsing
- Completely preserves `$` symbols in content
- Simpler and more predictable behavior

## Reviewer Test Plan

1. **Reproduce the issue** (before fix):
   - Run `node bundle/gemini.js`
   - Use prompts in comment(https://github.com/google-gemini/gemini-cli/issues/7550#issuecomment-3250357634)
   - Observe dollar signs being replaced with line breaks

2. **Verify the fix** (after applying changes):
   
image

image

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | ✅  | ❓  | ❓  |

## Linked issues / bugs

Fixes #7550

### CODE REVIEW

**Comment by lifefloating** [comment]
i didnt have google api key. So I can't run the e2e tests locally, which is a bit awkward.
@galz10 @jacob314 
 
image

File: packages/a2a-server/src/agent/task.ts [hunk 1]
```diff
@@ -508,7 +508,8 @@ export class Task {
     if (oldString === '' && !isNewFile) {
       return currentContent;
     }
-    return currentContent.replaceAll(oldString, newString);
+    // Use split/join to ensure replacement
+    return currentContent.split(oldString).join(newString);
```
Comment (jacob314) [inline packages/a2a-server/src/agent/task.ts]: this would change behavior

File: packages/core/src/tools/edit.ts [hunk 2]
```diff
@@ -51,7 +51,8 @@ export function applyReplacement(
   if (oldString === '' && !isNewFile) {
     return currentContent;
   }
-  return currentContent.replaceAll(oldString, newString);
+  // Use split/join to ensure replacement
+  return currentContent.split(oldString).join(newString);
```
Comment (jacob314) [inline packages/core/src/tools/edit.ts]: this doesn't seem safe. it will behave differently if the oldString is at the start or end of the currentContent.

**Comment by jacob314** [comment]
Temporarily approving to run E2E tests. Do not commit.

**Review by jacob314 — APPROVED** [review]

File: packages/core/src/tools/edit.ts (hunk 2 above)
Comment (lifefloating) [reply packages/core/src/tools/edit.ts]: Or I think we should rewrite replaceAll separately to handle this case specially, so the impact would be a bit smaller.

**Comment by lifefloating** [comment]
I think the current change would have too much impact if we just use `split(oldString).join(newString)` entirely. I think it would be better to make some adjustments. 
My current idea is: 
1. only use split/join when we detect problematic $ sequences, and otherwise keep the original replaceAll behavior. 
2. Also, we should enhance the test coverage.
@jacob314 @silviojr

**Comment by jacob314** [comment]
I think the robust solution is to use 
`const escapedNewString = newString.replaceAll('$', '$$')`;
and then use the existing solution that was robust except for the dollar sign issue I'm so glad you identified.

Some more details from Gemini.
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-042a8be2-7fff-c38e-fb05-c60aac996f53"><p dir="ltr" style="line-height:1.3799999713897704;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:11pt;font-family:'Google Sans Text',sans-serif;color:#1b1c1d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Of course. You're right to be cautious about the split/join method. The most robust and idiomatic solution is to </span><span style="font-size:11pt;font-family:'Google Sans Text',sans-serif;color:#1b1c1d;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">escape the $ character</span><span style="font-size:11pt;font-family:'Google Sans Text',sans-serif;color:#1b1c1d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"> in the replacement string before passing it to replaceAll().</span></p><p dir="ltr" style="line-height:1.3799999713897704;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:11pt;font-family:'Google Sans Text',sans-serif;color:#1b1c1d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The correct way to prevent the &quot;replacement template&quot; issue is to replace every literal $ with $$ in your new string.</span></p><br /><p dir="ltr" style="line-height:1.3799999713897704;margin-left: 12pt;margin-right: 6pt;margin-top:6pt;margin-bottom:7.5pt;"><span style="font-size:11pt;font-family:'Google Sans Text',sans-serif;color:#575b5f;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">JavaScript</span></p><br /><br /><p dir="ltr" style="line-height:1.3799999713897704;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:'Google Sans Text',sans-serif;color:#8430ce;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">const</span><span style="font-size:11pt;font-family:'Google Sans Text',sans-serif;color:#1b1c1d;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"> originalString = </span><span style="font-size:10pt;font-family:'Google Sans Text',sans-serif;color:#188038;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&quot;The price is PRICE.&quot;</span><span style="font-size:11pt;font-family:'Google Sans Text',sans-serif;color:#1b1c1d;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">;</span><span style="font-size:11pt;font-family:'Google Sans Text',sans-serif;color:#1b1c1d;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><br /></span><span style="font-size:10pt;font-family:'Google Sans Text',sans-serif;color:#8430ce;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">const</span><span style="font-size:11pt;font-family:'Google Sans Text',sans-serif;color:#1b1c1d;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"> oldString = </span><span style="font-size:10pt;font-family:'Google Sans Text',sans-serif;color:#188038;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&quot;PRICE&quot;</span><span style="font-size:11pt;font-family:'Google Sans Text',sans-serif;color:#1b1c1d;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">;</span><span style="font-size:11pt;font-family:'Google Sans Text',sans-serif;color:#1b1c1d;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><br /></span><span style="font-size:10pt;font-family:'Google Sans Text',sans-serif;color:#5f6368;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">// Malicious-looking new string from an external source (like an LLM)</span><span style="font-size:11pt;font-family:'Google Sans Text',sans-serif;color:#1b1c1d;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><br /></span><span style="font-size:10pt;font-family:'Google Sans Text',sans-serif;color:#8430ce;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">const</span><span style="font-size:11pt;font-family:'Google Sans Text',sans-serif;color:#1b1c1d;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"> newString = </span><span style="font-size:10pt;font-family:'Google Sans Text',sans-serif;color:#188038;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&quot;$' Wow, that's a lot! $&amp;&quot;</span><span style="font-size:11pt;font-family:'Google Sans Text',sans-serif;color:#1b1c1d;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">;</span><span style="font-size:11pt;font-family:'Google Sans Text',sans-serif;color:#1b1c1d;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><br /></span><span style="font-size:11pt;font-family:'Google Sans Text',sans-serif;color:#1b1c1d;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><br /></span><span style="font-size:10pt;font-family:'Google Sans Text',sans-serif;color:#5f6368;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">// This will be replaced with a literal '$' and '&amp;'</span><span style="font-size:11pt;font-family:'Google Sans Text',sans-serif;color:#1b1c1d;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><br /></span><span style="font-size:10pt;font-family:'Google Sans Text',sans-serif;color:#8430ce;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">const</span><span style="font-size:11pt;font-family:'Google Sans Text',sans-serif;color:#1b1c1d;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"> escapedNewString = newString.replaceAll(</span><span style="font-size:10pt;font-family:'Google Sans Text',sans-serif;color:#188038;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">'$'</span><span style="font-size:11pt;font-family:'Google Sans Text',sans-serif;color:#1b1c1d;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">, </span><span style="font-size:10pt;font-family:'Google Sans Text',sans-serif;color:#188038;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">'$$'</span><span style="font-size:11pt;font-family:'Google Sans Text',sans-serif;color:#1b1c1d;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">);</span><span style="font-size:11pt;font-family:'Google Sans Text',sans-serif;color:#1b1c1d;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><br /></span><span style="font-size:11pt;font-family:'Google Sans Text',sans-serif;color:#1b1c1d;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><br /></span><span style="font-size:10pt;font-family:'Google Sans Text',sans-serif;color:#8430ce;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">const</span><span style="font-size:11pt;font-family:'Google Sans Text',sans-serif;color:#1b1c1d;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"> result = originalString.replaceAll(oldString, escapedNewString);</span><span style="font-size:11pt;font-family:'Google Sans Text',sans-serif;color:#1b1c1d;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><br /></span><span style="font-size:11pt;font-family:'Google Sans Text',sans-serif;color:#1b1c1d;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><br /></span><span style="font-size:10pt;font-family:'Google Sans Text',sans-serif;color:#1967d2;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">console</span><span style="font-size:11pt;font-family:'Google Sans Text',sans-serif;color:#1b1c1d;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">.log(result);</span><span style="font-size:11pt;font-family:'Google Sans Text',sans-serif;color:#1b1c1d;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><br /></span><span style="font-size:10pt;font-family:'Google Sans Text',sans-serif;color:#5f6368;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">// Expected and correct output:</span><span style="font-size:11pt;font-family:'Google Sans Text',sans-serif;color:#1b1c1d;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><br /></span><span style="font-size:10pt;font-family:'Google Sans Text',sans-serif;color:#5f6368;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">// &quot;The price is $' Wow, that's a lot! $&amp;.&quot;</span><span style="font-size:11pt;font-family:'Google Sans Text',sans-serif;color:#1b1c1d;background-color:#f0f4f9;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><br /><br /></span></p><p dir="ltr" style="line-height:1.3799999713897704;margin-top:6pt;margin-bottom:12pt;"><hr /></p><h3 dir="ltr" style="line-height:1.3799999713897704;margin-top:0pt;margin-bottom:6pt;"><span style="font-size:13.999999999999998pt;font-family:'Google Sans',sans-serif;color:#1b1c1d;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Why This Works</span></h3><br /><p dir="ltr" style="line-height:1.3799999713897704;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:11pt;font-family:'Google Sans Text',sans-serif;color:#1b1c1d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">As you correctly pointed out, the second argument of String.prototype.replaceAll() is not treated as a literal string but as a replacement pattern. The $ character initiates special sequences.</span></p><p dir="ltr" style="line-height:1.3799999713897704;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:11pt;font-family:'Google Sans Text',sans-serif;color:#1b1c1d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Here are the main sequences:</span></p><div dir="ltr" style="margin-left:0pt;" align="left">
Sequence | Inserts
-- | --
$$ | A single literal dollar sign, $
$& | The entire matched substring.
$` | The portion of the string that precedes the matched substring.
$' | The portion of the string that follows the matched substring.
$n | The nth parenthesized capture group (e.g., $1, $2), where n is 1 or 2.

</div><p dir="ltr" style="line-height:1.3799999713897704;margin-top:24pt;margin-bottom:12pt;"><span style="font-size:11pt;font-family:'Google Sans Text',sans-serif;color:#1b1c1d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">By converting every $ to $$ in your input string, you are explicitly telling the replaceAll method, &quot;Treat this as a literal dollar sign,&quot; effectively disabling any other special interpretations and ensuring the string is inserted exactly as-is.</span></p><p dir="ltr" style="line-height:1.3799999713897704;margin-top:6pt;margin-bottom:12pt;"><hr /></p><h3 dir="ltr" style="line-height:1.3799999713897704;margin-top:0pt;margin-bottom:6pt;"><span style="font-size:13.999999999999998pt;font-family:'Google Sans',sans-serif;color:#1b1c1d;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Regarding split().join()</span></h3><br /><p dir="ltr" style="line-height:1.3799999713897704;margin-top:0pt;margin-bottom:12pt;"><span style="font-size:11pt;font-family:'Google Sans Text',sans-serif;color:#1b1c1d;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">You are correct that split().join() can have unexpected behavior and is generally not the right tool for this job. While the specific end-of-string issue you mentioned might not manifest in all cases, the method is less efficient and less clear about its intent than properly escaping the replacement string for replaceAll(). Sticking with the built-in method and using its intended escape mechanism ($$) is always the better practice.</span></p></b><br class="Apple-interchange-newline">

**Review by jacob314 — COMMENTED** [review]
Approved once this switches to the suggestion of escaping `$` as `$$`

**Comment by lifefloating** [comment]
> Approved once this switches to the suggestion of escaping `$` as `$$`

I completely agree with what you said. I've also become aware of this point. For now, I've made a revised version of the code this morning — you can take a look at the approach and see if it's feasible.

**Review by jacob314 — CHANGES_REQUESTED** [review]
Approved once the previous change about avoiding split is made.

File: packages/core/src/tools/edit.ts (hunk 2 above)
Comment (jacob314) [reply packages/core/src/tools/edit.ts]: Adding a recommend safe replaceAll util util sounds good to me. could them have some unittests to ensure we didn't mess up any of the escaping edge cases reducing the risk.

**Review by jacob314 — CHANGES_REQUESTED** [review]
Approved once the requested changes are made.

**Comment by lifefloating** [comment]
image

And use `newString.replaceAll('$', '$$$$')` have tested ok now. using origin https://github.com/google-gemini/gemini-cli/issues/7550 prompt



- We need a two-step escaping:

1) First, escape every `$` in `newString` so that it becomes a form that will be treated as a literal `$` later. If you write:
```js
newString.replaceAll('$', '$$')
```
the `$$` here is immediately interpreted as “insert a single `$`”, so the result still contains only one `$`—escaping fails.
The correct way is:
```js
newString.replaceAll('$', '$$$$')
```
Here, `$$$$` is interpreted at this step as “two literal `$`”, so the escaped string actually contains `$$`.

2) Then pass that escaped string to the final:
```js
str.replaceAll(oldString, escapedNewString)
```
In the final replacement, each `$$` is interpreted as a literal `$`, so the output preserves `$` as intended and avoids special sequences like ``$&``, ``$'``, and ``$1``.

Therefore: the escape step must use `$$$$` (to produce real `$$` in the escaped string), and the final replacement uses that `$$` to yield one literal `$` in the output.


This is the result of using  `newString.replaceAll('$', '$$');`

image

**Comment by lifefloating** [comment]
e2e run local passed
image

**Review by jacob314 — APPROVED** [review]
lgtm

**Comment by jacob314** [comment]
Great job! Amusing that four `$` is required.
