### PR TITLE
fix(core): silently retry API errors up to 3 times before halting session

### LINKED ISSUE #20144: API Errors should always trigger retries
We should retry at least 3 times even if we get an api error. Current we fail at the first error such as

Image

We should surface this like we surface other retries. The actual ApiError should not be shown to a user until we have retried the 3 times and still received errors.

This will make Gemini CLI more usable when under heavy loade and not let a single temporary APIError stop the session.

### PR DESCRIPTION
**Pull request by spencer426**
## Summary

Ensure stream API errors are retried a maximum of 3 times silently without changing the global retry configuration.

## Details

This PR introduces the following changes:
- Updates `GeminiChat`'s streaming loop to enforce a localized `maxMidStreamAttempts = 4` check so that mid-stream API errors specifically only retry silently up to 3 times before bubbling up to the user.
- Fixes `GeminiChat` catching logic to properly process mid-stream errors in the retry queue instead of dropping them immediately.

## Related Issues

Fixes #20144

## How to Validate

1. Run `npm run test -w @google/gemini-cli-core -- src/core/geminiChat_network_retry.test.ts`. All mid-stream and connection tests should pass natively without throwing.
2. In standard usage, verify that if an API drops mid-stream, the CLI displays "Attempt X of 4" loading spinners and handles the error gracefully without altering the user's broader 10-attempt general retry configuration.

## Pre-Merge Checklist

- [x] Updated relevant documentation and README (if needed)

### CODE REVIEW

File: packages/core/src/core/geminiChat.ts [hunk 1]
```diff
@@ -344,7 +344,7 @@ export class GeminiChat {
       this: GeminiChat,
     ): AsyncGenerator<StreamEvent, void, void> {
       try {
-        const maxAttempts = INVALID_CONTENT_RETRY_OPTIONS.maxAttempts;
+        const maxAttempts = this.config.getMaxAttempts();
```
Comment (scidomino) [inline packages/core/src/core/geminiChat.ts:347]: This removes the only reference to INVALID_CONTENT_RETRY_OPTIONS.maxAttempts Should we get rid of it?

File: packages/core/src/core/geminiChat.ts [hunk 2]
```diff
@@ -396,30 +396,35 @@ export class GeminiChat {
...
             if (
               (isContentError && isGemini2Model(model)) ||
               (isRetryable && !signal.aborted)
             ) {
-              // Check if we have more attempts left.
-              if (attempt < maxAttempts - 1) {
+              // The issue requests exactly 3 retries (4 attempts) for API errors during stream iteration.
+              // Regardless of the global maxAttempts (e.g. 10), we only want to retry these mid-stream API errors
+              // up to 3 times before finally throwing the error to the user.
+              const maxMidStreamAttempts = 4;
```
Comment (scidomino) [inline packages/core/src/core/geminiChat.ts]: Should we be using INVALID_CONTENT_RETRY_OPTIONS.maxAttempts here? It's not being used for anything else.

File: packages/core/src/core/geminiChat.ts (hunk 1 above)
Comment (spencer426) [reply packages/core/src/core/geminiChat.ts:347]: Good point. Since this retry block now handles both invalid content and mid-stream network API errors (which we want to limit to 4 attempts), I've renamed INVALID_CONTENT_RETRY_OPTIONS to a more generic MID_STREAM_RETRY_OPTIONS. I've updated its maxAttempts to 4 (to replace the hardcoded maxMidStreamAttempts) and am using it here to consolidate our mid-stream retry configuration.

**Review by galdawave — APPROVED** [review]
