### PR TITLE
fix(core): preserve dynamic tool descriptions on session resume

### LINKED ISSUE #18842: Tool descriptions are generic instead of dynamic on session resume
Dynamic tool descriptions (e.g., "Reading file X") are lost and replaced by static/generic ones (e.g., "Reads and returns content...") when resuming a session using `gemini --resume`.

This occurs because:
1. `ChatRecordingService` was overwriting dynamic descriptions with static ones from the `ToolRegistry`.
2. `GeminiChat` was not passing dynamic descriptions to the recording service.

This issue has been present since the initial implementation of session recording in September 2025 (PR #6721).

Fixing in PR #18835.

### PR DESCRIPTION
**Pull request by sehoon38**
## Summary

Fixes a bug where dynamic tool descriptions (e.g., specific filenames or search queries) were lost and replaced by generic tool descriptions when resuming a session.

## Details

Since the initial implementation of session recording (PR #6721), `ChatRecordingService.recordToolCalls` has been unconditionally overwriting incoming tool descriptions with generic ones from the `ToolRegistry`. Furthermore, `GeminiChat.recordCompletedToolCalls` was not extracting or providing the dynamic description from the tool invocation.

This PR:
1.  Modifies `ChatRecordingService.recordToolCalls` to prioritize and preserve existing descriptions if provided.
2.  Updates `GeminiChat.recordCompletedToolCalls` to extract the dynamic description using `invocation.getDescription()` (with a safe truthiness check) and pass it to the recording service.

## Related Issues

Fixes #18842

## How to Validate

1. Start a session: `gemini`
2. Run a command that uses tools with dynamic descriptions, e.g., `Read GEMINI.md`
3. Verify the UI shows "Read file GEMINI.md"
4. Exit the session.
5. Resume the session: `gemini --resume latest`
6. Verify the UI still shows "Read file GEMINI.md" instead of the generic "Reads and returns the content of a specified file."

### CODE REVIEW

File: packages/core/src/core/geminiChat.ts [hunk 1]
```diff
@@ -974,6 +974,10 @@ export class GeminiChat {
         status: call.status,
         timestamp: new Date().toISOString(),
         resultDisplay,
+        description:
+          'invocation' in call && call.invocation
```
Comment (jacob314) [inline packages/core/src/core/geminiChat.ts]: JSON.stringify seems like subpar description to show users. Is that really needed? If it is please at least add tests showing it generate nice output for some example cases.

Comment (sehoon38) [reply packages/core/src/core/geminiChat.ts]: removed, not needed. if call.invocation is missing, it will fallback to tool's description.

**Review by jacob314 — APPROVED** [review]
lgtm
