### PR TITLE
Limit search depth in path corrector

### LINKED ISSUE #12650: App freezes in the middle of a session
### What happened?

Issue: Gemini CLI application freezes completely, preventing user input (typing) and requiring a full restart of the application.                                

 Impact: This issue severely disrupts workflow and causes significant loss of time due to frequent restarts.      
 
Observed Behavior:                                                                                                                                                
- The entire CLI interface becomes unresponsive.                                                                                                                      
- User is unable to type any commands or interact with the application.                                                                                               
- The only resolution is to close and restart the Gemini CLI. 

### What did you expect to happen?

The Gemini CLI should remain responsive and allow user input at all times, even during periods of backend processing or network latency.                           

If a command is taking too long, it should ideally provide feedback or allow for interruption e.g. via Ctrl+C without freezing the entire                          application. 

### Client information

* **CLI Version:** 0.12.0
* **Git Commit:

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by scidomino**
## Summary

limit search depth in path corrector

## Details

This was causing the CLI to freeze (b466194131) for googlers working in very large, wide, and slow directories.

## Related Issues

Fixes #12650

## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [ ] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [ ] Validated on required platforms/methods:
  - [ ] MacOS
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

File: packages/cli/src/zed-integration/fileSystemService.ts [hunk 1]
```diff
@@ -44,7 +44,4 @@ export class AcpFileSystemService implements FileSystemService {
       sessionId: this.sessionId,
     });
   }
-  findFiles(fileName: string, searchPaths: readonly string[]): string[] {
```
Comment (galdawave) [inline packages/cli/src/zed-integration/fileSystemService.ts:47]: Don't have much visibility into Zed, so might be dumb question but why are we removing this ?

File: packages/core/src/utils/pathCorrector.ts [hunk 2]
```diff
@@ -41,9 +42,22 @@ export function correctPath(
...
   const searchPaths = workspaceContext.getDirectories();
-  const foundFiles = fileSystem.findFiles(filePath, searchPaths);
+  const basename = path.basename(filePath);
+
+  // Normalize path for matching and check if it ends with the provided relative path
+  const foundFiles = searchPaths
+    .flatMap((searchPath) =>
+      bfsFileSearchSync(searchPath, {
+        fileName: basename,
+        maxDirs: 50, // Capped to avoid deep hangs
```
Comment (galdawave) [inline packages/core/src/utils/pathCorrector.ts:54]: Nit: we might want to set this to a setting (doesn't need to be a visible one in /setting) but this way if a user wants to reduce or increase it they can.

File: packages/core/src/utils/pathCorrector.ts [hunk 3]
```diff
@@ -41,9 +42,22 @@ export function correctPath(
...
+        fileService: config.getFileService(),
+        fileFilteringOptions: config.getFileFilteringOptions(),
+      }),
+    )
+    .filter((f) =>
```
Comment (galdawave) [inline packages/core/src/utils/pathCorrector.ts]: Nit: The filePath is normalized inside the .filter() loop for every candidate file found. This is repetitive.

  Suggestion: Hoist the normalization of the target filePath outside the loop.

```typescript

 // packages/core/src/utils/pathCorrector.ts

   const basename = path.basename(filePath);
   // Normalize once
   const normalizedTarget = filePath.replace(/\\/g, '/');

   const foundFiles = searchPaths
     .flatMap((searchPath) =>                                                                                          
       bfsFileSearchSync(searchPath, {                                                                                
         fileName: basename,
         maxDirs: 50,
         fileService: config.getFileService(),
         fileFilteringOptions: config.getFileFilteringOptions(),
       }),
     )
     .filter((f) =>
       // Compare against the pre-normalized string
       f.replace(/\\/g, '/').endsWith(normalizedTarget),
     );

```

**Review by galdawave — APPROVED** [review]
Nit: you have a typo in the PR title

File: packages/core/src/utils/pathCorrector.ts (hunk 3 above)
Comment (scidomino) [reply packages/core/src/utils/pathCorrector.ts]: done.

File: packages/core/src/utils/pathCorrector.ts (hunk 2 above)
Comment (scidomino) [reply packages/core/src/utils/pathCorrector.ts:54]: Agreed. But I'm going to wait for someone to request it before we do it.

File: packages/cli/src/zed-integration/fileSystemService.ts (hunk 1 above)
Comment (scidomino) [reply packages/cli/src/zed-integration/fileSystemService.ts:47]: We're removing it because we're removing the findFiles() method from the FilesystemService interface (which this implements). The only place it was used was the path corrector and in this PR we're removing it.

File: packages/core/src/utils/pathCorrector.ts (hunk 2 above)
Comment (jacob314) [reply packages/core/src/utils/pathCorrector.ts:54]: I also worry 50 is quite low. think it would be worth it to fast follow with a higher setting or perhaps a time based setting. I believe part of the problem on the systems where this causes hangs in the filesystem is networked so directory traversals are very slow. Those users already have an existing setting they set to prevent recursive file searches for path autocompletes. Potentially we should also be leveraging that here. When that option is set I would expect we shouldn't be doing any recursive file search here or in autocomplete.
