### PR TITLE
fix(cli): resolve TTY hang on headless environments by unconditionally resuming process.stdin before React Ink launch

### LINKED ISSUE #20129: Freeze Entire app
### What happened?

When I perform Authentication process,after done successfully ,Entire app is freeze,I need to close the shell and run it again in new shell.

### What did you expect to happen?

It should work smoothly.

### Client information

* **CLI Version:** 0.29.7
* **Git Commit:** e84f9015f
* **Session ID:** ab40116a-ad41-4be2-88f6-3bd6f48b1eb5
* **Operating System:** linux v24.13.1
* **Sandbox Environment:** no sandbox
* **Model Version:** auto-gemini-3
* **Auth Type:** oauth-personal
* **Memory Usage:** 377.7 MB
* **Terminal Name:** xterm.js(6.1.0-beta.109)
* **Terminal Background:** #000c18
* **Kitty Keyboard Protocol:** Unsupported

### Login information

Google Account

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by cocosheng-g**
### What does this PR do?
Fixes a terminal hang (deadlock) that occurs directly after completing the interactive Web OAuth flow in headless environments such as Google Cloud Shell.

### Root Cause
1. Upon `gemini-cli` invocation, `TerminalCapabilityManager` temporarily places `process.stdin` into raw mode and attaches a `data` listener to interrogate color capability responses from proxy terminals.
2. In Google Cloud Shell, this capability check times out after 1000ms. The `cleanup` routine then calls `removeListener('data', onData)`.
3. When the listener count on `process.stdin` drops to exactly 0, Node.js implicitly pauses the TTY input buffer natively (`process.stdin.pause()`).
4. Because Cloud Shell strictly defaults `isBrowserLaunchSuppressed` to true, the CLI immediately proxies a headless interactive URI loop into `authWithWeb` skipping standard browser spawns.
5. When `authWithWeb` concludes and hands execution over to `startInteractiveUI`, React Ink's `useInput` hooks correctly bind interactive events, but because `process.stdin` was previously put into an implicitly paused state, it permanently hangs receiving standard input events.

### Changes Made
- Added a failsafe `process.stdin.resume()` immediately before the mount of the `startInteractiveUI` flow at the end of the `gemini.tsx` CLI initializers to ensure React Ink operates on a flowing TTY stream.
- Preserved a memory leak fix in `oauth2.ts` to actively `clearTimeout` the 5-minute authentication watchdog upon successful HTTP OAuth resolution.
- Added respective unit testing around the explicit stdout stream unpause hook and authentication watchdog clearing logic in `gemini.test.tsx` and `oauth2.test.ts`.

### Bug Addressed
Fixes #20129

### CODE REVIEW

File: packages/cli/src/gemini.tsx [hunk 1]
```diff
@@ -613,8 +611,17 @@ export async function main() {
     }
 
     cliStartupHandle?.end();
+
     // Render UI, passing necessary config values. Check that there is no command line question.
     if (config.isInteractive()) {
+      // Crucial fix: earlier initialization phases (like TerminalCapabilityManager resolving
```
Comment (jacob314) [inline packages/cli/src/gemini.tsx]: nit: Remove the text
`Crucial fix:` 

Comments should indicate what the code does not why it does that.

**Review by jacob314 — APPROVED** [review]
lgtm
