### PR TITLE
fix:reorder env var redaction checks to scan values first

### LINKED ISSUE #15349: ![critical](https://www.gstatic.com/codereviewagent/critical.svg)
critical

There is a potential security vulnerability in the order of operations within `shouldRedactEnvironmentVariable`. Currently, variables in `ALWAYS_ALLOWED_ENVIRONMENT_VARIABLES` (like `PATH` or `HOME`) are immediately allowed without checking their values for secrets. This could allow a secret (e.g., an API token) to be leaked if it's part of the value of an allowed environment variable (e.g., `HOME="/some/path/with/ghp_secret..."`).

To fix this, the value should always be checked for sensitive patterns first. The name-based allowlist should only prevent redaction based on the variable's name, not its value.

I suggest reordering the checks to prioritize value scanning, ensuring that even allowed variables have their values sanitized.

```typescript
function shouldRedactEnvironmentVariable(
  key: string,
  value: string | undefined,
): boolean {
  key = key.toUpperCase();
  value = value?.toUpperCase();

  // `GEMINI_CLI_` vars are fully trusted and never redacted.
  if (key.startsWith('GEMINI_CLI_')) {
    return false;
  }

  // First, check the value. If it looks like a secret, redact it
  // regardless of the key. This is the strongest signal.
  if (value) {
    for (const pattern of NEVER_ALLOWED_VALUE_PATTERNS) {
      if (pattern.test(value)) {
        return true;
      }
    }
  }

  // Now check the key.
  // If the key is in the general allowlist, we trust it's not a secret name.
  // Since we've already checked the value, we can safely allow it.
  if (ALWAYS_ALLOWED_ENVIRONMENT_VARIABLES.has(key)) {
    return false;
  }

  // These names are always redacted.
  if (NEVER_ALLOWED_ENVIRONMENT_VARIABLES.has(key)) {
    return true;
  }

  // Redact based on name patterns.
  for (const pattern of NEVER_ALLOWED_NAME_PATTERNS) {
    if (pattern.test(key)) {
      return true;
    }
  }

  return false;
}
```

_Originally posted by @gemini-code-assist[bot] in https://github.com/google-gemini/gemini-cli/pull/15348#discussion_r2636505444_

### PR DESCRIPTION
**Pull request by kartikangiras**
## Summary
Previously `shouldRedactEnvironmentVariable` would immediately allow variables in ALWAYS_ALLOWED_ENVIRONMENT_VARIABLES (like PATH, HOME, USER) without checking their values for secrets. This could allow API tokens, private keys, or other sensitive credentials to leak if embedded in the value of an allowed by name variable.

## Details
The fix reorders the checks to prioritise value scanning: all variables have their values checked against NEVER_ALLOWED_VALUE_PATTERNS before any name based allowlist is applied. This ensures even if a variable name is allowed, a secret value will still be caught and redacted

## Related Issues
fixes #15349 

## How to Validate
```yaml
npm run test --workspace=packages/core -- environmentSanitization
```
All 22 tests pass, including the 4 new security regression tests.

## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [x] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [ ] Validated on required platforms/methods:
  - [x] MacOS
    - [x] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

File: packages/core/src/services/environmentSanitization.ts [hunk 1]
```diff
@@ -148,23 +148,38 @@ function shouldRedactEnvironmentVariable(
   key = key.toUpperCase();
   value = value?.toUpperCase();
 
-  // User overrides take precedence.
+  // `GEMINI_CLI_` vars are fully trusted internal variables and never redacted.
```
Comment (scidomino) [inline packages/core/src/services/environmentSanitization.ts]: Remove this and most (or all) of these other comments. GCLI has a bad habit of narrating the code.

Comment (kartikangiras) [reply packages/core/src/services/environmentSanitization.ts]: i have removed most of the comments keeping only the platform and pattern based comments if you want i can remove them as well.

**Review by scidomino — APPROVED** [review]
