### PR TITLE
fix(plan): reserve minimum height for selection list in AskUserDialog

### LINKED ISSUE #23271: Exit plan mode confirmation UI not showing all options by default
https://x.com/i/status/2034762595761365436

Investigate UI tweak to show more options in plan mode confirmation.

### PR DESCRIPTION
**Pull request by ruomengz**
## Summary

This PR fixes a UI issue where the `ExitPlanModeDialog` truncated selection options in smaller terminal heights.

## Details

**UI Layout Fix**: In `ExitPlanModeDialog.tsx`, the `AskUserDialog` is configured with `unconstrainedHeight: false`.
The default height for plan content is `Math.min(15, Math.max(1, listHeight - DIALOG_PADDING))`, when 
In terminals with fewer than ~24 lines, the default 15-line cap for the plan content was starving the options list of space, causing it to truncate items. Updating the cap for plan content to leave space for at least 3 options if there are more.

## Related Issues

#23271 

## How to Validate

1.  **Build**: Run `npm run build` to ensure the compilation error is resolved.
2. **Unit test**: Run `npm test -w @google/gemini-cli -- src/ui/components/AskUserDialog.test.tsx`
3.  **Manual Check**:
    -   Resize your terminal to a small height (e.g., 20 lines).
    -   Enter plan mode and ask "create a dummy plan with 50 lines"
    -   Verify that all three options ("automatically accept", "manually accept", and "Type your feedback...") are visible simultaneously without scrolling.
image

## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [x] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [x] Validated on required platforms/methods:
  - [x] MacOS
    - [x] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

File: packages/cli/src/ui/components/AskUserDialog.tsx [hunk 1]
```diff
@@ -849,11 +849,19 @@ const ChoiceQuestionView: React.FC<ChoiceQuestionViewProps> = ({
     ? Math.max(1, availableHeight - overhead)
     : undefined;
 
+  // Reserve space for at least 3 items if more selectionItems available.
+  const reservedListHeight = Math.min(selectionItems.length * 2, 6);
```
Comment (jacob314) [inline packages/cli/src/ui/components/AskUserDialog.tsx:853]: why this min of 6? if the AskUserDialog has only 2 options won't thisesult is reserving too much space?

Comment (ruomengz) [reply packages/cli/src/ui/components/AskUserDialog.tsx:853]: If there are only 2 options, it will reserve 4 lines (selectionItems.length * 2).

**Review by jacob314 — APPROVED** [review]
This isn't quite right but is a step in the right direction. Approving and I'll land a fast follow to fix this fully.lgtm
