### PR TITLE
fix: unset GEMINI_API_KEY env var if empty

### LINKED ISSUE #5747: Empty API Key Handling and Input Validation Issue
### What happened?

Empty API keys not being handled gracefully. This is a challenge in systems where missing values default to empty.

### What did you expect to happen?

I'd expect empty API keys to be handled as though it's absent.

### Client information

```console
 CLI Version       0.1.18                              
 OS                darwin                              
 Auth Method       vertex-ai
```

### Login information

Vertex AI, but with an empty API key

### Anything else we need to know?

Other environment variables (GOOGLE_API_KEY, GOOGLE_CLOUD_PROJECT, etc.) should have validation too

### PR DESCRIPTION
**Pull request by gsquared94**
## TLDR
If the `GEMINI_API_KEY` env var is set to empty string and Vertex AI env vars are set, then the `GoogleGenAI` client is initialized with `{"apiKey":"","vertexai":true}` which fails to use Vertex AI.
```
[API Error: {"error":{"code":401,"message":"Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.","status":"UNAUTHENTICATED","details":[{"@type":"type.googleapis.com/google.rpc.DebugInfo","detail":"Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project."},{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"CREDENTIALS_MISSING","domain":"googleapis.com","metadata":{"method":"google.cloud.aiplatform.v1beta1.PredictionService.CountTokens","service":"aiplatform.googleapis.com"}}]}}]
```
This is causing failures for Github Action runtimes. 

Will submit a fix upstream, but handling it here directly.

Fixes: #5747

### CODE REVIEW

File: packages/cli/src/gemini.tsx [hunk 1]
```diff
@@ -227,6 +227,10 @@ export async function main() {
       );
     }
   }
+  // Empty key causes issues with the GoogleGenAI package.
+  if (process.env['GEMINI_API_KEY']?.trim() === '') {
+    delete process.env['GEMINI_API_KEY'];
+  }
```
Comment (jerop) [inline packages/cli/src/gemini.tsx:233]: I think we should do the same for GOOGLE_API_KEY as well; I'd expect it to have the same issue

**Review by jerop — COMMENTED** [review]
thanks for this fix @gsquared94!

File: packages/cli/src/gemini.tsx (hunk 1 above)
Comment (gsquared94) [reply packages/cli/src/gemini.tsx:233]: done

**Review by jerop — APPROVED** [review]
