### PR TITLE
fix(core): destroy PTY on kill() and exception to prevent fd leak

### LINKED ISSUE #21767: PTY file descriptors leak on kill() and post-spawn exception
## Problem

On macOS, each shell command spawns a PTY via `/dev/ptmx`. The kernel limits these to 511 (`kern.tty.ptmx_max`). `destroy()` is called in the `onExit` and `background()` paths, but is missing from `kill()` and the catch block after spawn.

This causes leaked file descriptors that accumulate until the Gemini process exits, eventually exhausting the PTY limit and preventing new terminal tabs from opening.

## Steps to reproduce

1. Use Gemini CLI with shell commands
2. Cancel/kill running commands repeatedly
3. After many kills, new terminal tabs fail to open
4. `ls /dev/ttys* | wc -l` shows count approaching 511

## Expected behavior

PTY file descriptors should be released when:
- `kill()` terminates an active PTY process
- An exception occurs after PTY spawn but before the exit handler is registered

## Environment

- macOS (kern.tty.ptmx_max = 511)
- Affects all macOS users running shell commands via Gemini CLI

### PR DESCRIPTION
**Pull request by nbardy**
Fixes #21767

## Summary
- Add `destroy()` call in `kill()` before removing from activePtys map
- Hoist `spawnedPty` ref outside try block so catch can destroy on error
- Matches existing cleanup pattern used in `onExit` and `background()`

## Test plan
- [x] Regression test: PTY destroy on `kill()`
- [x] Regression test: PTY destroy on post-spawn exception
- [x] All 55 shellExecutionService tests passing
- [x] Verified PTY reclamation: 527 → 48 `/dev/ttys*` after killing leaking sessions

### CODE REVIEW

File: packages/core/src/services/shellExecutionService.ts [hunk 1]
```diff
@@ -552,6 +552,11 @@ export class ShellExecutionService {
       // This should not happen, but as a safeguard...
       throw new Error('PTY implementation not found');
     }
+    // Declared outside try so catch can destroy it if spawn succeeded
```
Comment (jacob314) [inline packages/core/src/services/shellExecutionService.ts]: revert this comment as it is low value

File: packages/core/src/services/shellExecutionService.ts [hunk 2]
```diff
@@ -585,6 +590,8 @@ export class ShellExecutionService {
         },
         handleFlowControl: true,
       });
+      // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
```
Comment (jacob314) [inline packages/core/src/services/shellExecutionService.ts]: add appropriate casts rather than ignoring this lint.

File: packages/core/src/services/shellExecutionService.ts [hunk 3]
```diff
@@ -882,6 +889,18 @@ export class ShellExecutionService {
     } catch (e) {
       // eslint-disable-next-line @typescript-eslint/no-unsafe-type-assertion
       const error = e as Error;
+
+      // FIX: If the PTY was spawned before the exception, destroy it to
```
Comment (jacob314) [inline packages/core/src/services/shellExecutionService.ts]: remove the FIX comment. it describes changes made rather than why the code does what it does.

File: packages/core/src/services/shellExecutionService.ts [hunk 4]
```diff
@@ -1008,6 +1027,15 @@ export class ShellExecutionService {
       this.activeChildProcesses.delete(pid);
     } else if (activePty) {
       killProcessGroup({ pid, pty: activePty.ptyProcess }).catch(() => {});
+      // FIX: Destroy the PTY to release the /dev/ptmx file descriptor.
```
Comment (jacob314) [inline packages/core/src/services/shellExecutionService.ts]: revert this fix comment as well

**Review by jacob314 — COMMENTED** [review]
Thanks for this fix! Approved once the suprious comments are removed and the unrelated keychain changes are removed. if you think they are needed feel free to add a separate pr for them

**Comment by nbardy** [comment]
All review feedback addressed in the latest force-push:

- Removed all low-value/FIX comments
- Replaced `eslint-disable no-unsafe-assignment` with proper `as IPty` type cast
- Keychain idempotent-delete changes moved to separate PR #21762
- Removed `Co-Authored-By: Claude` (was blocking CLA)
- Squashed to a single clean commit on upstream/main

**Review by jacob314 — APPROVED** [review]
lgtm
