### PR TITLE
fix(cli): gemini command stuck in git bash

### LINKED ISSUE #4588: Git Bash on windows doesn't run the gemini command.
### What happened?

When trying to run ~gemini~ command in a git bash terminal on windows, nothing happens. The program doesn't start the auth process, nor does it seem to even operate. The terminal just gets stale and nothing happens. Running it as administrator doesn't help either.

Image

### What did you expect to happen?

Authentication prompt, and theme selector to initiate.

### Client information

<details>

```console
CLI Version            0.1.13                                      │
│ Git Commit             412b78c5 (local modifications)              │
│ Model                  gemini-2.5-pro                              │
│ Sandbox                no sandbox                                  │
│ OS                     win32                                       │
│ Auth Method            OAuth
```

</details>

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by dumbbellcode**
## TLDR

This MR fixes the problem where `gemini` command gets stuck when run on git bash. This primarily happens because we expect input to be already piped in when stdin is not TTY i.e `isTTY` is false.

## Dive Deeper

**Ideal case**
When you type `gemini` in terminal, since nothing is already piped, stdin gets connected to terminal (i.e `isTTY` flag is true)

**Edge case (In git bash)**
In this git bash when we type `gemini` in git bash, stdin is connected to bash but the flag  `isTTY` is still false because windows implements it's own way of piping git bash data into stdin i.e stdin does not look like a terminal device but a pipe. 

Now because `isTTY` is false, we expect the data was already piped before, but that isn't the case, this causes the program to wait for stdin (`readStdin()`), but there's nothing to read, so the program is stuck is waiting state. Even if user types something, there is nothing to indicate end of input stream. 

To solve this problem, we can wait for a short period to see whether input stream has some text or not, if not then we stop reading and exit. 

## Reviewer Test Plan

There's two ways of testing this
1. Actual test on git bash on windows or similar non tty shell.
2. Manually modifying code to trigger that flow

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | x  | x  | ❓  |
| npx      | ❓  | ❓  | ❓  |
| Docker   | ❓  | ❓  | ❓  |
| Podman   | ❓  | -   | -   |
| Seatbelt | ❓  | -   | -   |

## Linked issues / bugs

- Fixes #4588

### CODE REVIEW

File: packages/cli/src/utils/readStdin.ts [hunk 1]
```diff
@@ -4,16 +4,25 @@
...
+import { clearTimeout } from 'node:timers';
+
 export async function readStdin(): Promise<string> {
   const MAX_STDIN_SIZE = 8 * 1024 * 1024; // 8MB
   return new Promise((resolve, reject) => {
     let data = '';
     let totalSize = 0;
     process.stdin.setEncoding('utf8');
 
+    const pipedInputShouldBeAvailableInMs = 100;
```
[the remark this answers is not in the document]
Comment (dumbbellcode) [reply packages/cli/src/utils/readStdin.ts]: fair point, i have increased the reading timeout

File: packages/cli/src/utils/readStdin.ts [hunk 2]
```diff
@@ -4,16 +4,27 @@
...
+      // stop reading if input is not available yet, this is needed
+      // in terminals where stdin is never TTY and nothing's piped
+      // which causes the program to get stuck expecting data from stdin
+      onEnd();
+    }, pipedInputShouldBeAvailableInMs);
+
     const onReadable = () => {
       let chunk;
       while ((chunk = process.stdin.read()) !== null) {
+        clearTimeout(pipedInputTimeout);
```
Comment (jacob314) [inline packages/cli/src/utils/readStdin.ts]: nit: mark that the timeout has already been cleared rather than repeatedly clearing it each chunk. if nothing else that makes it clear we are only intending to do it once.

**Review by jacob314 — COMMENTED** [review]
I'll approve once we have a test for this. ideally this would be tested both by a unittest to verify the logic about when we timeout and an integration test that verifies the problematic behavior with git bash so we do not regress it.

Thank you for this change. This is a great robustness fix.

File: packages/cli/src/utils/readStdin.ts (hunk 2 above)
Comment (dumbbellcode) [reply packages/cli/src/utils/readStdin.ts]: agree, have refactored to use timer id and reset it once timeout it cleared

**Comment by dumbbellcode** [comment]
Thanks for reviewing @jacob314, I have added a few unit tests that mock the behaviour in terminals like Git bash where gemini gets stuck reading for end of stream. I tried reproducing it with e2e test but seems like we will need to run it in a new job (where isTTY returns false and it's still non interactive) where we run it in git bash / mintty. Let me know if that's a good idea.

Update: Found a way to add a regression test, checkout [this test](https://github.com/google-gemini/gemini-cli/pull/6397/commits/d8da329cf0b40a376d6d05f545b54553e2a0f6a7) 🙂

File: integration-tests/stdin-context.test.ts [hunk 3]
```diff
@@ -67,4 +67,31 @@ describe('stdin context', () => {
       'Expected the model to identify the secret word from stdin',
     ).toBeTruthy();
   });
+
+  it.only('should exit quickly if stdin stream does not end', async () => {
```
Comment (NTaylorMullen) [inline integration-tests/stdin-context.test.ts]: @dumbbellcode thank you for the contribution! Would you mind removing this `.only` portion? It'll skip all the other test sotherwise

File: packages/cli/src/gemini.tsx [hunk 4]
```diff
@@ -342,7 +342,8 @@ export async function main() {
     }
   }
   if (!input) {
-    console.error('No input provided via stdin.');
+    console.error(`No input provided via stdin. Input can be provided by piping 
+    data into gemini or using the --prompt option.`);
```
Comment (NTaylorMullen) [inline packages/cli/src/gemini.tsx]: Lets drop the newline here.

**Review by NTaylorMullen — COMMENTED** [review]
Agree with @jacob314, than you for addressing @dumbbellcode!

**Comment by NTaylorMullen** [comment]
Can help approve once merge conflicts are taken care of and a few of my comments!

File: integration-tests/stdin-context.test.ts (hunk 3 above)
Comment (dumbbellcode) [reply integration-tests/stdin-context.test.ts]: yup, pushed by mistake, was for local testing, removed

**Comment by dumbbellcode** [comment]
hey @NTaylorMullen, have resolved merge conflicts and above comments, seems like a similar change was merged 3 hours back without tests, have written this one as it's cleaner.

**Review by NTaylorMullen — APPROVED** [review]

**Comment by NTaylorMullen** [comment]
@dumbbellcode looks like you may need to run `npm run format` and push the branch one more time to fix formatting issues

**Comment by dumbbellcode** [comment]
sorry for this @NTaylorMullen, is fixed now 👍

**Comment by dumbbellcode** [comment]
hmm, looks like an arbitrary failure
