### PR TITLE
fix(cli): cap shell output at 10 MB to prevent RangeError crash

### LINKED ISSUE #19664: Gemini CLI crashed after inactivity with a RangeError: Invalid string length.
### What happened?

RangeError: Invalid string length
    at Ink.onRender

More details in b/485951886

Note that this is after multiple days of inactivity in a tmux session

### What did you expect to happen?

No error

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
# paste output here
```

</details>

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by ProthamD**
Screenshot 2026-03-07 094632

Screenshot 2026-03-07 093238

## Summary

The idea was . cap background shell output at 10 MB to prevent a `RangeError: Invalid string
length` crash that occurs in long-running sessions (e.g. a tmux session left open
for multiple days) when accumulated PTY output exceeds JavaScript's maximum string
length.

### The Problem
Background shells append every PTY chunk to an unbounded string in `shellReducer.ts`. 
After days of inactivity, this string can exceed ~1 GB (JavaScript's limit), causing 
`RangeError: Invalid string length` and crashing the entire CLI process.

### The Solution
Two-part fix:
1. **Hard cap**: `MAX_SHELL_OUTPUT_SIZE = 10_000_000` (10 MB) — large enough for 
   ~200,000 lines of terminal output, well below the crash threshold
2. **Amortized truncation**: Only slice when output exceeds 
   `MAX_SHELL_OUTPUT_SIZE + SHELL_OUTPUT_TRUNCATION_BUFFER` (11 MB), then truncate 
   back to 10 MB. This reduces the O(n) string copy cost from once-per-chunk to 
   once-per-1MB-of-output, eliminating steady-state performance overhead.

### Why This Approach?
- **Simple**: 3 lines of code, easy to review and maintain
- **Efficient**: Amortization eliminates the slice overhead in high-throughput shells
- **Safe**: Multiple shells (5 × 10 MB = 50 MB) stay 20x below crash threshold

### Why NOT Other Approaches?
- **Sliding window (chunk array)**: Would require joining on every Ink re-render 
  (~60 FPS) — O(n) cost per frame instead of per 1 MB of input
- **Larger cap (100 MB)**: 10× more memory per shell, tighter safety margin
- **Smaller cap (1 MB)**: Loses useful history; users expect at least 5-10 MB

### Performance Impact
- **Before**: Unbounded memory growth; crash after ~days in production
- **After**: O(n) string copy once per 1 MB of output; bounded memory ≤ 10 MB per shell
- **CPU overhead**: Negligible (1 copy per 1 MB on busy shells, none on quiet shells)

## How It Works

When `appendShellOutput` is called:
1. Append the chunk to `shell.output`
2. Check: if length > 11 MB, slice back to 10 MB (keep newest bytes)
3. Continue normally

This means the expensive slice operation only fires when you've accumulated 1 MB 
of new output past the cap — in a typical busy shell (~1 KB/sec), that's once 
every ~280 hours of continuous output.

## Edge Cases Covered
- ✅ Output below cap (no truncation needed) — test covers this
- ✅ Output exactly at cap (no truncation) — test covers this  
- ✅ Output past trigger (truncates correctly) — test covers this
- ✅ Multiple background shells (each has independent 10 MB cap)
- ✅ Idle shells (no truncation overhead when quiet)
- ✅ AnsiOutput type (not truncated, only string type is capped)

## Related Issues

Fixes #19664

## How to Validate

1. Build the project:
   ```
   npm run build -w packages/cli
   ```
2. Run the unit tests for the changed reducer:
   ```
   npx vitest run packages/cli/src/ui/hooks/shellReducer.test.ts
   ```
   All 13 tests should pass, including:
   `✓ shellReducer > should truncate shell output when it exceeds MAX_SHELL_OUTPUT_SIZE`

3. **Manual smoke test (simulating the crash):** Start a long-running background
   shell command and confirm the CLI continues to function normally without
   crashing after extended output.

## Pre-Merge Checklist

- [x] Updated relevant documentation and README (if needed) — no doc changes required
- [x] Added/updated tests (if needed) — new test added in `shellReducer.test.ts`
- [ ] Noted breaking changes (if any) — none
- [ ] Validated on required platforms/methods:
  - [ ] MacOS
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [x] Windows
    - [x] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

File: packages/cli/src/ui/hooks/shellReducer.ts [hunk 1]
```diff
@@ -98,13 +102,38 @@ export function shellReducer(
...
+          typeof task.output === 'string' ? task.output : '';
+        const combinedLength = currentOutput.length + action.chunk.length;
+
+        if (
+          combinedLength >
+          MAX_SHELL_OUTPUT_SIZE + SHELL_OUTPUT_TRUNCATION_BUFFER
+        ) {
+          // Truncate using Array.from to avoid splitting multi-byte Unicode
+          // characters (e.g. emojis) at a code-unit boundary.
+          const chunkArr = Array.from(action.chunk);
```
Comment (ruomengz) [inline packages/cli/src/ui/hooks/shellReducer.ts]: Great catch on preventing surrogate pair splits! However, using Array.from() on a 10MB string is extremely heavy—it blocks the main thread for up to 1 second and causes huge memory spikes on every
truncation.

Even worse, Array.from().length counts code points, but string.length counts code units. If the log has lots of emojis (2 units each), keeping 10 million code points will result in a string longer than our
11 million code unit threshold. This causes the CLI to run the expensive 1-second truncation on every single incoming chunk, freezing the app.

We can get the exact same surrogate-safety with native slicing (which takes ~2ms) by just checking if the slice landed on a low surrogate half (\uDC00-\uDFFF).

Here is the optimized logic:
```
        if (
          combinedLength >
          MAX_SHELL_OUTPUT_SIZE + SHELL_OUTPUT_TRUNCATION_BUFFER
        ) {
          if (action.chunk.length >= MAX_SHELL_OUTPUT_SIZE) {
            // Incoming chunk alone exceeds the cap — keep its tail.
            newOutput = action.chunk.slice(-MAX_SHELL_OUTPUT_SIZE);
          } else {
            // Keep as much of the existing output as possible, then append.
            const keepFromCurrent = MAX_SHELL_OUTPUT_SIZE - action.chunk.length;
            newOutput = currentOutput.slice(-keepFromCurrent) + action.chunk;
          }

          // Truncation by code unit might split a surrogate pair at the start.
          // If the first character is a low surrogate (\uDC00-\uDFFF),
          // slice it off to avoid displaying a broken character.
          if (newOutput.length > 0) {
            const firstCharCode = newOutput.charCodeAt(0);
            if (firstCharCode >= 0xDC00 && firstCharCode <= 0xDFFF) {
              newOutput = newOutput.slice(1);
            }
          }
        } else {
          newOutput = currentOutput + action.chunk;
        }
```

**Review by ruomengz — APPROVED** [review]

File: integration-tests/replace.test.ts
Comment (ruomengz) [inline integration-tests/replace.test.ts:1]: This test failure is probably just flaky, can you remove this unrelated change?

Comment (ProthamD) [reply integration-tests/replace.test.ts:1]: Okey I will remove this change and push it again

**Comment by ProthamD** [comment]
I guess it's still on hold even after allowing auto merge

**Comment by ProthamD** [comment]
Thank you for all the support

**Comment by ProthamD** [comment]
Hello @SHARABUMANOJKUMAR , This is a merged PR, means the work is done already, the fix is there, look for an open issue ,  thank you for showing interest.

**Comment by SHARABUMANOJKUMAR** [comment]
Thanks for the clarification!

I’ll look for another open issue to work on. Appreciate the guidance.
