### PR TITLE
fix(cli): allow perfect match @-path completions to submit on Enter

### LINKED ISSUE #19245: Unable to accept a directory completion to submit a prompt
If you write `@foo/bar` where foo/bar is a valid directory in your project then you cannot submit the prompt by pressing enter as you remain stuck on the directory completion for @foo/bar 

This should be mitigated by having pressing enter when the completion exactly matches the text already in the input prompt close autocomplete.

### PR DESCRIPTION
**Pull request by spencer426**
## Summary

Fixes a UX bug where directory and file autocompletion was "sticky," requiring users to press Enter twice to submit a prompt even when the input exactly matched a suggestion.

## Details

- Removed the explicit exclusion of `CompletionMode.AT` from the "perfect match" submission logic in `InputPrompt.tsx`.
- Updated `InputPrompt.test.tsx` to verify that @-paths now submit on Enter when they are a perfect match.

## Related Issues

Fixes #19245

## How to Validate

1. Build the project: `npm run build`
2. Run the CLI: `node packages/cli/dist/index.js`
3. Type a perfect match path like `@package.json` and press **Enter**.
   - **Expected:** The prompt submits immediately.
4. Type a partial match like `@pack` and press **Enter**.
   - **Expected:** The text autocompletes to `@package.json` but does NOT submit.

## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [x] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [x] Validated on required platforms/methods:
  - [ ] MacOS
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [x] Linux
    - [x] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

File: packages/cli/src/test-utils/render.tsx [hunk 1]
```diff
@@ -357,7 +357,8 @@ export const render = (
       debug: false,
       exitOnCtrlC: false,
       patchConsole: false,
-      onRender: (metrics: { output: string; staticOutput?: string }) => {
+      // eslint-disable-next-line @typescript-eslint/no-explicit-any
+      onRender: (metrics: any) => {
```
Comment (scidomino) [inline packages/cli/src/test-utils/render.tsx]: Don't use `any`.

Comment (spencer426) [reply packages/cli/src/test-utils/render.tsx]: Done

**Review by scidomino — APPROVED** [review]
