### PR TITLE
At Command Race Condition Bugfix For Non-Interactive Mode

### LINKED ISSUE #6474: Degradation of Instruction Following in Gemini Model
### What happened?

Both in Gemini CLI and via the API, users had been reporting issues with instruction following - the model fails to respond to the most recent message and instead get into a loop of responding to an older message or other context in the chat history. This appears to had been an issue for some time now, but has gotten worse recently.

##### Gemini CLI

- https://github.com/google-gemini/gemini-cli/issues/6147
- https://github.com/google-gemini/gemini-cli/issues/6246
- https://github.com/google-gemini/gemini-cli/issues/6455
- https://github.com/google-gemini/gemini-cli/issues/6239
- https://github.com/google-gemini/gemini-cli/issues/6221
- https://github.com/google-gemini/gemini-cli/issues/6200
- https://github.com/google-gemini/gemini-cli/issues/6190
- https://github.com/google-gemini/gemini-cli/issues/6443
- https://github.com/google-gemini/gemini-cli/issues/6149
- https://github.com/google-gemini/gemini-cli/issues/6136
- https://github.com/google-gemini/gemini-cli/issues/6127
- https://github.com/google-gemini/gemini-cli/issues/6319
- https://github.com/google-gemini/gemini-cli/issues/6067
- https://github.com/google-gemini/gemini-cli/issues/6034
- https://github.com/google-gemini/gemini-cli/issues/5971
- https://github.com/google-gemini/gemini-cli/issues/5963
- https://github.com/google-gemini/gemini-cli/issues/5854
- #6739
- #6735
- #6719

##### Google Support:

- [Gemini AI chat returning repeated responses](https://support.google.com/gemini/thread/365334436/issue-with-gemini-ai-chat-returning-repeated-responses?hl=en)
- [Gemini Pro keeps referring back to older prompts](https://support.google.com/gemini/thread/342765378/gemini-pro-keeps-referring-back-to-older-prompts?hl=en)
- [Gemini 2.5 Pro Repeats Itself](https://support.google.com/gemini/thread/349203730/gemini-2-5-pro-repeats-itself-seems-not-to-be-related-to-stuck-loop-issue-reported-elsewhere?hl=en)

##### Reddit:
- [For the first time, I believe Gemini 2.5 Pro is performing worse. Power User since Day 1.](https://www.reddit.com/r/GeminiAI/comments/1mnc3ty/for_the_first_time_i_believe_gemini_25_pro_is/)
- [Has gemini got a lobotomy last Friday?](https://www.reddit.com/r/Bard/comments/1mnko71/has_gemini_got_a_lobotomy_last_friday/)
- [RooCode Gemini 2.5 has been awful lately](https://www.reddit.com/r/RooCode/comments/1mq9p9h/roocode_gemini_25_has_been_awful_lately/)
- [Gemini 2.5 Pro Suddenly Struggling with Coding Instructions. Anyone else?](https://www.reddit.com/r/GeminiAI/comments/1mne23q/gemini_25_pro_suddenly_struggling_with_coding/)

### What did you expect to happen?

That the model responds to the most recent user instruction or agent-generated tool-call.

### Client information

<details>
Version 0.1.21
</details>

### Login information

Google Account (OAuth): 3
Api key: 3

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by mrcabbage972**
## TLDR
Fixing a race condition in non-interactive mode that occurs when a @include command in a user query is slower to execute than a next speaker check.

## Dive Deeper
Follow up of https://github.com/google-gemini/gemini-cli/pull/6663 to fix the issue in non-interactive mode.

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | ❓  | ❓  | ❓  |
| npx      | ❓  | ❓  | ❓  |
| Docker   | ❓  | ❓  | ❓  |
| Podman   | ❓  | -   | -   |
| Seatbelt | ❓  | -   | -   |

### CODE REVIEW

File: packages/cli/src/nonInteractiveCli.ts [hunk 1]
```diff
@@ -40,9 +41,26 @@ export async function runNonInteractive(
...
+      addItem: (_item, _timestamp) => 0,
+      onDebugMessage: () => {},
+      messageId: Date.now(),
+      signal: abortController.signal,
+    });
+
+    if (!shouldProceed || !processedQuery) {
+      // An error occurred during @include processing (e.g., file not found).
+      // The error message is already logged by handleAtCommand.
+      return;
```
Comment (anj-s) [inline packages/cli/src/nonInteractiveCli.ts]: can we add an exit error message  so that we don't exit silently?

Comment (mrcabbage972) [reply packages/cli/src/nonInteractiveCli.ts]: Done

Comment (anj-s) [reply packages/cli/src/nonInteractiveCli.ts]: shouldn't process.exit() suffice or do we need a return?

**Review by anj-s — APPROVED** [review]
