### PR TITLE
fix(core): Allow model to be set from `settings.json`

### LINKED ISSUE #4191: Public Roadmap
This is a tracking issue for navigating the living public roadmap for Gemini CLI. If you are interested in following along with what we are doing, or even more exciting, looking to contribute. Please browse through here. Any items within are fair game and would be great contributions.

### LINKED ISSUE #5373: Hardcoded DEFAULT_GEMINI_MODEL overrides settings.json configuration
**Description:**

The Gemini CLI appears to have a hardcoded default model, `gemini-2.5-pro`, which overrides the user's configured default model in `~/.gemini/settings.json`. This prevents users from setting a different default model through the recommended configuration file.

**Steps to Reproduce:**

   1.  Set a default model in `~/.gemini/settings.json`, for example:
      {
        "model": "gemini-2.5-flash"
      }

  2.  Ensure no model is specified in shell configuration files (e.g., `.zshrc`, `.bashrc`).
  3.  Run the `gemini` command without any model flags.

**Expected Behavior:**

The Gemini CLI should use the model specified in `~/.gemini/settings.json`.

**Actual Behavior:**

The Gemini CLI uses the hardcoded `gemini-2.5-pro` model.

**Investigation Details:**

A search reveals that the file `.npm/_npx/38c708f8d73fe4c9/node_modules/@google/gemini-cli/bundle/
      gemini.js` contains the following line:
  var DEFAULT_GEMINI_MODEL = "gemini-2.5-pro";

This hardcoded value seems to be the cause of the issue.

**Workaround:**

Explicitly specify the model on the command line:
`gemini --model gemini-2.5-flash`

**Suggested Fix:**

Remove the hardcoded `DEFAULT_GEMINI_MODEL` and allow the `settings.json` configuration to take precedence.

### PR DESCRIPTION
**Pull request by richieforeman**
## TLDR

This allows `model` setting to be applied from `settings.json`, defaulting only to the DEFAULT_MODEL (Gemini 2.5 Pro) iff there is nothing in argv && merged settings.

## Dive Deeper

I felt it made sense to have the `--model` flag always take priority over other values, since that's always invoked by the user on demand rather than a passive config file.

## Reviewer Test Plan

- If `settings.json` && `--model` are empty, then the default model should kick in
- `--model` always wins over `settings.json`

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | x  | ❓  | x  |
| npx      | ❓  | ❓  | ❓  |
| Docker   | x  | ❓  | ❓  |
| Podman   | ❓  | -   | -   |
| Seatbelt | x  | -   | -   |

## Linked issues / bugs

- Resolves #5373

### CODE REVIEW

File: packages/cli/src/config/settings.ts [hunk 1]
```diff
@@ -86,6 +86,8 @@ export interface Settings {
   bugCommand?: BugCommandSettings;
   checkpointing?: CheckpointingSettings;
   autoConfigureMaxOldSpaceSize?: boolean;
+  /** The model name to use (e.g 'gemini-9.0-pro') */
```
Comment (jacob314) [inline packages/cli/src/config/settings.ts:89]: wow didn't realize 9.0 pro was out :)

**Review by jacob314 — APPROVED** [review]
lgtm

**Comment by NGS-NEGUS** [comment]
> ## TLDR
> 
> This allows `model` setting to be applied from `settings.json`, defaulting only to the DEFAULT_MODEL (Gemini 2.5 Pro) iff there is nothing in argv && merged settings.
> 
> ## Dive Deeper
> 
> I felt it made sense to have the `--model` flag always take priority over other values, since that's always invoked by the user on demand rather than a passive config file.
> 
> ## Reviewer Test Plan
> 
> - If `settings.json` && `--model` are empty, then the default model should kick in
> - `--model` always wins over `settings.json`
> 
> ## Testing Matrix
> 
> |          | 🍏  | 🪟  | 🐧  |
> | -------- | --- | --- | --- |
> | npm run  | x  | ❓  | x  |
> | npx      | ❓  | ❓  | ❓  |
> | Docker   | x  | ❓  | ❓  |
> | Podman   | ❓  | -   | -   |
> | Seatbelt | x  | -   | -   |
> 
> ## Linked issues / bugs
> 
> - Resolves #5373
