### PR TITLE
fix(cli): wrap terminal capability queries in hidden sequence

### LINKED ISSUE #19081: fix(cli): stray 'm' character printed during terminal startup
### What happened?

During startup, the Gemini CLI queries the terminal for capabilities (like modifyOtherKeys and Kitty protocol). On some terminals (e.g., Apple Terminal, certain tmux versions), this query results in a stray "m" character being printed to the command line, which can interfere with the user's input or display.

### What did you expect to happen?

The terminal capability detection should happen silently in the background without leaving any visual artifacts like a stray "m" on the command line.

### Client information

<details>
<summary>Client Information</summary>

Platform: macOS (Darwin)
Architecture: arm64
Version: 0.30.0-nightly (development)

</details>

### Login information

Google Account (Gemini Code Assist)

### Anything else we need to know?

The issue seems related to how certain terminals handle the `modifyOtherKeys` or Kitty protocol queries. Wrapping the queries in a hidden mode sequence and clearing the line afterwards resolves the visibility issue.

### PR DESCRIPTION
**Pull request by srithreepo**
## Summary

Wrap terminal capability queries in a hidden mode sequence and clear the line afterwards to prevent a stray "m" character from appearing on some terminals (e.g., Apple Terminal, some tmux versions) during startup.

## Details

When the CLI starts, it queries the terminal for various capabilities (Kitty protocol, background color, etc.). Some terminals might echo part of the response or malform it such that a stray "m" remains on the command line. By wrapping these queries in `\x1b[8m` (hidden mode) and following up with `\x1b[2K
` (clear line and return) and `\x1b[0m` (reset attributes), we ensure any echoed or malformed output is not visible to the user.

## Related Issues

Fixes #19081

None.

## How to Validate

1. Run the project in a terminal that was previously showing the stray "m".
2. Observe that the "m" no longer appears during startup.
3. Run unit tests: `npm test -w @google/gemini-cli -- src/ui/utils/terminalCapabilityManager.test.ts`.

## Pre-Merge Checklist

- [x] Updated relevant documentation and README (if needed) - Not needed
- [x] Added/updated tests (if needed)
- [x] Noted breaking changes (if any) - None
- [x] Validated on required platforms/methods:
  - [x] MacOS
    - [x] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
  - [ ] Linux

### CODE REVIEW

File: packages/cli/src/ui/utils/terminalCapabilityManager.ts [hunk 1]
```diff
@@ -219,11 +219,19 @@ export class TerminalCapabilityManager {
       try {
         fs.writeSync(
           process.stdout.fd,
-          TerminalCapabilityManager.KITTY_QUERY +
+          // Use hidden mode to prevent potential "m" character from being printed
+          // to the terminal during startup when querying for modifyOtherKeys.
+          // This can happen on some terminals that might echo the query or
+          // malform the response. We hide the output, send queries, then
+          // immediately clear the line and reset attributes.
+          '\x1b[8m' +
```
Comment (scidomino) [inline packages/cli/src/ui/utils/terminalCapabilityManager.ts]: Make these constants like the other codes

**Review by scidomino — APPROVED** [review]

File: packages/cli/src/ui/utils/terminalCapabilityManager.ts (hunk 1 above)
Comment (srithreepo) [reply packages/cli/src/ui/utils/terminalCapabilityManager.ts]: Good call !
