### PR TITLE
Fix `-e <extension>` for disabled extensions

### LINKED ISSUE #8752: -e/--extensions flag does not override disabledExtensions setting in settings.json
### What happened?

The `-e` or `--extensions` flag does not override the `disabledExtensions` setting in `settings.json`. If an extension has been disabled using `gemini extensions disable <extension_name>`, it cannot be temporarily re-enabled for a single session using the `-e <extension_name>` flag. This prevents a useful workflow where an extension can be disabled by default but enabled for a specific, one-off command.

**To Reproduce:**

1.  Install an extension, for example, `MyExtension`.
2.  Disable the extension using the command: `gemini extensions disable MyExtension`
3.  Verify that the extension is listed in the `disabledExtensions` array in your `~/.gemini/settings.json` file.
4.  Attempt to run Gemini CLI with the disabled extension enabled for a single session using the `-e` flag: `gemini -e MyExtension -p "hello"`
5.  Observe that the extension is not loaded and its tools are not available.

### What did you expect to happen?

The `-e <extension_name>` flag should take precedence over the `disabledExtensions` setting in `settings.json`, allowing a disabled extension to be enabled for the current session only. This would enable a workflow where extensions can be installed but disabled by default, and then activated on-demand for specific sessions.

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
╭────────────────────────────────────────────────────────╮
│                                                        │
│ About Gemini CLI                                       │
│                                                        │
│ CLI Version        0.6.0-nightly-git.c4c81e3d          │
│ Git Commit         c4c81e3d                            │
│ Model              gemini-2.5-pro                      │
│ Sandbox            no sandbox                          │
│ OS                 linux                               │
│ Auth Method        gemini-api-key                      │
│ IDE Client         IDE                                 │
│                                                        │
╰────────────────────────────────────────────────────────╯

```

</details>

### Login information

GEMINI_API_KEY

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by jakemac53**
## TLDR

Fixes an issue where disabled extensions could not be enabled with `-e <extension>`.

This also fixes a bug where the `update` command would fail for disabled extensions, even if you explicitly asked to update an extension by name.

## Dive Deeper

Moves all handling of extension overrides into the ExtensionEnablementManager, which gives us a central place with all the knowledge necessary for handling the answer to "is some extension enabled".

All APIs that used to take the argv extensions argument now just take an ExtensionEnablementManager. This also allows us to load the extension configurations fewer times from disk (if you share that instance).

This did cause a LOT of churn in tests due to changing the public APIs, and the usage is more verbose, but I think better. 

## Reviewer Test Plan

Do `gemini extensions disable <extension>` and then `gemini -e <extension>` and then `/extensions list` in the CLI. You should see the disabled extension is enabled (and no other extensions).

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | ❓  | ❓  | ❓  |
| npx      | ❓  | ❓  | ❓  |
| Docker   | ❓  | ❓  | ❓  |
| Podman   | ❓  | -   | -   |
| Seatbelt | ❓  | -   | -   |

## Linked issues / bugs

Fixes #8752

### CODE REVIEW

File: packages/cli/src/config/extensions/extensionEnablement.ts [hunk 1]
```diff
@@ -104,24 +105,55 @@ function globToRegex(glob: string): RegExp {
...
+  /**
+   * Determines if an extension is enabled based on its name and the current
+   * path. The last matching rule in the overrides list wins.
+   *
+   * @param extensionName The name of the extension.
+   * @param currentPath The absolute path of the current working directory.
+   * @returns True if the extension is enabled, false otherwise.
+   */
   isEnabled(extensionName: string, currentPath: string): boolean {
+    // If we have a single override called 'none', this disables all extensions.
```
Comment (chrstnb) [inline packages/cli/src/config/extensions/extensionEnablement.ts:143]: took me a second to parse this....would clarify that these are args or something?

**Review by chrstnb — APPROVED** [review]
Looks good-- one part was a little confusing, but overall makes sense to me
