### PR TITLE
fix: Add warning message for token limit truncation

### LINKED ISSUE #2104: Silent termination when Gemini API output token limit is reached
### What happened?

The Gemini CLI silently stops generating responses when the API reaches its output token limit, without providing any feedback to the user about why the generation was truncated.

  **Steps to Reproduce:**
  1. Start Gemini CLI
  2. Request generation of long content (e.g., "Create a complete Tetris game in Python")
  3. Observe that the response stops abruptly mid-generation (e.g., around line 527 of generated code)
  4. No error message or notification is shown to the user

  **Actual Behavior:**
  - Response stops silently without any indication
  - User is left confused about whether it's a network issue, bug, or intentional behavior
  - No way to understand what happened

  **Screenshot Evidence:**
  User reported that Tetris code generation stopped at line 527 with no error or explanation.

Image

Image

### What did you expect to happen?

**Expected Behavior:**
  - User should be notified when response is truncated due to output token limits
  - Clear message explaining why the generation stopped
  - Guidance on how to handle the situation

  **Suggested Message:**
  > ⚠️ Response was truncated due to output token limits. The model reached its maximum generation length. Try asking for a shorter response or break your request into smaller parts.

  This would help users understand the limitation and know how to adjust their requests accordingly.

### Client information

<details>
│ About Gemini CLI                                   │
│                                                    │
│ CLI Version       0.1.4                            │
│ Git Commit        1078a54                          │
│ Model             gemini-2.5-pro                   │
│ Sandbox           no sandbox                       │
│ OS                win32        
</details>

### Login information

Google Account

### Anything else we need to know?

**Root Cause Analysis:**
  The current codebase does not check the `finishReason` field in API responses. When `finishReason` is `"MAX_TOKENS"` or `"LENGTH"`, the system should detect this and notify the
  user.

  **Technical Details:**
  - Issue occurs in `packages/core/src/core/turn.ts` where API responses are processed
  - No validation of `response.candidates[0].finishReason` currently exists
  - Similar to reported issues in Google AI Developers Forum about Gemini 2.5 Flash truncation

  **Impact:**
  This affects user experience significantly as users may think the CLI is broken or their network connection failed, when in fact it's a normal API limitation that should be
  communicated clearly.

  **Proposed Solution:**
  Add detection for truncation in response processing and display an informative message using the existing notification system (similar to chat compression warnings).

### PR DESCRIPTION
**Pull request by darkdarkcocoa**
## Summary
  This PR addresses issue #2104 by adding a clear warning message when the Gemini CLI response is truncated due to API
   token limits.

  ## Changes Made
  - Added finishReason check in turn.ts to detect MAX_TOKENS
  - Display clear warning when response is truncated due to token limits
  - Resolves silent termination issue described in #2104

  ## Problem Solved
  - Users no longer experience silent termination of response generation
  - Clear indication when token limits are reached
  - Improved user experience and reduced confusion

  ## Testing
  - Project builds successfully
  - Code follows existing patterns and style
  - Minimal, targeted fix that addresses the core issue

  Fixes #2104

### CODE REVIEW

File: packages/core/src/core/turn.ts [hunk 1]
```diff
@@ -215,6 +215,15 @@ export class Turn {
...
         }
+
+        // Check if response was truncated due to token limits
+        const finishReason = resp.candidates?.[0]?.finishReason;
+        if (finishReason === 'MAX_TOKENS') {
+          yield {
+            type: GeminiEventType.Content,
+            value: '\n\n⚠️  Response truncated due to token limits.',
+          };
+        }
```
[the remark this answers is not in the document]
Comment (darkdarkcocoa) [reply packages/core/src/core/turn.ts]: Thanks for the feedback! I've expanded the implementation to handle all finish reasons (SAFETY, RECITATION, LANGUAGE, BLOCKLIST, PROHIBITED_CONTENT, SPII, OTHER) with appropriate user-friendly messages in commit b8e7ff2.

**Review by darkdarkcocoa — COMMENTED** [review]
Thanks for the feedback! I've expanded the implementation to handle all finish reasons (SAFETY, RECITATION, LANGUAGE, BLOCKLIST, PROHIBITED_CONTENT, SPII, OTHER) with appropriate user-friendly messages in commit 3a64a14.

**Comment by darkdarkcocoa** [comment]
@umairidris I've addressed all review comments in commit 3a64a14. Could you please help me with the next steps or the final review?

**Comment by darkdarkcocoa** [comment]
@umairidris  I've updated the branch to the latest version. Ready for review when you have a moment. Thank you! 😊

File: packages/core/src/core/turn.ts [hunk 2]
```diff
@@ -216,6 +216,41 @@ export class Turn {
...
+
+        if (resp.usageMetadata) {
+          this.lastUsageMetadata =
+            resp.usageMetadata as GenerateContentResponseUsageMetadata;
+        }
+
+        // Check if response was truncated or stopped for various reasons
+        const finishReason = resp.candidates?.[0]?.finishReason;
+        
+        const finishReasonMessages: Record<string, string> = {
```
Comment (NTaylorMullen) [inline packages/core/src/core/turn.ts]: For all these would you mind migrating to the official `FinishReason.MAX_TOENS` etc.

File: packages/core/src/core/turn.ts [hunk 3]
```diff
@@ -216,6 +216,41 @@ export class Turn {
...
+          'LANGUAGE': '\n\n⚠️  Response stopped due to unsupported language.',
+          'BLOCKLIST': '\n\n⚠️  Response stopped due to forbidden terms.',
+          'PROHIBITED_CONTENT': '\n\n⚠️  Response stopped due to prohibited content.',
+          'SPII': '\n\n⚠️  Response stopped due to sensitive personally identifiable information.',
+          'OTHER': '\n\n⚠️  Response stopped for other reasons.',
+        };
+        
+        if (finishReason && finishReasonMessages[finishReason]) {
+          yield {
+            type: GeminiEventType.Content,
```
Comment (NTaylorMullen) [inline packages/core/src/core/turn.ts]: Instead of returning content this way what if we did the message creation in `useGeminiStream.tsx`? To do this you'll want to create a new `GeminiEventType`. Lets call it "Finished" that has a value of the `@google/genai`'s `FinishReason` type. This way the useGeminiStream hook can turn each reason into an informational message.

This approach will also ensure that anyone consuming the `core` library wont get extra non-model generated messages.

**Review by NTaylorMullen — COMMENTED** [review]
Thanks for the contribution @darkdarkcocoa ! This is a great addition. Left some relayering suggestions but looking forward to working with you to get this in!

File: packages/core/src/core/turn.ts (hunk 3 above)
Comment (darkdarkcocoa) [reply packages/core/src/core/turn.ts]: @NTaylorMullen Thank you for the excellent review! I've implemented all your suggestions:

✅ **Migrated to official FinishReason enum** from `@google/genai`
✅ **Added new `GeminiEventType.Finished` event** for better separation
✅ **Moved message formatting from core to UI layer**:
   - `turn.ts` now only emits the raw FinishReason value
   - `useGeminiStream.ts` handles user-facing message generation
   - Core library consumers won't receive UI-specific messages

All tests are passing and the separation of concerns is now properly implemented. Ready for your re-review!

File: packages/cli/src/ui/hooks/useGeminiStream.ts [hunk 4]
```diff
@@ -422,6 +423,34 @@ export const useGeminiStream = (
...
+        [FinishReason.SPII]: '\n\n⚠️  Response stopped due to sensitive personally identifiable information.',
+        [FinishReason.OTHER]: '\n\n⚠️  Response stopped for other reasons.',
+        [FinishReason.MALFORMED_FUNCTION_CALL]: '\n\n⚠️  Response stopped due to malformed function call.',
+        [FinishReason.IMAGE_SAFETY]: '\n\n⚠️  Response stopped due to image safety violations.',
+        [FinishReason.UNEXPECTED_TOOL_CALL]: '\n\n⚠️  Response stopped due to unexpected tool call.',
+      };
+      
+      const message = finishReasonMessages[finishReason];
+      if (message) {
+        handleContentEvent(message, '', userMessageTimestamp);
```
Comment (NTaylorMullen) [inline packages/cli/src/ui/hooks/useGeminiStream.ts]: Instead of a content message can we produce an informational message?

File: packages/cli/src/ui/hooks/useGeminiStream.ts [hunk 5]
```diff
@@ -501,6 +530,12 @@ export const useGeminiStream = (
           case ServerGeminiEventType.MaxSessionTurns:
             handleMaxSessionTurnsEvent();
             break;
+          case ServerGeminiEventType.Finished:
+            handleFinishedEvent(event as ServerGeminiFinishedEvent, userMessageTimestamp);
+            break;
+          case ServerGeminiEventType.UsageMetadata:
```
Comment (NTaylorMullen) [inline packages/cli/src/ui/hooks/useGeminiStream.ts]: Hmm, lets drop this if we could from the PR. Would like to keep this more targeted for now

File: packages/core/src/core/turn.ts [hunk 6]
```diff
@@ -134,6 +138,16 @@ export type ServerGeminiMaxSessionTurnsEvent = {
   type: GeminiEventType.MaxSessionTurns;
 };
 
+export type ServerGeminiFinishedEvent = {
+  type: GeminiEventType.Finished;
+  value: FinishReason;
+};
+
+export type ServerGeminiUsageMetadataEvent = {
```
Comment (NTaylorMullen) [inline packages/core/src/core/turn.ts]: Lets not add a usagemetadata event for now to keep the PR scoped

File: packages/core/src/core/turn.ts [hunk 7]
```diff
@@ -222,6 +240,29 @@ export class Turn {
...
+
+        if (resp.usageMetadata) {
+          this.lastUsageMetadata =
+            resp.usageMetadata as GenerateContentResponseUsageMetadata;
+        }
+
+        // Check if response was truncated or stopped for various reasons
+        const finishReason = resp.candidates?.[0]?.finishReason;
+        
+        if (finishReason && finishReason !== FinishReason.STOP && finishReason !== FinishReason.FINISH_REASON_UNSPECIFIED) {
```
Comment (NTaylorMullen) [inline packages/core/src/core/turn.ts]: You can produce the finish event always. We can react in useGeminiStream on whether or not we produce a message or not there

**Review by NTaylorMullen — CHANGES_REQUESTED** [review]
Almost there, few more changes!

File: packages/core/src/core/turn.ts (hunk 7 above)
Comment (darkdarkcocoa) [reply packages/core/src/core/turn.ts]: @NTaylorMullen Thanks for the review! 
I've implemented all the requested changes:
✅ Removed all UsageMetadata-related code to keep the PR focused
✅ Changed from content messages to informational messages for warnings
✅ Modified to always emit finish events (letting UI layer handle filtering)
✅ Updated branch with latest main

The build is passing now. You're right about handling finish events in the UI layer - it's a cleaner approach.
Let me know if anything else needs adjustment. :)

**Comment by NTaylorMullen** [comment]
@darkdarkcocoa we're almost there! The product code changes look great, approve-worthy! Would you mind writing some tests for the changes now?

**Comment by darkdarkcocoa** [comment]
@NTaylorMullen Thank you for the review! I've added comprehensive test coverage as requested:

✅ **Added tests in `turn.test.ts`** (5 cases):
- Turn emits `Finished` when `finishReason` is present
- MAX_TOKENS finish reason
- SAFETY finish reason
- No `finishReason` -> no Finished event
- Multiple streamed responses with different finish reasons

✅ **Added tests in `useGeminiStream.test.tsx`**:
- Info message for MAX_TOKENS
- No message for STOP & FINISH_REASON_UNSPECIFIED
- Appropriate messages for other finish reasons (coverage across SAFETY, RECITATION, LANGUAGE, etc.)

All **new tests pass locally** (turn: 12/12, useGeminiStream: 26/26).  
Ready for your review!  Thanks! 🙏

**Review by NTaylorMullen — APPROVED** [review]
Love it @darkdarkcocoa!! Thank you for the contribution, lets get this in! Looks like you may have some formatter failures. You can run `npm run format` and push the branch to fix

**Comment by darkdarkcocoa** [comment]
> Love it @darkdarkcocoa!! Thank you for the contribution, lets get this in! Looks like you may have some formatter failures. You can run `npm run format` and push the branch to fix

Thank you @NTaylorMullen! I've run `npm run format` and pushed the changes. 
The formatter has been applied to all 4 files. Looking forward to getting this merged!
