### PR TITLE
Fix and unskip flakey integration test in replace.test.ts

### LINKED ISSUE #10916: Integration tests: Fix "replace.test.ts" flakes
### What happened?

This was disabled in https://github.com/google-gemini/gemini-cli/pull/10914

### What did you expect to happen?

it shouldn't flake

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
# paste output here
```

</details>

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by scidomino**
## TLDR

Fixes "should fail safely when old_string is not found" to give the agent clearer directions.

Also: Fix arg parsing in deflake.ts so I can run:

```
$ npm run deflake:test:integration:sandbox:none -- integration-tests/replace.test.ts 
```
instead of having to run everything.

## Reviewer Test Plan

See this run using `deflake`. There was one flake but not from this test file: https://github.com/google-gemini/gemini-cli/actions/runs/18480274254/job/52653514207?pr=11073

## Linked issues / bugs

Fixes #10916

### CODE REVIEW

File: scripts/deflake.js [hunk 1]
```diff
@@ -16,15 +16,7 @@ import { hideBin } from 'yargs/helpers';
...
-function runCommand(command) {
-  // Split the command string into the command name and its arguments.
-  // This handles quotes and spaces more robustly than a simple split(' ').
-  // For 'npm run test:e2e -- --test-name-pattern "replace"', it results in:
-  // cmd: 'npm', args: ['run', 'test:e2e', '--', '--test-name-pattern', 'replace']
-  const parts = command.match(/(?:[^\s"]+|"[^"]*")+/g) || [];
-  const cmd = parts[0];
-  const args = parts.slice(1).map((arg) => arg.replace(/"/g, '')); // Remove surrounding quotes
-
+function runCommand(cmd, args = []) {
```
Comment (cornmander) [inline scripts/deflake.js:19]: I don't see how this change is related?

Comment (scidomino) [reply scripts/deflake.js:19]: Oh yeah. I updated the description to explain that.

**Review by cornmander — APPROVED** [review]
