### PR TITLE
fix: acp/zed race condition between MCP initialisation and prompt

### LINKED ISSUE #18893: Acp/ZedIntegration Race between mcp initialization and first prompt
### What happened?

ACP mode assumed to be `Config.interactive`, which caused MCP initialization to run in the background. As a result, when the first `GeminiAgent.prompt` request is received, MCP may not be connected yet (or it may be!), and the agent can produce inconsistent responses

### What did you expect to happen?

`GeminiAgent.prompt` should wait for MCP initialization before doing anything

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
│ About Gemini CLI                                                                                │
│                                                                                                 │
│ CLI Version                      0.28.2                                                         │
│ Git Commit                       da5e47ae3                                                      │
│ Model                            auto-gemini-3                                                  │
│ Sandbox                          no sandbox                                                     │
│ OS                               darwin                                                         │
│ Auth Method                      vertex-ai                                                      │
│ GCP Project                      aihktn25-shared       
```

</details>

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by kartikangiras**
## Summary
Fix a race condition in ACP/Zed mode where GeminiAgent.prompt could be handled before MCP server connections had finished initialising, causing the model to produce inconsistent responses.

## Details
`Config.initialize()` intentionally starts MCP server connections in the background so the interactive CLI prompt appears quickly.

Two code paths violated this contract:

`config.ts` set `interactive: true` without `experimentalZedIntegration: true`, so MCP always ran in the background and was never awaited — even though the a2a-server is not a terminal and has no reason to skip waiting.

`zedIntegration.ts` had no guard to wait for MCP to be ready before invoking the model.

## Related Issues
fixes #18893 

## How to Validate
- Configure one or more MCP servers in ~/.gemini/settings.json.
- Start the CLI in ACP mode: [gemini --experimental-acp].
- Send a prompt immediately after session initialisation (before MCP would have had time to connect in the old code).
- Verify the model consistently has access to the configured MCP tools on the very first response.
- Run the unit tests: npx vitest run [zedIntegration.test.ts] packages/a2a-server/src/config/config.test.ts

## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [x] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [ ] Validated on required platforms/methods:
  - [x] MacOS
    - [x] npm run
    - [x] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

File: packages/core/src/config/config.ts [hunk 1]
```diff
@@ -1082,6 +1083,8 @@ export class Config {
       }
     });
 
+    this.mcpInitializationPromise = mcpInitialization;
```
Comment (scidomino) [inline packages/core/src/config/config.ts]: Remove the mcpInitialization variable and just immediately assign it to this.mcpInitializationPromise

**Review by scidomino — CHANGES_REQUESTED** [review]

File: packages/core/src/config/config.ts (hunk 1 above)
Comment (kartikangiras) [reply packages/core/src/config/config.ts]: i have assigned it to the this.mcpInitializationPromise

**Comment by scidomino** [comment]
please revert the changes to package-lock.json.

**Review by scidomino — APPROVED** [review]
