### PR TITLE
fix: Use Email for Clearcut Logging and Refactor User Info Fetching

### LINKED ISSUE #3149: Google ID is incorrectly being sent to Clearcut
### What happened?

This is fixed (hopefully) in https://github.com/google-gemini/gemini-cli/pull/3147

### What did you expect to happen?

Previous implementation was setting the wrong field into Clearcut. It turns out that a UserInfo object needs to be populated:

The UserInfo message within input proto is the standard place to store user-related identifiers.
The UserID field within UserInfo is specifically designated for the user's Gaia ID.
This should correctly result in Google user IDs being passed in for logging purposes. They will then be obfuscated before storing to clear all personally identifiable information.

### Client information

<details>

``` CLI Version              0.1.9                                           │
│ Git Commit               a7d8bb2a (local modifications)                  │
│ Model                    gemini-2.5-pro                                  │
│ Sandbox                  no sandbox                                      │
│ OS                       darwin                                          │
│ Auth Method              OAuth                                           │
│ GCP Project              crescendo-ai-test  
```

</details>

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by gsquared94**
This PR addresses an issue with our Clearcut logging by replacing the previously used Google Account ID with the user's email. This change aligns with standard practices (see http://go/cloudmill-1p-oss-instrumentation#define-sessionable-id) which should also work for clearcut to automatically delete the email field and populate the obscured_gaia_id.

### Key Changes:

*   **Updated Clearcut Logging:**
    *   The `ClearcutLogger` now sends the user's email (`client_email`) instead of the installation ID or a numeric Google Account ID.
    *   This ensures that logs are associated with a recognizable user identity when available.
    *   Logging falls back to `client_install_id` if the email is not available.

*   **Refactored User Information Fetching:**
    *   The logic for retrieving user information has been updated to use the `googleapis.com/oauth2/v2/userinfo` endpoint.
    *   This replaces the previous method of decoding the `id_token` to get the `sub` claim.
    *   The new approach fetches both the user's email and their Google Account ID, caching them for future use.

*   **Cached Credentials:**
    *   The user's email is now cached locally, similar to how the Google Account ID was previously handled.
    *   The `getGoogleAccountEmail()` utility function provides a consistent way to access the cached email.

*   **Error Handling and Dependencies:**
    *   Removed `id_token` verification logic that is no longer needed.
    *   Simplified promise handling and error logging around the flushing of telemetry data.
    *   Switched to using `require` for dynamic imports to avoid circular dependency issues.

Fixes #3149

### CODE REVIEW

File: packages/core/src/code_assist/oauth2.ts [hunk 1]
```diff
@@ -275,57 +270,73 @@ export function getCachedGoogleAccountId(): string | null {
   }
 }
 
+function getGoogleAccountEmailCachePath(): string {
+  return path.join(os.homedir(), GEMINI_DIR, GOOGLE_ACCOUNT_EMAIL_FILENAME);
```
Comment (NTaylorMullen) [inline packages/core/src/code_assist/oauth2.ts:274]: Should this go in the tmp dir there?

File: packages/core/src/telemetry/clearcut-logger/clearcut-logger.ts [hunk 2]
```diff
@@ -66,47 +68,46 @@ export class ClearcutLogger {
...
 
-    // Fire and forget - don't await
-    this.flushToClearcut().catch((error) => {
-      console.debug('Error flushing to Clearcut:', error);
-    });
+    this.flushToClearcut();
   }
 
-  async flushToClearcut(): Promise<LogResponse> {
+  flushToClearcut(): Promise<LogResponse> {
```
Comment (NTaylorMullen) [inline packages/core/src/telemetry/clearcut-logger/clearcut-logger.ts:100]: Should this still return a promise?

File: packages/core/src/telemetry/clearcut-logger/clearcut-logger.ts [hunk 3]
```diff
@@ -268,9 +267,7 @@ export class ClearcutLogger {
     ];
 
     this.enqueueLogEvent(this.createLogEvent(new_prompt_event_name, data));
-    this.flushToClearcut().catch((error) => {
-      console.debug('Error flushing to Clearcut:', error);
```
Comment (NTaylorMullen) [inline packages/core/src/telemetry/clearcut-logger/clearcut-logger.ts]: Should we be try catching more to protect log failures?

File: packages/core/src/utils/user_id.ts
Comment (NTaylorMullen) [inline packages/core/src/utils/user_id.ts:1]: Just saw this file name / the test ones. THey're very pythonic lol, we should change. Doesn't need to be this PR

**Review by NTaylorMullen — DISMISSED** [review]

**Comment by owenofbrien** [comment]
@gsquared94 - I think we should log both the client_install_id and the client_email. We need to be able to look for cases where multiple client_emails are associated with the same client_install_id.

**Comment by NTaylorMullen** [comment]
> @gsquared94 - I think we should log both the client_install_id and the client_email. We need to be able to look for cases where multiple client_emails are associated with the same client_install_id.

@gsquared94 please address ^ as well

**Comment by gsquared94** [comment]
> > @gsquared94 - I think we should log both the client_install_id and the client_email. We need to be able to look for cases where multiple client_emails are associated with the same client_install_id.
> 
> @gsquared94 please address ^ as well

We cannot log both client_email and client_install_id for the same entry to concord. It's a violation of Google's wipeout policy compliance.

If the objective is to find multiple accounts against the same install ID, can we instead keep a record of all old values of client_email in the settings across multiple sign-ins, and log the duplicate count directly?

File: packages/core/src/telemetry/clearcut-logger/clearcut-logger.ts (hunk 2 above)
Comment (gsquared94) [reply packages/core/src/telemetry/clearcut-logger/clearcut-logger.ts:100]: Sorry, sending a PR on Github after many years. I accidentally resolved comments without posting my messages. 

This code is a revert from a previous commit. So I'll just keep it as-is for now. Will try to figure out a better way of doing this after familiarizing myself with the project.

File: packages/core/src/code_assist/oauth2.ts (hunk 1 above)
Comment (gsquared94) [reply packages/core/src/code_assist/oauth2.ts:274]: I think that the tmp directory manages settings that a different for different projects, since the immediate subdirectories seem to be project-name-hashes(?). Since auth is being maintained globally this setting would need to live somewhere outside tmp. Keeping as-is for now.

File: packages/core/src/utils/user_id.ts
Comment (gsquared94) [reply packages/core/src/utils/user_id.ts:1]: Ack

File: packages/core/src/telemetry/clearcut-logger/clearcut-logger.ts (hunk 3 above)
Comment (gsquared94) [reply packages/core/src/telemetry/clearcut-logger/clearcut-logger.ts]: Done.

**Review by mattKorwel — APPROVED** [review]
