### PR TITLE
Fix oauth support for MCP servers

### LINKED ISSUE #10165: MCP SSE errors
### What happened?

When starting up Gemini, I get errors connecting to my specified MCP servers:

```
│ Debug Console (ctrl+o to close)                                               │
│                                                                               │
│ ℹ Authenticated via "gemini-api-key".                                        │
│ ✖ MCP ERROR (Notion): Error: SSE error: Non-200 status code (401)            │
│ ✖ Error during discovery for server 'Notion': SSE error: Non-200 status code │
│    (401)                                                                      │
│ ✖ MCP ERROR (context7): Error: SSE stream disconnected: TypeError:           │
│    terminated (x2)
```

### What did you expect to happen?

There should be no errors, since both MCP servers are specified correctly (they used to connect successfully).

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
│ CLI Version     0.6.1                         │
│ Git Commit      f3078136                      │
│ Model           gemini-2.5-pro                │
│ Sandbox         no sandbox                    │
│ OS              linux                         │
│ Auth Method     gemini-api-key
```

</details>

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by jakemac53**
## TLDR

Previously during tool discovery we would go through a different code path than the standard one to connect to the MCP server, and this code path did not support OAUTH. This caused OAUTH mcp servers to not connect at all.

I changed that logic to use the same top level function that is used by other code paths.

## Dive Deeper

Longer term it seems to me like we are connecting to these servers repeatedly, and through many different code paths which is very confusing. The culprit in this case was the McpClientManager which has a `discoverAllMcpTools` function which calls McpClient.connect, but then we also have a top level `connectAndDiscover` function in mcp-client.ts which this mcp client manager does not use, and that function would do the oauth stuff correctly.

We should try and consolidate all this code into the McpClientManager or something along those lines to reduce duplicate code paths.

## Reviewer Test Plan

Attempt to connect to an MCP server that supports oauth.

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | ❓  | ❓  | ❓  |
| npx      | ❓  | ❓  | ❓  |
| Docker   | ❓  | ❓  | ❓  |
| Podman   | ❓  | -   | -   |
| Seatbelt | ❓  | -   | -   |

## Linked issues / bugs

Fixes https://github.com/google-gemini/gemini-cli/issues/10165

### CODE REVIEW

File: packages/core/src/tools/mcp-client.ts [hunk 1]
```diff
@@ -188,11 +168,12 @@ export class McpClient {
     updateMCPServerStatus(this.serverName, status);
   }
 
-  private async createTransport(): Promise<Transport> {
-    return createTransport(this.serverName, this.serverConfig, this.debugMode);
-  }
-
   private async discoverTools(cliConfig: Config): Promise<DiscoveredMCPTool[]> {
+    if (!this.client) {
```
Comment (cornmander) [inline packages/core/src/tools/mcp-client.ts]: Can you wrap this in a helper and use the helper in discoverTools and discoverPrompts? verifyConnected() or something like this.

File: packages/core/src/tools/mcp-client.ts [hunk 2]
```diff
@@ -168,12 +142,18 @@ export class McpClient {
    * Disconnects from the MCP server.
    */
   async disconnect(): Promise<void> {
+    if (this.isDisconnecting) return;
```
Comment (cornmander) [inline packages/core/src/tools/mcp-client.ts]: Can we do something simpler here, and just check if client is set? Why do we need a separate state variable?

File: packages/core/src/tools/mcp-client.ts [hunk 3]
```diff
@@ -92,51 +92,25 @@ export class McpClient {
...
-        timeout: this.serverConfig.timeout,
-      });
-
+      this.client = await connectToMcpServer(
+        this.serverName,
+        this.serverConfig,
+        this.debugMode,
+        this.workspaceContext,
+      );
       this.updateStatus(MCPServerStatus.CONNECTED);
```
[the remark this answers is not in the document]
Comment (jakemac53) [reply packages/core/src/tools/mcp-client.ts:124]: Yikes it looks like the MCP server state is also managed separately today for the top level `connectToMcpServer` function versus things going through `McpClient.connect`. I have just added an extra onerror handler here so _both_ states will be update but this is another thing that needs to be cleaned up.

File: packages/core/src/tools/mcp-client.ts [hunk 4]
```diff
@@ -168,12 +142,18 @@ export class McpClient {
...
     if (this.transport) {
       await this.transport.close();
     }
-    this.client.close();
+    if (client) {
+      await client?.close();
+    }
     this.updateStatus(MCPServerStatus.DISCONNECTED);
+    this.isDisconnecting = false;
   }
```
[the remark this answers is not in the document]
Comment (jakemac53) [reply packages/core/src/tools/mcp-client.ts:168]: I update this so calling `connect` while still disconnecting is an error. That looks safe to do (current code does await `disconnect` calls).

File: packages/core/src/tools/mcp-client.ts (hunk 2 above)
Comment (cornmander) [reply packages/core/src/tools/mcp-client.ts]: I see the code in the other code path is doing the same.

Comment (jakemac53) [reply packages/core/src/tools/mcp-client.ts]: Sure, I could do that

File: packages/core/src/tools/mcp-client.ts (hunk 1 above)
Comment (jakemac53) [reply packages/core/src/tools/mcp-client.ts]: done

**Review by jacob314 — COMMENTED** [review]
Should we add additional tests to mcp-client.test.ts to avoid regressing this?

**Comment by jakemac53** [comment]
> Should we add additional tests to mcp-client.test.ts to avoid regressing this?

We should but it will take some work to set up, I am trying to write some tests though

**Comment by jakemac53** [comment]
@jacob314 I did add some tests

**Comment by scidomino** [comment]
FYI, you should merge changes from main since it contains a fix that makes integration test much less flakey.

**Review by jacob314 — APPROVED** [review]
lgtm
