### PR TITLE
fix(hooks): fix BeforeAgent/AfterAgent inconsistencies (#18514)

### LINKED ISSUE #18514: Hook inconsistencies - AfterAgent not firing, BeforeAgent firing when not needed
### What happened?

Attached is my [settings.json](https://github.com/user-attachments/files/25143430/settings.json) and the [hook-file](https://github.com/user-attachments/files/25143435/logger.js)

The summary of what happened:
1. BeforeAgent hook is not fired when I interrupt an AfterAgent event with a prompt
2. BeforeAgent hook is fired after the first tool call after I interrupt an AfterAgent event with a prompt
3. AfterAgent does not fire after text-only responses

Actual order of events:
1. I first opened gemini cli and gave this prompt: "Does the world have 13 continents? Say yes or no"
2. BeforeAgent, BeforeModel and many thinking AfterModel events fired and then the text AfterModel as well
3. Then the AfterAgent hook fired with "no" prompt_response. Now the hook listener wrote "Which country hosted the last G7? Say just the country's name" and exited with code 2
4. No BeforeAgent hook fired (is this the intended behavior because the user didn't give any prompts, or a bug?)
5. A BeforeModel and thinking AfterModel hooks are fired, and then an empty (no text and thinking) AfterModel hook is fired (I assume this is the tool call)
6. Then a BeforeAgent hook is fired with an empty string prompt field. (Why is this fired here? Don't udnerstand the reason)
7. BeforeModel and AfterModel hooks fired with thinking and text contents
8. AfterAgent hook fired with the prompt_response "Canada". Now the hook listener writes "Does the world have 5 oceans? Say yes or no" to stderr and exits with code 2
9. No BeforeAgent hooks fired (same question as point 4)
10. Now an AfterModel hook and some thinking AfterModel hooks fired, and then a text AfterModel hook is also fired
11. No AfterAgent hook fired now (This doesn't seem to be intended, as such a case is not mentioned in the docs)

### What did you expect to happen?

1. BeforeAgent fires after prompt injection by failing AfterAgent hook
2. BeforeAgent does not fire in wierd order (after first tool call after the prompt injection using AfterAgent hook)
3. AfterAgent fires after every assistant's turn (including after text-only assistant responses)

I'm trying to run gemini-cli through the network from an app on my phone, using the hooks. So the AfterAgent not firing causes the headless gemini-cli instance to die and now my whole chat is lost and I have to start a new conversation

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                                                                                                                                            │
│ About Gemini CLI                                                                                                                                                                                                                           │
│                                                                                                                                                                                                                                            │
│ CLI Version                                                                       0.29.0-nightly.20260205.a3af4a8ca                                                                                                                        │
│ Git Commit                                                                        a3af4a8ca                                                                                                                                                │
│ Model                                                                             gemini-3-flash-preview                                                                                                                                   │
│ Sandbox                                                                           no sandbox                                                                                                                                               │
│ OS                                                                                linux                                                                                                                                                    │
│ Auth Method                                                                       Logged in with Google (____________@gmail.com)                                                                                                           │
│ Tier                                                                              Gemini Code Assist in Google One AI Pro                                                                                                                  │
│                                                                                                                                                                                                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯


```

</details>

### Login information

Google Account

(Do you need this field in the Bug Report template now? It is printed in the /about command which will be pasted in the Client Information section right?)

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by krishdef7**
Fixes #18514

## Root Cause

All three bugs trace to hook state management in `sendMessageStream` in `packages/core/src/core/client.ts`.

When `isBlockingDecision()` fires and triggers a recursive `sendMessageStream` call with the same `prompt_id`:

1. **BeforeAgent not firing on injected prompt**, `hasFiredBeforeAgent` is still `true` from the prior turn. The guard at `fireBeforeAgentHookSafe` returns early, silently skipping BeforeAgent for the injected prompt.

2. **AfterAgent not firing after text-only continuation**, the recursive call increments `activeCalls` to 2. `fireAfterAgentHookSafe` guards on `activeCalls !== 1` and returns `undefined`, so AfterAgent never fires for that turn.

3. **BeforeAgent firing spuriously after first tool call** — the `finally` block checks `pendingToolCalls` on the *outer* turn (not the continuation turn), which can prematurely delete the hookState mid-sequence. The next call creates a fresh hookState with `hasFiredBeforeAgent=false`, causing an unexpected BeforeAgent fire.

## Fix

Three surgical changes, all in `sendMessageStream`:

- Before the recursive `sendMessageStream` call in the `isBlockingDecision` branch: reset `hasFiredBeforeAgent = false` and decrement `activeCalls` on the hookState, so the continuation is treated as a fresh outermost turn.
- Set a `continuationHandled` flag to prevent the `finally` block from double-decrementing `activeCalls` when the continuation has already managed its own state.

## Testing

- All 71 existing tests pass (`npx vitest run packages/core/src/core/client.test.ts`)
- Full preflight passes (`npm run preflight`) - 0 errors
- The fix specifically covers the exact event sequences described in the issue: hook injection via exit code 2, text-only responses, and tool call sequences

### CODE REVIEW

**Comment by krishdef7** [comment]
Cleaned up - the PR now touches only packages/core/src/core/client.ts. The paste-related files (InputPrompt.tsx, atCommandProcessor.ts, unescapeLiteralAt.ts) were accidentally bundled from a prior branch and have been removed. The previous bot feedback on those files is now outdated.

File: packages/core/src/core/client.ts [hunk 1]
```diff
@@ -110,19 +105,15 @@ export class GeminiClient {
    */
   private hasFailedCompressionAttempt = false;
 
-  constructor(private readonly context: AgentLoopContext) {
-    this.loopDetector = new LoopDetectionService(this.config);
+  constructor(private readonly config: Config) {
```
Comment (spencer426) [inline packages/core/src/core/client.ts]: It looks like this reverts the recent introduction of `AgentLoopContext`. This constructor should still accept `private readonly context: AgentLoopContext` instead of falling back to just `Config`.

File: packages/core/src/core/client.ts [hunk 2]
```diff
@@ -264,15 +255,15 @@ export class GeminiClient {
     return this.chat !== undefined;
   }
 
-  getHistory(): readonly Content[] {
+  getHistory(): Content[] {
```
Comment (spencer426) [inline packages/core/src/core/client.ts]: This reverts the method signature by removing the `readonly` modifier. Please keep `readonly Content[]` to preserve type safety.

File: packages/core/src/core/client.ts [hunk 3]
```diff
@@ -264,15 +255,15 @@ export class GeminiClient {
...
     return this.getChat().getHistory();
   }
 
   stripThoughtsFromHistory() {
     this.getChat().stripThoughtsFromHistory();
   }
 
-  setHistory(history: readonly Content[]) {
+  setHistory(history: Content[]) {
```
Comment (spencer426) [inline packages/core/src/core/client.ts]: Same here, please keep the `readonly` modifier in the parameter signature: `setHistory(history: readonly Content[])`.

File: packages/core/src/core/client.ts [hunk 4]
```diff
@@ -1097,18 +1099,7 @@ export class GeminiClient {
         onValidationRequired: onValidationRequiredCallback,
         authType: this.config.getContentGeneratorConfig()?.authType,
         maxAttempts: availabilityMaxAttempts,
-        retryFetchErrors: this.config.getRetryFetchErrors(),
         getAvailabilityContext,
```
Comment (spencer426) [inline packages/core/src/core/client.ts:1112]: This unintentionally reverts PR #22027 by removing `retryFetchErrors` and `onRetry` from the `generateContentWithRetry` call, which are needed for network retry telemetry. Please restore these properties.

**Review by spencer426 — CHANGES_REQUESTED** [review]
Thanks for the PR! The core logic fix for the hook states looks good, but it appears your branch is out of sync with `main` and is actively reverting some very recent changes. Could you please rebase or restore these missing lines?

**Review by spencer426 — APPROVED** [review]
LGTM
