### PR TITLE
fix(core): parse raw ASCII buffer strings in Gaxios errors

### LINKED ISSUE #20631: Raw ASCII buffer strings appear in Gaxios error responses in dev
When a Gaxios error is thrown in development, the response data sometimes contains a raw ASCII buffer string (comma-separated character codes) instead of the decoded error message. We need to handle this by properly decoding the buffer back to a readable string.

### PR DESCRIPTION
**Pull request by sehoon38**
## Summary

This PR fixes an issue where raw ASCII buffer strings (comma-separated char codes) were appearing in the `Gaxios` error response data in development environments. This usually happens when the response is not properly decoded by the library.

## Details

The fix involves checking if the `error.response.data` is a string containing commas. If so, it attempts to parse it as a sequence of character codes and convert it back to a readable string using `String.fromCharCode`. A safety check using `.every((code) => !isNaN(code))` is included to ensure only valid numeric sequences are parsed.

This logic is refactored into a private `_parseGaxiosErrorData` helper within `LoggingContentGenerator`.

## Related Issues

Closes #20631

## How to Validate

Run the tests in `packages/core/src/core/loggingContentGenerator.test.ts`:
```bash
npm test -w @google/gemini-cli-core -- src/core/loggingContentGenerator.test.ts
```

The "Gaxios error parsing" describe block contains robust tests (using `expect(...).rejects`) for:
1. Correct parsing of ASCII buffer strings.
2. Leaving non-comma-separated strings alone.
3. Leaving invalid numeric sequences alone.

## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [x] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [x] Validated on required platforms/methods:
  - [x] MacOS
    - [x] npm run

### CODE REVIEW

File: packages/core/src/core/loggingContentGenerator.ts [hunk 1]
```diff
@@ -274,6 +274,24 @@ export class LoggingContentGenerator implements ContentGenerator {
     logApiResponse(this.config, event);
   }
 
+  private _parseGaxiosErrorData(error: unknown): void {
+    // Fix for raw ASCII buffer strings appearing in dev with the latest
+    // Gaxios updates.
+    // eslint-disable-next-line @typescript-eslint/no-unsafe-type-assertion
```
Comment (scidomino) [inline packages/core/src/core/loggingContentGenerator.ts]: can you rework this to avoid disabling this lint rule? Like, look to see if 'error' contains a field called "response" etc.

File: packages/core/src/core/loggingContentGenerator.ts [hunk 2]
```diff
@@ -274,6 +274,24 @@ export class LoggingContentGenerator implements ContentGenerator {
     logApiResponse(this.config, event);
   }
 
+  private _parseGaxiosErrorData(error: unknown): void {
```
Comment (scidomino) [inline packages/core/src/core/loggingContentGenerator.ts]: this name makes it sound like it parses and returns some value, but it's actually modifying the argument. can we pick a more descriptive name that includes like "fix" or something?

**Review by scidomino — APPROVED** [review]
