### PR TITLE
fix(a2a-server): prioritize ADC before evaluating headless constraints for auth initialization

### LINKED ISSUE #1598: Git command allow-list should handle sub-commands by default
**Describe the bug**

This may be similar to #490 but not certain given that it is closed, and filing this separately since it's specific to git.

I am working in a git directory and Gemini CLI tried to run a `git diff` command. It prompted me to allow once or allow always, but seemed to be scoped to the entire `git` command.

Expected behavior: The default "allow always" for a git command is scoped to the specific sub-command (possibly with relevant flags?), e.g. in this case `git diff`.

**Client information**
Linux

```
╭──────────────────────────────────────────────────────────────────────╮
│                                                                      │
│ About Gemini CLI                                                     │
│                                                                      │
│ CLI Version             0.1.0-a3c46c0.0                              │
│ Git Commit              a3c46c0                                      │
│ Model                   gemini-2.5-pro                               │
│ Sandbox                 no sandbox                                   │
│ OS                      linux                                        │
│                                                                      │
╰──────────────────────────────────────────────────────────────────────╯
```
Please paste the full text from the /about command run from Gemini CLI. Also include which platform (MacOS, Windows, Linux).

**Login information**
Describe how you are logging in.

Not sure what this means? I'm using an API key if that's what it's asking

**Additional context**

### PR DESCRIPTION
**Pull request by spencer426**
## Summary

This PR fixes a bug introduced in #21045 that inadvertently prevented headless authentication using `GOOGLE_APPLICATION_CREDENTIALS` (or `GEMINI_CLI_USE_COMPUTE_ADC`). 

Previously, the logic immediately evaluated `isHeadlessMode()` and threw a `FatalAuthenticationError` if headless, completely blocking processes like IDE background agents from authenticating via explicitly provided ADC paths. 

## Details

This update refactors the authentication flow in `packages/a2a-server/src/config/config.ts` to prioritize `COMPUTE_ADC`. It now attempts to load and validate credentials via `COMPUTE_ADC` *before* evaluating any interactive/headless constraints. If the credentials are valid, the interactive flow and headless checks are bypassed. If ADC fails, it will properly throw a `FatalAuthenticationError` in headless environments (or fall back to `LOGIN_WITH_GOOGLE` in interactive ones), appending the reason for the ADC failure.

I also updated `packages/a2a-server/src/config/config.test.ts` to ensure these behaviors are fully covered.

## Related Issues

Fixes #1598

## How to Validate

Run tests inside `packages/a2a-server`:
`npm test -w @google/gemini-cli-a2a-server`

## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [x] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [ ] Validated on required platforms/methods:
  - [ ] MacOS
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [x] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

File: packages/a2a-server/src/config/config.ts [hunk 1]
```diff
@@ -282,51 +281,49 @@ async function refreshAuthentication(
...
+      initialAdcError = adcError;
+      logger.info(
+        `[${logPrefix}] COMPUTE_ADC failed or not available: ${
+          adcError instanceof Error ? adcError.message : String(adcError)
+        }`,
+      );
+    }
+
+    if (!isAdcSuccessful) {
+      if (shouldSkipOauth) {
```
Comment (kschaab) [inline packages/a2a-server/src/config/config.ts]: I think there is still an issue here, shouldSkipOauth will be true if isHeadless is true.  I believe A2A server always headless, so it seems at least some of this is unreachable?  Also shouldSkipOauth is set to true when trying compute ADC, but that just failed so there is no fallback here even if GOOGLE_APPLICATION_CREDENTIALS is set to a valid credential.

File: packages/a2a-server/src/config/config.ts [hunk 2]
```diff
@@ -282,51 +281,49 @@ async function refreshAuthentication(
...
+        const adcMessage =
+          initialAdcError instanceof Error
+            ? initialAdcError.message
+            : String(initialAdcError);
         throw new FatalAuthenticationError(
-          `Interactive terminal required for LOGIN_WITH_GOOGLE. Run in an interactive terminal or set GEMINI_CLI_USE_COMPUTE_ADC=true to use Application Default Credentials.`,
+          `Interactive terminal required for LOGIN_WITH_GOOGLE. Run in an interactive terminal or set GEMINI_CLI_USE_COMPUTE_ADC=true to use Application Default Credentials. (COMPUTE_ADC also failed: ${adcMessage})`,
```
Comment (kschaab) [inline packages/a2a-server/src/config/config.ts]: GEMINI_CLI_USE_COMPUTE_ADC seems different at least as a concept than USE_CCPA and GOOGLE_APPLICATION_CREDENTIALS both being set.

File: packages/a2a-server/src/config/config.ts
Comment (kschaab) [inline packages/a2a-server/src/config/config.ts]: Right here, we know USE_CCPA is set, GOOGLE_APPLICATION_CREDENTIALS is set and that it points to a valid file path (since there was no error thrown).  At this point shouldn't we try this as the default auth? I'm trying to figure out what AuthType.COMPUTE_ADC is in comparison to this flow.  I would think the other case is isCloudShell() or not using USE_CCPA.

**Review by kschaab — APPROVED** [review]
