### PR TITLE
fix(cli): pass node arguments via NODE_OPTIONS during relaunch to support SEA

### LINKED ISSUE #24591: [bug]  SEA - Unknown arguments: max-old-space-size, maxOldSpaceSize
### What happened?

~$ npm run build:binary

~$ ./dist/linux-x64/gemini

Unknown arguments: max-old-space-size, maxOldSpaceSize
Usage: gemini [options] [command]

Gemini CLI - Defaults to interactive mode. Use -p/--promp
t for non-interactive (headless) mode.

Commands:
  gemini mcp                   Manage MCP servers
  gemini extensions <command>  Manage Gemini CLI extensions.            [aliases: extension]
  gemini skills <command>      Manage agent skills.                         [aliases: skill]
  gemini hooks <command>       Manage Gemini CLI hooks.                      [aliases: hook]
  gemini [query..]             Launch Gemini CLI                                   [default]

Positionals:
  query  Initial prompt. Runs in interactive mode by default; use -p/--prompt for non-intera
         ctive.

Options:
  -d, --debug                     Run in debug mode (open debug console with F12)
                                                                  [boolean] [default: false]
  -m, --model                     Model                                             [string]
  -p, --prompt                    Run in non-interactive (headless) mode with the given prom
                                  pt. Appended to input on stdin (if any).          [string]
  -i, --prompt-interactive        Execute the provided prompt and continue in interactive mo
                                  de                                                [string]
  -w, --worktree                  Start Gemini in a new git worktree. If no name is provided
                                  , one is generated automatically.                 [string]
  -s, --sandbox                   Run in sandbox?                                  [boolean]
  -y, --yolo                      Automatically accept all actions (aka YOLO mode, see https
                                  ://www.youtube.com/watch?v=xvFZjo5PgG0 for more details)?
                                                                  [boolean] [default: false]
      --approval-mode             Set the approval mode: default (prompt for approval), auto
                                  _edit (auto-approve edit tools), yolo (auto-approve all to
                                  ols), plan (read-only mode)
                                  [string] [choices: "default", "auto_edit", "yolo", "plan"]
      --policy                    Additional policy files or directories to load (comma-sepa
                                  rated or multiple --policy)                        [array]
      --admin-policy              Additional admin policy files or directories to load (comm
                                  a-separated or multiple --admin-policy)            [array]
      --acp                       Starts the agent in ACP mode                     [boolean]
      --experimental-acp          Starts the agent in ACP mode (deprecated, use --acp instea
                                  d)                                               [boolean]
      --allowed-mcp-server-names  Allowed MCP server names                           [array]
      --allowed-tools             [DEPRECATED: Use Policy Engine instead See https://geminic
                                  li.com/docs/core/policy-engine] Tools that are allowed to
                                  run without confirmation                           [array]
  -e, --extensions                A list of extensions to use. If not provided, all extensio
                                  ns are used.                                       [array]
  -l, --list-extensions           List all available extensions and exit.          [boolean]
  -r, --resume                    Resume a previous session. Use "latest" for most recent or
                                   index number (e.g. --resume 5)                   [string]
      --list-sessions             List available sessions for the current project and exit.
                                                                                   [boolean]
      --delete-session            Delete a session by index number (use --list-sessions to s
                                  ee available sessions).                           [string]
      --include-directories       Additional directories to include in the workspace (comma-
                                  separated or multiple --include-directories)       [array]
      --screen-reader             Enable screen reader mode for accessibility.     [boolean]
  -o, --output-format             The format of the CLI output.
                                           [string] [choices: "text", "json", "stream-json"]
      --raw-output                Disable sanitization of model output (e.g. allow ANSI esca
                                  pe sequences). WARNING: This can be a security risk if the
                                   model output is untrusted.                      [boolean]
      --accept-raw-output-risk    Suppress the security warning when using --raw-output.
                                                                                   [boolean]
  -v, --version                   Show version number                              [boolean]
  -h, --help                      Show help       

### What did you expect to happen?

gemini binary work

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
# paste output here
```

</details>

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by cocosheng-g**
## Summary

Fixes the issue where Node.js arguments (like `--max-old-space-size`) were incorrectly parsed as application arguments when running the CLI as a Single Executable Application (SEA).

## Details

When Node.js is run as a SEA, `process.execPath` is the binary itself. Passing Node.js flags as command-line arguments to the binary causes them to be passed to the application's argument parser (`yargs`), which fails with an "Unknown argument" error.

This PR implements a robust, simplified design to address this and subsequent architectural findings:
- **Moved Node.js flags to `NODE_OPTIONS` (SEA only)**: When relaunching in SEA mode, newly calculated Node.js flags (like memory auto-config) are appended to the `NODE_OPTIONS` environment variable instead of being passed as command-line arguments. This ensures they are consumed by the runtime and never reach `yargs`.
- **Fixed Compounding Argument Duplication**: A critical bug was identified where consecutive relaunches caused arguments to compound indefinitely (e.g., `gemini start start start`). This was fixed by explicitly injecting `process.execPath` as the `argv[1]` placeholder for the child process, guaranteeing the `argv[0] === argv[1]` invariant and breaking the cycle.
- **Robust SEA Detection**: SEA detection was refined to accurately handle both the initial standard SEA execution (where user args start at `argv[1]`) and subsequent relaunches. It safely falls back to Node.js's native `process.isSea?.()` and `argv[0] === argv[1]`.
- **Strict Argument Validation**: Because the CLI only dynamically adds simple flags (e.g., `--max-old-space-size=X`), the relaunch logic now explicitly throws a clear error if a flag contains a space, single quote, double quote, or backslash. This guarantees we never encounter a silent `NODE_OPTIONS` parsing failure in production and avoids fragile string-escaping logic.
- **Centralized Logic**: Extracted and DRY'd up `isStandardSea`, `getScriptArgs`, and `getSpawnConfig` into the shared `processUtils.ts` utility. The `ProcessWithSea` interface was also exported to eliminate `any` casting.
- **Reliable Testing**: Completely refactored the test environment to use `vi.stubEnv` instead of directly mutating `process.env`. `NODE_OPTIONS` is also explicitly stubbed to prevent test failures on Windows CI runners that inject their own global memory flags.

## Related Issues

Fixes #24591

## How to Validate

1. Build the binary using `npm run build:binary`
2. Run the binary from the output directory (e.g., `./dist/darwin-arm64/gemini --version`). It should execute successfully without an unknown argument error.
3. Validate standard node execution via `npm run start -- --version`.
4. Validate manual relaunch by running the CLI interactively (`npm run start`), opening `/settings`, toggling a setting (e.g., UI -> "Show Line Numbers"), and exiting the settings menu. The CLI should successfully restart without duplicating the executed command.

## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [x] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [ ] Validated on required platforms/methods:
  - [x] MacOS
    - [x] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

**Review by devr0306 — CHANGES_REQUESTED** [review]
from `/review-frontend`

### Review Summary
The PR successfully addresses the issue by appropriately routing Node arguments through the `NODE_OPTIONS` environment variable when running in SEA (Single Executable Application) mode. The implementation also includes solid validation to prevent injection vulnerabilities by blocking complex arguments with spaces or quotes.

However, there is a critical logic flaw in how script arguments are passed to the child process that will cause compounding argument duplication upon consecutive relaunches.

### Findings

#### Critical: Compounding Argument Duplication
The interaction between `isStandardSea` and the script placeholder in `getSpawnConfig` can create a compounding argument duplication bug if the app is relaunched more than once (e.g., a restart triggered from within the application).

**The Scenario:**
1. A user runs `gemini my-cmd`. `process.argv` is `['/bin/gemini', 'my-cmd']`.
2. `isStandardSea` evaluates to `true`, so `scriptArgs` is parsed as `['my-cmd']`.
3. In `getSpawnConfig`, it uses `process.argv[1] ?? process.execPath` as the placeholder. Because `process.argv[1]` is `'my-cmd'`, `finalSpawnArgs` becomes `['my-cmd', 'my-cmd']`.
4. The spawned child process receives `process.argv = ['/bin/gemini', 'my-cmd', 'my-cmd']`. The CLI parser works fine here because it ignores the first two elements (`slice(2)`).
5. **The Bug:** If that child process needs to relaunch *again*, it will check `argv[0] !== argv[1]` (`'/bin/gemini' !== 'my-cmd'`), which means `isStandardSea` evaluates to `true` again! It will incorrectly slice from index 1, capturing `['my-cmd', 'my-cmd']` as the `scriptArgs`, and pass those forward. The arguments will compound indefinitely on each relaunch.

**Suggested Fixes:**
1. In `packages/cli/src/utils/processUtils.ts`, always use `process.execPath` as the explicit placeholder instead of dynamically using `process.argv[1]`. This guarantees `argv[0] === argv[1]` in the child process, breaking the cycle.
   ```typescript
   // Change:
   // finalSpawnArgs.push(process.argv[1] ?? process.execPath, ...scriptArgs);
   
   // To:
   finalSpawnArgs.push(process.execPath, ...scriptArgs);
   ```
2. In `index.ts` and `relaunch.ts`, group the `argv[0] !== argv[1]` check so that it applies to *both* `IS_BINARY` and `isSea()`. This ensures the child properly identifies the injected placeholder even if Node native `process.isSea()` is true.
   ```typescript
   const isStandardSea =
     process.argv[0] !== process.argv[1] &&
     (process.env['IS_BINARY'] === 'true' || (process as ProcessWithSea).isSea?.() === true);
   ```

#### Improvement: DRY up SEA Detection
The `ProcessWithSea` interface and the SEA detection logic (`isStandardSea` / `isBinary`) are currently duplicated across `index.ts`, `relaunch.ts`, and `processUtils.ts`. Consider extracting a shared helper function (e.g., `getScriptArgs` and `isStandardSea`) into `processUtils.ts` to consolidate this logic.

### Conclusion
**Status:** Request Changes
The core strategy of utilizing `NODE_OPTIONS` is solid, but the script argument passing logic needs to be corrected to prevent the compounding argument bug.

File: packages/cli/src/utils/processUtils.ts [hunk 1]
```diff
@@ -29,3 +29,101 @@ export async function relaunchApp(): Promise<void> {
   await runExitCleanup();
   process.exit(RELAUNCH_EXIT_CODE);
 }
+
+interface ProcessWithSea extends NodeJS.Process {
+  isSea?: () => boolean;
+}
```
Comment (devr0306) [inline packages/cli/src/utils/processUtils.ts]: you could export this and import it in `processUtils.test.ts` to get rid of the `any` cast

**Review by devr0306 — APPROVED** [review]
minor nit but approving
