### PR TITLE
fix(cli): switch default back to terminalBuffer=false and fix regressions introduced for that mode

### LINKED ISSUE #24874: Set terminalBuffer back to false
TerminalBuffer is causing performance regressions so needs to be optional until they are resolved.

Address regressions in non-terminal buffer rendering introduced since TerminalBuffer was made the default.

### PR DESCRIPTION
**Pull request by jacob314**
## Summary

TerminalBuffer mode was causing some performance issues with long chat histories. Turn it off by default again until they are addressed.

## Details

Fixed InputPrompt to render well outside of TerminalBuffer mode

## Related Issues

Fixes #24874

## How to validate
Run gemini CLI. Verify you are not in terminal buffer and all actions are still fine.

### CODE REVIEW

File: packages/cli/src/interactiveCli.tsx [hunk 1]
```diff
@@ -156,8 +156,9 @@ export async function startInteractiveUI(
         useAlternateBuffer || config.getUseTerminalBuffer(),
       patchConsole: false,
       alternateBuffer: useAlternateBuffer,
-      renderProcess: config.getUseRenderProcess(),
       terminalBuffer: config.getUseTerminalBuffer(),
+      renderProcess:
```
Comment (jacob314) [inline packages/cli/src/interactiveCli.tsx:160]: sadly passing in useRenderProcess without useTerminalBuffer was leading to Ink being in a bad state.

**Review by scidomino — APPROVED** [review]
