### PR TITLE
Fix alt key mappings for mac

### LINKED ISSUE #12000: Scandinavian lower-case character 'å' cannot be typed
### What happened?

   * The problem: The lowercase 'å' character cannot be typed.
   * The scope: The issue only occurs within the Gemini CLI. Other applications are not
     affected.
   * My system: I'm are on Linux, and other Scandinavian characters work correctly.

### What did you expect to happen?

I expected the character 'å' to appear and it did not do so. All the other Scandinavian characters 'ÅäÄöÖ' work as expected.

### Client information

* **CLI Version:** 0.10.0
* **Git Commit:** 5d92b507
* **Session ID:** 5d14e930-fb06-4372-b446-a0865f0cb1c1
* **Operating System:** linux v22.21.0
* **Sandbox Environment:** no sandbox
* **Model Version:** gemini-2.5-pro
* **Memory Usage:** 266.7 MB

### Login information

I'm logged in using a Google Account.

### Anything else we need to know?

This used to work and stopped working within the last week. Unfortunately I don't have an exact date to give for when this issue surfaced.

### PR DESCRIPTION
**Pull request by scidomino**
## Summary

Only map Alt-keys we use and only on mac.

## Details

This makes two changes:

1. Only do alt-key mapping on Mac
2. Only map the three keys we actually bind to:
  -  `alt-b`: "∫" back one word
  - `alt-f`: "ƒ" forward one word
  - `alt-m`: "µ" toggle markup view

## Related Issues

Fixes #12000 

## How to Validate

Verify that you can use the ctrl chars in mac.

## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [ ] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [ ] Validated on required platforms/methods:
  - [ ] MacOS
    - [x] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

File: packages/cli/src/ui/contexts/KeypressContext.tsx [hunk 1]
```diff
@@ -48,33 +48,12 @@ export const PASTE_CODE_TIMEOUT_MS = 50; // Flush incomplete paste code after 50
...
-  '\u00AE': 'r',
-  '\u00DF': 's',
-  '\u2020': 't',
-  '\u00A8': 'u',
-  '\u221A': 'v',
-  '\u2211': 'w',
-  '\u2248': 'x',
-  '\u00A5': 'y',
-  '\u03A9': 'z',
+// On Mac, hitting alt+char will yield funny characters.
```
Comment (jacob314) [inline packages/cli/src/ui/contexts/KeypressContext.tsx:51]: add a comment at the top level clarifying that only some alt keys are supported on mac

**Review by jacob314 — APPROVED** [review]
lgtm

**Review by jacob314 — APPROVED** [review]
lgtm
