### PR TITLE
fix(tools): Handle special characters in file paths for glob and read_many_files

### LINKED ISSUE #5086: You are referencing files with [id] in the path. The tool is unable to read files with brackets in the name.
### What happened?

I have a react native project using expo-router and the file names contain `[id]` pattern 

```
I see that you are referencing files with [id] in the path. The tool is unable to read files with brackets
  in the name. To help me with your request, please provide the whole content of the files:
  src/app/(app)/Tab1/[id]/index.tsx and src/app/(app)/Tab2/[id]/index.tsx.
```

### What did you expect to happen?

It's not able to read file but it's possible to provide directory instead till `src/app/(app)/Tab1/` 

### Client information

<details>

```console
$ gemini /about
│ CLI Version            0.1.14                                      │
│ Git Commit             de968877 (local modifications)              │
│ Model                  gemini-2.5-pro                              │
│ Sandbox                no sandbox                                  │
│ OS                     linux                                       │
│ Auth Method            OAuth                                       │
│ GCP Project            gen-lang-client-0227558081                  │
│                                                           
```
</details>

### Login information

Google Account

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by galdawave**
## TLDR

This PR fixes a bug in the `glob` and `read-many-files` tools that prevented them from working with file paths containing special characters like `[]` and `()`. The fix ensures these paths are correctly escaped when they refer to existing files, while still allowing glob patterns to be used.

## Dive Deeper

The issue stemmed from the `glob` library interpreting special characters in file paths as part of a glob pattern. To resolve this, we now check if a given path exists on the filesystem before passing it to `glob`.

- If `fs.stat()` confirms the path exists, we treat it as a literal path and escape any special characters using `glob.escape()`.
- If the path does not exist, we assume it's a glob pattern and use it as-is.

This logic has been implemented in both the `GlobTool` and the `ReadManyFilesTool`. Additionally, new unit tests have been added to verify that both tools can now correctly handle file paths and names with special characters, ensuring this bug is resolved and preventing future regressions.

## Reviewer Test Plan

To validate the fix, a reviewer can perform the following steps:

1.  Create a file within a directory structure that includes special characters:
    ```bash
    mkdir -p 'my-dir(v1)/[test]'
    echo "hello world from file1.txt" > 'my-dir(v1)/[test]/file1.txt'
    echo "hello world from file2.txt" > 'my-dir(v1)/[test]/file2.txt'
    ```
2.  Use the `read-many-files` tool to read the content of the newly created file. The tool should successfully read and display the file's content.
    ```bash
    what is in @my-dir(v1)/[test]/file.txt 
    ```

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | ✅  | ❓  | ❓  |
| npx      | ❓  | ❓  | ❓  |
| Docker   | ❓  | ❓  | ❓  |
| Podman   | ❓  | -   | -   |
| Seatbelt | ❓  | -   | -   |

## Linked issues / bugs
- Fixes: #5086

### CODE REVIEW

File: packages/core/src/tools/glob.ts [hunk 1]
```diff
@@ -137,7 +138,20 @@ class GlobToolInvocation extends BaseToolInvocation<
       let allEntries: GlobPath[] = [];
 
       for (const searchDir of searchDirectories) {
-        const entries = (await glob(this.params.pattern, {
+        let pattern = this.params.pattern;
+        try {
+          await fs.promises.stat(path.join(searchDir, pattern));
+          pattern = escape(pattern);
```
Comment (jacob314) [inline packages/core/src/tools/glob.ts:143]: if you apply the suggestions in read-many-files please apply them here

File: packages/core/src/tools/read-many-files.test.ts [hunk 2]
```diff
@@ -524,6 +524,43 @@ describe('ReadManyFilesTool', () => {
       expect(truncatedFileContent).toContain('L200');
       expect(truncatedFileContent).not.toContain('L2400');
     });
+
+    it('should read files with special characters like [] and () in the path', async () => {
+      const filePath = 'src/app/[test]/(dashboard)/testing/components/code.tsx';
```
Comment (jacob314) [inline packages/core/src/tools/read-many-files.test.ts:532]: great regression test!

File: packages/core/src/tools/read-many-files.ts [hunk 3]
```diff
@@ -245,18 +247,32 @@ ${finalExclusionPatternsForDescription
...
-            absolute: true,
-            nocase: true,
-            signal,
-          },
-        );
+        const processedPatterns = [];
+        for (const p of searchPatterns) {
+          const normalizedP = p.replace(/\\/g, '/');
+          try {
+            await fs.stat(path.join(dir, normalizedP));
```
Comment (jacob314) [inline packages/core/src/tools/read-many-files.ts]: same nit about using stat instead of access and tossing the result.

File: packages/core/src/tools/read-many-files.ts [hunk 4]
```diff
@@ -245,18 +247,32 @@ ${finalExclusionPatternsForDescription
...
+            processedPatterns.push(escape(normalizedP));
+          } catch (e: unknown) {
+            if (isNodeError(e) && e.code === 'ENOENT') {
+              // The path does not exist, so we treat it as a glob pattern.
+              processedPatterns.push(normalizedP);
+            } else {
+              // For other errors (e.g., permissions), we should not silently continue.
+              throw e;
```
Comment (jacob314) [inline packages/core/src/tools/read-many-files.ts]: why is this useful? shouldn't we just let glob try to do its thing in this case? Is so we can use
fs.existsSync which would be simpler and a bit more idiomatic.

**Review by jacob314 — COMMENTED** [review]
approved once these pretty minor comments are addressed.

File: packages/core/src/tools/read-many-files.test.ts (hunk 2 above)
Comment (galdawave) [reply packages/core/src/tools/read-many-files.test.ts:532]: Thanks!

**Review by jacob314 — APPROVED** [review]
lgtm
