### PR TITLE
refactor(cli): fix settings merging so that settings using the new json format take priority over ones using the old format

### LINKED ISSUE #14807: Persistent "Screen Reader Mode" on Windows due to "Access is denied" on nudge file
### What happened?

Upon starting the gemini CLI, it defaults to "Screen Reader-friendly view" and cannot be permanently disabled on Windows 11. The CLI reverts back to Screen Reader mode on every startup, even after complete uninstall/reinstall, due to a permission error.

**Error Details:**
- Windows error dialog: "Error Applying Attributes: Access is denied"
- File path: `C:\Users\Joep\.gemini\tmp\seen_screen_reader_nudge.json`
- The error prevents the file from being written, causing the accessibility nudge logic to trigger on every boot

**Steps to Reproduce:**
1. Install Gemini CLI on Windows 11
2. Ensure the `.gemini/tmp/seen_screen_reader_nudge.json` file has permission restrictions
3. Run `gemini`
4. Disable Screen Reader mode via `/settings` or config
5. Restart `gemini`
6. Observe it forces itself back ON

**Root Cause:**
The CLI attempts to track accessibility nudge state using the nudge file. When this file has permission restrictions or is locked, the "Access is denied" error occurs. Since the nudge state fails to persist and no explicit user preference exists in `settings.json`, the OS accessibility auto-detection wins during the settings merge process.

**Code Reference (settings.ts):**
The merge order is: System Defaults → User Settings → Workspace Settings → System Settings (last wins). If OS auto-detection sets `screenReader: true` and User Settings doesn't explicitly contain `screenReader: false`, auto-detection wins.

### What did you expect to happen?

The CLI should:
1. Remember the user's choice to disable Screen Reader mode
2. Fail gracefully if the nudge file cannot be written
3. Not override explicit user preferences with OS auto-detection
4. Provide a clear error message when permission issues occur

**Current Workaround:**`
taskkill /F /IM node.exe /T 2>$null

Remove-Item -Path "C:\Users\[USER]\.gemini\seen_screen_reader_nudge.json" -Force -ErrorAction SilentlyContinue

$jsonContent = '{
  "screenReader": false,
  "telemetryEnabled": false
}'
Set-Content -Path "C:\Users\[USER]\.gemini\settings.json" -Value $jsonContent -Force

### Client information

* **CLI Version:** 0.19.4
* **Git Commit:** 935114875
* **Session ID:** 783ad12c-7465-49c3-b1d5-faeb483e78b8
* **Operating System:** win32 v24.8.0
* **Sandbox Environment:** no sandbox
* **Model Version:** auto
* **Memory Usage:** 212.0 MB

### Login information

Google Account

### Anything else we need to know?

Image

### PR DESCRIPTION
**Pull request by jacob314**
## Summary
Legacy settings were taking priority over the new setting syntax when merging which is surprising behavior.

## Details

Fixed so that new settings take priority over legacy and tried to simplify merging logic a little bit by removing special cases that aren't needed.

## Related Issues

This make fix #14807

## How to Validate

Define a mix of old and new format settings in your settings.json. Verify that the new format settings take priority.

### CODE REVIEW

File: packages/cli/src/utils/deepMerge.ts [hunk 1]
```diff
@@ -28,11 +28,16 @@ function mergeRecursively(
   path: string[] = [],
 ) {
   for (const key of Object.keys(source)) {
-    if (key === '__proto__' || key === 'constructor' || key === 'prototype') {
+    // JSON.parse can create objects with __proto__ as an own property.
```
Comment (jacob314) [inline packages/cli/src/utils/deepMerge.ts:31]: constructor and prototype didn't need to be skipped as they won't be included in Object.

File: packages/cli/src/config/settings.ts [hunk 2]
```diff
@@ -331,8 +344,8 @@ function migrateSettingsToV2(
       v2Settings[remainingKey] = customDeepMerge(
         pathAwareGetStrategy,
         {},
-        newValue as MergeableObject,
         existingValue as MergeableObject,
+        newValue as MergeableObject,
```
Comment (jacob314) [inline packages/cli/src/config/settings.ts:348]: the new names should take priority over the legacy names. I believe that previously the reverse was true.

File: packages/cli/src/config/settings.ts [hunk 3]
```diff
@@ -302,6 +302,19 @@ function migrateSettingsToV2(
 
   for (const [oldKey, newPath] of Object.entries(MIGRATION_MAP)) {
     if (flatKeys.has(oldKey)) {
+      // If the key exists and is a V2 container (like 'model'), and the value is an object,
+      // it is likely already migrated or partially migrated. We should not move it
+      // to the mapped V2 path (e.g. 'model' -> 'model.name').
+      // Instead, let it fall through to the "Carry over" section to be merged.
+      if (
```
Comment (jacob314) [inline packages/cli/src/config/settings.ts:309]: this was needed as otherwise reversing the order of existingValue and newValue caused crashes for the case shown in settings_repro.test.ts

**Review by galdawave — APPROVED** [review]

File: packages/cli/src/utils/deepMerge.ts [hunk 4]
```diff
@@ -28,11 +28,16 @@ function mergeRecursively(
...
+    // We must skip it to prevent prototype pollution.
+    if (key === '__proto__') {
       continue;
     }
```
[the remark this answers is not in the document]
Comment (jacob314) [reply packages/cli/src/utils/deepMerge.ts:35]: think previous code was cargo culting... there is no reason I can see why constructor or prototype needed to be special cased given we are iterating using Object.keys
