### PR TITLE
fix(plan): isolate plan files per session

### LINKED ISSUE #18723: Design issue in Plan mode
In Plan mode, the generated markdown files are stored under:

~/.gemini/tmp/<project_hash>/plans

This causes plan files from different sessions to be shared and accessible across sessions. As a result, new sessions can be polluted by plans generated in previous sessions.

Today, when I was using the Gemini CLI, the model explicitly mentioned that it inspected the directory ~/.gemini/tmp/<project_hash>/plans, found some information related to my question, and then read those plan files. Because of this, the current session was continuously influenced by plan files generated by other sessions, making it unable to complete the task correctly.

I believe this is a design issue. Plan files should be isolated per session, or at least not automatically visible to new sessions.

### PR DESCRIPTION
**Pull request by Adib234**
## Summary

This PR implements session-based isolation for plan storage. By including the sessionId in the plans directory path, it prevents plan file collisions between different sessions in the same project and ensures that the Plan Mode policy correctly restricts file operations to the session-specific plans folder.

## Details

   - Storage Class Update: Modified the Storage class in packages/core to accept and store an optional sessionId.
   - Session-Isolated Plan Paths: Updated getProjectTempPlansDir() to return .../plans/<sessionId> when a session ID is present, falling back to the base plans directory otherwise.
   - Config Integration: Updated the main Config class to pass the current sessionId when initializing the Storage service.
   - Policy Enforcement: Updated the plan.toml policy file to adjust the argsPattern regex. The new pattern accounts for the additional directory level `(/plans/<sessionId>/<file>.md)`, ensuring write_file and replace tools remain functional and secure within Plan Mode.
## Related Issues

Fixes #18723 
## How to Validate
Start a new session and create a plan. End it and try re-running the same prompt to create the plan. Gemini CLI should have no memory of the plan that was created in the past and act as if it's creating the plan for the first time. 

## Pre-Merge Checklist

- [ ] Updated relevant documentation and README (if needed)
- [ ] Added/updated tests (if needed)
- [ ] Noted breaking changes (if any)
- [ ] Validated on required platforms/methods:
  - [ ] MacOS
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
    - [ ] Podman
    - [ ] Seatbelt
  - [ ] Windows
    - [ ] npm run
    - [ ] npx
    - [ ] Docker
  - [ ] Linux
    - [ ] npm run
    - [ ] npx
    - [ ] Docker

### CODE REVIEW

**Review by jerop — COMMENTED** [review]
we should flip the order of plans and session id

`~/.gemini/tmp/<project>/plans/<session-id>/` --> `~/.gemini/tmp/<project>/<session-id>/plans/` 

this way, we can add easily tasks and other planning items within the session subdirectory:

- `~/.gemini/tmp/<project>/<session-id>/plans/` 
- `~/.gemini/tmp/<project>/<session-id>/tasks/` 

this would be much better than:
- `~/.gemini/tmp/<project>/plans/<session-id>/` 
- `~/.gemini/tmp/<project>/tasks/<session-id>/` 

then down the road, we can move the other artifacts like chat history within this subdirectory e.g. `~/.gemini/tmp/<project>/chats` --> `~/.gemini/tmp/<project>/<session-id>/chats` (out of scope for now though)

File: packages/core/src/config/storage.ts [hunk 1]
```diff
@@ -20,11 +20,13 @@ const AGENTS_DIR_NAME = '.agents';
 
 export class Storage {
   private readonly targetDir: string;
+  private readonly sessionId: string | undefined;
   private projectIdentifier: string | undefined;
   private initPromise: Promise<void> | undefined;
 
-  constructor(targetDir: string) {
+  constructor(targetDir: string, sessionId?: string) {
```
Comment (jerop) [inline packages/core/src/config/storage.ts:27]: are there situations when sessionId doesn't exist? if not, we should make it required

Comment (Adib234) [reply packages/core/src/config/storage.ts:27]: This was made optional to prevent us from changing the constructor in multiple places where sessionId is not required. When we initialize `storage` in `package/core/src/config/config.ts` it seems that sessionId is a required field in `Config` class so it's highly unlikely there would be situations where the sessionId doesn't exist.

**Review by jerop — APPROVED** [review]

File: packages/core/src/config/storage.ts (hunk 1 above)
Comment (jerop) [reply packages/core/src/config/storage.ts:27]: Follow up in https://github.com/google-gemini/gemini-cli/pull/21360
