### PR TITLE
Add session id to session summary and /bug template

### LINKED ISSUE #6249: Display session and prompt ids in debug mode
### What would you like to be added?

When a session ends, print the session id and prompt ids.

### Why is this needed?

For logs analysis and debugging use cases, we need an easy way to view session and prompt ids.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by owenofbrien**
… command.

## TLDR

Added session id to session summary display and bug template for /bug command.

## Dive Deeper

This enables viewing the session id in order to quickly look up the logs for a session for eval curation and debugging purposes. It also provides the session id in 

## Reviewer Test Plan

- Run the CLI, use the /bug command, examine the resulting bug, quit the CLI and look at the session summary.

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | y  | ❓  | ❓  |
| npx      | ❓  | ❓  | ❓  |
| Docker   | ❓  | ❓  | ❓  |
| Podman   | ❓  | -   | -   |
| Seatbelt | ❓  | -   | -   |

## Linked issues / bugs

Resolved #6249

### CODE REVIEW

**Review by bdmorgan — APPROVED** [review]
LGTM

File: packages/core/src/telemetry/clearcut-logger/event-metadata-key.ts [hunk 1]
```diff
@@ -223,11 +223,11 @@ export enum EventMetadataKey {
...
   // ===========================================================================
 
-  // Logs the length of the kitty sequence that overflowed.
-  GEMINI_CLI_KITTY_SEQUENCE_LENGTH = 53,
-
   // Logs the truncated kitty sequence.
   GEMINI_CLI_KITTY_TRUNCATED_SEQUENCE = 52,
+
+  // Logs the length of the kitty sequence that overflowed.
+  GEMINI_CLI_KITTY_SEQUENCE_LENGTH = 53,
```
Comment (jacob314) [inline packages/core/src/telemetry/clearcut-logger/event-metadata-key.ts:230]: thanks for the cleanup :)

**Review by jacob314 — APPROVED** [review]
lgtm
