### PR TITLE
fix: make @file suggestions case-insensitive

### LINKED ISSUE #11369: @file suggestions must be case insensitive
### What happened?

When user types @ for file suggestions and types in the name of the file with different case than the file name, the suggestions don't appear. 

### What did you expect to happen?

The file suggestions must come regardless of the case.

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
│ CLI Version                 0.11.0-nightly.20251015.203bad7c                     │
│ Git Commit                  f3ffaf09                                             │
│ Model                       auto                                                 │
│ Sandbox                     no sandbox                                           │
│ OS                          linux                                                │
│ Auth Method                 OAuth                                                │
│ IDE Client                  VS Code      
```

</details>

### Login information

N/A

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by IamRiddhi**
## Description
Fixes #11369

Makes @file suggestions case-insensitive by converting the search pattern to lowercase.

## Changes
- Modified `useAtCompletion.ts` to convert search pattern to lowercase before file search
- Users can now type `@readme` to match `README.md` regardless of case

## Testing
- ✅ All existing unit tests pass
- ✅ Manually verified case-insensitive matching works

### CODE REVIEW

File: packages/cli/src/ui/hooks/useAtCompletion.ts [hunk 1]
```diff
@@ -197,10 +197,13 @@ export function useAtCompletion(props: UseAtCompletionProps): void {
       }, 200);
 
       try {
-        const results = await fileSearch.current.search(state.pattern, {
-          signal: controller.signal,
-          maxResults: MAX_SUGGESTIONS_TO_SHOW * 3,
-        });
+        const results = await fileSearch.current.search(
+          state.pattern.toLowerCase(),
```
Comment (scidomino) [inline packages/cli/src/ui/hooks/useAtCompletion.ts]: Can we lowercase it when pattern is updated instead of lowercasing it here every time?

File: packages/cli/src/ui/hooks/useAtCompletion.ts [hunk 2]
```diff
@@ -197,10 +197,13 @@ export function useAtCompletion(props: UseAtCompletionProps): void {
       }, 200);
 
       try {
-        const results = await fileSearch.current.search(state.pattern, {
-          signal: controller.signal,
-          maxResults: MAX_SUGGESTIONS_TO_SHOW * 3,
-        });
+        const results = await fileSearch.current.search(
```
Comment (scidomino) [inline packages/cli/src/ui/hooks/useAtCompletion.ts]: Add tests for this.

File: packages/cli/src/ui/hooks/useAtCompletion.test.ts [hunk 3]
```diff
@@ -138,6 +138,39 @@ describe('useAtCompletion', () => {
         'file.txt',
       ]);
     });
+
+    it('should perform a case-insensitive search by lowercasing the pattern', async () => {
+      const structure: FileSystemStructure = { 'file.txt': '' };
```
Comment (scidomino) [inline packages/cli/src/ui/hooks/useAtCompletion.test.ts]: nit: inline this var.

File: packages/cli/src/ui/hooks/useAtCompletion.test.ts [hunk 4]
```diff
@@ -138,6 +138,39 @@ describe('useAtCompletion', () => {
...
+      testRootDir = await createTmpDir(structure);
+
+      const mockFileSearch: FileSearch = {
```
Comment (scidomino) [inline packages/cli/src/ui/hooks/useAtCompletion.test.ts]: Let's use a real FileSearch here. We want to make sure this actually works end to end

**Review by scidomino — APPROVED** [review]

File: packages/cli/src/ui/hooks/useAtCompletion.test.ts [hunk 5]
```diff
@@ -138,6 +138,41 @@ describe('useAtCompletion', () => {
...
+        useTestHarnessForAtCompletion(true, 'File', mockConfig, testRootDir),
+      );
+
+      await waitFor(() => {
+        expect(result.current.suggestions.map((s) => s.value)).toEqual([
+          'file.txt',
+        ]);
+      });
+
+      // Expect the search to have been called with the lowercased pattern.
```
Comment (scidomino) [inline packages/cli/src/ui/hooks/useAtCompletion.test.ts]: Don't both testing this. It's an impl detail. What matters is that we got the right file.

File: packages/cli/src/ui/hooks/useAtCompletion.test.ts [hunk 6]
```diff
@@ -138,6 +138,41 @@ describe('useAtCompletion', () => {
         'file.txt',
       ]);
     });
+
+    it('should perform a case-insensitive search by lowercasing the pattern', async () => {
+      testRootDir = await createTmpDir({ 'file.txt': '' });
```
Comment (scidomino) [inline packages/cli/src/ui/hooks/useAtCompletion.test.ts]: Please test searching "CrAzYCaSe" matches a file called `cRaZycAsE.txt`.

**Review by scidomino — APPROVED** [review]
