### PR TITLE
fix: properly report tool errors in telemetry

### LINKED ISSUE #5679: Tool calls errors are not reported correctly.
Description of the bug:
Most of our tools gracefully handle errors in try catches, and our tool executors only log failures when errors are thrown. For example, when a replace call fails with "Failed to edit, could not find the string to replace", that counts as a success in the logs.

Gemini CLI wrote a helpful analysis doc exploring this issue: https://docs.google.com/document/d/1y-CDvFVfr4vQadweVabFgAMhQNFzI-fEUfzruC-Na4w/edit?tab=t.0

Actual vs expected behavior:
No response

Any other information you'd like to share?
No response

### PR DESCRIPTION
**Pull request by akhil29**
- Update tools to use error property in ToolResult for failures
  - read-file: use error property with appropriate ToolErrorType
  - write-file: use error property for validation and execution errors
  - shell: use error property for validation errors
  - Update tests to check error property instead of llmContent
  - Use ToolErrorType enum in tests for type safety

  Fixes #5679

  ## TLDR

  This PR fixes the tool telemetry issue where tool failures were incorrectly reported as successes when tools returned errors gracefully instead
  of throwing exceptions. Now tools properly use the `error` property in `ToolResult` to indicate failures, which flows through to correct
  telemetry logging.

  ## Dive Deeper

  As documented in the [analysis doc](https://docs.google.com/document/d/1y-CDvFVfr4vQadweVabFgAMhQNFzI-fEUfzruC-Na4w/edit?tab=t.0), our telemetry
  was reporting a 99%+ success rate because the executors only considered thrown exceptions as failures. When tools handled errors gracefully (like
   file not found), they returned error messages but were still logged as successful.

  The fix implements the proposed solution:
  1. Tools now use the `error` property with appropriate `ToolErrorType` values
  2. Executors check `toolResult.error` to determine success/failure
  3. Tests updated to verify the new error reporting pattern

  This ensures accurate telemetry that distinguishes between:
  - Successful executions (no error property)
  - Logical failures (error property set)
  - Exceptions (caught and logged as failures)
  - User cancellations (separate status)

  ## Reviewer Test Plan

  1. **Run the updated tests** to verify error handling:
     ```bash
     npm test -- src/tools/read-file.test.ts src/tools/write-file.test.ts src/tools/shell.test.ts

  2. Test tool failures manually:
    - Try reading a non-existent file: Should report failure with FILE_NOT_FOUND error type
    - Try writing to an invalid path: Should report failure with INVALID_TOOL_PARAMS
    - Try running a shell command with empty string: Should report failure
  3. Verify telemetry (if you have telemetry enabled):
    - Tool failures should now show success: false in logs
    - Error types should be properly categorized

  Testing Matrix

  |          | 🍏  | 🪟  | 🐧  |
  |----------|-----|-----|-----|
  | npm run  | ✅   | ❓   | ❓   |
  | npx      | ✅   | ❓   | ❓   |
  | Docker   | ❓   | ❓   | ❓   |
  | Podman   | ❓   | -   | -   |
  | Seatbelt | ❓   | -   | -   |

  Linked issues / bugs

  Fixes #5679

### CODE REVIEW

**Comment by akhil29** [comment]
All review feedback has been addressed:

- ✅ Fixed IS_DIRECTORY error mapping to use INVALID_TOOL_PARAMS instead of READ_CONTENT_FAILURE
- ✅ Implemented using switch statement for better clarity
- ✅ Added FileErrorType enum for structured error handling
- ✅ Removed redundant "Error:" prefixes for consistency
- ✅ Enhanced error logging with specific Node.js error codes

Ready for another review @google-gemini/gemini-code-assist

File: packages/core/src/tools/read-file.ts [hunk 1]
```diff
@@ -78,9 +80,33 @@ class ReadFileToolInvocation
...
+        case FileErrorType.FILE_NOT_FOUND:
+          errorType = ToolErrorType.FILE_NOT_FOUND;
+          llmContent = 'Could not read file.';
+          break;
+        case FileErrorType.IS_DIRECTORY:
+          errorType = ToolErrorType.INVALID_TOOL_PARAMS;
+          llmContent = 'Could not read file due to invalid parameters.';
+          break;
+        default:
+          // FILE_TOO_LARGE and other read errors map to READ_CONTENT_FAILURE
```
Comment (owenofbrien) [inline packages/core/src/tools/read-file.ts]: Let's add a ToolErrorType for FILE_TOO_LARGE. I'd like to see how often this happens to help prioritize potential fixes such as AST-based file chunking.

File: packages/core/src/tools/read-file.ts [hunk 2]
```diff
@@ -78,9 +80,33 @@ class ReadFileToolInvocation
...
 
     if (result.error) {
+      // Map structured error types to ToolErrorType
+      let errorType: ToolErrorType;
+      let llmContent: string;
+
+      switch (result.errorType) {
+        case FileErrorType.FILE_NOT_FOUND:
+          errorType = ToolErrorType.FILE_NOT_FOUND;
+          llmContent = 'Could not read file.';
```
Comment (owenofbrien) [inline packages/core/src/tools/read-file.ts]: This should say 'Could not read file because no file was found at the specified path.'

File: packages/core/src/tools/read-file.ts [hunk 3]
```diff
@@ -78,9 +80,33 @@ class ReadFileToolInvocation
...
+          break;
+        case FileErrorType.IS_DIRECTORY:
+          errorType = ToolErrorType.INVALID_TOOL_PARAMS;
+          llmContent = 'Could not read file due to invalid parameters.';
```
Comment (owenofbrien) [inline packages/core/src/tools/read-file.ts]: This should say something more specific like 'Could not read file because the provided path is a directory, not a file. ' to help the LLM self-heal.

File: packages/core/src/tools/read-file.ts [hunk 4]
```diff
@@ -78,9 +80,33 @@ class ReadFileToolInvocation
...
+          break;
+        default:
+          // FILE_TOO_LARGE and other read errors map to READ_CONTENT_FAILURE
+          errorType = ToolErrorType.READ_CONTENT_FAILURE;
+          llmContent = 'Could not read file.';
```
Comment (owenofbrien) [inline packages/core/src/tools/read-file.ts]: Let's also include result.error here in case it has more details that can help the LLM self-heal.

File: packages/core/src/tools/shell.ts [hunk 5]
```diff
@@ -186,8 +187,12 @@ export class ShellTool extends BaseTool<ShellToolParams, ToolResult> {
     });
     if (validationError) {
       return {
-        llmContent: validationError,
+        llmContent: 'Could not execute command due to invalid parameters.',
```
Comment (owenofbrien) [inline packages/core/src/tools/shell.ts]: We should still include the validationError in the llmContent in case it has helpful details.

File: packages/core/src/tools/write-file.ts [hunk 6]
```diff
@@ -225,8 +226,12 @@ export class WriteFileTool
     const validationError = this.validateToolParams(params);
     if (validationError) {
       return {
-        llmContent: `Error: Invalid parameters provided. Reason: ${validationError}`,
```
Comment (owenofbrien) [inline packages/core/src/tools/write-file.ts:233]: Can you revert these changes to llmContent and returnDisplay? The validationError could be useful.

File: packages/core/src/tools/write-file.ts [hunk 7]
```diff
@@ -225,8 +226,12 @@ export class WriteFileTool
...
-        returnDisplay: `Error: ${validationError}`,
+        llmContent: 'Could not write file due to invalid parameters.',
+        returnDisplay: validationError,
+        error: {
+          message: validationError,
+          type: ToolErrorType.INVALID_TOOL_PARAMS,
```
Comment (owenofbrien) [inline packages/core/src/tools/write-file.ts:238]: Would it help to break this down into more specific error types, similar to what we do for the replace and read tools?

File: packages/core/src/tools/write-file.ts [hunk 8]
```diff
@@ -240,8 +245,12 @@ export class WriteFileTool
       const errDetails = correctedContentResult.error;
       const errorMsg = `Error checking existing file: ${errDetails.message}`;
       return {
-        llmContent: `Error checking existing file ${params.file_path}: ${errDetails.message}`,
```
Comment (owenofbrien) [inline packages/core/src/tools/write-file.ts:248]: Revert as the previous string seems more useful.

File: packages/core/src/tools/write-file.ts [hunk 9]
```diff
@@ -327,10 +336,40 @@ export class WriteFileTool
...
+          console.error('Write file error stack:', error.stack);
+        }
+      } else if (error instanceof Error) {
+        errorMsg = `Error writing to file: ${error.message}`;
+      } else {
+        errorMsg = `Error writing to file: ${String(error)}`;
+      }
+
       return {
-        llmContent: `Error writing to file ${params.file_path}: ${errorMsg}`,
```
Comment (owenofbrien) [inline packages/core/src/tools/write-file.ts:349]: Revert as the previous version seems more helpful.

**Review by owenofbrien — COMMENTED** [review]
Thanks for jumping on this!

**Comment by akhil29** [comment]
@owenofbrien done. pls check.

File: packages/core/src/tools/read-file.ts [hunk 10]
```diff
@@ -78,9 +79,49 @@ class ReadFileToolInvocation
...
+        errorType = ToolErrorType.INVALID_TOOL_PARAMS;
+        llmContent =
+          'Could not read file because the provided path is a directory, not a file.';
+      } else if (
+        result.error.includes('too large') ||
+        result.error.includes('File size exceeds')
+      ) {
+        errorType = ToolErrorType.FILE_TOO_LARGE;
+        llmContent = result.error
+          ? `Could not read file. ${result.error}`
```
Comment (owenofbrien) [inline packages/core/src/tools/read-file.ts]: this seems redundant, as the if block already checks result.error content above

**Comment by akhil29** [comment]
@owenofbrien fixed conflicts.

**Comment by akhil29** [comment]
@owenofbrien fixed the failing tests

**Review by owenofbrien — APPROVED** [review]
LGTM. Thanks again for tackling this!

**Review by anj-s — APPROVED** [review]

**Comment by akhil29** [comment]
trivial question.

how to i merge this? It says workflow awaiting approval.

@anj-s  @owenofbrien

**Comment by owenofbrien** [comment]
> trivial question.
> 
> how to i merge this? It says workflow awaiting approval.
> 
> @anj-s @owenofbrien

I enabled "Merge when ready" and kicked off the tests, so it'll merge once the tests pass
