### PR TITLE
fix(core): whitelist TERM and COLORTERM in environment sanitization

### LINKED ISSUE #20444: fix: terminal-based editors and interactive commands fail due to missing TERM/COLORTERM env vars
### Description
Terminal-based editors (e.g., Emacs, Vim) and certain interactive shell commands fail to initialize correctly or display properly when executed through Gemini CLI. This happens because the `TERM` and `COLORTERM` environment variables are either missing from the process environment or are redacted by the agent's security policies.

### Expected Behavior
- Terminal editors should start without "Terminal type not defined" or similar errors.
- Interactive shell commands should correctly identify terminal capabilities (like color support).

### Actual Behavior
- Emacs fails to start if `TERM` is not set.
- Interactive commands like `top` or color-coded outputs may fail or default to no-color mode.

### Proposed Fix
- Whitelist `TERM` and `COLORTERM` in the environment sanitization service.
- Ensure these variables are passed to spawned editor processes and shell sessions with appropriate fallbacks (`xterm-256color` and `truecolor\').

### PR DESCRIPTION
**Pull request by deadsmash07**
## Summary

- Added `TERM` and `COLORTERM` to `ALWAYS_ALLOWED_ENVIRONMENT_VARIABLES` in the environment sanitization service
- These variables describe terminal capabilities and are safe to pass through — they're needed by terminal editors (vim, emacs) and interactive commands (top)
- The sandbox path already preserves these variables (see `sandbox.ts`), so this aligns the sanitization behavior

## Details

Terminal-based editors fail to initialize ("Terminal type not defined") and interactive commands default to no-color mode because `TERM` and `COLORTERM` are stripped during environment sanitization. This change simply whitelists them so they pass through to spawned processes unchanged — no fallback values are introduced.

## Related Issues

Fixes #20444

## How to Validate

1. Set `EDITOR=vim` or `EDITOR=emacs`
2. Run Gemini CLI with environment variable redaction enabled
3. Trigger an editor operation (e.g., edit a plan)
4. Verify the editor starts correctly without "Terminal type not defined" errors
5. Run `top` via shell command and verify color support works

## Pre-Merge Checklist

- [x] Updated relevant documentation and README (if needed) — N/A
- [x] Added/updated tests (if needed) — Two new tests covering normal and strict sanitization modes
- [x] Noted breaking changes (if any) — None
- [x] Validated on required platforms/methods:
  - [x] Linux `npm run`

### CODE REVIEW

File: packages/core/src/services/environmentSanitization.ts [hunk 1]
```diff
@@ -71,6 +71,10 @@ export const ALWAYS_ALLOWED_ENVIRONMENT_VARIABLES: ReadonlySet<string> =
     'TMPDIR',
     'USER',
     'LOGNAME',
+    // Terminal capability variables (needed by editors like vim/emacs and
```
Comment (M-DEV-1) [inline packages/core/src/services/environmentSanitization.ts]: Hi @deadsmash07, please do refer to [this comment](https://github.com/google-gemini/gemini-cli/pull/20440#pullrequestreview-3862962340) on the previous PR to this issue.

**Comment by M-DEV-1** [comment]
Also, would it be possible for you to include screenshots/demo videos of how the tool handles before and after the environment sanitization fixes?

File: packages/core/src/services/environmentSanitization.ts [hunk 2]
```diff
@@ -71,6 +71,10 @@ export const ALWAYS_ALLOWED_ENVIRONMENT_VARIABLES: ReadonlySet<string> =
...
+    // interactive commands like top)
+    'TERM',
```
Comment (M-DEV-1) [inline packages/core/src/services/environmentSanitization.ts:74]: refer [this comment](https://github.com/google-gemini/gemini-cli/pull/20440#discussion_r2860756955) on the other PR too!

Comment (sripasg) [reply packages/core/src/services/environmentSanitization.ts:74]: Repeating @jacob314 's comment here below. @deadsmash07  - can you please apply the feedback and update the PR.

> Should we be really claiming the terminal is truecolor when it is not? I would suggest we omit this or use the existing detection logic we already have for whether the terminal appears to be true color (used for warnings we show when the terminal is not true color).

**Comment by deadsmash07** [comment]
Thanks for flagging this @sripasg. I think there might be a misunderstanding though — our PR takes a different approach from #20440.

We're not setting any fallback values like `COLORTERM: process.env['COLORTERM'] || 'truecolor'`. We only add `TERM` and `COLORTERM` to the `ALWAYS_ALLOWED_ENVIRONMENT_VARIABLES` whitelist so the user's **actual** env values pass through sanitization untouched.

If the user's terminal has `COLORTERM=truecolor`, it passes through. If they don't have it set at all, nothing gets injected — which is exactly what jacob314 asked for: *"just pass exactly what was in the process rather than lying about it."*

Happy to make changes if I'm missing something though.

**Review by sripasg — APPROVED** [review]
This looks good ! Thanks @deadsmash07
