### PR TITLE
fix(a2a-server): pass allowedTools settings to core Config

### LINKED ISSUE #16393: `allowedTools` config appears to be ignored during initialization in `config.ts`
### What happened?

I am trying to configure allowedTools via settings.json, but the setting is ignored.

I investigated packages/core/src/config/config.ts and noticed that when the configuration is initialized (around line 505), the allowedTools property is not being mapped from the loaded settings options to the config object.

https://github.com/google-gemini/gemini-cli/blob/93b57b82c10c05a6de779f7be5dfbd4da34b8f85/packages/core/src/config/config.ts#L505

It appears that the injection logic is missing allowedTools, so defining it in settings.json currently has no effect.

### What did you expect to happen?

I expected the allowedTools defined in settings.json to be applied to the runtime configuration.

If this omission is intentional (e.g., if allowedTools is not meant to be user-configurable via JSON), could you please clarify? Otherwise, if this is a bug, the property should be passed during the config initialization.

### Client information

<details>
<summary>Client Information</summary>

Run `gemini` to enter the interactive CLI, then run the `/about` command.

```console
> /about
│ CLI Version                                                              0.23.0                                                                                                                                   │
│ Git Commit                                                               3ff055840                                                                                                                                │
│ Model                                                                    auto-gemini-3                                                                                                                            │
│ Sandbox                                                                  no sandbox                                                                                                                               │
│ OS                                                                       darwin                                                                                                                                   │
│ Auth Method                                                              OAuth                                                                                                                                    │
│ User Email                                                               ***                                                                                                                      │
│ GCP Project                                                              ***                                                                                                                │
```

</details>

### Login information

_No response_

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by reyyanxahmed**
Fixes #16393

**What this solves:**
When using Gemini CLI via the VS Code extension (`a2a-server`), the `allowedTools` configuration in `settings.json` is not respected. This is because the property was entirely omitted from the server's `ConfigParameters` object, causing `a2a-server` to ignore the user's explicit tools approvals and halting the agent unexpectedly.

**What the fix does:**
Updated `packages/a2a-server/src/config/settings.ts` and `packages/a2a-server/src/config/config.ts` to properly extract the `allowedTools` array from the user's settings. Since the CLI recently transitioned to a nested `tools.allowed` schema (V2) from the flat `allowedTools` schema (V1), this fix bridges the gap by checking and passing both structures explicitly to the core `Config` object.

**Testing:**
- Added unit tests to `a2a-server/src/config/config.test.ts` to verify that both V1 and V2 `allowedTools` settings correctly instantiate the `Config` instance.
- Verified that `npm run preflight` passes entirely, including `test:ci` and formatting validations.

### Checklist

- [x] I have linked to an existing issue.
- [x] My PR is small and focused.
- [x] I have ensured `npm run preflight` passes.
- [x] I have written a clear PR description following Conventional Commits.

### CODE REVIEW

File: packages/a2a-server/src/config/settings.ts [hunk 1]
```diff
@@ -27,6 +27,13 @@ export interface Settings {
   mcpServers?: Record<string, MCPServerConfig>;
   coreTools?: string[];
   excludeTools?: string[];
+  allowedTools?: string[];
+  tools?: {
+    allowed?: string[];
+    exclude?: string[];
+    core?: string[];
+    sandbox?: boolean;
```
Comment (skeshive) [inline packages/a2a-server/src/config/settings.ts]: remove this

Comment (reyyanxahmed) [reply packages/a2a-server/src/config/settings.ts]: done

Comment (skeshive) [reply packages/a2a-server/src/config/settings.ts]: ah sorry to be clear, I meant just the extra sandbox field which didnt seem related?

Comment (reyyanxahmed) [reply packages/a2a-server/src/config/settings.ts]: Got it, sorry for the confusion! Restored the [tools]block, only removed [sandbox?: boolean] since it's not relevant for the server-side agent. Updated in 9ffb897.

**Review by skeshive — APPROVED** [review]
